### ISSUE TITLE
Offer the app on F-Droid

### ISSUE THREAD

**Issue by ghost** [Julow/Unexpected-Keyboard#1]
It would be nice to have this app on [F-Droid](https://f-droid.org/). It reminds me a lot of [Hacker's Keyboard](https://github.com/klausw/hackerskeyboard) but, unlike it, this project is still alive. I hope you consider it

**Comment by Julow** [comment]
Hi! Thanks for having a look at the app and sorry for the slow reply.

I've just added a license (surprisingly, there weren't any until now) and [submitted](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9799) the app to F-Droid. I'll close this issue when it's available :)

**Comment by Julow** [comment]
Sorry for the delay! (mostly my fault)
The app is available on F-Droid now :)
