### ISSUE TITLE
Swedish language - accentflag ring is missing

### ISSUE THREAD

**Issue by TomWalde** [Julow/Unexpected-Keyboard#10]
Hi!

Thanks for your keyboard on F-droid. I think to swipe for accents is a much better input method for me than long press.

I write a lot in the swedish language. Unfortunately I can't construct the **Å** and **å** with the Unexpected Keyboard. I switched on _Show every accents_ in the configuration but can not find the ring ◌̊ <https://en.wikipedia.org/wiki/Ring_(diacritic)> on any key.

It would be great if you could add it to the default QWERTY-layout.

Thanks a lot!

**Comment by Julow** [comment]
Hi! I just added the ring accent: 573c13fb825f41a926dca838ef5a396ccce6a3eb. It should show up on the `s` key, feel free to suggest an other location.
I'll try to make a release in a few days.

Btw, the "Show every accents" option is not necessary if you have the swedish language installed on your device.

**Comment by Julow** [comment]
This is part of the new release. I'd like to get your feedback, please re-open if it needs to be improved.

**Comment by TomWalde** [comment]
Hi! I have got the latest version via F-droid today. Your fix works like a charm. Thanks a lot for your exceptional quick response. The Ring on the s-key works fine with me.

"Show every accents" option was needed earlier.
I have three system languages installed. English, German and Swedish. The previous app version used English only so no accents were shown at all. The stock keyboard uses all three.

With todays release I do not need this option anymore. "...for all the installed languages" is now sufficient for my needs.
The app recognises English and Swedish but German is still missing. This is not a problem. The german accents are part of the swedish so I have everything I need :-).

We can open a new issue if you want deep dive in the system languages.

**Comment by Julow** [comment]
The problem you observe with languages is due to the fact that every languages need to be explicitly supported by the keyboard (in the code). This is mainly due to the specific accents and layout of this keyboard, that can't be derived from Android's language mechanisms.
This is why "Show every accents" wasn't helping: the keyboard had no knowledge of Swedish until now.

I'll try to add the German language for the next release (a few weeks from now).
