### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by pawn343** [Julow/Unexpected-Keyboard#103]
Unexpected key pressed repeatedly continuously including backspace (all keys are affected) while doing something like holding the Capslock key and holding the arrow key gesture for selecting words.
I think the problem is in the Key repeat timeout&interval.
I tried using the maximum value for both, so all keys wont be repeated (including backspace), and it solved the problem but sometime it will appear again.
i really love this keyboard since its functionality is just different.
i used to use Hacker keyboard but has bug like the capslock/shift key will be locked when you holding them for example selecting words or repeating the ctrl+key function.
and also Gboard, sadly it's not well made for coding purpose since the symbol can't be accesed easily, but have word suggestion/correction and less typo while typing on it.
i also use codeboard keyboard but nope, it just like hacker keyboard's bug and with minimum functionality.
and many others keyboard but ended fall in love with this keyboard.
so what i wanna say is i want a virtual keyboard that has functionality like external physical keyboard like having special keys like ctrl, alt, shift, tab, arrows, etc just like a physical keyboard, less typo while typing words and or symbols/keys, having word suggestion or correction so it will speed up your typing, etc etc.
typing with an external physical keyboard on phone is just difficult to achive (am using bluetooth keyboard 18.5x8cm with having difficulty to type since the keys separation are too close so i made a lot of typo) so i want the virtual keyboard instead (if it can be achived just the same with virtual keyboard, why bother using the external one?) especially for coding and typing purpose on phone.

**Comment by Julow** [comment]
Thanks for the report. The unstoppable key-repeat bug should be fixed (d53ee81).

Word suggestion is planned for some time this year. I'll close this issue, thanks for the useful feedback.

**Comment by pawn343** [comment]
> Thanks for the report. The unstoppable key-repeat bug should be fixed ([d53ee81](https://github.com/Julow/Unexpected-Keyboard/commit/d53ee811d97692cebe91a5d5d2207dca4d5b8fd8)).
> 
> Word suggestion is planned for some time this year. I'll close this issue, thanks for the useful feedback.

my pleasure & thanks for replying and fixing the issue.
this is a great project especially for someone coding on phone like me.
i would like to see and support its development in the future.
for now, the unstopable-key bug can be canceled when it's happening by closing the keyboard itself like pressing the back navigation.
Another feature suggestion is adding an Option in the setting for auto completion like auto indent, auto closing: the quote, curly bracket, etc. Just to make your life easier i guest.
But maybe will interfere with a text editor like Acode.

**Comment by Julow** [comment]
Thanks :) I don't plan on adding editor features to the keyboard at the moment but I'll keep this in mind.
