### ISSUE TITLE
"Select input method" button disappeared under Android 10

### ISSUE THREAD

**Issue by 9-2-1** [Julow/Unexpected-Keyboard#105]
In Android 7, up-right swipe the alt key can switch to another imput method.

However, it disappeared in Android 10, and only Alt was highlighted after I swipe it.

Will the feature support Android 10 in the future?

Detail: the keyboard icon show on Android 7.0, HUAWEI AGS-W09, EMUI 5.1.3

disappeared on Android 10, vivo S7e V2031EA, Origin OS 1.0

**Comment by Julow** [comment]
Android decides whether the keyboard should show this key. I've added an extra condition just in case (2eb615d) but I don't think it will have any effect.

This key should show up only if there would be several choice. Perhaps you have only one keyboard enabled and have languages that are not supported by the keyboard ?
The keyboard only supports a limited number of languages: https://github.com/Julow/Unexpected-Keyboard/blob/master/res/xml/method.xml

**Comment by 9-2-1** [comment]
Maybe. My Android-7 device have installed the original Android keyboard, while the other device dosen't.

The interesting thing is I can open keyboard list on both devices by holding setting botton in Hacker's keyboard. It seems that there're ways to change keyboard by the keyboard itself anyway.

**Comment by Julow** [comment]
If you have Hacker's keyboard also installed, the button should show. This is a bug.

**Comment by Julow** [comment]
This bug might have been fixed in 1.14.0. Please re-open if this was not the case.

**Comment by 9-2-1** [comment]
> This bug might have been fixed in 1.14.0. Please re-open if this was not the case.

I am using Unexpected Keyboard v1.16.1 from f-droid and the button still disappeared.

**Comment by Julow** [comment]
Thanks for answering. I fail to reproduce inside the emulator with Android 7.
How many keyboards do you have installed ? How many languages installed ?

**Comment by 9-2-1** [comment]
> Thanks for answering. I fail to reproduce inside the emulator with Android 7. How many keyboards do you have installed ? How many languages installed ?

keyboards:

* Jovi 输入法 (a input method)
* Unexpected Keyboard
* 搜狗输入法定制版 (another input method)

My phone supports a lot of languages, including English, Chinese(Simplified and Traditional), Japanese, Deutsch

**Comment by 9-2-1** [comment]
It is interesting that when I install the debug version from github which produced by CA, both version of the keyboard show the button.

**Comment by Julow** [comment]
Can you try this debug version and remove the released version of the keyboard ? https://github.com/Julow/Unexpected-Keyboard/actions/runs/3554180488

**Comment by Julow** [comment]
This should be fixed in 0a86f9a (and part of the last two releases)
