### ISSUE TITLE
[feature request] switching from russian to qwerty on ctrl/alt/meta

### ISSUE THREAD

**Issue by slashdevslashurandom** [Julow/Unexpected-Keyboard#109]
I really like this keyboard app. It is easy enough to use and provides me with all the keys needed for apps like Termux.

Having said that, one annoying feature I have noticed is that, when using the Russian keyboard layout, the Ctrl/Alt/Meta keys are kind of useless, since the combinations still expect a Latin key to go along with them.

I think that, when a non-Latin layout is being used, whenever any of the aforementioned keys are active, the rest of the keyboard should temporarily switch to a QWERTY layout.

**Comment by Julow** [comment]
Hi! Your suggestion is interesting but I hoped to come up with a more general solution to switching between different layouts.

My last attempt is to add an button for switching to a "programming" layout and back (aa78229).
I believe this is not a satisfying solution but I'd like to release soon, so I'll include it so you have at least something. It'll be disabled by default, you'll have to enable it in the keyboard's settings.

I delay fixing this issue to the next-next release.

**Comment by Julow** [comment]
This issue will be solved with per-layout custom Ctrl mappings and not by switching layouts. I'll close this in favor of https://github.com/Julow/Unexpected-Keyboard/issues/438 and https://github.com/Julow/Unexpected-Keyboard/issues/721
