### ISSUE TITLE
great start for an utility keyboard

### ISSUE THREAD

**Issue by FONZACUS** [Julow/Unexpected-Keyboard#11]
seems its going to be a fun ride. id love to suggest some more easy to reach utility keys. the keyboard im currently using has a ton of them, and itd be awesome if you could also take some inspirations. i honestly am boring, i dont mind custom theming|settings not arriving anytime soon.

to switch to it, long tap the spacebar and select the qwerty(arrows)
https://play.google.com/store/apps/details?id=kl.ime.oh
here are some ss
https://drive.google.com/file/d/1ODQtA8ZS_tXxSmx5105NFgTUVyByEIyq/view

**Comment by Julow** [comment]
Hi! That's an interesting idea. However it's quite far from how Unexpected Keyboard works. Is here a specific features you'd want from it ?

**Comment by FONZACUS** [comment]
its your project, your vision. i like the top (not suggestions) rows as there are many more possibilities than normal keyboards, plus the buttons arent too small. unexpkeyb is sort of hard to tap the right button then swipe.

honestly your keyboard could actually have way more possible key combos. its a bit hard to use and its not for everyone, but its still fun thinking what a monstrosity it could become if we could have user modifiable layouts
