### ISSUE TITLE
Bone-keyboard-layout

### ISSUE THREAD

**Issue by Quantenzitrone** [Julow/Unexpected-Keyboard#116]
Would you accept a Layout like this, if I would make it:
https://www.neo-layout.org/Layouts/bone/
?
There is unfortunately no English website, just scroll to the bottom and click through the tabs to see what it features.
I would probably put Layer 3 "Ebene 3" to 6 in the corners.

**Comment by Julow** [comment]
Of course I would!

Layer 4 should be unnecessary since the recent changes to the numeric pane. 
You will have enough work already for reducing the 12 columns to 10, layers 5 should perhaps go into a separate pane (layers 6 would be with shift), similarly to the numeric pane.

**Comment by Quantenzitrone** [comment]
Ok Thanks!

**Comment by Quantenzitrone** [comment]
I have been abandoning this project for quite a while, but yesterday I got back with less fear of changing some things...

This is where I am at:

the letter pane:

![keys1](https://user-images.githubusercontent.com/74491719/168667736-142d7827-2e41-4121-ae27-be60c69509f1.png)

the Greek & Math pane:

![keys2](https://user-images.githubusercontent.com/74491719/168667888-6594f711-a24d-4f75-be31-b1399e773ad8.png)

The keys divided by this | are changes I want to show up when toggling the fn key.

The red keys are ones I might wanna change. 

In the letter pane, I'm not sure if I should instead use dead keys. Dead keys would give more possible combinations, but  just having the most used letters with diacritics would make the whole thing a bit simpler.

In the Greek pane, I'm not sure about the Uppercase Greek letters that are literally just Latin letters. On the one hand, it is not like that in the original bone layout, on the other hand, I have the space to put all the extra math keys in the corners and make typing Greek letters much less confusing.

The green ones are some another category I am not sure about, but I will have to decide on the red keys first, I think.

At the bottom are some more keys I might wanna include, but I'm not sure yet.

**Comment by Julow** [comment]
This looks really nice ! Do you need some help to implement this ? There's a bit of work to implement the switching to and from the greek&math, I do that if you provide me with the layout file :)

> In the letter pane, I'm not sure if I should instead use dead keys

Don't use dead-keys unless you use dead keys on your desktop keyboard too.

> The keys divided by this | are changes I want to show up when toggling the fn key.

This is not implemented in the layout file, this is done in `KeyModifier` in the function `handleFn`. The transformation is common to every layouts but you can add the math characters in that function.

**Comment by Quantenzitrone** [comment]
Ok, I am redesigning a bit first since I can't change `handleFn` except adding math.

One question though: If I add `case "σ": name = "ς"; break;` to `handleFn` will it automatically work for Σ → Ϛ because Ϛ is the uppercase character of ς or do I have to add `case "Σ": name = "Ϛ"; break;` too?

**Comment by Quantenzitrone** [comment]
oh damn i got something really wrong...
ς or greek final sigma does not have an uppercase.
Ϛ is uppercase of ϛ which is another letter: stigma.

**Comment by Quantenzitrone** [comment]
Another thing: How is the uppercase modifier handled? Is it possible to define new functions for uppercase? Like in the picture above, I want to make ∇ as the uppercase of ∂.
If it is possible, it is probably not layout-specific, right?
