### ISSUE TITLE
Keyboard height in Landscape mode

### ISSUE THREAD

**Issue by nrid3v** [Julow/Unexpected-Keyboard#117]
On otientation change 
if [ Landscape -> Portrait ]
    the keyboard size settings working fine
if [ Portrait -> Landscape ]
    unable to set the keyboard size trought the settings
    the  keyboard show with fixed size

**Comment by Julow** [comment]
Your analyze is right, the height of the keyboard cannot be changed in landscape mode.
How much would you like to change the height in landscape mode ? And what's the height you choose in portrait mode ?

The reason for this is that the keyboard height is relative to the height of the screen and both orientation can't use the same value. The default value in portrait is 35% and in landscape it is 55%. This is fixable!

**Comment by cehteh** [comment]
Please add/split settings for "height in portrait/landscape" mode, 55% covers way too much screen area.

**Comment by ChiefMikeK** [comment]
Or  __My VOTE__ is to change the default landscape to 45%

**Comment by Julow** [comment]
There will be an option for this in the next version, and some other fixes related to landscape mode. In my testing, 45% is too small, as a compromise I changed the default value to 50%.

**Comment by cehteh** [comment]
Thanks for adding this, still there is some strange bug left: on my Fairphone with CalyxOS (3.5.1, Android12) changing the size pads on the bottom instead shrinking the keyboard. see: https://photocave.net/storage/m/_v2/427465584705089537/2f76a232a-f08599/y5UZJo60kM2G/FvhnUrtDjif0QWJjrpStWw8MUthwbCPJvh3ucoue.jpg

Even weirder, on a tablet and another phone it works well.

Small remark: on a tablet 35% is nice/plenty in landscape mode, but it might be nice when you set the lowest limit to 25% which may still give a big enough keyboard and ample screenspace above.

**Comment by cehteh** [comment]
> Thanks for adding this, still there is some strange bug left: on my Fairphone with CalyxOS (3.5.1, Android12) changing the size pads on the bottom instead shrinking the keyboard. see: https://photocave.net/storage/m/_v2/427465584705089537/2f76a232a-f08599/y5UZJo60kM2G/FvhnUrtDjif0QWJjrpStWw8MUthwbCPJvh3ucoue.jpg
> 
> Even weirder, on a tablet and another phone it works well.

I just noticed: this padding happens in portrait mode as well.

**Comment by parkerlreed** [comment]
@Julow wow thank you! Much better on tablet now (on 35%)

![Screenshot_20220618-141659_Termux](https://user-images.githubusercontent.com/841440/174451544-a1ed8b2a-753d-4043-ad2a-7c7b9cfa7798.png)

**Comment by Julow** [comment]
@cehteh This padding might be the navigation bar (that have the "back" and "home" buttons) that have the same color as the keyboard since the last release.

I don't know for sure what I can do about that, but my bet is nothing can be done. How is it with the default keyboard ?
