### ISSUE TITLE
Key tap vibration is very strong

### ISSUE THREAD

**Issue by StephenLasseter** [Julow/Unexpected-Keyboard#118]
Compared to the stock keyboard, the key tap vibration is much more powerful for Unexpected Keyboard.  So much so that I need to leave it disabled to avoid bothering others around me.  Is this something that could be reduced in the code or add an adjustable setting for vibration strength?
I'm running version 1.14.1 on the latest release of GrapheneOS (Android 12 base).

**Comment by Julow** [comment]
Thanks for the report. I wasn't aware that it was possible to tweak strength of the vibrator but there are new APIs since Android 8 for this. 

At the moment it is only possible to tweak the duration of the vibration, which was the only variable for a while.

**Comment by StephenLasseter** [comment]
I stumbled across a possible workaround on this for me.  If I navigate to system settings -> Accessibility -> Vibration & haptic strength, there is a setting for Touch feedback I can adjust from low from the default of high.  This is an overall system setting, however, so I'm unsure of whether this will affect other areas in ways I would not like.  We'll see.

**Comment by Julow** [comment]
I've removed the vibration option entirely (ef03dfe). The keyboard should now use the system's settings.
