### ISSUE TITLE
Vibration feedback seems a bit off

### ISSUE THREAD

**Issue by iacobucci** [Julow/Unexpected-Keyboard#119]
When tapping keys at a fast pace, the vibration feedback cant keep up and that is confusing for the user! It's hard to know if one has actually pressed a key or not this way.

I totally love the idea of the project but sometimes i am keen to switch to AOSP keyboard. If this is fixed then the unexpected keyboard is hands down the best keyboard for android!! Let alone the fact that it's open source ❤️

**Comment by Julow** [comment]
Hi, sorry for the slow reply.
There's a delay between vibration, on purpose to avoid overloading the vibrator. Do you think this should be removed?

**Comment by iacobucci** [comment]
> 

Yeah I get that it's a matter of resources handling, but with modern phones it should be no trouble, e.g. the Google Pixel motors easily give a good feedback even with little activation time. 
I have quickly skimmed through the source code of this project but couldn't find methods related to this delay in the vibration feedback (I know little to nothing about Android development) but if you could point me to the snippet of code where the delay happens I could fork the repo with the "fix".
Plus adding a checkbox in the keyboard's setting for experimental vibration would be neat!!

**Comment by Julow** [comment]
You're right, this is not useful. I've removed the delay (402bf49). Sadly, this missed the release by 10 minutes.
This was useful when there was a vibration at every key repeats, but this is no longer the case.
