### ISSUE TITLE
Add privacy policy

### ISSUE THREAD

**Issue by sirfredrick** [Julow/Unexpected-Keyboard#124]
I know that this keyboard doesn't collect any data but it would be nice to have that in a privacy policy for something as important to privacy as a digital keyboard. I've been loving the keyboard so far keep up the good work!

**Comment by Julow** [comment]
Thanks for the suggestion.

On F-Droid, an app that doesn't collect any data is the default so I don't think it's useful to scream it in the description.

On the Play store, there's already a [privacy policy](https://sites.google.com/view/unexpectedkeyboard-privacy) link (which should be rewritten). It could be useful to highlight it in the description too. Related discussion in https://github.com/Julow/Unexpected-Keyboard/pull/123.

**Comment by Julow** [comment]
I acknowledge that the description of the app on the play store could be improved but I'll close this issue because I don't think the privacy policy is a problem.
