### ISSUE TITLE
Latest release 1.10 missing in Fdroid?

### ISSUE THREAD

**Issue by sdrapha** [Julow/Unexpected-Keyboard#13]
Latest release 1.10 missing in Fdroid?

I'm realing looking forward the fixes that were merged and released in 1.10.0 but I can't seem to find that apk anywhere.

**Comment by Julow** [comment]
I think it is. F-Droid can have a few days of delay and then you need to manually update the repository (pull top to bottom on the "Updates" tab).

**Comment by sdrapha** [comment]
Hey, Thank you for getting back. Yep, the delay is on the fdroid side, and it did show up today.
Thank you for the great app! Awesome job
