### ISSUE TITLE
[feature request] Navigation bar coloring

### ISSUE THREAD

**Issue by slashdevslashurandom** [Julow/Unexpected-Keyboard#137]
Right now, Unexpected Keyboard doesn't seem to have a "change navigation bar color" setting like other keyboard apps, like "Simple Keyboard", do. This means that the area below the keyboard, instead of using the keyboard's background color, is always black.

Here are some screenshots (taken on a Nokia 7.2 running Android 11) to demonstrate:

![Screenshot_20220505-133257_1](https://user-images.githubusercontent.com/53902042/166906855-61237bb9-4755-4be7-a7d2-79d0af6637a1.png)
![Screenshot_20220505-133306_1](https://user-images.githubusercontent.com/53902042/166906859-1286c317-fbf5-426f-b522-2f1ce1a4875b.png)

**Comment by Julow** [comment]
Implemented in 7da7a50, thanks for the report.
