### ISSUE TITLE
No dead keys in QWERTZ-layout

### ISSUE THREAD

**Issue by jenslody** [Julow/Unexpected-Keyboard#139]
As the title says, there are no dead-keys in QWERTZ-layout.

I live in germany and german Umlauts work fine, but no matter which settings I use to show accents (I use show all), there are no dead keys.

So everytime I need to write e.g. some french words, I have to switch to QWERTY.

I use version 1.15.0 from Fdroid.
I can provide screenshots, of course,but I think the issue should be easy to reproduce.

**Comment by Julow** [comment]
Thanks for the report. I plan on fixing this by changing the way the accents are placed on the layouts, or, if time runs out, by simply adding the missing keys to the QWERTZ layout.

**Comment by Julow** [comment]
This should be fixed in 2e81cb5.
