### ISSUE TITLE
[QoL] Alternative Keys (corner values) behaviour

### ISSUE THREAD

**Issue by 0xlne** [Julow/Unexpected-Keyboard#14]
The current behaviour of the keyboard is whenever typing, it's not possible to target the center of the key for regular characters.
There are invariably situations where the fingertip touches the key closer to the corner & triggers the corner values instead.
Meaning, that more often than on traditional keyboards, regular words require correction & thus typing is more time consuming.
Changing the size of the keys, long press interval or "distance of corner values" in the settings doesn't help much.
I thus suggest revisiting the behaviour of triggering the corner values to a more efficient mechanism; example: slide to corner would trigger a popup & the selection of that character would be on the popup itself. A press of the base key would only trigger that key itself, not any of the corner values.

**Comment by Julow** [comment]
The "swiping distance" option (formely "distance of corner values") will change for the next release. Please re-open this issue if it's not helping.

I'm not planning to change the swiping mechanism.
