### ISSUE TITLE
Unify positions of some characters for all layouts

### ISSUE THREAD

**Issue by GrimPixel** [Julow/Unexpected-Keyboard#145]
On the Swedish layout, brackets are in the upper-left and lower-right corners; on other layouts, they are in the lower-left and lower-right corners. The keys where brackets are on also vary from layout to layout. On QWERTZ, it's more complicated: square brackets are on the same key, round and curly brackets are on different keys. Other keys are also placed randomly.

There is also one thing: For the rightmost key on the first row, the key usually in the upper-right corner is moved to the upper-left corner. I don't believe it's for convenience, since the “delete” and “next” keys are also at the ridge of the screen.

**Comment by Julow** [comment]
Since https://github.com/Julow/Unexpected-Keyboard/pull/138, the placement of keys near the edge of the screen should be less of an issue. `0` could be put back on the right if that's bothering you.

Contributions welcome.

**Comment by Julow** [comment]
Consistency across all layouts is not a goal. I'm not interested in making bulk changes to all layouts and I prefer to let them live, maintained by people that use them.
