### ISSUE TITLE
Change the folder name Unexpected-Keyboard/res/values-zh-rCN

### ISSUE THREAD

**Issue by GrimPixel** [Julow/Unexpected-Keyboard#147]
That rCN doesn't make sense. Please change it.

**Comment by Julow** [comment]
The `-rCN` prefix means Chinese Simplified, if it is incorrect, what's the right string ?

**Comment by GrimPixel** [comment]
I have only seen CN as the ISO 3166 code. Could you find another case where rCN is used?

**Comment by Julow** [comment]
Android doesn't exactly follow the ISO standard. I couldn't find an official source but this list confirms it: https://github.com/championswimmer/android-locales
