### ISSUE TITLE
Hungarian/QWERTY support

### ISSUE THREAD

**Issue by TamasSzerb** [Julow/Unexpected-Keyboard#149]
I am a kind who uses GBoard with Hungarian/QWERTY layout, could you please add this support to this very useful application?

**Comment by Julow** [comment]
Hungarian was added in the last release of the keyboard. You should be able to select the QWERTY layout in the settings, you'll have the dead keys.

Do you wish for a Hungarian/QWERTY layout with the diacritics directly instead of the dead keys ?

**Comment by TamasSzerb** [comment]
I'm almost fine with the Hungarian layout, except one thing: Y and Z should be swapped in a new variant, ie. having Hungarian/QWERTY instead of Hungarian/QWERTZ. Thank you!

**Comment by Julow** [comment]
Added in 815025a, you can find a debug build here if you want to try it out: https://github.com/Julow/Unexpected-Keyboard/actions/runs/2404756975
