### ISSUE TITLE
Start on boot

### ISSUE THREAD

**Issue by 5265644D61736F6E** [Julow/Unexpected-Keyboard#150]
This is a feature request.

Currently, when enabling this keyboard, there is a pop-up saying, "If you restart your phone and have a screen lock set, this app can't start until you unlock your phone." If the Unexpected Keyboard could start on boot (like OpenBoard, maybe using [ACTION_BOOT_COMPLETED](https://developer.android.com/reference/android/content/Intent#ACTION_BOOT_COMPLETED)), it could function as a usable screen lock.

**Comment by Julow** [comment]
Will be added in the next release.
