### ISSUE TITLE
[Feature request] Auto capitalise as an option in text input feilds

### ISSUE THREAD

**Issue by mexicancartel** [Julow/Unexpected-Keyboard#152]
This is the only thing that hold me back from using as main keyboard app. Its good to have auto capitalise first word of each sentence. Please add it like in other keyboards, and thanks for this app! :)

**Comment by Julow** [comment]
This will be part of the next release (3247565, bfde31d, 081e9a6). It will be opt-out as I think it's a better experience. Of course, it won't trigger on Termux or similar.
