### ISSUE TITLE
Number consistency on standard keyboard

### ISSUE THREAD

**Issue by alabre** [Julow/Unexpected-Keyboard#154]
Hi there,

I stumbled over your great keyboard and I love it. I noticed that on the standard QWERTZ-Layout all numbers in top row are in the upper right corner, except the zero on the "p" key, which is in top left. What would you think about placing all numbers in top right and move the zero to top right?

All the best
Achim

**Comment by Julow** [comment]
Hi! The `0` was moved there because it was too hard to type for some users due to being close to the edge of the screen. This problem has been solved in a more elegant way https://github.com/Julow/Unexpected-Keyboard/pull/138.
I've moved it back in 646ff48.
