### ISSUE TITLE
A case for the single quote to be an upward short-swipe

### ISSUE THREAD

**Issue by qokrb2t** [Julow/Unexpected-Keyboard#157]
Unexpected implements short swipes in a way i've not seen anywhere else in terms of precision & performance.

I'd like to get a feedback on what everyone thinks about making the single quote an upward short-swipe rather than what it is now (a downward short-swipe)

![Singlequote](content://com.mixplorer.file/525!/Snapseed/Screenshot_20220605-091835_Trebuchet-01.jpeg)

My case for the request is,
1. As we write on a paper with a pen, the dot, comma, underscore etc are a tiny movement down & single/double quotes are a tiny movement up
2. I'd like to see unexpected mimick the natural movements of the hand in its implementation of short swipes

**Comment by amiaship** [comment]
I agree with this. It's unintuitive to me that marks placed at the top of a line are downward swipes. It's also harder for my eyes to scan. My preference would be to swap the current placement of colon and single quote keys

**Comment by Julow** [comment]
Sorry for the slow reply. The `'` and `"` are placed like that to be closer to a QWERTY keyboard, `"` is `shift+'` (same for `;` and `:`). Movement of the hand was never taken while making the layouts.

I agree that `'` would be slightly easier to read if it was at the top of a key (swapped with `:` would be good). Contribution welcome.

**Comment by Julow** [comment]
The `'` key didn't move. Is this still an issue for you ?

**Comment by Julow** [comment]
No one moved the `'` in two years so I think this is no longer an issue.
