### ISSUE TITLE
[Feature Request] A convenient & an easier access to uppercase

### ISSUE THREAD

**Issue by qokrb2t** [Julow/Unexpected-Keyboard#158]
The access to uppercase in unexpected right now is costlier as i see it (2 keypresses for a single letter & '3+number of letters' keypresses of 'a number of letters')

As a fan of the short-swipes, i'd like to request the developers to explore the possibility of a short-swipe for an uppercase. To any-one of the corners or even to an edge(upper?).

My case,
1. It would be a lot convenient. Eg. 'Fun' would be 1 swipe+ 2 keypresses compared to what it is now (4 keypresses). That's atleast a 25% improvement even when short-swipes are considered the same as keypresses (which its not, they're way better)
2. Short-swipes are a lot easier than keypresses
3. Easier for non-dictionary words like passwords, word captcha's, writing a local language in english alphabets etc

What goes against my case is a possibility of smart features (Auto-complete, Next word suggestion, Spell-check, Auto-capitalize first letter etc) in the coming versions

My counter is, it's a performance cost. If unexpected as is, takes a 100us to perform an action & a feature implementation takes it to 200us, it still is a 100% performance cost even if we may not notice & even when the h/w is perfectly capable of handling it as normal

I'm not against the smart feature's bucketlist of a traditional virtual keyboard development. Just that it'd be convenient for users who wish to disable(given an option) it

**Comment by Julow** [comment]
Thanks for the suggestion.

An other cons is that the layouts are already pretty full and free spots are needed for the keys (often dead-keys) that are automatically added to the layouts depending on the user's installed languages.
There can be a lot of these for some users, and it's only going to increase over time.
Making room for the uppercase swipe would also be a big change to layouts.

**Comment by Julow** [comment]
This PR makes uppercase accessible via a clockwise circle gesture: https://github.com/Julow/Unexpected-Keyboard/pull/640
You can find the debug build here: https://github.com/Julow/Unexpected-Keyboard/actions/runs/9213480758?pr=640

**Comment by Spike-from-NH** [comment]
That's a clever solution! I think this should be an option in Settings, simply to provide an explanation that the feature exists. It's unlikely anyone would make this gesture by accident, but if they did, the result would be baffling!

Should a counterclockwise gesture produce lowercase despite CAPS LOCK?

**Comment by Julow** [comment]
I think the new circle gesture should answer this issue. Please re-open with suggestions otherwise.

**Comment by Spike-from-NH** [comment]
Rats, that build won't install over the previous 1.28+ debug build!

**Comment by Julow** [comment]
This patch is released.
