### ISSUE TITLE
[Feature Request] WiFi Keyboard Support

### ISSUE THREAD

**Issue by irfnrdh** [Julow/Unexpected-Keyboard#159]
Unexpected Keyboard is the best keyboard for me, but if it supports a wi-fi keyboard will be a wow
-> https://github.com/marcosdiez/aosp-morelang-ime/

**Comment by Julow** [comment]
Sorry, this won't be implemented.

The swipes don't make much sense on a desktop and the web interface wouldn't expose them anyway. Also I'm not willing to add network code into the app. I wouldn't merge such a contribution.
