### ISSUE TITLE
Reinstate show every accents feature

### ISSUE THREAD

**Issue by oxwivi** [Julow/Unexpected-Keyboard#164]
Is there any justification for removing this? I couldn't find any doing a quick search for "accent" in issues. As far as I am aware, this feature did not break anything or get in the way of any other function, so there is no reason for removing this useful feature.

Also, the option is still displayed in the settings yet it doesn't do anything. Please bring it back.

**Comment by Julow** [comment]
Hi, this option was in the way of implementing layouts, languages and internal changes I wanted to make (mainly 2e81cb5cf, which is not working as expected yet, https://github.com/Julow/Unexpected-Keyboard/issues/161).

What is an "accent" (designation I want to get rid of) is now defined in each layouts and languages definitions. It is impractical to maintain a general list of "accents".

Ideally, you would see the dead-keys and other characters you need without tweaking the settings.
What are your languages and what keys are you missing ?

**Comment by adimineman** [comment]
i would love to have a way of typing čžš

**Comment by oxwivi** [comment]
Sorry for the late response, I didn't get notification of your reply right away.
I'm simply using English, but have the occasional want to properly right French words appropriated in English, and even more rarely some non-English latin words in general.

I don't understand what you mean by a "dead-key"; perhaps, instead of enumerating every accent for a given letter in the corners, maybe a single corner for every accented letter would bring a pop-up with the accents? Or even with a modifier, since it won't be used much for languages that doesn't commnly use accents.

As an aside, unrelated to the issue, I've always been wanting for the keyboard to be able to input for symbols like the em and en dashes. While the swiping gestures are really good once you get used to it—besides the edge buttongs like 0—it definitely does limit additional inputs to just the corners.

**Comment by Silent-Hunter** [comment]
I would definitely like a way of typing ä è etc. without switching to a different language, as sometimes I want to type a foreign word.

**Comment by Julow** [comment]
By "dead keys", I mean accents. You are right that the release removed an useful feature. The "show every accents" option can't work anymore, there was 14 "accents" and a couple of "extra keys" and the plan is to add more.

I'm considering to add an option to add an accent or any symbol to the keyboard but I doubt that would help your case. Maybe you'd need some (or all) accents under the `Fn` layer or in an unintrusive place ?

**Comment by Silent-Hunter** [comment]
There are a lot of keys kn the regular QWERTY layout that have symbols on only two corners, or even no corners, so maybe they could go there? Optionally, of course. Fn layer would also be awesome! Just any way to type them without going into the settings would be nice.

**Comment by oxwivi** [comment]
It seems quick reply to email to add comment here doesn't work. Anyway, I'm just here to say, I'm all for any methods quick access to accents, whether it's via Fn or otherwise.

**Comment by dziban303** [comment]
I just started using this keyboard and so far it's great for interacting with termux. The lack of diacritics access is a bummer though. I'd like to see quick access to dead keys or some other method.

**Comment by slartibart70** [comment]
especially if you take into account this screenshot
https://github.com/Julow/Unexpected-Keyboard/blob/master/metadata/android/en-US/images/phoneScreenshots/5.png?raw=true

This was available in previous versions, but sinc my last upgrade, it is gone.

Any idea how to get these special characters back? (without installing any other language in android)

**Comment by heinrichat** [comment]
> especially if you take into account this screenshot https://github.com/Julow/Unexpected-Keyboard/blob/master/metadata/android/en-US/images/phoneScreenshots/5.png?raw=true
> 
> This was available in previous versions, but since my last upgrade, it is gone.
> 
> Any idea how to get these special characters back? (without installing any other language in android)

I have the same issue. I am using "English (Austria)" as a System Language. I have a dashed "ö". I can swipe to it and then type äüö on the keyboard.

I want to also type á à é è ó ò ß and €.


Should I install languages which use this acents? Why can't this be used with one language?

**Comment by Julow** [comment]
The next version of the keyboard will have the "Extra keys" option for this purpose (25a6e71). I plan to improve further this option in the future but I hope to have a better solution.

I see two problems:
- The keyboard is not aware of your language. The best solution is to add support into [`method.xml`](https://github.com/Julow/Unexpected-Keyboard/blob/master/res/xml/method.xml).
- Diacritics are not available to people that needs them only occasionally. I have several ideas ([Compose key](https://github.com/Julow/Unexpected-Keyboard/issues/204), diacritics on the Fn layer) but nothing perfect.

**Comment by Silent-Hunter** [comment]
I like compose key.

**Comment by Julow** [comment]
It's now possible to bring any dead-keys back to the keyboard. Discussions about better ways of typing more characters will happen in new issues. (eg. https://github.com/Julow/Unexpected-Keyboard/issues/204, https://github.com/Julow/Unexpected-Keyboard/issues/191)
Closing.

**Comment by Julow** [comment]
Update: The compose key is done in https://github.com/Julow/Unexpected-Keyboard/pull/559. Feedback welcome
