### ISSUE TITLE
How do I type ñ?

### ISSUE THREAD

**Issue by Nqtural** [Julow/Unexpected-Keyboard#166]
I can type ˜ (marked blue) but when I press another key it dissapears. How do I type ñ?

**Comment by Julow** [comment]
When `˜` is marked blue, `n` should turn into `ñ`. Do you see something else ?

**Comment by Silent-Hunter** [comment]
For me, dead keys do not work at all. When I do Alt and then n and it shows the `˜`, if I then type `n` it just makes an `n`. Or `˜n`, on some text boxes.

**Comment by Julow** [comment]
The `Alt` key is not doing dead keys and it is interpreted by the application. You should see a `˜` key on the keyboard if you have Spanish or Portuguese installed, otherwise, your issue might be related to https://github.com/Julow/Unexpected-Keyboard/issues/164.

**Comment by Silent-Hunter** [comment]
Yeah I realize that now, after trying one of the other language layouts.

**Comment by Julow** [comment]
I think I can close this issue.

**Comment by Julow** [comment]
To remove the confusion, Alt will be hidden by default unless enabled in the settings. (e1145d3)
