### ISSUE TITLE
1.16.0: Abrupt removal of Vibration setting

### ISSUE THREAD

**Issue by eeriemyxi** [Julow/Unexpected-Keyboard#168]
I am feeling despondent after the eradication of the option of whether the user wants their phone shaking on every key press or not. I find it annoying and the latest version makes my phone shake whenever I press a key. I'm being forced to use older version of this application. I request the contributors to bring back that user preference option back; I don't even know why would someone remove it in the first place.

**Comment by Julow** [comment]
You can disable the vibration in the system settings, Sound, the vibration setting is near the end. Do you have it on your device ?

I removed this option in ef03dfe as a fix for https://github.com/Julow/Unexpected-Keyboard/issues/118. The keyboard now follows Android's settings and the option is redundant with the system settings.

**Comment by m-y-x-i** [comment]
> You can disable the vibration in the system settings, Sound, the vibration setting is near the end. Do you have it on your device ?
> 
> I removed this option in ef03dfe as a fix for https://github.com/Julow/Unexpected-Keyboard/issues/118. The keyboard now follows Android's settings and the option is redundant with the system settings.

Oh yeah I found it. It works _but_ I'd say it's still better to include the option to specifically remove it through the application settings. By turning off the option in settings, it also disables some other vibrations that I appreciate. I'd say, if possible, include an in-app option for such preferences if possible.

**Comment by Julow** [comment]
I agree, I removed it too quickly. The option is added back in ff01678.

**Comment by sdrapha** [comment]
For me this is still an open issue. The old behaviour worked perfectly fine on all my devices. With the ability to customize the intensity, and not following the system, which is the most important feature.
To have the vibration following the system is a flawn in my use case. Most times I don't have and don't want any vibration on the system settings, but I do want to have some on this keyboard. Also some phone manufacturers just don't let you customize it enough. Controlling the vibration directly was a better aproach in my opinion.
I really missed not having vibration feedback while testing the latest apk, especially when holding keys to lock, and not knowing when I could lift the finger.

**Comment by Julow** [comment]
You are right controlling the vibration intensity was good to have. Android's code evolved and now vibrations are not a simple duration, this was the reason for the removal. Also, the code don't differentiate between the different things that cause a vibration (simple press, swiping, long press on a modifier).

Contributions welcome :)

**Comment by AgentConDier** [comment]
> Also some phone manufacturers just don't let you customize it enough. Controlling the vibration directly was a better aproach in my opinion.
Case in Point: Huawei EMUI12 (Android 10) only has a binary toggle
![Screenshot_20221218_133219_com android settings](https://user-images.githubusercontent.com/27744962/208298715-f08d33d9-4fb4-44e2-b775-bf44840c1eeb.png)

**Comment by Julow** [comment]
The vibration option will be added back in a different form. Feedback welcome in https://github.com/Julow/Unexpected-Keyboard/issues/360#issuecomment-1574805314
