### ISSUE TITLE
App crashes when swiping on any key

### ISSUE THREAD

**Issue by kidhanis** [Julow/Unexpected-Keyboard#174]
On Marshmallow (API 23), app version 1.16.1. Swiping crashes the keyboard and logcat shows a `NoSuchMethodError` at https://github.com/Julow/Unexpected-Keyboard/blob/1951448f9e26ec99b6c091c678821abcb9e4d264/srcs/juloo.keyboard2/Pointers.java#L166

[Android documentation](https://developer.android.com/reference/java/lang/Math#floorMod(int,%20int)) says that `floorMod` was added in API 24.

**Comment by Julow** [comment]
Thanks for the report. Should be fixed in 1ddd089.

You can find a debug APK here: https://github.com/Julow/Unexpected-Keyboard/actions/runs/2606432628 (it will be a separate app that you need to enable in the language settings)
