### ISSUE TITLE
Add $ (dollar symbol) to Hungarian layout

### ISSUE THREAD

**Issue by kintrix007** [Julow/Unexpected-Keyboard#177]
I need to use the Hungarian layout to have the special characters from Hungarian, but I would like to use the same keyboard for all purposes. I don't want to switch a keyboard just to type other special charavcters. Especially that the `$` is the only character missing.

Pleaae add it to the Hungarian keyboard layout, the letters `h` and `j` don't even have a swipe action, so there is plenty of space.

**Comment by kintrix007** [comment]
Actually, same goes for `~` (tilde).

**Comment by Julow** [comment]
Thanks for the report. Fixed in 2d8ed2d
