### ISSUE TITLE
option to change numeric layouts?

### ISSUE THREAD

**Issue by OilSubjectLoss7** [Julow/Unexpected-Keyboard#178]
from:

```
789
456
123
 0  
```
to:

```
123
456
789
 0
```

**Comment by Julow** [comment]
This issue talks about a layout for typing pins: https://github.com/Julow/Unexpected-Keyboard/issues/153

Do you have a different use-case ?

**Comment by OilSubjectLoss7** [comment]
for that as well also it just looks wrong.

**Comment by Julow** [comment]
I've added an option to choose between the two layouts: c17b53c
