### ISSUE TITLE
ctrl+alt+ [a-z] does not work [Termux]

### ISSUE THREAD

**Issue by OilSubjectLoss7** [Julow/Unexpected-Keyboard#179]
please fix

if i did `ctrl+alt+P` it thinks i pressed `CTRL+P`

**Comment by ChiefMikeK** [comment]
Q: does alt+ctrl+alpha using the [Termux Keyboard - Extra_Keys_Row](https://wiki.termux.com/wiki/Touch_Keyboard#Extra_Keys_Row ) work for you?

**Comment by Julow** [comment]
Ctrl+Alt+C is working on my side. Could this be related to https://github.com/Julow/Unexpected-Keyboard/issues/169 ? (`a-z` would work fine but not `?` for example)
Please re-open if this still doesn't work.

**Comment by Julow** [comment]
This should be fixed since c5f2c0b.
