### ISSUE TITLE
TAB key odd behavior

### ISSUE THREAD

**Issue by sdrapha** [Julow/Unexpected-Keyboard#18]
Currently the TAB key inserts an (unicode tab stop char?) identation.
Where most coding focused keyboards treat the TAB key as a special key and send the TAB key code as it was pressed in a real keyboard. So the final result is not the same.
For example, editing code in homeassistant, selecting a whole block of text and pressing TAB in others keyboards or a physical one would change the identation of the whole block, while in this keyboard it will overwrite all text and substitute for a single 'tab stop' invisible char.
If this use case makes sense for anyone, and fixing it would be a regression for those, would at least make sense to have both behaviors with the use of FN key plus the tab...

**Comment by Julow** [comment]
Thanks for the report !

> Currently the TAB key inserts an (unicode tab stop char?) identation.

That's right and that's not the right thing to do. I've fixed that in 86655d495913d16ced4c2bab489dcec50cdeb4a0.

> For example, editing code in homeassistant, selecting a whole block of text and pressing TAB in others keyboards or a physical one would change the identation of the whole block

If this works with a physical keyboard, this behavior is most probably handled by the application itself. However, if this still doesn't work, please re-open this issue.
The standard behavior would be to focus an other UI element but I'd be in favor of implementing something else directly in the keyboard.

> If this use case makes sense for anyone

I hope not. This is not a standard behavior and not something I want. If someone is affected, please re-open this issue and we'll find an other solution.

**Comment by sdrapha** [comment]
Exactly, the code block identation thing is handled by the code editor when it receives a TAB event, that was just an example. In other places it would change focus just as you said.
Anyway, thank you for the fix! Getting really excited with this keyboard, awesome job!
