### ISSUE TITLE
Automatic capitalisation

### ISSUE THREAD

**Issue by sdrapha** [Julow/Unexpected-Keyboard#181]
Last commits added auto capitalisation, that is great!
But I noticed one annoying behavior.
To reproduce: Try to hold ctrl and press backspace a couple times on a paragraph. The expected behaviour would be to eventually delete the whole thing. But the actual behaviour will be interruoted by the auto capitalisation pressing the shift key halfway in the process next to a period.

I think there could be a case when the autocapitalisation doesn't activate whike holding another modifier key.

**Comment by Julow** [comment]
Thanks for trying! I've changed the auto completion to behave more standard in 85d7982. Please tell me if it's enough to fix your issue.

**Comment by sdrapha** [comment]
Confirmed, issue fixed.  Thanks !!!!

**Comment by sdrapha** [comment]
Wait a moment. Not reaaly fixed. It still happening with latest debug apk.

**Comment by Julow** [comment]
Should be fixed in f56b926.
