### ISSUE TITLE
Stuck in fullscreen mode

### ISSUE THREAD

**Issue by Schroedingers-Hat** [Julow/Unexpected-Keyboard#183]
I can't figure out if it's user error or a bug, but 1.16.1 installed via fdroid keeps bringing up the fullscreen text entry dialogue in some apps. I'm about 80% sure it didn't do this when I first installed it. This is only happening on unexpected keyboard.

**Comment by Julow** [comment]
Sorry for the slow reply. I couldn't reproduce your problem at the time.

Fullscreen mode will be entirely disabled in the next release and fullscreen mode related discussion will happen in new issues (if any).
