### ISSUE TITLE
I would like configure Keys-to-Go physical keyboard layout to Azerty

### ISSUE THREAD

**Issue by stephane-klein** [Julow/Unexpected-Keyboard#185]
Hello,

I have:

- a [Keys-to-Go](https://www.logitech.com/fr-fr/products/ipad-keyboards/keys-to-go.html) Logitech Keyboard in Azerty
- an Oppo Find X3 Lite 5G Android smartphone powered by Android 12, ColorOS v12.1
- I use Unexpected-Keyboard

I can connect Keys-to-Go to my smartphone with success, but I can't get to configure Azerty Layout.

The virtual layout keyboard is well configured in Azerty, but when a press A key on the physical keyboard, I get a `Q`.

I have the same issue with Gboard.

Is it a Android 12, ColorOS v12.1 issue?

How can I configure Azerty layout for my physical keyboard?

Best regards,  
Stéphane

**Comment by ChiefMikeK** [comment]
You need to create a new or modify your [Key Layout Files see Android Open Source Project](https://source.android.com/devices/input/key-layout-files ) this requires rooting your device. try searching on https://www.xda-developers.com/ or Reddit.

**Comment by Julow** [comment]
Thanks @ChiefMikeK. This seems to be an issue with Android not knowing your keyboard. Please re-open if it would behave differently with an other virtual keyboard.
