### ISSUE TITLE
T9 layout

### ISSUE THREAD

**Issue by ralmcruz** [Julow/Unexpected-Keyboard#188]
Hello! Thank you for this amazing keyboard.

I was wondering if is possible to add an t9 layout? Some phone apps like open contacts use that layout with those letters below numbers.

**Comment by sdrapha** [comment]
issue #153

**Comment by Julow** [comment]
I just added the T9 layout (called `pin` in the code, e01a273). It shows up when typing phone numbers, dates and positive integers.
