### ISSUE TITLE
Keyboard hides behind System UI

### ISSUE THREAD

**Issue by heinrichat** [Julow/Unexpected-Keyboard#189]
Sometimes when opening a app and tapping into a text field the keyboard appears but behind System UI. When exiting the keyboard and invoking it again the UI looks correct again. I don't have the issue with the default keyboard or "Hackers Keyboards".

I also think it only appears in non stock apps like whatsapp. When e.g. searching for settings in the stock settings app I don't think that I've ever seen that the UI is shifted. I mostly see it in Whatsapp and Element/Matrix.

I've attached some pictures.
Before (first time invoking keyboard in a app)
![IMG_20220817_164321](https://user-images.githubusercontent.com/5469642/185169242-ab277aec-c3bf-4734-94d6-fbe7116fd40a.jpg)

After (exiting and invoking keyboard again)
![IMG_20220817_164237](https://user-images.githubusercontent.com/5469642/185169231-92f1ffaa-2c09-4df0-8051-646de7ddb146.jpg)

Device: Pixel 4a
OS: GrapheneOS, Android Version 12
Build number: SQ3A.220705.004.2022080900

**Comment by Julow** [comment]
Sorry for the slow reply. I can't reproduce the issue on Android 12 and on the emulators. Do you still experience this with the latest version of the keyboard ?

**Comment by heinrichat** [comment]
Seems to be fixed with GOS on Android 13

**Comment by Julow** [comment]
Thanks!
