### ISSUE TITLE
Arabic Language Pleaseeee

### ISSUE THREAD

**Issue by qtr101** [Julow/Unexpected-Keyboard#192]
put arabic Language pls

**Comment by Julow** [comment]
I don't have the competence to do it but contributions are welcome.

**Comment by islam2hamy** [comment]
Hello ,
@Julow  could this help ?
https://github.com/onattech/Arabic-Keyboard

**Comment by mostafaayesh** [comment]
PR #314 adds an Arabic IBM PC layout with a small tweak. Feedback on the layout would help make it useable for most people.

**Comment by Julow** [comment]
This have been released.
