### ISSUE TITLE
[Feature Request] Clipboard

### ISSUE THREAD

**Issue by RickyM7** [Julow/Unexpected-Keyboard#195]
If possible, will be really nice to have a clipboard on this keyboard.
Anyway, thank you very much for this awesome project!

**Comment by rancidfrog** [comment]
You can take a look at how florisboard implemented this feature, as they did a good job, https://github.com/florisboard/florisboard.
Very convenient.

**Comment by sloanlance** [comment]
My apologies in advance for mentioning the G-word, but I really like how Gboard implemented the clipboard. Several recent clips are available, clips may be pinned to stay on the clipboard, images are supported, and clips with special text, like phone numbers, PINs, URLs, IP addresses, etc. are added as individual clips.

**Comment by RickyM7** [comment]
> You can take a look at how florisboard implemented this feature, as they did a good job, https://github.com/florisboard/florisboard. Very convenient.

Yes, and the Florisboard implementation isn't too much different as Gboard.
Obs: Florisboard is my 1st keyboard at the moment, and I use its clipboard everytime.

**Comment by rancidfrog** [comment]
Yes,
It also supports images, and maybe more...

**Comment by OmlineEditor** [comment]
I ask you to store in the clipboard all the text fields placed there in the past and make it possible to clear the clipboard.

**Comment by LantashTheTokra** [comment]
The KeyMapper Keyboard also implimented this https://github.com/keymapperorg/KeyMapperKeyboard

**Comment by jeff-hykin** [comment]
As soon as this supports the most barebones clipboard history, I'll be making it my daily driver 👌

**Comment by farzadmf** [comment]
It would be great if this is implemented; it's the only blocker for me to switch to this nice keyboard

**Comment by Julow** [comment]
Implemented in https://github.com/Julow/Unexpected-Keyboard/pull/681, debug build is [available here](https://github.com/Julow/Unexpected-Keyboard/actions/runs/9727168851?pr=681). Feedback welcome :)

**Comment by Julow** [comment]
https://github.com/Julow/Unexpected-Keyboard/pull/681 is merged.
