### ISSUE TITLE
Switch between two layouts directly, no pop-up window needed

### ISSUE THREAD

**Issue by sudo-nice** [Julow/Unexpected-Keyboard#197]
When we have only two layouts, it's obvious what layout we want to switch to, so the pop-up becomes a bit annoying. I suggest the pop-up window to be displayed only when there are three or more layouts.

---
Thank you for this great keyboard! :thumbsup:

**Comment by lpv11** [comment]
Second this. A bit weird it's not been implemented as a setting at least.

**Comment by Julow** [comment]
Implemented in 51b330c. A new key is placed on the top edge of the space bar. The secondary layout can be chosen in the settings.
