### ISSUE TITLE
drawing glitch on initial show

### ISSUE THREAD

**Issue by a1291762** [Julow/Unexpected-Keyboard#2]
There's a glitch when switching to this keyboard.

![Screenshot_20211203-233045](https://user-images.githubusercontent.com/327162/144610848-12ae80de-a3ea-45d6-84da-8ce1425d0163.png)

Only seems to affect the initial show, and maybe only when switching to it from another keyboard.

**Comment by Julow** [comment]
Thanks for the report! I've pushed a fix. I'll try to release at the end of next week.

**Comment by Julow** [comment]
This should be released now :) Please re-open if it still happens.
