### ISSUE TITLE
Feature request: Compose key

### ISSUE THREAD

**Issue by Julow** [Julow/Unexpected-Keyboard#204]
Related issues: https://github.com/Julow/Unexpected-Keyboard/issues/30 https://github.com/Julow/Unexpected-Keyboard/issues/171 https://github.com/Julow/Unexpected-Keyboard/issues/191 https://github.com/Julow/Unexpected-Keyboard/issues/164

The [compose key](https://en.wikipedia.org/wiki/Compose_key) is a good way to type rarely needed characters. For example, `Compose, -, >` types `→`, `Compose, ', e` types `é`.

Key combinations are generally intuitive but the keyboard has the opportunity to show the possible combinations during typing, making them easy to discover.

This feature is called `Multi_key` in XKB and the list of [combinations is huge](https://cgit.freedesktop.org/xorg/lib/libX11/plain/nls/en_US.UTF-8/Compose.pre)

**Comment by Julow** [comment]
@Spike-from-NH suggested to use Hacker's Keyboard's compose key sequences in https://github.com/Julow/Unexpected-Keyboard/issues/523

**Comment by parkerlreed** [comment]
What sets the icon for the compose key? I can't tell what it's supposed to be. It's just a circle with a vertical line which looks weird in the middle of the arrow keys.

**Comment by Julow** [comment]
I started from the [ISO keyboard symbol](https://en.wikipedia.org/wiki/File:ISO_7000_-_Ref-No_2021.svg) and removed the square part because the symbol was too wide. I don't have other suggestions and no one complained until now.
