### ISSUE TITLE
[Feature Suggestion] Breve accent for Latin and Cyrillic keyboards

### ISSUE THREAD

**Issue by slashdevslashurandom** [Julow/Unexpected-Keyboard#209]
Thanks a lot for the recent update, which added the ability to manually specify which accented characters should be added to the keyboard. Having said that, I am finding that the breve accent is missing from the list.

In the Latin keyboard, the breve accent can be applied to the letter "U" to form Ŭ, a letter used in Esperanto and Belarusian (when written with the Latin alphabet).

In the Cyrillic keyboard, the breve can be applied to the letter "У" to form Ў, a letter used in Belarusian. (Technically, the Russian letter "Й" is an И with a breve, but I would not advise removing Й as a separate key in the Russian layout, as it is a pretty common letter.)

In addition, other languages also have characters that use the breve accent.

**Comment by Julow** [comment]
Added the breve accent to the keyboard (db347c6). It is not added to any layout as there are no Esperanto or Belarusian layout currently but it can be enabled in the settings.
