### ISSUE TITLE
[Feature Suggestion] Ukrainian and Belarusian alternate characters in the Russian layout

### ISSUE THREAD

**Issue by slashdevslashurandom** [Julow/Unexpected-Keyboard#210]
This may be a rather unusual suggestion, but I think it would be pretty useful if the Russian layout for this keyboard also had a way to type the characters used in Ukrainian and Belarusian languages (preferably the same way the German "ß" can be typed by swiping the "s" key in latin layouts)

The Ukrainian alphabet features the following characters unavailable on the Russian keyboard layout:

* Ґ/ґ, "ghe with upturn". (preferably by swiping from Г/г)
* Є/є, "ukrainian ye". (Е/е)
* І/і, the "belarusian/ukrainian i". (И/и)
* Ї/ї, the "yi". (Й/й)

In addition, Belarusian uses the "short U" (Ў/ў), which would work well with a breve accent modifier, as suggested in issue #209 (or, if not, can be placed as a swipe from У/у).

**Comment by Julow** [comment]
This can be implemented by making the keyboard recognize other languages in `res/xml/method.xml`.

For example, Lithuanian and Polish uses the qwerty layout but with keys added to it: https://github.com/Julow/Unexpected-Keyboard/blob/master/res/xml/method.xml#L14, https://github.com/Julow/Unexpected-Keyboard/blob/master/res/xml/method.xml#L18
The qwerty layout defines a position for some of them, https://github.com/Julow/Unexpected-Keyboard/blob/master/res/xml/qwerty.xml#L17-L20, but this is not strictly necessary as they would be added automatically. The `loc ` prefix defines a position for a key on the layout but don't actually add the key there.

Of course, it's also possible to create a new layout to, for example, move keys around.

**Comment by Julow** [comment]
The breve accent works on `у` but if there's just one useful accented letter, it's better to add it directly to the layout. Implemented in d7e4840 and bac228e.
