### ISSUE TITLE
Please do not remove lockable modifiers

### ISSUE THREAD

**Issue by lytex** [Julow/Unexpected-Keyboard#215]
In the last version, I see `Depcrecated: Lockable modifiers`

I use them pretty often, for example if I'm editing a text and jumping between words, locking Ctrl is very useful. Without lockable modifiers I would have to keep my right finger pressing Ctrl and I'd rather not to.

**Comment by Julow** [comment]
Since the last release, any modifier can be locked with a long press. Is that enough for you?

**Comment by lytex** [comment]
Ah, okay, I thought the plan was to remove them all entirely but Caps Lock!
A text saying just that right after "This option will be removed" would be great to stop users like me freaking out  😅

**Comment by Julow** [comment]
Good idea! I've added the message to avoid freaking out more people (7f51cf0) but documentation is clearly lacking.
