### ISSUE TITLE
make diaeresis (characters) more accessible

### ISSUE THREAD

**Issue by 07416** [Julow/Unexpected-Keyboard#219]
https://en.wikipedia.org/wiki/Diaeresis_(diacritic)

To my knowledge the diaeresis (e.g. umlaut, ¨ ) modifier keys **only appears** when a related language, such as the Nordic languages or Germany, has been enabled in the Android settings. I use all of my devices in US English and would prefer not adding any additional ones — and more importantly, I can only assume that this process is confusing to new users.

I feel that an on/off option in the settings would improve the keyboard app accessibility.

compare these screenshots:

![image](https://user-images.githubusercontent.com/14923168/195852308-0e612d16-4650-413e-ba6e-b2dbe1b8e735.png)

![image](https://user-images.githubusercontent.com/14923168/195852485-5928d204-8eeb-45e6-bf4c-0e96e998a5e3.png)

---

[a related issue](https://github.com/Julow/Unexpected-Keyboard/issues/4)

**Comment by sdrapha** [comment]
that option is exactly what Julow implemented in the last commit even before your post. check out the debug apk on actions tab. That 'extra chars' setting is working good to me. thanks Julow, that is a nice feature!

**Comment by 07416** [comment]
> that option is exactly what Julow implemented in the last commit even before your post. check out the debug apk on actions tab. That 'add keys' setting is working good to me. thanks Julow, that is a nice feature!

You're referring to [this commit](https://github.com/Julow/Unexpected-Keyboard/commit/dda8f0314d786d09791512ad949ae76f2068b25a)?

I found the (at the time of writing) latest [debug APK](https://github.com/Julow/Unexpected-Keyboard/actions/runs/3239652214); the options:

![image](https://user-images.githubusercontent.com/14923168/195973198-3b6a319a-c71d-4e97-99e1-dd738be03225.png)

**Comment by 07416** [comment]
I'm assuming that the feature will make it to the next release.

**Comment by Julow** [comment]
The release from 3 weeks ago contains this feature but I decided to halt rollout on the Play store due to a crash report. Thanks for trying the debug APK :)

**Comment by 07416** [comment]
> The release from 3 weeks ago contains this feature but I decided to halt rollout on the Play store due to a crash report. 

The option is available in the current F-Droid build, I missed this somehow.
