### ISSUE TITLE
Pasting (Ctrl+Shift+V) and copying (Ctrl+Shift+C) text doesn't work in Termux

### ISSUE THREAD

**Issue by 07416** [Julow/Unexpected-Keyboard#221]
I believe pasting and copying by using the keyboard hasn't been possible in Termux since the launch of Unexpected-Keyboard. Is the issue on the Termux's side or something the keyboard app developer can fix?

**Comment by Julow** [comment]
Is Termux reacting to these keys ? Have you seen that with an other keyboard ?

**Comment by Julow** [comment]
Apps often don't handle keyboard keys well so I consider adding "editing keys". (https://github.com/Julow/Unexpected-Keyboard/issues/101, https://github.com/Julow/Unexpected-Keyboard/issues/99, https://github.com/Julow/Unexpected-Keyboard/issues/233)
Perhaps you've used a keyboard that performs the editing actions itself ?

**Comment by laurentlbm** [comment]
In Termux, you have to use `ctrl+alt+c` and `ctrl+alt+v`, not `shift`.

**Comment by Julow** [comment]
Termux's [wiki](https://wiki.termux.com/wiki/Touch_Keyboard) only mentions Ctrl+Alt+C (create a new session) in the keys it accepts from "touch keyboards". This binding works for me.
The wiki page on ["Hardware Keyboard"](https://wiki.termux.com/wiki/Hardware_Keyboard) mentions those Ctrl+Alt+C/V bindings but they have no effect when typed from this keyboard. I don't know why Termux needs to handle "touch" and "hardware" keyboards differently, it might be worth opening an issue there to ask.

Please re-open if you find an other virtual keyboard in which these bindings are working as you expect.

**Comment by doak** [comment]
At least `Ctrl` + `Alt` + `v` works for paste, btw.
