### ISSUE TITLE
[Feature Request] Swipe up on shift key for caps lock

### ISSUE THREAD

**Issue by tonyaajjackson** [Julow/Unexpected-Keyboard#223]
Right now, to enable caps lock, I need to double-tap the shift key. I would love to be able to swipe up or up-right on the shift key to toggle caps lock so that I can do it in a single movement.

Thanks again for making such an awesome keyboard!

**Comment by Julow** [comment]
Good idea! I added the key in 36e10a7, it is not added to the layout by default so it needs to be enabled in the settings.
