### ISSUE TITLE
Make settings match the theme to be usable on eink devices

### ISSUE THREAD

**Issue by csdvrx** [Julow/Unexpected-Keyboard#227]
On a eink device, white text on black backward is almost unreadable.

The settings window only has a dark mode: at least 2 should be provide ; ideally, it should match the system theme by default (or at least, the keyboard theme) with an option for overriding

**Comment by Julow** [comment]
Thanks for the report. Automatic theme switching according to the system should be fixed in d2328d4. I don't think an option would be useful.
