### ISSUE TITLE
[request feature] Dim sharp white color

### ISSUE THREAD

**Issue by gthu34** [Julow/Unexpected-Keyboard#229]
The sharp white color of keys on black/dark theme is irritating to eyes. plz add an option to change the color or just give another black theme with color of keys changed to something like #666666 or #333333 or any similar dimmed white color like these two. 
Also can we have to option to change location of ctrl,alt,fn keys ?
Thank you for making such an awesome keyboard.

**Comment by Julow** [comment]
I've experimented a bit with colors and dimmed some symbols (4d99bd4) and added an option to control the "brightness" (815e30a, internally makes the labels transparent).
Don't hesitate to try and say what you think: https://github.com/Julow/Unexpected-Keyboard/actions/runs/3447276869
