### ISSUE TITLE
Ctrl not working

### ISSUE THREAD

**Issue by linkkalians** [Julow/Unexpected-Keyboard#23]
please fix ctrl not working in my phone, thanks 🙏

**Comment by Julow** [comment]
Thanks for the report. In what applications is it not working ?

There have been a fix related to the ctrl key in the last release (https://github.com/Julow/Unexpected-Keyboard/issues/9), can you check if you have the lastest version (1.11.0) ?

**Comment by Julow** [comment]
I just released a new version. Please re-open this issue if this isn't fixed after updating.
