### ISSUE TITLE
Dead keys for Croatian

### ISSUE THREAD

**Issue by quexpexx** [Julow/Unexpected-Keyboard#230]
The new update allows you to add custom dead keys to the keyboard, so support for specific languages isn't *super* important, but what then becomes an issue is a dead key just not existing, and thus being unable to be added to the keyboard. This issue is specifically for Croatian keys Đđ, which use a [bar diacritic](https://en.m.wikipedia.org/wiki/Bar_(diacritic)). Perhaps this should be added as a dead key? Thank you.

**Comment by Julow** [comment]
I added the dead key in 1e067c9. It allows to type đ but also many of the "with stroke" latin letters listed by wikipedia.
I encourage you to add support for Croatian and to add a layout.
