### ISSUE TITLE
[Feature Request] fully customizable keyboard by the user

### ISSUE THREAD

**Issue by OmlineEditor** [Julow/Unexpected-Keyboard#231]
please make it possible to customize the appearance of the keyboard yourself. I want to choose which keys and where they should be, what size and what color they will be.

here is an analogue of your program that allows you to make a complete appearance adjustment jbak2:
https://play.google.com/store/apps/details?id=com.jbak2.JbakKeyboard

source code: https://jbak2.ucoz.net/load/iskhodnye_teksty/jbkbd2_v2_36_11_source_code/23-1-0-184

I ask you to install this program and study its functions, then take a part and make it better for yourself.

**Comment by OmlineEditor** [comment]
I looked at all the requests and I see that users are asking to change something in the keyboard and add some buttons. But if you make it possible for users to create keyboards for themselves, then some of the problems will disappear by themselves, for example these:
https://github.com/Julow/Unexpected-Keyboard/issues/176
https://github.com/Julow/Unexpected-Keyboard/issues/178
https://github.com/Julow/Unexpected-Keyboard/issues/192
https://github.com/Julow/Unexpected-Keyboard/issues/195
https://github.com/Julow/Unexpected-Keyboard/issues/210
https://github.com/Julow/Unexpected-Keyboard/issues/133
https://github.com/Julow/Unexpected-Keyboard/issues/131

**Comment by Julow** [comment]
A first step might be to allow passing a XML layout file in the settings. Such a file looks like that: [qwerty.xml](https://github.com/Julow/Unexpected-Keyboard/blob/master/res/xml/qwerty.xml)
It goes quite far for full customization, there's an issue open about this: https://github.com/Julow/Unexpected-Keyboard/issues/31

Then, there's the activity for modifying the layout interactively. Such a feature would be interesting but it sounds like a lot of work.

The app you link to also allow changing the colors and sizes, that would be theming. Issues: https://github.com/Julow/Unexpected-Keyboard/issues/222, https://github.com/Julow/Unexpected-Keyboard/issues/92

Are you proposing to do the work ?

**Comment by OmlineEditor** [comment]
it doesn't matter what the function is called (theme or setting or something else) the main task is so that the user can create a keyboard from the necessary keys himself, set them arbitrary colors.

arbitrary keys anywhere on the keyboard and any functionality needed by users.

in the future, we may make a separate branch and post different versions of ready-made keyboards and themes.
here are examples of different keyboards:
https://play.google.com/store/apps/details?id=com.jbak2.layout

**Comment by Julow** [comment]
I think everything in this issue is covered by other issues. I'll close.

**Comment by OmlineEditor** [comment]
have you already done a full customization of the keyboard? where is the ticket responsible for full customization?

**Comment by Julow** [comment]
The other issues are: https://github.com/Julow/Unexpected-Keyboard/issues/222 https://github.com/Julow/Unexpected-Keyboard/issues/92 https://github.com/Julow/Unexpected-Keyboard/issues/226 https://github.com/Julow/Unexpected-Keyboard/issues/229
