### ISSUE TITLE
[Feature Request] Full configuring keyboard swipe

### ISSUE THREAD

**Issue by OmlineEditor** [Julow/Unexpected-Keyboard#232]
I want to independently configure how the swipe on the keyboard will work.

for me, a swipe to the side is more convenient for removing 1 character from the left or right, depending on where I made my swipe with my finger. Swipe down to hide the keyboard. I want to be able to configure all these swipes myself.

**Comment by Julow** [comment]
Sorry this is unclear. Do you mean swiping left or right anywhere on the keyboard to remove a character? Every keys already react to swiping so this wouldn't be possible.

Do you mean swiping from the sides (the finger starts outside the screen and move toward the center)? These could be interesting gestures but I'm not sure if they add something useful over the existing delete key.

**Comment by OmlineEditor** [comment]
you are right, you can configure Skype by length, if the swipe is very long and from the edge of the screen then this is one function, if it is short then it is a function for a key and a set of characters.

**Comment by Julow** [comment]
Sorry, I do not wish to add gesture to the whole keyboard area. I'm afraid this would interfere too much with the other gestures (swipe over every keys as well as long press and slow swipe).

**Comment by OmlineEditor** [comment]
then at least I ask you to add the ability to hide the keyboard by pressing the button
