### ISSUE TITLE
copy, paste, cut, undo, redo, select all - separate keys (not Ctrl + <key>)

### ISSUE THREAD

**Issue by OmlineEditor** [Julow/Unexpected-Keyboard#233]
I ask you to create separate keys for: copy, paste, cut, undo, redo, select all...
I don't want to use hotkeys consisting of two combinations Ctrl + < key >

it will be very convenient when the user can create the appearance of the keyboard himself https://github.com/Julow/Unexpected-Keyboard/issues/231

**Comment by AdePelumi** [comment]
Here is a sample from Google keyboard for the features he's requesting
![IMG_20221105_143029](https://user-images.githubusercontent.com/78900413/200137711-c28ce694-6ca2-48db-a310-9f68f9411838.jpg)

**Comment by xi7** [comment]
i like the shortcut like computer - using ctrl a x c v   .... new layout looks slow

**Comment by OmlineEditor** [comment]
you can add buttons to the keyboard yourself and it will be fast.

![keybrd](https://user-images.githubusercontent.com/13348933/201476813-130a79a6-9b58-48c1-8098-635095a1a076.jpg)

**Comment by rancidfrog** [comment]
Florisboard has a wonderful implementation of copy paste clipboard etc.
![](https://i.imgur.com/55cDzsv.png)

**Comment by xi7** [comment]
still no like all layout, too much height keyboard.  ctrl + a x c v faster and compact.

**Comment by xi7** [comment]
![1](https://user-images.githubusercontent.com/67331785/201497520-125fe2a4-eb43-4645-9c08-2b855544c251.png)

arrow controlled by space bar key , and we can use a x c v using that empty key

**Comment by OmlineEditor** [comment]
different people need different keyboards. therefore, it is necessary to make it possible for the user to choose independently how to do it. to do this, you need to create a custom keyboard by default https://github.com/Julow/Unexpected-Keyboard/issues/222

**Comment by xi7** [comment]
will add a lot of complexity code and next u will open issue save/open customized backup.

i still prefer compact and faster possible

**Comment by OmlineEditor** [comment]
backup from old versions is not suitable for new versions. This is better than simplifying the program.

**Comment by Julow** [comment]
I've added some editing keys in 2aa98de as a first step for https://github.com/Julow/Unexpected-Keyboard/issues/242 (the goal was to make that fit in the code, 078dbcd). Undo and redo are missing and there's no symbol for them yet (if any of you is interested in continuing the work).
Also, an editing mode might add the code for interesting keys (move to begin/end of line, delete word, etc...), TBD later.

@xi7 This issue talks about moving the cursor with the space bar: https://github.com/Julow/Unexpected-Keyboard/issues/7 (also see https://github.com/Julow/Unexpected-Keyboard/issues/46 for inspiration). There's also some preliminary code in https://github.com/Julow/Unexpected-Keyboard/pull/102

I wouldn't be against an editing toolbar like the one from the florisboard screenshot, if someone is motivated to implement it.

**Comment by rancidfrog** [comment]
Another thing about having an editing toolbar,
- It can be disabled easily as it is a complete row by a simple toggle
- It can be customized easier for the same reason, i.e. user adding keys to this toolbar which they use, needs a mechanism but doable like how:
For example, a full on solution would be to have drag and drop like how edit quick settings works,
![](https://i.imgur.com/9MdEzJl.png) 

However, a simpler solution would be to have an input dialog **Add key to toolbar**  where users would enter the _key code_  to add. and a select key to **remove key from toolbar**

**Comment by OmlineEditor** [comment]
> I wouldn't be against an editing toolbar like the one from the florisboard screenshot, if someone is motivated to implement it.

the user must create the keyboard he needs using the configuration file. You don't need to do this yourself if you don't need it.

> However, a simpler solution and more versatile would be to have an input dialog **Add key to toolbar** where users would enter the _key code_ to add. and a select key to **remove key from toolbar**

all settings are inside .xml configuration file. editing settings inside a file is easier and more accessible than dragging keys.
if you are interested, look at the keyboard: https://play.google.com/store/apps/details?id=com.jbak2.JbakKeyboard

**Comment by Julow** [comment]
I've added an option to specify a custom layout (e745c81). See qwerty as an example: https://github.com/Julow/Unexpected-Keyboard/blob/master/res/xml/qwerty.xml
I don't plan to add documentation and improving the option yet. Knowledge about the keyboard's code is needed for any advanced use.

Please experiment with it and give feedback.

**Comment by OmlineEditor** [comment]
> you can add buttons to the keyboard yourself and it will be fast.

to do this, there should be convenient and understandable templates. there is no such functionality right now

**Comment by Julow** [comment]
The keys exist within the keyboard but are not practical due to https://github.com/Julow/Unexpected-Keyboard/issues/242. I'll close this issue.

I encourage participants to try experiment with a editing shortcut bar or opening more specific issues.

**Comment by OmlineEditor** [comment]
> The keys exist within the keyboard but are not practical due to #242. I'll close this issue.

what do you mean, not practical? what exactly is the problem with making separate keys with the necessary functions?

**Comment by Julow** [comment]
Have you tried the keys ? See the linked issue for context.

**Comment by OmlineEditor** [comment]
> Have you tried the keys ? See the linked issue for context.

I don't understand you. give links to a where there is information to read

**Comment by Julow** [comment]
Use the option "Add keys to the keyboard" in the settings to add the keys to the keyboard. If you find that they don't work reliably in every apps, that's a known issue. (https://github.com/Julow/Unexpected-Keyboard/issues/242)
