### ISSUE TITLE
Does ctrl+F1 until F10 Not supported?

### ISSUE THREAD

**Issue by rektpartyaftermath** [Julow/Unexpected-Keyboard#236]
# Does ctrl+F1 until F10 Not supported?
When i try to press ctrl the F1 until F10 key that show up when fn button is pressed dissapear.
Then how i make key combination like ctrl+F5 for example?
the only key combination that possible is ctrl+F11 and F12 as they didn't dissapear when ctrl is pressed.

**Comment by Julow** [comment]
Thanks for the report. Fixed in ebe66eb.
