### ISSUE TITLE
Unexpected Keyboard crash-loops on boot login with version 1.19.0

### ISSUE THREAD

**Issue by StephenLasseter** [Julow/Unexpected-Keyboard#238]
Unexpected Keyboard Version: 1.19.0
Phone: Pixel 5
OS: GrapheneOS version 2022110800 (latest as of today and this is Android 13)

I upgraded the Unexpected Keyboard version (from 1.18.0 to 1.19.0) and applied GOS system updates.  The keyboard continued to work fine as usual until I restarted the phone.  After boot-up the login screen was shown requesting a password, but no onscreen keyboard was present.  After a while, a popup message appeared stating the Unexpected Keyboard was in a crash-loop.  I was unable to login to the phone because Unexpected keyboard was crashing, no alternative keyboard was offered, and USB was not an option without first logging in.

To restore the phone to  usable state, I booted into safe mode, which prevented third-party apps, including Unexpected Keyboard, from running.  Once logged in using the ASOP keyboard, I was able to downgrade the Unexpected Keyboard version back to 1.18.0.  Subsequent reboots are working fine.  The ASOP keyboard is presented for the boot screen login, and Unexpected Keyboard is presented for input once logged in.

This issue is repeatable by installing Unexpected Keyboard version 1.19.0, selecting it as the primary keyboard, and rebooting the device.

**Comment by StephenLasseter** [comment]
I suspect that this is related to this commit, which was included in the 1.19.0 release:  25cefc589051b22b4492cafc94fec54aa003096b

**Comment by darhma** [comment]
I confirm the issue with version 1.19 on android 12

**Comment by Julow** [comment]
It should be fixed in f1ce6ab, you can find a debug version here: https://github.com/Julow/Unexpected-Keyboard/actions/runs/3445400199

I'd appreciate if someone could test this, as I have only one device and this can't be tested in an emulator.

**Comment by T-3B** [comment]
Yep, just tested it works as expected now! (I'm the author from #216 )

Should be the same for others here.

**Comment by darhma** [comment]
I also confirm that the debug version is working correctly

**Comment by Julow** [comment]
Thanks a lot for testing :) Releasing soon.
