### ISSUE TITLE
Feature Request:Clipboard Key & Polished Emoji Display

### ISSUE THREAD

**Issue by DeMoN100** [Julow/Unexpected-Keyboard#239]
It would be nice to have a clipboard button so I don't have to hold down on a blank space to access it. The button can go in the top right corner of the fn key since that space is unused.

Also it would be nice if the emoji key's interface was polished up to match the standard look by samsung.
![Screenshot_20221109_205205](https://user-images.githubusercontent.com/8564572/200980984-70020f84-1542-4bb9-abf2-d2c798b8218f.jpg)
It doesn't have to have everything at the top like gifs or the other buttons but it would be nice to include the AR Zone Emoji button that's in the picture. As you can see below it the second bar in the emojis is the categories which scrolls horizontally and has a search button to search the emojis. Where the emojis display can scroll vertically through every category.

**Comment by Julow** [comment]
Clipboard is implemented in https://github.com/Julow/Unexpected-Keyboard/pull/681, debug build is [available here](https://github.com/Julow/Unexpected-Keyboard/actions/runs/9727168851?pr=681). Feedback welcome :)

**Comment by Julow** [comment]
https://github.com/Julow/Unexpected-Keyboard/pull/681 is merged. I'll close this as other issues track the various problem that the emoji pane has.
