### ISSUE TITLE
Issue:Lost Clipboard After Updating!

### ISSUE THREAD

**Issue by DeMoN100** [Julow/Unexpected-Keyboard#240]
Hello after updating this I lost the ability to access my clipboard by holding on a blank space. This option has been replaced with autofill which does not work on my phone. Now I have to use the older version or switch to another keyboard to get the clipboard back. Can you add this back and also implement the clipboard key as I suggested in my other issue?

**Comment by DeMoN100** [comment]
Android 12 One UI 4.1 AT&T A53 5G.

Since I have posted this issue. I attempted to try previous versions of unexpected keyboard and my clipboard has not returned. I was able to access my clipboard by holding down on a blank space and pressing the clipboard button.
![Screenshot_20221110_121744](https://user-images.githubusercontent.com/8564572/201441961-4b1d8413-1e60-4bf4-bd41-c27439c0cdd8.jpg)
When I updated to the latest version released I lost this button and it has been replaced with autofill which does not work.

After I posted the issue I did search around and unexpected keyboard may or may not be the cause of this. Search results most people comment saying its something with android 12 that samsung made a change to hide the clipboard on all third party keyboards and only make it appear on the samsung keyboard.

But these results are wrong & were posted 8 months ago and incorrect I have multiple devices 7 to be exact on android 12 at the latest versions and all my other devices are using unexpected keyboard and only this one my main cell phone the  AT&T A53 5G has lost its clipboard. My other devices are not using the latest version of unexpected keyboard they are all on the version previous to the latest. I haven't updated them in fear I may lose my clipboard on those as well.

**Comment by Julow** [comment]
I can't see why unexpected keyboard would cause this. I'd blame either an update of the system or of samsung's keyboard.
If you are used to long pressing the space bar, what's wrong with long pressing the text box instead ?

**Comment by DeMoN100** [comment]
it does the same thing in a blank space or textbox its only paste & autofill not paste & clipboard. Also i have software updates and ota updates disabled by using ADB to disable those system apps so my devices can't automaticaly perform system updates.

**Comment by Julow** [comment]
Long press on the space bar is supposed to repeatedly type the space character, not to open any menu. Are you sure you are using the right keyboard?

The keyboard has nothing to do with long pressing the text box. There's nothing I can do, sorry.
There have been many requests for a clipboard button inside the keyboard, maybe that would help you? https://github.com/Julow/Unexpected-Keyboard/issues/195

**Comment by DeMoN100** [comment]
im not talking about the spacebar. Anywhere on the screen is what im referring to. Yes I have suggested that as well a clipboard button be placed in the top right of the fn key along with redesign of the emoji list. 

Are you sure it has nothing to do with it because on the other keyboard its there on this one it dissapears and all my other devices which are on the last version before the current ond still have it.

**Comment by DeMoN100** [comment]
As you can see in the pictures

![Screenshot_20221113-002050_Bromite](https://user-images.githubusercontent.com/8564572/201507209-7a46cfcf-fc0e-4cc9-a91e-dc1bad23ff9d.jpg)
![Screenshot_20221113-002037_Bromite](https://user-images.githubusercontent.com/8564572/201507210-9d6fe939-4e29-4d2b-b95d-4b17de56e8b9.jpg)

**Comment by Julow** [comment]
Perhaps the "Clipboard" button is placed there by the keyboard itself ? But then that doesn't explain why the clipboard button was here before while using unexpected keyboard.

**Comment by DeMoN100** [comment]
> Perhaps the "Clipboard" button is placed there by the keyboard itself ? But then that doesn't explain why the clipboard button was here before while using unexpected keyboard.

Right thats what I don'y get either this is a screenshot from my A02S which you can see its still there with unexpected keyboard.
![Screenshot_20221114-053506_Samsung Notes](https://user-images.githubusercontent.com/8564572/201639219-444956cc-f2b4-42fa-891d-2cc0fd990b92.jpg)
