### ISSUE TITLE
Unable to write letters đ,Đ

### ISSUE THREAD

**Issue by Mel34** [Julow/Unexpected-Keyboard#244]
Basically simbol ![image](https://user-images.githubusercontent.com/13254332/203276358-56f78828-9796-4ea9-b6ce-93c40b973564.png) doesn't apply to letter d thus is unable to form letter đ and it's capitalized version Đ. These letters are used in certain Slavic languages.

![image](https://user-images.githubusercontent.com/13254332/203276213-2184fab8-2d92-43cb-a3cf-5fd144e6a0d9.png)

![image](https://user-images.githubusercontent.com/13254332/203275967-049d0af6-855c-4897-a87a-1ef8506f6924.png)

**Comment by Julow** [comment]
The key you are looking for is:
![Unsaved Image 1](https://user-images.githubusercontent.com/2310568/203295636-c483355d-0c37-443a-b185-4b44b32dec74.png)

I agree the glyph is ambiguous, it looks like a little arrow. I'll improve it.
