### ISSUE TITLE
how to force the pin Numpad order

### ISSUE THREAD

**Issue by OilSubjectLoss7** [Julow/Unexpected-Keyboard#247]
instead of the select few?
how to force this
123
456
789
  0

it's not showing for alphanumeric view or normal text typing
i get this instead
789
456
123
  0

**Comment by Julow** [comment]
There's an issue open for this already: https://github.com/Julow/Unexpected-Keyboard/issues/178 (opened by you)

I lack the time to implement this at the moment but contributions are welcome.
