### ISSUE TITLE
[Bug(?)] Key locked on 3 or more button press

### ISSUE THREAD

**Issue by ZueyEnfe** [Julow/Unexpected-Keyboard#248]
When I press 3 button or more on the keyboard, it will lock on repeating press that can only be stopped by colapsing the keyboard

https://user-images.githubusercontent.com/99162380/204195642-479aa99b-0185-422a-be8c-fde066afa452.mp4

can somone confirm this? Also I'm using lastest f-droid ver.

**Comment by Julow** [comment]
Should be fixed in 804ea84.
