### ISSUE TITLE
Rotation breaks keyboard after latest update

### ISSUE THREAD

**Issue by aaronjamt** [Julow/Unexpected-Keyboard#254]
My phone automatically updated the app from the Play Store but now, whenever I rotate the screen while the keyboard is active, it disappears and just shows a small white bar at the bottom. The only way to restore the keyboard is to Force Stop it from the settings app. It works fine in landscape, it works fine in portrait, but changing between them while it's open breaks everything.

**Comment by SakumaDaisukeWaifu** [comment]
Uploading screen-20221213-194440.mp4…

The same thing happen to me except i didnt even rotate the screen . The keyboard just crash & theres weird white color on the bottom of my screen . Cant even type nothing in ohio 🥲

**Comment by SakumaDaisukeWaifu** [comment]
https://vimeo.com/780784811

It crash on my phone Infinix X6511E too. I hv to uninstall for now bc i literally cant use it 🥲

**Comment by GuardCat** [comment]
It's a real problem: Xiaomi Note 9 pro.

**Comment by Julow** [comment]
Thanks for the report. This should be fixed in 7d6306f, I'll release soon.

**Comment by aaronjamt** [comment]
Can confirm that it's fixed, thanks!
