### ISSUE TITLE
Please Revert or make Customizable Border

### ISSUE THREAD

**Issue by DeMoN100** [Julow/Unexpected-Keyboard#256]
Hello I am not a fan of the white edge border color. If this could be reverted or made customizable that would be great.
![Screenshot_20221215_201551_PS App](https://user-images.githubusercontent.com/8564572/208000274-e356629e-9a7d-4769-af0d-1cbcac0cfd13.jpg)

I'd rather stick with the older version which doesn't have this border on the black theme.
![Screenshot_20221214_153245_Bromite](https://user-images.githubusercontent.com/8564572/208000348-60b9e073-efce-4e77-a5a4-b3e6fd0448db.jpg)

**Comment by 0xlne** [comment]
I second @DeMoN100 ; Borderless was working fine until 1.19.0; v1.20.0 introduced the borders; at least please provide an option in the settings to choose the variant.

**Comment by AgentConDier** [comment]
I like how the border looks, but I agree being able to customize it would be better 👍

**Comment by ProminentChrystal** [comment]
Yes please, I want the old theme back, this one is cool but I loved the old one.

**Comment by Julow** [comment]
Thanks for the feedback. Borders removed in dcc4a64.
