### ISSUE TITLE
Crashes and never recovers when folding/unfolding the Z Fold 4 with Android 12

### ISSUE THREAD

**Issue by allan-null** [Julow/Unexpected-Keyboard#257]
To reproduce this bug you just need to fold/unfold the Z Fold 4 while the keyboard is open. Not sure if it affects other foldable phones.

**Comment by Julow** [comment]
Could this be the same bug as in https://github.com/Julow/Unexpected-Keyboard/issues/254 ? It is fixed and released.

Le 16 décembre 2022 03:14:53 GMT+01:00, Allan ***@***.***> a écrit :

**Comment by landfillbaby** [comment]
I think it's a different bug, it's happening if I don't use it for a while on my Pixel 6 with rotation turned off, it seems like at some point it gets unloaded to free up resources and doesn't load in again.

**Comment by Julow** [comment]
This seems like the same bug. Can you try the version 1.20.1 ? It's available soon on f-droid and is already available on the play store. You can also download it here: https://github.com/Julow/Unexpected-Keyboard/releases/tag/1.20.1

**Comment by landfillbaby** [comment]
switched from f-droid 1.20.0 to google play 1.20.1 a few hours ago, seems to be working fine now

**Comment by allan-null** [comment]
> This seems like the same bug. Can you try the version 1.20.1 ? It's available soon on f-droid and is already available on the play store. You can also download it here: https://github.com/Julow/Unexpected-Keyboard/releases/tag/1.20.1

It is the same bug. It's working flawlessly now with the version 1.20.1, thanks!
