### ISSUE TITLE
Keyboard needs to be reselected after every rotate

### ISSUE THREAD

**Issue by KtheVeg** [Julow/Unexpected-Keyboard#258]
I'm using a Samsung S10 using the default un-rooted Android 12. Whenever I rotate my screen (and tap the rotate button in the navigation bar), the keyboard doesn't appear and I need to select another keyboard and switch back to Unexpected Keyboard before I can use it again.

How can I fix this?

Android 12, Samsung Galaxy S10, Unexpected Keyboard version 1.20.0, installed from F-droid

**Comment by AgentConDier** [comment]
Same here, I've got this issue both on my Huawei Mate 20 Pro (Android 10) and Samsung Galaxy A21s (Android 12), same app version.

Now that I know how to make it happen its even more annoying…

**Comment by Julow** [comment]
This should be fixed in version 1.20.1, which is available in the stores since last week.

**Comment by AgentConDier** [comment]
Yup that fixed it, thanks for the heads-up. F-Droid doesn't like running in the background for me, and I last checked on the 17th, probably right before the fix was published.

**Comment by KtheVeg** [comment]
Fixed. All good!
