### ISSUE TITLE
[Feature request]: Adding a key or option to select the previously used keyboard

### ISSUE THREAD

**Issue by darhma** [Julow/Unexpected-Keyboard#260]
First of all, thank you for the excellent work you do in developing this keyboard.

My request is the exact opposite of #34.
I have several keyboards but I generally use unexpected keyboard and the password manager keyboard (kepassdx), in the password manager keyboard if I briefly press the key to change keyboard it directly opens the previously used keyboard (with a long press it opens the menu for selection), for me it would be convenient to have a key with a similar behaviour also on unexpected keyboard so I can easily switch between the two keyboards I use most. 

The 'problem' to avoid conflicts with #34, in my opinion, can be solved either by adding a dedicated key or by adding an option to choose how the key to switch between keyboards should behave (since in any case the key to open the keyboard selection menu generally appears below the keyboard in the"'navigation bar").

**Comment by Julow** [comment]
I implemented this with an option (0f62b30). A long press opens the selection menu.
