### ISSUE TITLE
[Feature Request] add undo and redo

### ISSUE THREAD

**Issue by OilSubjectLoss7** [Julow/Unexpected-Keyboard#262]
key `Z` and `X` has free slots, we could assign `undo` to `Z` and `redo` to `X`

**Comment by Julow** [comment]
You can enable `undo` and `redo` in the settings ("Add keys to the keyboard"). They won't be placed on `Z` and `X` but you can have a try.

These keys don't work in every apps. `Ctrl+Z` is more often handled than `undo`. `redo` rarely have any effect. https://github.com/Julow/Unexpected-Keyboard/issues/242
