### ISSUE TITLE
[Feature Request] Revert the old behavior regarding PIN screen

### ISSUE THREAD

**Issue by OilSubjectLoss7** [Julow/Unexpected-Keyboard#263]
Before the update, when the app force the PIN/Password input scrren, i was able to go between qwerty mode if i swipe to `abc` key/shortcut. but now, after the update i can't anymore, i can only switch `123+` input screen and back to PIN/Password input screen.

**Comment by Julow** [comment]
Fixed in 764cd88. It's not possible to go back to the pin layout from the other layouts but that's for an other time.
