### ISSUE TITLE
Buggy char size between orientation change

### ISSUE THREAD

**Issue by devingfx** [Julow/Unexpected-Keyboard#265]
I have a weird bug on huawei P smart 2019, when keyboard is shown and orientation change, the char on keys gets bigger and bigger when I switch from portrait to landscape back and forth.
It seems left and rigjt margin gets bigger so the place for keys get smaller and letters get huge (keyboard unusable).
![Screenshot_20221229_183549_com brave browser](https://user-images.githubusercontent.com/3640197/209989326-6f90e655-53a0-46c3-aed3-993e3f3c636c.jpg)
![Screenshot_20221229_183607_com brave browser](https://user-images.githubusercontent.com/3640197/209989331-6d784699-7222-47a0-8862-9db1ba3a13bf.jpg)
![Screenshot_20221229_183618_com brave browser](https://user-images.githubusercontent.com/3640197/209989333-829a90d3-e907-4f22-86d4-21597c194e2d.jpg)
![Screenshot_20221229_183629_com brave browser](https://user-images.githubusercontent.com/3640197/209989336-d19f7bbe-311e-4d4e-9759-194e73f88eb5.jpg)
![Screenshot_20221229_183638_com brave browser](https://user-images.githubusercontent.com/3640197/209989340-415b973d-d73d-49e8-93e3-f2bcc5f2ac53.jpg)
![Screenshot_20221229_183651_com brave browser](https://user-images.githubusercontent.com/3640197/209989341-185b4d6d-01db-49f3-a5db-a1aa74000dd3.jpg)

**Comment by Julow** [comment]
Thanks for the report. Should be fixed in c5f5a23

**Comment by devingfx** [comment]
Thx!
Do you have an idea of wich tag version will include this patch?

**Comment by devingfx** [comment]
The 1.20.2 update did correct the issue...
Thx very much!
