### ISSUE TITLE
Cannot open settings on android 7

### ISSUE THREAD

**Issue by zongou** [Julow/Unexpected-Keyboard#266]
Cannot open settings from keyboard on android 7, device is (Redmi note 4x), it is working on android 10.

**Comment by Julow** [comment]
Can you get a stack trace ?

**Comment by zongou** [comment]
[bugreport-2023-01-10-180039.zip](https://github.com/Julow/Unexpected-Keyboard/files/10381383/bugreport-2023-01-10-180039.zip)

In the log file i found this may helps:
01-10 18:00:10.561  1829  1829 W System  : ClassLoader referenced unknown path: /data/app/juloo.keyboard2-1/lib/arm64

**Comment by Julow** [comment]
Sorry, I couldn't see anything in the bugreport. I also fail to reproduce in an emulator.

What happen when you try to open the settings ?

**Comment by zongou** [comment]
> Sorry, I couldn't see anything in the bugreport. I also fail to reproduce in an emulator.
> 
> What happen when you try to open the settings ?

i found the answer, its about Permission of "Display over other apps"
from here [](https://stackoverflow.com/a/74667906)

**Comment by Julow** [comment]
Good to know, thanks!
