### ISSUE TITLE
[Feature Request] merge arrows key with space bar

### ISSUE THREAD

**Issue by akriegman** [Julow/Unexpected-Keyboard#267]
I think it would be a good idea to merge the arrows key with the space bar, or at least to provide an option to do this in the settings. The arrows key doesn't have a normal press, and the space bar doesn't have any swipe functions, so there's no conflict. Here are some of the advantages and opportunities I see for this idea:

- the arrows key is kinda hard to reach in the corner.
- I keep accidentally pressing enter when I'm trying to pree right. Hopefully this change might prevent that.
- this would align better with other keyboards, since swiping on the space bar to move the cursor is a common feature on many keyboards these days.
- since the space bar is wide, we could take this as an opportunity to increase the sensitivity just for the left and right arrows, since precision cursor adjustments can be difficult.
- we could even take it a step further and have the distance you swipe be related to the distance the cursor moves, rather than the speed at which the cursor moves. This is how it works in Gboard for example, and I think this is better for precision cursor adjustments. This might make it harder to generate a single press of left or right however. Something to think about.

What do you guys think?

**Comment by Julow** [comment]
This is a commonly requested feature: https://github.com/Julow/Unexpected-Keyboard/issues/7 https://github.com/Julow/Unexpected-Keyboard/issues/46 https://github.com/Julow/Unexpected-Keyboard/issues/95 https://github.com/Julow/Unexpected-Keyboard/pull/102

I had in mind something similar to what you suggest, at least for right and left. The current "modulated repeat" thing is not working well and doesn't seem popular, I would remove it.
I plan to work on this during the year. Of course, contributions are welcome!

**Comment by Julow** [comment]
I just implemented this. See https://github.com/Julow/Unexpected-Keyboard/issues/7#issuecomment-1399625673
I also plan to make the space bar slightly bigger. I don't know what to do with the arrows keys yet.
