### ISSUE TITLE
Keyboard is completelly broken on Godot Engine

### ISSUE THREAD

**Issue by qarmin** [Julow/Unexpected-Keyboard#269]
Steps to reproduce:

(This is shown on video, but simpler step is available below)
- Install Godot from  site - https://godotengine.org/download/android
- Create new project
- Click at + at the left side of screen below "Scena"
- Click multiple times at line edit below "Szukaj:" text

or at the first screen click multiple at lineedit node with text "Filtruj Projekty"

https://user-images.githubusercontent.com/41945903/212307096-1a5904ce-229a-46d9-bd28-78714407bd87.mp4

**Comment by Julow** [comment]
Thanks for the report. This should have been fixed in c5f5a23, which is not released yet. I'll release this weekend.

**Comment by Julow** [comment]
Until then, you can download the last debug build (installs in parallel of the released version) of the master branch: https://github.com/Julow/Unexpected-Keyboard/actions/workflows/make-apk.yml?query=branch%3Amaster
