### ISSUE TITLE
Improve the design! [feature request]

### ISSUE THREAD

**Issue by Wjxfi** [Julow/Unexpected-Keyboard#273]
your keyboard looks terrible compared to the [Openboard](https://github.com/openboard-team/openboard). You need to improve the design. really...

![301305.jpg](https://user-images.githubusercontent.com/113500363/212477128-8a91e8bb-e819-46db-ba02-da41e890375b.jpg)
![301301.jpg](https://user-images.githubusercontent.com/113500363/212477130-3cdead8b-aa5b-414d-a6c7-0065603df464.jpg)
![301312.jpg](https://user-images.githubusercontent.com/113500363/212477139-ec03b39e-ff92-49be-9db9-6ccb9c648f4a.jpg)
![301303.jpg](https://user-images.githubusercontent.com/113500363/212477133-7b87d828-ff98-44e7-b4a5-bf14a61eea6b.jpg)
I just don't want to use it even because of this design

**Comment by Julow** [comment]
This issue doesn't show anything actionable. Please give specific feedback, or even better, contribute code.
