### ISSUE TITLE
copy history [feature request]

### ISSUE THREAD

**Issue by Wjxfi** [Julow/Unexpected-Keyboard#275]
https://user-images.githubusercontent.com/113500363/212478327-432619fa-f4a9-4e68-92f1-3c56871166ae.mp4

additionally:
you can set the clipboard log storage time. 0-120 minutes
(as in [Openboard](https://github.com/openboard-team/openboard))

**Comment by Julow** [comment]
Maybe related: https://github.com/Julow/Unexpected-Keyboard/issues/239 https://github.com/Julow/Unexpected-Keyboard/issues/195 https://github.com/Julow/Unexpected-Keyboard/issues/234

**Comment by Julow** [comment]
Indeed.

**Comment by Julow** [comment]
Implemented in https://github.com/Julow/Unexpected-Keyboard/pull/681, debug build is [available here](https://github.com/Julow/Unexpected-Keyboard/actions/runs/9727168851?pr=681). Feedback welcome :)

**Comment by Julow** [comment]
https://github.com/Julow/Unexpected-Keyboard/pull/681 is merged.
