### ISSUE TITLE
Improve the design, please (concept)

### ISSUE THREAD

**Issue by Wjxfi** [Julow/Unexpected-Keyboard#278]
I want it to be like this 
![Polish_20230115_022013960.jpg](https://user-images.githubusercontent.com/113500363/212501428-91f1c769-1e54-4725-a72a-540da601a231.jpg)

my concept is much better than the current style
![301312.jpg](https://user-images.githubusercontent.com/113500363/212501494-d5548022-90d0-43f7-a113-993897748e4b.jpg)

I tried to replicate the Openboard style
![301301.jpg](https://user-images.githubusercontent.com/113500363/212501532-34a2ae53-8b23-4536-959f-b09085d06e8e.jpg)

**Comment by Julow** [comment]
According to your pictures, it seems that you want keys with no borders and of the same color as the background and a different color for the margin around the keyboard. In addition to using the same accent color as the application.

Contributions to the code are welcome.

**Comment by Julow** [comment]
Thanks for your time but this issue is not actionable. I'll close.
Feel free to open issues to suggest specific changes.
