### ISSUE TITLE
[Request] Make the space bar as a scroll(left right)

### ISSUE THREAD

**Issue by OilSubjectLoss7** [Julow/Unexpected-Keyboard#281]
i know the hold repeat mechanic is in conflict with it, but double tapping then hold it then swiping left or right should do the trick.   
Most keyboard app does it. and please, do not remove the arrow buttons if you decided to implement this. they're very useful for precise movement.

**Comment by Julow** [comment]
This has been implemented: https://github.com/Julow/Unexpected-Keyboard/issues/7
