### ISSUE TITLE
[Feature request] Make tapping arrow button optionally do space

### ISSUE THREAD

**Issue by Silent-Hunter** [Julow/Unexpected-Keyboard#283]
I have an issue where when I type, I often accidentally hit the arrows key instead of the spacebar. I noticed the arrows key does nothing when you just tap it. It would be a great help to me if there was an option to make it simply make a space if you just tap it instead of swiping.

**Comment by Julow** [comment]
There might be something on this key in the future: https://github.com/Julow/Unexpected-Keyboard/issues/204
Perhaps the space bar should be longer ?
I'm planning to implement https://github.com/Julow/Unexpected-Keyboard/issues/7 and make the space bar slightly bigger.

**Comment by Silent-Hunter** [comment]
I do like the arrows key having up and down arrows also though, hopefully that functonality will be retained too.

**Comment by Julow** [comment]
I've slightly increased the width of the spacebar (5f283cd). This only partially solves your problem but I'm not willing to implement the proposed fix.
