### ISSUE TITLE
no-delay mode (feature request)

### ISSUE THREAD

**Issue by Wjxfi** [Julow/Unexpected-Keyboard#285]
for the "delete", "reversed delete", "ctrl + delete" buttons

interferes. On another keyboard I got used to it without delay

**Comment by Julow** [comment]
I don't understand. Can you write an example ?

**Comment by Julow** [comment]
Some delay is needed to be able to reliably delete once. I've experimented with fast repeating keys in the past without success, it's not precise enough. I'll close this in favor of https://github.com/Julow/Unexpected-Keyboard/issues/46

You might want to try the new "sliding" feature https://github.com/Julow/Unexpected-Keyboard/issues/7

**Comment by Julow** [comment]
Delete to the right is used less often than delete to the left. Shift+sliding should be enough in this case.

You can reduce the delay in the settings, but that will affect the repeat delay of every keys.
