### ISSUE TITLE
Bug: Visual glitch

### ISSUE THREAD

**Issue by cyzuvu** [Julow/Unexpected-Keyboard#289]
Device Model: M2004J19C (Android12)
API Level: 31

Keyboard shadow shows up for split second on the upper portion of the screen in applications like DuckDuckGo (during tab opening) and Infinityforreddit (when searched).

https://user-images.githubusercontent.com/124552451/216899326-641892c1-99ee-402e-be17-07b082a676af.mp4

**Comment by K4zoku** [comment]
I have tested on Infinity and cannot reprocedure that glitch

**Comment by vladgba** [comment]
PUBG has stable behavior
![Screenshot_20230506-181509_PUBG_MOBILE](https://user-images.githubusercontent.com/11693645/236632792-e3b304f9-1d09-401a-8f4f-307a55c01775.png)

i thinking we can fix it using ViewGroup wrapper for keyboard View as there https://github.com/vladgba/VKeyboard/commit/187a9efd5fb5b1159a6a150affa6488c16467f4a

**Comment by Julow** [comment]
@vladgba Thanks a lot for debugging this! Can you open a PR to allow the CI to build the apk ?

**Comment by Julow** [comment]
Closed by https://github.com/Julow/Unexpected-Keyboard/pull/363
