### ISSUE TITLE
[Feature Suggestion] Accents for Vietnamese keyboards

### ISSUE THREAD

**Issue by rVnPower** [Julow/Unexpected-Keyboard#290]
Hello! I am very interested in this project and I wanted to contribute too. We are currently translating the app and implementing the Vietnamese layout for this keyboard. Only the accents for some Vietnamese characters are missing from the list. 

- The hook above (u -> ủ)
- The underdot (u -> ụ)
- The horn (u -> ư)

Vietnamese keyboards also use the breve, the acute, the grave, the tilde and the circumflex, which were already included in the list.

**Comment by Julow** [comment]
Thanks for your interest. @K4zoku has implemented the accents and written the layout in https://github.com/Julow/Unexpected-Keyboard/pull/291
Feel free to review the PR, especially the placement of the accents.
