### ISSUE TITLE
Enabling the number raw almost hides the lowest raw

### ISSUE THREAD

**Issue by sudo-nice** [Julow/Unexpected-Keyboard#294]
Please, see the screenshots:
<details>
  <summary>Disabled number raw</summary>

![normal](https://i.imgur.com/JPA281l.jpeg)

</details>
<details>
  <summary>Enabled number raw</summary>

![number](https://i.imgur.com/D9hyv5U.jpeg)

</details>

Changing keyboard height didn't help.
I'm on Android 9, Huawei tablet, model JDN2-L09.

**Comment by Indranil012** [comment]
increase bottom margin

**Comment by errr-maxx** [comment]
> increase bottom margin

Then it looks like this:

![Screenshot_2023-02-14-17-40-14-54_fabcf84468fe24a21c455c8746eca541](https://user-images.githubusercontent.com/30185766/218770188-c87d83a4-c1bc-418c-95e7-c97ef149fc17.jpg)
and
![Screenshot_2023-02-14-17-37-31-91_fabcf84468fe24a21c455c8746eca541](https://user-images.githubusercontent.com/30185766/218769988-57ab99b6-1ce1-4682-8297-de6a074e8404.jpg)

**Comment by Julow** [comment]
Thanks for the report. Fixed in 798494e
