### ISSUE TITLE
[Feature Request] An option to bring back black theme borders/outlines

### ISSUE THREAD

**Issue by JackDotJS** [Julow/Unexpected-Keyboard#296]
A few months ago, this keyboard had an update to the black theme that introduced a simple border around each key. I was a *huge* fan of this change, because it made it significantly easier to see which corner characters belonged to which key. 

Unlike the other themes, the black theme normally has absolutely no discernible borders, and no difference between the keys and the keyboard background (y'know... cus it's supposed to be all black). This creates an issue where individual keys can be nearly impossible to distinguish at a glance, which was easily solved by drawing a thin border around them. This solution is great, because it distinguishes each key without having to add an entire background color, helping to still keep most of the keyboard solid black as intended (which, of course, helps with battery life on devices with OLED displays).

However, despite all this, it was quickly removed after some complaints in #256.

I personally believe keeping this border as a customization option would be a great improvement for this keyboard, maybe as an "alternative black" theme. Please consider it!

**Comment by zongou** [comment]
it will be better if user can have a system to manage color scheme, to set these color scheme related properties in one place

**Comment by JackDotJS** [comment]
i do agree that fully customizable themes would be a much better long-term solution, but that suggestion is already covered in #222.

here, i'm just asking for a simple extra theme to go alongside the current black theme, which would be significantly easier to implement in the short term. adding new themes is as simple as updating a single XML file as far as i can tell. in fact, i might just try making a PR for it

**Comment by JackDotJS** [comment]
ok turns out there was way more to it than i initially realized lol
still, not too complicated.

**Comment by Julow** [comment]
Merged in https://github.com/Julow/Unexpected-Keyboard/pull/297. Thanks for your time.
