### ISSUE TITLE
swipe behaviour could be explained better

### ISSUE THREAD

**Issue by a1291762** [Julow/Unexpected-Keyboard#3]
Nothing on the store listing or in the app let me know how to use the keyboard (specifically the alternate symbols that need swipes). It's on the GitHub readme but how many people will find that?

It's easy once you know what to do, but it took a bit of head scratching before I figured it out.

**Comment by Julow** [comment]
Thanks for the report. I'll update the description to be the same as the one in the README during the next upgrade.
In the meantime, do you have a suggestion to explain it better ?

**Comment by a1291762** [comment]
After reading the README it made sense, so I guess putting that in front of
people discovering the app might be enough?

**Comment by Julow** [comment]
I've improved the documentation for the release. Please re-open if there's something missing.
