### ISSUE TITLE
Superscript modifier for every letters

### ISSUE THREAD

**Issue by Wjxfi** [Julow/Unexpected-Keyboard#301]
inside "add keys to the keyboard" add: min and sm (minimal and small) (you can call it something else)
![Polish_20230222_025852875.jpg](https://user-images.githubusercontent.com/113500363/220485933-5de49f83-8857-4788-8cc8-4b93d05a672e.jpg)
they are near "l".

it should work like caps lock added from "add key to keyboard".

min will reduce the letters. e.g., ⁿ and ʳ. This is necessary for mathematicians. In 123+ it takes too long to click to come to them and there are very few there. This will allow you to use them all at once and very quickly

sm - the same for numbers (e.g. ⁶, ³)
(this will be instead of the usual numbers)

**Comment by Julow** [comment]
These are called "subscript" and "superscript" and are implemented here https://github.com/Julow/Unexpected-Keyboard/blob/master/srcs/juloo.keyboard2/KeyModifier.java#L444-L500
I'd appreciate if you could add the missing symbols.

**Comment by Julow** [comment]
You need to add them to your layouts directly for now. Notice that they are not implemented for every letters.

**Comment by Julow** [comment]
This is implemented since f522a678f97a1cf21fa27ea603d9f9af83e93140
