### ISSUE TITLE
[Feature Request]Add an option to bring back side swiping space key to change language layouts

### ISSUE THREAD

**Issue by DimasDSF** [Julow/Unexpected-Keyboard#303]
Currently side swipe acts as an arrow key while there is a dedicated "arrows key" next to it, lots of apps do not correctly support arrow keys and just disable input when they are used especially when the input box is empty. After using this keyboard for multiple months I've built muscle memory to swipe space to switch layouts and now it just causes input loss.

**Comment by Julow** [comment]
The keyboard never had this. Perhaps you are thinking of a different keyboard ?

In the settings, you can turn on the "Switch to the last used keyboard" option. The keyboard key will immediately switch to the previously used keyboard instead of prompting. The prompt is accessible by a long press.
Would that work for you ?

**Comment by DimasDSF** [comment]
I may have worded that incorrectly but before the latest update I could swipe the space key to change languages

**Comment by Julow** [comment]
You can try previous releases here: https://github.com/Julow/Unexpected-Keyboard/releases

**Comment by DimasDSF** [comment]
My bad, just downgraded to the previous version and apparently what I thought was a side swipe action was always the swipe up action, it just worked with side swipes too because there were no other actions on the space key. Still would be nice if there was a way to get the old behavior back.

**Comment by Julow** [comment]
This key switches between two layouts, there's no need for a left and right movement. Do you wish for an option to disable the new left and right keys ?

**Comment by DimasDSF** [comment]
Yeah, that would work.

I took a look at the space bar arrows code and I wonder if it would be possible to make the old 4 way arrows key work the same way as the new swipe(move cursor for the distance swiped, whereas now it is recognised as an arrow key being held) preferably as a toggle not to inconvenience the users who are used to the current behavior?

**Comment by Julow** [comment]
I would prefer not to add any option. The 4 way arrows key is used to type arrows once while the space bar is preferred for moving the cursor in a text field. This seems like a popular feature.

I would prefer not to maintain behaviors that were not added on purpose. Maintaining your use case has a huge cost that I'm not willing to pay.
