### ISSUE TITLE
Navigation bar overlaps the bottom row when the number row is enabled

### ISSUE THREAD

**Issue by eandersons** [Julow/Unexpected-Keyboard#309]
Android navigation bar overlaps the bottom keyboard row when the number row is enabled.
The same behavior was observed with Android 7.0, 8.0, 8.1 and 11.

![Screenshot_20230301-105926](https://user-images.githubusercontent.com/9976861/222092127-fd878347-4723-4e01-980b-4ff7b875620c.png)

**Comment by Julow** [comment]
This might be solved in 798494e. Can you try one of the latest debug build ? https://github.com/Julow/Unexpected-Keyboard/actions/workflows/make-apk.yml

**Comment by eandersons** [comment]
Yes, seems that the mentioned commit resolves this issue.
