### ISSUE TITLE
Let users create layouts

### ISSUE THREAD

**Issue by GrimPixel** [Julow/Unexpected-Keyboard#31]
I think it could be a feature to let users create his/her own keyboard layouts and load it into the program. There is no perfect keyboard layout for a language, so there are always new layouts.

**Comment by Julow** [comment]
This is a huge feature that is more complicated in itself than the current app. I don't plan on implementing it and I don't plan on slowing down the development of the app because of this.

Remember that this keyboard is intended for programmers. It shows all the ascii characters because programming use mostly that and support a few other characters via dead keys for the few languages that it supports.

**Comment by eandersons** [comment]
This indeed would be a useful feature. Even programmers might want to tweak layout to move around some characters or add new ones. Some programmers or other people might prefer Unexpected Keyboard as an overall keyboard application, therefore the ability to make customizations would be even more desirable.

For example, lets take a look at the pull request #29. I made a new Latvian specific QWERTY layout to easier access diacritic characters. This part is fine, but I also took the liberty to make additional adjustments (for example, I moved dot to the key that is located at the right side of the space key and placed similarly looking special characters near each other so they would be easier to spot) and I still am thinking about some more tweaks (for instance, moving some characters to the space key). I do not know if @Julow will accept these changes and if other Latvians would find this customized layout useful.

Of course, I fully understand @Julow's will to focus on the main functionality of this application, so right now the only option is to make a fork of this repository, add new or modify existing layouts and manually [build the application](/Julow/Unexpected-Keyboard/blob/master/CONTRIBUTING.md#building-the-app) and meanwhile wait for someone who would be willing to implement this feature.
I would like to, but I have no experience with Java and mobile application development, so it would take forever for me to do this.

Thank you for your attention and have a nice weekend!

**Comment by amiaship** [comment]
I respect the choice not to implement a layout customizing menu within the application itself. It would slow your work and increase the application size. What if you made the application able to accept layouts uploaded from a text file, and left it up to us users to learn to make our own layout files? QMK comes to mind.

**Comment by Julow** [comment]
Such a layout description exists within the app (see for example [qwerty.xml](https://github.com/Julow/Unexpected-Keyboard/blob/master/res/xml/qwerty.xml)) but it is not stable.

The main inconvenient would be that custom layouts may stop working after an upgrade. You would need to read the changelog to understand what you need to change.

An advantage is to test new layouts before proposing them without having to build the app.

@amiaship Would you be interesting in implementing this ?

**Comment by Silent-Hunter** [comment]
I would love this feature of loading layouts from a file. I want to love this keyboard, but swiping on any buttons in the bottom row to access their extra characters hurts my thumbs after a very short amount of time. I'd love to move the shortcuts from those bottom keys to the next row up.

**Comment by Julow** [comment]
I've added this option (e745c81). It's very basic at the moment, it won't even report errors.
I don't invest time in polishing this option as I'm not convinced I should keep it yet. Contributions are still welcome.
