### ISSUE TITLE
[feature request] Do not remove swipes for keys that are also available on the numpad

### ISSUE THREAD

**Issue by slashdevslashurandom** [Julow/Unexpected-Keyboard#310]
The numpad feature in the newer versions of this app is great, although it does get a bit annoying when the usual diagonal swipe for a character (like a period or a digit) disappears just because that character is now available on the numpad instead.

I think there should be an option to prevent the keyboard from removing swipes from the regular part of the keyboard just because the characters for those swipes are instead available on the numpad.

**Comment by Julow** [comment]
You are right, this is pretty annoying. No need for an option, this behavior is gone in 0da02d6.
