### ISSUE TITLE
Unable to write specials characters like comma, semilcolon (or ? / :, etc) ?

### ISSUE THREAD

**Issue by quoidautre** [Julow/Unexpected-Keyboard#311]
Hi,

I've just installed the app, but I can't write specials characters (? , . ; / !, etc).
It's just a bug or what ?

I don't find a "how to" neither :)
Can you help me please ?

Thanks,
F

**Comment by Julow** [comment]
You need to press on the key and swipe your finger toward a symbol in a corner.

**Comment by quoidautre** [comment]
Thanks a lot
