### ISSUE TITLE
[Bug] swipe up-left outputs up-right key

### ISSUE THREAD

**Issue by lrvideckis** [Julow/Unexpected-Keyboard#315]
I've narrowed it down to this commit

https://github.com/Julow/Unexpected-Keyboard/commit/a6fe5cae00c58365d3ca261783cc745006b2f117

(It occurs after this commit, and doesn't occur before it)

**Comment by lrvideckis** [comment]
https://user-images.githubusercontent.com/33103480/224506332-ac32d60e-c43c-488d-a3a5-537979704787.mp4

**Comment by Julow** [comment]
This has annoyed me for more than a week. Fixed in 2f938dc.
