### ISSUE TITLE
[Feature request] Add Workman layout

### ISSUE THREAD

**Issue by popeyes-chicken** [Julow/Unexpected-Keyboard#317]
This is my absolute favorite keyboard app but recently I switched my layout from Qwerty to Workman, so for the time being I have to use AnySoftKeyboard. 

I'd love it if this layout were supported (I tried adding it myself using the guidelines but I had issues installing the apk I couldn't work out :/)

**Comment by Julow** [comment]
To create a new layout, you need to make a `.xml` file that looks like this: https://github.com/Julow/Unexpected-Keyboard/blob/master/res/xml/qwerty.xml

**Comment by Hourglass-Hayden** [comment]
I've made the xml file, but I can't figure out how to use it. Seems I need to build the app with my xml file in the source code, but idk how to actually build it in the first place even with the instructions on the contributing page.

**Comment by Julow** [comment]
You can try to paste the XML into the "custom layout" option in the settings of the app. If there's an error in the XML, the app will likely not tell you.
If that doesn't work for you, you can paste your layout here and I'll debug it.

**Comment by Hourglass-Hayden** [comment]
That worked, but there's a few problems. First, the default bottom row is present and idk how to remove it, and certain characters (@, #, ?, etc.) have a \ before it. I used Lixquid's online layout editor if that helps.

![IMG_20230627_111114](https://github.com/Julow/Unexpected-Keyboard/assets/121844473/46910f69-c8e2-47c9-a953-ff9f81999cbc)

Here's what's in the xml:

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<keyboard>
  <row shift="0.1">
    <key key0="q" key7="esc" key8="1"/>
    <key shift="0.03" key0="d" key7="\@" key8="2"/>
    <key shift="0.03" key0="r" key7="\#" key8="3"/>
    <key shift="0.03" key0="w" key7="$" key8="4"/>
    <key shift="0.03" key0="b" key7="%" key8="5"/>
    <key shift="0.03" key0="j" key7="^" key8="6"/>
    <key shift="0.03" key0="f" key7="&amp;" key8="7"/>
    <key shift="0.03" key0="u" key7="*" key8="8"/>
    <key shift="0.03" key0="p" key7="switch_numeric" key8="9"/>
    <key shift="0.03" key0=":" key7=";" key8="0"/>
  </row>
  <row shift="0.03">
    <key key0="a"/>
    <key shift="0.03" key0="s"/>
    <key shift="0.03" key0="h" key1="(" key2=")" key3="[" key4="]"/>
    <key shift="0.03" key0="t"/>
    <key shift="0.03" key0="g" key5="-" key6="+" key7="=" key8="_"/>
    <key shift="0.03" key0="y" key5="&lt;" key6=">"/>
    <key shift="0.03" key0="n" key7="selectAll" key8="copy"/>
    <key shift="0.03" key0="e" key1="(" key2=")" key3="[" key4="]"/>
    <key shift="0.03" key0="o"/>
    <key shift="0.03" key0="i"/>
  </row>
  <row shift="0.03">
    <key width="2.03" key0="shift" key5="tab" key6="capslock"/>
    <key shift="0.03" key0="x" key3="{" key4="}"/>
    <key shift="0.03" key0="m" key7="undo" key8="redo"/>
    <key shift="0.03" key0="c" key3="/" key4="\\" key7="|"/>
    <key shift="0.03" key0="v" key1="'" key2="&quot;" key3="`" key4="~"/>
    <key shift="0.03" key0="k" key7="cut" key8="paste"/>
    <key shift="0.03" key0="l" key3="{" key4="}"/>
    <key shift="0.03" key0="." key1="\?" key2="!" key3=","/>
    <key shift="0.03" key0="backspace" key7="delete"/>
  </row>
  <row shift="0.03">
    <key key0="ctrl" key2="alt" key4="fn"/>
    <key shift="0.03" key0="switch_emoji" key7="config" key8="switch_greekmath"/>
    <key width="6.15" shift="0.03" key0="space" key5="left" key6="right" key7="up" key8="down"/>
    <key width="2.03" shift="0.03" key0="enter"/>
  </row>
  <row/>
</keyboard>

**Comment by goyalyashpal** [comment]
yes, having workman layout in default offering will help a lot.  while the key placement is easy, i can't figure out how to even decide for what the symbols placement should be.

following is the layout xml i made from the default template, it has duplicate symbols due to above very reason.


<details><summary>Details</summary>
<p>

```xml
<?xml version="1.0" encoding="utf-8"?>
<!-- This file defines the WORKMAN layout.

A layout is made of keys arranged into rows. Keys can be made bigger with the
'width' attribute and blank space can be added on the left of a key with the
'shift' attribute.

'key0' assigns the symbol on the middle of the key. 'key1', 'key2', etc..
assign symbols to the corners of a key, they are arranged like this:

  1 7 2
  5 0 6
  3 8 4

Keys prefixed with 'loc ' are not visible on the keyboard. They are used to
specify a place for a key, if it needed to be added to the layout later.
(for example, by the "Add keys to keyboard" option)

See bottom_row.xml for the definition of the bottom row and neo2.xml for a
layout that re-defines it.
See srcs/juloo.keyboard2/KeyValue.java for the keys that have a special meaning.
-->
<keyboard name="WORKMAN (US)" script="latin">
  <row>
    <key key0="q" key2="1" key4="loc esc"/>
    <key key0="d" key1="~" key2="2" key3="\@"/>
    <key key0="r" key1="!" key2="3" key3="\#" key4="loc €"/>
    <key key0="w" key2="4" key3="$"/>
    <key key0="b" key2="5" key3="%"/>
    <key key0="j" key2="6" key3="^"/>
    <key key0="f" key2="7" key3="&amp;"/>
    <key key0="u" key2="8" key3="*"/>
    <key key0="p" key2="9" key3="(" key4=")"/>
    <key key0=";" key2="0"/>
  </row>
  <row>
    <key key0="a" key1="loc tab" key2="`" shift="0"/>
    <key key0="s" key2="loc §" key3="loc ß"/>
    <key key0="h"/>
    <key key0="t"/>
    <key key0="g" key2="-" key3="_"/>
    <key key0="y" key2="=" key3="+"/>
    <key key0="n" key4="}" key3="{"/>
    <key key0="e" key3="[" key4="]"/>
    <key key0="o" key2="|" key3="\\"/>
    <key key0="i" key2="|" key3="\\"/>
  </row>
  <row>
    <key width="1.5" key0="shift" key2="loc capslock"/>
    <key key0="z"/>
    <key key0="x" key2="loc †"/>
    <key key0="m" key2="&lt;" key3="."/>
    <key key0="c" key2="&gt;" key3=","/>
    <key key0="v" key2="\?" key3="/"/>
    <key key0="k" key2=":" key3=";"/>
    <key key0="l" key2="&quot;" key3="'"/>
    <key width="1.5" key0="backspace" key2="delete"/>
  </row>
</keyboard>
``` 

</p>
</details> 




* unexpected keyboard 

   <img src="https://github.com/user-attachments/assets/95c58f82-0428-4a7a-88b1-cf38b22a9ab0" width=400px />

* rkkr simple keyboard

   <img src="https://github.com/user-attachments/assets/19670c56-d8ca-4b51-8c06-d273ae411e9d" width=400px />

**Comment by Julow** [comment]
Looks nice! Some keys are present twice on the layout: ;, \, |. Is that intended ?

**Comment by goyalyashpal** [comment]
> following is the layout xml i made from the default qwerty template, it has duplicate symbols due to above very reason.
> \- _me at https://github.com/Julow/Unexpected-Keyboard/issues/317#issuecomment-2526744663_




> Some keys are present twice on the layout: ;, , |. Is that intended ?
> \- _@ Julow at https://github.com/Julow/Unexpected-Keyboard/issues/317#issuecomment-2543059567_

hi!  no, those are not intended.  i just couldnt think where to start regarding symbol placement.  i just duplicated the keys (code lines), & modified their main element.
