### ISSUE TITLE
[Feature Request] Add a multiple selection for a secondary layout

### ISSUE THREAD

**Issue by 2b** [Julow/Unexpected-Keyboard#318]
It would be nice to be able to switch through several layouts instead of primary and secondary layout only.

**Comment by Shareef101** [comment]
so when is it comming

**Comment by Julow** [comment]
I'm planning this for next release, though that might change.

**Comment by Julow** [comment]
Implemented in dad5f57

**Comment by Shareef101** [comment]
where do i install it from

**Comment by Julow** [comment]
You can find a debug APK here: https://github.com/Julow/Unexpected-Keyboard/actions/runs/5708616269

**Comment by Julow** [comment]
One as before. This is tracked in this issue: https://github.com/Julow/Unexpected-Keyboard/issues/396

**Comment by Shareef101** [comment]
> One as before. This is tracked in this issue: https://github.com/Julow/Unexpected-Keyboard/issues/396

Oh please make it fast

**Comment by Julow** [comment]
That's not something you can ask.

**Comment by Shareef101** [comment]
> That's not something you can ask.

Don't get me wrong it was a humble request
