### ISSUE TITLE
Customize height of the virtual keyboard

### ISSUE THREAD

**Issue by GrimPixel** [Julow/Unexpected-Keyboard#32]
I am currently using Multiling O Keyboard. It is highly customizable except for keyboard layouts. I think an important feature is being able to adjust the height of the keyboard so people can type comfortably according to their own habits.

**Comment by GrimPixel** [comment]
I'm sorry, I didn't see that. I mean if it could be adjusted in real time. I wish I could simply drag the upper-left corner to resize its height like O Keyboard.

**Comment by Julow** [comment]
Sorry, I do not wish to implement this feature, to ensures the application remains small and fast.
