### ISSUE TITLE
Nine directions

### ISSUE THREAD

**Issue by GrimPixel** [Julow/Unexpected-Keyboard#322]
There is a competitor: [Thumb-Key](https://github.com/dessalines/thumb-key). It has nine directions. Are you interested in adding this feature: Nine-key keyboards?

**Comment by Julow** [comment]
The keyboard has nine directions already, though no layout use it. I would indeed be interested in a one-hand layout.

Do you wish to experiment with layouts and send a PR ?

**Comment by GrimPixel** [comment]
Glad to know that.
One thing unclear: those “key0=”, “key2=”, ... are not intuitive on their directions. How about numbering them with the nine-key positions and even rename like “key0” to “k0” for compactness?

Here are principles I come up with for such nine-key nine-direction layout creation for now:
1. Reduce the use of the upper-right position as it is hardest to reach;
2. Reduce the use of positions with directions that reaches the ridge of the screen;
3. Reduce the finger movement according to the frequencies of bigrams and letters;

**Comment by Julow** [comment]
Keys are numbered like this for compatibility with existing layouts at the time the positions 5-8 were added. It's possible to introduce `k0..k8` with clockwise numbering while leaving `key0..key8` for a while. Are you interested in doing the work ?

These seems to be nice principles, thanks.

**Comment by GrimPixel** [comment]
Thank you for saying that. I will have a try.
