### ISSUE TITLE
App doesn't run  on some Android versions

### ISSUE THREAD

**Issue by GrimPixel** [Julow/Unexpected-Keyboard#323]
It doesn't work on 8.1.0 and maybe also other versions. The app will instantly quit when tapping on it.

**Comment by Julow** [comment]
This is hopefully fixed with the release from 5 days ago. Can you confirm ?

You can find a release build compatible with the Google Play install: https://github.com/Julow/Unexpected-Keyboard/releases/tag/1.22.1
If you use F-Droid, you'll have to wait a little.

**Comment by GrimPixel** [comment]
Fixed.
