### ISSUE TITLE
Use Unicode characters instead of special fonts

### ISSUE THREAD

**Issue by GrimPixel** [Julow/Unexpected-Keyboard#326]
Symbols:
⇧⇤⇥␣⏎↹🙂⚙🠈🠉🠊🠋⌨⌫⌦⇪
some are converted to images on GitHub.

diacritics:
https://en.wikipedia.org/wiki/Diacritic

**Comment by Julow** [comment]
Most of these symbols don't render properly on most phones. The few symbols that are supported are rendered inconsistently and are not pleasant to see.
Some symbols in the embedded font are not represented in unicode (for example, the two layout switching keys).

The embedded font file is 8kb and doesn't cause any problem.
