### ISSUE TITLE
Switch among more than two layouts

### ISSUE THREAD

**Issue by GrimPixel** [Julow/Unexpected-Keyboard#327]
Currently, only two layout can be switched to each other. There could be a list of layouts to switch from.

**Comment by Julow** [comment]
Dup of https://github.com/Julow/Unexpected-Keyboard/issues/327

**Comment by GrimPixel** [comment]
This is https://github.com/Julow/Unexpected-Keyboard/issues/327 🤣

**Comment by Julow** [comment]
Sorry! Dup of https://github.com/Julow/Unexpected-Keyboard/issues/318
