### ISSUE TITLE
Remove method.xml

### ISSUE THREAD

**Issue by GrimPixel** [Julow/Unexpected-Keyboard#328]
Even if users use other languages, they may want to use English as the default one, at least for unlocking their screen; they may be more used to another layout in that language. They can simply go to settings and select what they want. Thus, method.xml can be omitted.

**Comment by Julow** [comment]
This file is important to specify the default layout that people see. It also defines `extra_keys`, which are most important to people using the QWERTY layout.
People that prefer to use QWERTY as the default are the exception and are asked to select the layout they want in the settings.
