### ISSUE TITLE
Improve layout_of_string and arrays.xml

### ISSUE THREAD

**Issue by GrimPixel** [Julow/Unexpected-Keyboard#329]
Every time a new layout is added, the layout also need to be added here. Is there any ways to simplify that case switch?

**Comment by Julow** [comment]
This is a long time issue that I would like to fix at some point.
An other important issue to consider is the fragile pairing between `pref_layout_values`/`entries`.

**Comment by Julow** [comment]
This is changed in 8ba82d2 and 15c608b. See the updated guidelines: https://github.com/Julow/Unexpected-Keyboard/blob/master/CONTRIBUTING.md#adding-a-layout

Feedback welcome.
