### ISSUE TITLE
Add support for CJKV

### ISSUE THREAD

**Issue by GrimPixel** [Julow/Unexpected-Keyboard#33]
Han characters are not typed like alphabet, but a sequence of letters that turns into a character.

So if Chinese, Japanese, Korean, Vietnamese are going to be supported, two mechanisms are needed: text replacement and dictionary (key-value pair).

For Chinese, there are two types of input methods: phonetic-based and shape-based. The former includes Pinyin (Latin script) and Bopomofo, the latter includes Wubi and Cangjie. Both types turn their inputs into Hanzi (Han script). The phonetic-based are able to input words but hard to input characters because there are plenty of homophones to select from; the shape-based are good at inputing characters but unable to input words because of ambiguity of the input. Both types need text replacement.

For Japanese, there are two types of input methods: Kana and Romaji (Latin script). Kana input requires text replacement for voiced and semi-voiced as well as geminized and palatalized sounds. Romaji requires text replacement to convert Romaji into Kana. Both finally require a dictionary to turn Kana into Kanji (Han script) words and characters. Because of plenty of homophones, candidates are to be shown as well.

For Korean, Hangul is used in most cases, while Romaja (Latin script) is also available. The Hangul character is constructed from syllables, which requires text replacement. To input Hanja (Han script), another text replacement is required. Romaja is similar to Romaji in Japanese.

For Vietnamese, Hán Nôm (Han script) can be done with text replacement from Quốc Ngữ (Latin script).

**Comment by Julow** [comment]
Thanks for all the explanations, this was interesting!

Unfortunately, this is too much work and will surely be a lot of work to maintain too.
If you are interested on working on this, I'd suggest forking the app and start working on this without taking care of the other languages and features the keyboard support currently.
Of course I accept contributions but I can't promise I'd be able to keep these languages working over time or add new features for them. Also, I might not accept compromise to the other features.

**Comment by Julow** [comment]
Thanks for the explanations but I don't plan on adding support for new languages all at once. The keyboard doesn't seem to be a good fit for these languages, but if a native user is able to invest time, I'd be happy to add support for these, one by one.
