### ISSUE TITLE
Currency symbols

### ISSUE THREAD

**Issue by GrimPixel** [Julow/Unexpected-Keyboard#330]
Symbols ฿₿₵¢₡₫֏€Ξƒ₲₴₭₾₺₼₦₱£﷼៛₽ރ₹₪৳$₸₮₩¥¤ could be added. The position can be next to emoji.

**Comment by Julow** [comment]
This would be best solved by https://github.com/Julow/Unexpected-Keyboard/issues/204

Do you often use all these symbols ? I'm guessing no and I'll close this issue. Some of them are already present in `Fn` combinations. 

If some of them are most useful to you, please suggest specific modifications.
