### ISSUE TITLE
swipe anywhere if there's only one subkey has been removed?

### ISSUE THREAD

**Issue by OilSubjectLoss7** [Julow/Unexpected-Keyboard#339]
the last update remove the ability to swipe everywhere if there is only one subkey like i.e. :   
   
d key has copy button at the top, before the update i can swipe everywhere and it would press the copy key but after the  update i can no longer do this. it would press the d key instead. i have to like swipe up to press the copy key.   
  
please revert.

**Comment by Julow** [comment]
The `copy` button have been added by the "Add keys to keyboard" option and its position is subject to changes at any time.
It could change after an upgrade or after touching any setting.

Reverting this change would not fix the underlying issue and you will complain again later.
I prefer to place the keys in the most ergonomic position.

**Comment by OilSubjectLoss7** [comment]
I am not specifically referring to the copy key; it is just an example. My main issue is that if there is only one subkey in a button, for example, the ‘A’ button with a subkey ‘paste’ at the top, before, if I held down the A button and swiped anywhere I wanted, it would do the paste subkey. But after recent changes, I have to actually swipe up where the actual subkey is or else it would output the letter ‘A’.

**Comment by Julow** [comment]
The problem remains. The `paste` key could move elsewhere or a different key could be added to an other corner of the `A` button.

This is a reminder that the keyboard can change and that new keys can fill the empty spaces.
