### ISSUE TITLE
Better switching keyboards

### ISSUE THREAD

**Issue by Quantenzitrone** [Julow/Unexpected-Keyboard#34]
When switching keyboards (Upper right corner of the Alt key) it always switches to a specific keyboard, instead of letting me decide.
I'm sorry I compare you to OpenBoard but on Open Board I can decide to what Keyboard I switch. 
This is annoying because I have another Keyboard imput Method from KeePassDX installed which has the same Problem. So It happens that I am stuck in a loop between Magikeyboard and unecpected Keyboard and have to visit the system settings to go back to OpenBoard.

**Comment by Julow** [comment]
Thanks for the report !

**Comment by Julow** [comment]
I changed that (e031de6), will now show the dialog for choosing which keyboard to switch to.

**Comment by Quantenzitrone** [comment]
thanks
