### ISSUE TITLE
Need bullet (•)

### ISSUE THREAD

**Issue by Spike-from-NH** [Julow/Unexpected-Keyboard#345]
I now have Julow Keyboard installed alongside Hacker's Keyboard. Have used HK happily for years but it is famously not being maintained. I like the access to emojis in JK, but I miss two characters from the 8-bit ASCII set: em-dash and large bullet, which I use often. HK has these and many more from UNICODE (like ① etc., helpful for typing lists) using its Compose key.

The swipe of JK is faster than long tap in HK. But I prefer HK's layout ("5-row compact") and especially having period and comma with no gestures at all.

**Comment by Julow** [comment]
I would like to have a compose key as well, it's represented by this issue: https://github.com/Julow/Unexpected-Keyboard/issues/204

Em-dash is `Fn+_`. The bullet would be a great addition, see the `apply_fn_char` function in [KeyModifier.java](https://github.com/Julow/Unexpected-Keyboard/blob/master/srcs/juloo.keyboard2/KeyModifier.java#L187).

I would accept a PR for a HK inspired layout. You would have a lot of modifications to do, though.

**Comment by Spike-from-NH** [comment]
Thanks for the reply—There, I got the em-dash with JK.

You already have Fn+. mapped to ellipsis (useful but not vital exc. on Twitter) so it's not available for bullet. Small bullet (mid dot) seems to be Fn+V.

You may close this issue unless you'd like to keep it open as a memo to do bullet.

**Comment by Spike-from-NH** [comment]
I've read #349 and have found qwerty.xml in the ZIP file. If I modified this for personal use, could I reference the file using Custom Layout ("This option is not meant to be used")? Or must it be built into the package? If this is an option, in what directory must it reside?

**Comment by Julow** [comment]
The layout file can be pasted directly into the "Custom Layout" option. However, if there's an error in the file, the option won't tell you.

**Comment by Spike-from-NH** [comment]
Thank you! This has been tons of fun
![20230430_082539](https://user-images.githubusercontent.com/126838489/235353152-f7fca97c-b47f-40f7-9a6e-c252b533e88d.jpg)

**Comment by Spike-from-NH** [comment]
Indeed @frimdo, your issue showed me that this was an option.

**Comment by Spike-from-NH** [comment]
Here's my XML code:

<?xml version="1.0" encoding="utf-8"?>

<keyboard>
  <row>
    <key key0="1" key1="!" key2="①" key3="¡"/>
    <key key0="2" key1="@" key2="②"/>
    <key key0="3" key1="#" key2="③" key4="loc €"/>
    <key key0="4" key1="$" key2="④" key4="loc ₪"/>
    <key key0="5" key1="%" key2="⑤"/>
    <key key0="6" key1="^" key2="⑥"/>
    <key key0="7" key1="&amp;" key2="⑦"/>
    <key key0="8" key1="*" key2="⑧"/>
    <key key0="9" key1="(" key2="⑨"/>
    <key key0="0" key1=")" key2="⑩" key3="f11_placeholder" key4="f12_placeholder"/>
    <key width="1.67" key0="backspace" key3="delete"/>
  </row>
  <row>
    <key shift="0.33" key0="q" key1="esc"/>
    <key key0="w" key1="~"/>
    <key key0="e" key1="=" key2="loc €"/>
    <key key0="r" key1="≠" key2="loc ₪" key4="selectAll"/>
    <key key0="t" key4="undo"/>
    <key key0="y"/>
    <key key0="u" key1="_"/>
    <key key0="i"/>
    <key key0="o" key1="loc accent_macron"/>
    <key key0="p" key1="+" key3="¶"/>
    <key width="1.33" key0="-" key1="[" key2="]" key3="{" key4="}"/>
  </row>
  <row>
    <key width="0.67" key0="tab"/>
    <key key0="a" key1="`"/>
    <key key0="s" key1="§" key2="loc accent_ring" key3="loc ß" key4="loc accent_ogonek"/>
    <key key0="d" key1="loc accent_grave" key2="loc £" />
    <key key0="f" key1="loc accent_aigu" key2="loc accent_dot_above"/>
    <key key0="g" key1="loc accent_caron"/>
    <key key0="h" key1="←"/>
    <key key0="j" key1="—" key3="loc accent_trema" key4="loc accent_circonflexe"/>
    <key key0="k" key1="→" key3="loc accent_double_aigu"/>
    <key key0="l" key1="…" key3="£"/>
    <key key0=";" key1=":"/>
    <key key0="'" key1="&quot;"/>
  </row>
  <row>
    <key key0="shift" key1="loc capslock"/>
    <key key0="z"/>
    <key key0="x" key1="×"/>
    <key key0="c" key1="loc accent_cedille"/>
    <key key0="v"/>
    <key key0="b" key1="•"/>
    <key key0="n" key1="loc accent_tilde"/>
    <key key0="m"/>
    <key key0="," key1="&lt;"/>
    <key key0="." key1="&gt;"/>
    <key key0="?" key1="¿" key3="/" key8="|" key4="\"/>
  </row>
</keyboard>

**Comment by Julow** [comment]
Thanks for your observations. 

1. I plan to improve this option as soon as I have the time. In the meantime, that's why it's marked as not ready for use.
2. `Fn+!` and `Fn+?` should work. You can also add these to your layouts.
3. You can add a location for these with `loc copy` for example. Feel free to experiment changing qwerty.xml.
4. What option are you trying to crank up ?
5. Would be an appreciated addition.

**Comment by Spike-from-NH** [comment]
Thanks, @Julow.
② After adding these to the keyboard by num. codes, I was able to type them into my Qwerty in quotes, so problem solved.
③ To the contrary, I pulled out the "loc" legends for cut/sel/copy/paste/undo and let them go where they go, if selected in the config.
④ I was referring to the "Label size" config. option; 120% is the maximum allowed, but I would like 140%.
⑤ Yes, please add key click sound! In fact, I enabled vibration but am not getting any.

**Comment by Julow** [comment]
4. I increased the maximum value to 150% in 649aea8.
5. Other issues are tracking this one.

**Comment by Spike-from-NH** [comment]
@Julow, thanks for that!
