### ISSUE TITLE
Downward swipes risk inadvertent touch of Back and Recents

### ISSUE THREAD

**Issue by Spike-from-NH** [Julow/Unexpected-Keyboard#354]
In the QWERTY layout, four gestures extend downward from the bottom tier. Although the user can specify a bottom margin, swiping down may occasionally reach Android's soft Back and Recents buttons, aborting the typing the user was doing.

It would be better if all gestures from the bottom tier were upward (surely the three on the Ctrl and Fn keys). Not sure what can be done about down-arrow; perhaps tap the key to go down, and the other three directions remain swipes. (The northeast corner is not a problem in QWERTY, but in my customization in #345, I felt a northeasterly swipe would occasionally send a text prematurely, so I moved it.)

If the bottom tier were under the control of layout files, it would enable further customization.

**Comment by Spike-from-NH** [comment]
This enables another evening of experimentation!

As before, you may close this issue, or leave it open as a reminder if you think it is something you should change in the built-in layouts.

**Comment by Spike-from-NH** [comment]
@Julow, I've now regenerated the bottom tier in my custom Qwerty.xml, except that I can't tell from Keyvalue.java how to get ① the sliding effects of the space bar (at key5 and key6), or ② the "Done" legend of the Enter key (at key2) or even what it does.

**Comment by Julow** [comment]
To have the sliding effect, your space bar must look like this:
```xml
<key key0="space" key5="left" key6="right" slider="true"/>
```
At the moment, this effect can only be used with `key5` and `key6`.

The label of the enter key cannot be configured and is changed dynamically by the app.

**Comment by Spike-from-NH** [comment]
Thanks, @Julow. I figured out most of that after I wrote. I thought I had gotten a slider effect with key7 and key8 as well (in a merged up-arrow/down-arrow key) but it is merely auto-repeat, not the more precise control of the slider. Supporting key7 and key8 would be a nice enhancement.
