### ISSUE TITLE
[Feature Request] Ability to toggle holding any key pressed until let go to type character. 

### ISSUE THREAD

**Issue by TehDomic** [Julow/Unexpected-Keyboard#359]
As a user with brainfarts I'm often resting my finger on a key before I know what to type next,
It would help users also avoid typing the same character multiple times while holding the key pressed. This would include any key as far as I can think of. 🤔
Including the corner key actions when swiping a key diagonally.
I'd be happy to test a test apk build if it's available somewhere later.

Looks like a promising app as well. :)

**Comment by Spike-from-NH** [comment]
This tendency, like most errors in athletic competition, is overcome by training and repetition. I have the same problem with swipes that I will have to unlearn. (In Hacker's Keyboard, a long-press calls up the key's alternate-character menu.)

Do you realize that Unexpected Config menu has options for "Key repeat timeout" (how long to wait before generating the 2nd char) and "Key repeat interval"? Setting the former to 2.000 sec should make this mistake rare.

**Comment by Julow** [comment]
Key repeat is not terribly useful and I've heard many times people that didn't know it was here or were annoyed by it.

The keyboard currently understand long presses:
- holding a modifier locks it
- the key for switching between keyboards have a different behavior when long pressed
- key repeat is useful for some keys like backspace, delete, up and down arrows, etc..

One thing to keep in mind is that holding a key is not useful on purpose. A long press breaks the flow of typing and this app have been built primarily to get rid of long presses.

I'm not against experimenting with long presses but I don't want it to appear in normal typing. You can experiment with it in [`KeyModifier.modify_long_press`](https://github.com/Julow/Unexpected-Keyboard/blob/master/srcs/juloo.keyboard2/KeyModifier.java#L71).

**Comment by Spike-from-NH** [comment]
I wouldn't say long-press "breaks the flow of typing," but Unexpected's swipes are faster than long-presses in Hacker's Keyboard. However, could you add an option in the XML file with which to specify what a key does (instead of repeat) when long-pressed?

**Comment by Julow** [comment]
> could you add an option in the XML file with which to specify what a key does (instead of repeat) when long-pressed?

This could help trying various ideas however I think this is a bad idea. What keys would you modify on a long press ?

**Comment by Spike-from-NH** [comment]
I don't want to long-press anything; again, swiping is faster. So all I have to do is not use the feature if you add it! @TehDomic might want to tag the key he rests his finger on so it doesn't repeat.

Helpful you say, and invisible except to users who customize. What makes it a bad idea?

**Comment by Julow** [comment]
The time needed to implement and maintain new things, especially things that were not planned, is huge. On the other hand, I don't think this idea would fix the issue.

**Comment by Anarchtism** [comment]
> However, could you add an option in the XML file with which to specify what a key does (instead of repeat) when long-pressed?

Man, I need this so bad.

Like I mentioned in #520 
> I have a use case for long press actions;
For number input using a MessagEase layout. Since most of the keys already have swipe actions and switching to numbers mode chages the layout of the keyboard.
>
> ANIHORTES(space) -> 7894561230

**Comment by TehDomic** [comment]
Closing this issue as the project seems to need more contributors to grow.

**Comment by Julow** [comment]
Hi, key-repeat is not that useful and discussions about that are happening in https://github.com/Julow/Unexpected-Keyboard/issues/548, https://github.com/Julow/Unexpected-Keyboard/issues/520

I plan to add an option to disable key-repeat in next release. We need more ideas to make long pressing more useful.
