### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by eandersons** [Julow/Unexpected-Keyboard#36]
Are strings translatable? If no, are there any plans to make application multi-language?

**Comment by Julow** [comment]
It's definitely possible to translate the application. This wasn't planned but I'm open to the idea.
Let me translate it to French first so I can be sure every strings are translatable.

**Comment by Julow** [comment]
I've added a translation (baf867a9f9075f4fed43534770afc44f0473b131), the application is translatable :)
