### ISSUE TITLE
voice typing shortcut

### ISSUE THREAD

**Issue by uGeek** [Julow/Unexpected-Keyboard#361]
sometimes you need to multitask to send a text message and voice typing is comfortable. Would it be possible to add this option to launch it directly from the keyboard?

**Comment by Julow** [comment]
Implemented in 85cdb9b. You can find the debug APK here: https://github.com/Julow/Unexpected-Keyboard/actions/runs/5164566094

**Comment by uGeek** [comment]
Thank you very much!!!! Fantastic
