### ISSUE TITLE
Allow for keyswaps on bottom row?

### ISSUE THREAD

**Issue by rbreaves** [Julow/Unexpected-Keyboard#362]
I freaking love this app!! Thank you so much for creating it, there is only one tweak I would make to this app that would literally make it perfect for my remote mac/pc/linux use cases. I remap literally everything to use the Meta key as my primary modifier (aka Ctrl), and I use Alt a lot, and still use Ctrl when I need it for terminal usage mostly.

Can we implement 2 or 3 toggles that would re-organize the bottom row slightly?

https://github.com/Julow/Unexpected-Keyboard/blob/master/res/xml/bottom_row.xml

The end result I am looking for is.
```
<?xml version="1.0" encoding="utf-8"?>
<row height="0.95">
  <key width="1.1" key0="ctrl" key1="loc switch_greekmath" key2="" key4="switch_numeric"/>
  <key width="1.1" key0="alt" key1="loc fn" key2="change_method" key3="switch_emoji" key4="config"/>
  <key width="1.7" key0="meta" key1="" key2="" key4=""/>
  <key width="3.3" key0="space" key7="switch_second" key5="left" key6="right" slider="true"/>
  <key width="1.1" key7="up" key6="right" key5="left" key8="down"/>
  <key width="1.7" key0="enter" key2="action"/>
</row>
```

In my opinion this is the layout that would appeal to TONS of programmers that use macOS daily, granted many of them are iPhone users as well, but there are tons of developers that only use macs and heavily make use of all 3 modifier keys unlike dominantly Windows and Linux users that try to get by with only 2 modifier keys plus a shift key or whatever contortions they use.

**Comment by rbreaves** [comment]
@Spike-from-NH I am confused, where am I supposed to put my new qwerty.xml file? When I select custom layout in the app vs using Qwerty it never prompts me for a file or location?

I can add the custom line you mentioned, but I don't see what good that will do if I can't point it to an xml file. Am I supposed to compile, build and install this entire application? At which point was the point of adding custom anything...

**Comment by Spike-from-NH** [comment]
No, it never asks you for a filename. Here's how to do it:
① Get Qwerty anywhere on your phone.
② Apply the edits.
③ Do Select all, Copy (Ctrl-A Ctrl-C).
④ Call up Unexpected Config with the gear logo.
⑤ You've already selected Custom layout.
⑥ Go to the bottom of the menu and click.
⑦ Tap on the editing area if necessary to bring up the soft keyboard.
⑧ Your text is in the clipboard; do Paste (Ctrl-V) and click OK. (If there was already text there, do Seldct all, Paste to replace it.)
⑨ Return to your edit. If the keyboard reflects your edits, save the file.

**Comment by rbreaves** [comment]
Thank you for breaking that down as what you said earlier made me think I needed to type in just that specific line yiou mentioned earlier and I assumed it would want me to point to an actual xml file, not paste it all in together like that, but I am happy to do that as well!!

Here is what I came up w/ for any one that is curious!

![IMG_1283](https://github.com/Julow/Unexpected-Keyboard/assets/10969616/39126481-fa40-4c90-87ec-fda61cdb8e38)


https://pastebin.com/raw/iMXf8Chz

```
<?xml version="1.0" encoding="utf-8"?>
<!-- This file defines the QWERTY layout.

A layout is made of keys arranged into rows. Keys can be made bigger with the
'width' attribute and blank space can be added on the left of a key with the
'shift' attribute.

'key0' assigns the symbol on the middle of the key. 'key1', 'key2', etc..
assign symbols to the corners of a key, they are arranged like this:

  1 7 2
  5 0 6
  3 8 4

Keys prefixed with 'loc ' are not visible on the keyboard. They are used to
specify a place for a key, if it needed to be added to the layout later.
(for example, by the "Add keys to keyboard" option)

See bottom_row.xml for the definition of the bottom row and neo2.xml for a
layout that re-defines it.
See srcs/juloo.keyboard2/KeyValue.java for the keys that have a special meaning.
-->
<keyboard bottom_row="false">
  <row>
    <key key0="q" key2="1" key4="esc"/>
    <key key0="w" key1="2" key2="~" key3="@"/>
    <key key0="e" key1="3" key2="!" key3="#" key4="loc €"/>
    <key key0="r" key2="4" key3="$" key1="loc ₪"/>
    <key key0="t" key2="5" key3="%"/>
    <key key0="y" key2="6" key3="^"/>
    <key key0="u" key2="7" key3="&amp;"/>
    <key key0="i" key2="8" key3="*"/>
    <key key0="o" key1="loc accent_macron" key2="9" key3="(" key4=")"/>
    <key key0="p" key2="0" key3="\" key4="|" key5="f11_placeholder" key6="f12_placeholder"/>
  </row>
  <row>
    <key shift="0.5" key0="a" key1="tab" key2="`"/>
    <key key0="s" key1="loc accent_ring" key3="loc ß" key4="loc accent_ogonek"/>
    <key key0="d" key1="loc accent_grave" key2="loc £" key3="loc accent_aigu"/>
    <key key0="f" key1="loc accent_dot_above"/>
    <key key0="g" key1="loc accent_caron" key2="-" key3="_"/>
    <key key0="h" key2="=" key3="+"/>
    <key key0="j" key1="loc accent_trema" key2="loc accent_circonflexe" key4="}" key3="{"/>
    <key key0="k" key1="loc accent_double_aigu" key3="[" key4="]"/>
    <key key0="l" key1="&gt;" key2="&lt;" key3="," key4="."/>
  </row>
  <row>
    <key width="1.5" key0="shift" key2="loc capslock"/>
    <key key0="z"/>
    <key key0="x"/>
    <key key0="c" key1="loc accent_cedille" />
    <key key0="v" />
    <key key0="b" key2="?" key3="/"/>
    <key key0="n" key1="loc accent_tilde" key2=":" key3=";"/>
    <key key0="m" key2="&quot;" key3="'"/>
    <key width="1.5" key0="backspace" key2="delete"/>
  </row>
  <row height="0.95">
    <key width="1.1" key0="ctrl" key1="loc switch_greekmath" key2="" key4="switch_numeric"/>
    <key width="1.1" key0="alt" key1="loc fn" key2="change_method" key3="switch_emoji" key4="config"/>
    <key width="1.1" key0="meta" key1="" key2="" key4=""/>
    <key width="3.9" key0="space" key7="switch_second" key5="left" key6="right" slider="true"/>
    <key width="1.1" key7="up" key6="right" key5="left" key8="down"/>
    <key width="1.7" key0="enter" key2="action"/>
</row>
</keyboard>
```
