### ISSUE TITLE
Disable PIN layout

### ISSUE THREAD

**Issue by sdrapha** [Julow/Unexpected-Keyboard#370]
The addition of the PIN Layout was a good thing, but the implementation of it can be improved.

I personally don't like it at all, every time it comes up, I'm probably expecting the other number layout. So the number order has muscle memory consistency, and I have the other symbols available, I'm often typing IP numbers or formulas, and the PIN layout is just annoyingly coming up every time.

My plan was to fix it myself and do a PR, (If I get enough time), But first I want to collect opinions on the approach for the fix.
Should I make it an option in the settings?
Which kind of option? 

1-To enable or disable the PIN layout automatically coming up feature, in a checkbox? ant that is it?

2-To have a list of options to set which layout is always the default? (Always Numeric, Always PIN, Automatic(current behavior))

And I also plan to add an extra key to go to the PIN layout from any other layout, so it's always manually reachable.

@Julow If you have all that already currently in the works, please tell me so I don't loose time working on it.

**Comment by Julow** [comment]
The PIN layout shows up when the symbols in the other number layout are not wanted. IP addresses can be written (`.:/`) with it.

The order of the keys is your only problem with the pin layout ? There's an option, "NumPad layout", that controls the order of the number keys. It's implemented by inverting the digits (`1 <> 7`, `2 <> 8`, etc...) and annoyingly the PIN layout and the number layout always have the opposite order.

This might be considered a bug. Perhaps the PIN layout order should be changed to match the other number layout ?

**Comment by sdrapha** [comment]
Sorry, I've been really busy and haven't had time to answer.
My point is, muscle memory. Every single time the pin layout shows up I have to waste time looking for stuff, while, if it was the regular numeric layout, I could type if my eyes closed.

There is no advantage in having a pared down version with less keys available ( and in a different positions ). Once you are already used to a more complete layout.

>"The PIN layout shows up when the symbols in the other number layout are not wanted."

That is an almost impossible job to get done right, because that is a guess, based on the type of input element used on a third party app. There is no way to really tell what the user want, unless there was an option to chose one layout only and stick with it, so it always match what you expect since you chose so.

For reference, one notable place that the pin layout always comes up is Google Sheets, and that is a place you probably want to type formulas, not phone numbers. And EVERY cell selection change, the layout changes again.

Again, I'm willing to find my way into coding this change, it will probably take me some time, more because of lack of time I have available. But I don't want to lose that precious time if you would tackle that change yourself, or say you really don't want the change. So that is why discussing it first.

**Comment by Julow** [comment]
Thanks for the explanations. I agree that the defaults don't work in every situation. I've added an option to turn off the pin entry layout (fce8ff7).

Just in case, I also added `=` to the layout (427ef6a). Perhaps it would cause the layout to change when you want to write formulas ? I do not have Google Sheets to try. You can find a debug build here: https://github.com/Julow/Unexpected-Keyboard/actions/runs/5701242702

**Comment by sdrapha** [comment]
That is awesome ! Thank you so much for that !!! I'll test it soon. Really appreciate!

**Comment by sdrapha** [comment]
New updates are working, issue resolved. Thanks a lot again!
