### ISSUE TITLE
is there any documents about how to compile src to apk?

### ISSUE THREAD

**Issue by emacs-newer** [Julow/Unexpected-Keyboard#371]
is there any documents about how to compile src to apk?

and which file i should modify to change qwerty layout key,thanks very much!

**Comment by Julow** [comment]
All of this is explained in this document: https://github.com/Julow/Unexpected-Keyboard/blob/master/CONTRIBUTING.md

I'm closing this issue but if you have any feedback or question, please re-open.

**Comment by emacs-newer** [comment]
thanks,i'll read that firstly.

**Comment by emacs-newer** [comment]
according wiki,shall iinstall ubuntu latest at first?

i know how to modify the xml files already.

**Comment by Julow** [comment]
Sorry for the slow reply. You need a linux system preferably with Nix installed.
If that's too much trouble, you can push changes to any branch your forked repository and wait for the automated build to finish. See the "Action" tab on Github.

You might also be able to edit the layouts from Github directly.
