### ISSUE TITLE
Show Every Accents feature not working on one specific device

### ISSUE THREAD

**Issue by freecycler** [Julow/Unexpected-Keyboard#375]
I saw the threads about issues #164 and  #166 but those don't quite fit my situation. I have the Android language setting as English (United States), and the app "Change keyboard layout" set to "System settings".

I mostly write in English but sometimes need to use words like "mañana", so I tried using the "show every accents" setting and the "Add keys to keyboard" with the tilde item checkbox marked. On most devices I have, this works; I can diagonal swipe upper-left from the "n" character, and the item in the corner highlights blue. And on most of my devices the "n" changes to "ñ" so I can type it.

But on one problematic device, the item in the corner changes to blue, but the character in the center of the key does NOT change, making it difficult to enter those words that use it.  It just produces a normal "n". For this device I had to configure a secondary layout in QUERTY-Spanish, this adds the "ñ" key at the end of the second row, then change layouts every time I need this character, and change back after I am done with it. While this works, it is less convenient than on other devices where the deadkey works.

Is this feature intended to be device specific or android version specific? Or is this some sort of bug? FWIW, the emoji keypad does not seem to work for this device either, though it does for my other devices.

I'm using Version 1.22.1 from f-droid, and the problematic device is a Skytex Skypad Alpha2 (SX-SP715A) tablet running Ice Cream Sandwich (4.0.3).

**Comment by Julow** [comment]
The issue seems to be that the app is not tested on Android 4.0. The oldest version I currently can use is Android 6.0.

I fixed the dead key combination for ñ in 01bfe73 but it's possible that many more useful combinations that you didn't try are broken. I'll leave this issue open until I could assess that.

You can find a debug APK here: https://github.com/Julow/Unexpected-Keyboard/actions/runs/5171209593

**Comment by freecycler** [comment]
> You can find a debug APK here:

Oh my, now THAT is YUMMY... not only does it fix this issue, but the extra range of adjustment for size of key labels is much needed for low-res screens viewed by aging eyeballs! Thanks much!

The emoji keypad is still borked, but I never use that anyway so not a problem for me. Should I open a separate issue for that so you have someplace to keep track of it?

Are there any other items that you might like me to test for you since I have this installed on the IceCreamSandwich device? I'm not a developer thus have no coding skills, but the device IS rooted, and I have ADB working if that helps.

**Comment by Julow** [comment]
There's no issue specially about the emoji board but this is a known problem. An issue would be useful.

It's possible that many other dead key combinations are not working, maybe all. It's not useful to test them all as I'll eventually specify all the needed combinations similarly to 01bfe73.
Thanks for you help!

**Comment by Julow** [comment]
I added explicit mappings for the other accents in c0833de.
