### ISSUE TITLE
Calling keyboard on FroYo device produces crash

### ISSUE THREAD

**Issue by freecycler** [Julow/Unexpected-Keyboard#379]
I'm using Version 1.22.1 from f-droid, and the problematic device is a Huawei Ideos U8150-B running FroYo (2.2).  Oddly enough the settings screen seems to work okay, as does the Android setting to choose it as default keyboard.

Logcat attached.

[unexpectedKeyboard.logcat.2ndtry.txt](https://github.com/Julow/Unexpected-Keyboard/files/11688632/unexpectedKeyboard.logcat.2ndtry.txt)

**Comment by Julow** [comment]
Thanks for the report. Could you try this debug build ? https://github.com/Julow/Unexpected-Keyboard/actions/runs/5215245210

The code is on this branch: https://github.com/Julow/Unexpected-Keyboard/tree/2-2-layout-crash

**Comment by freecycler** [comment]
It seems to do the same thing...

[unexpectedKeyboard_debug.logcat.txt](https://github.com/Julow/Unexpected-Keyboard/files/11710569/unexpectedKeyboard_debug.logcat.txt)

**Comment by Julow** [comment]
Debugging like this is not easy! Could you try again with this build ? https://github.com/Julow/Unexpected-Keyboard/actions/runs/5229176348

**Comment by freecycler** [comment]
> Debugging like this is not easy!

No, but there is progress this time... it does not crash at launch anymore, the main keypad can type text, the uppercase seems to work, so does the numeric/symbol layout. So thank you for that.

Trying to bring up the emoji keypad does crash though; not sure if that belongs on this issue or the other one about emoji. Do you want a logcat for that now, or would it be better to wait until you have something ready to try for that other issue? If so, which issue should I attach it to?

As noted before, I don't use emoji so no biggie for me.

**Comment by Julow** [comment]
Thanks for the help! The fix is on master: a26a535

I'll postpone debugging the emoji pane until I have a debugger for 2.2. I'll close this issue.
