### ISSUE TITLE
[feature request]: Add schwa as an extra key

### ISSUE THREAD

**Issue by darhma** [Julow/Unexpected-Keyboard#382]
In Italian, the use of the schwa letter "ə" for a more inclusive language has grown in recent years (see the section "Use for gender neutrality in Italian" at https://en.wikipedia.org/wiki/%C6%8F) and I believe it has been added to gboard as well, although I personally am not a big proponent of using schwa, I am also not particularly against it and think that all in all adding the ability to use it as an extra key might come in handy for those who prefer to use it.

**Comment by Julow** [comment]
An important key to have! I choose to add it to the extra keys (9f90b80) meaning it will be added to any layout for users with the Italian language installed.
