### ISSUE TITLE
Auto Completion feature

### ISSUE THREAD

**Issue by BtAbdul** [Julow/Unexpected-Keyboard#385]
Please add auto completion feature for no coding user, who wants use it for all apps like chats etc it would be help full.

**Comment by Julow** [comment]
This is a commonly requested feature that I would like to have for myself too.
I do not have enough free time to implement such a big feature. Help is welcome.

I'll close this issues as duplicate of https://github.com/Julow/Unexpected-Keyboard/issues/68
