### ISSUE TITLE
Adding extra key "select all" causes crash on FroYo device

### ISSUE THREAD

**Issue by freecycler** [Julow/Unexpected-Keyboard#389]
I'm using the [second debug build](https://github.com/Julow/Unexpected-Keyboard/actions/runs/5229176348) linked from [issue 379](https://github.com/Julow/Unexpected-Keyboard/issues/379) from f-droid, and the problematic device is a Huawei Ideos U8150-B running FroYo (2.2).

Here's the logcat.
[unexpectedKeyboard_debug.add_select_all.logcat.txt](https://github.com/Julow/Unexpected-Keyboard/files/11933293/unexpectedKeyboard_debug.add_select_all.logcat.txt)

**Comment by Julow** [comment]
The bug visible in the logs should be fixed in 37d4a52 but it's possible that there's more hidden bugs.
Debug build: https://github.com/Julow/Unexpected-Keyboard/actions/runs/5466952152

**Comment by freecycler** [comment]
That does seem to fix the crash, thank you. It even does the select all function. As for more hidden bugs, I have not found any yet.

One thing I did notice, thought I'd mention it in case it confuses anyone else... this would not install over the top of the other debug version, I had to uninstall that one first before I could get this one to install.

**Comment by Julow** [comment]
> this would not install over the top of the other debug version, I had to uninstall that one first before I could get this one to install.

This is known. Normally, debug builds downloaded from this action should be compatible but it's possible that caches are reset sometimes.
