### ISSUE TITLE
Feature request: more combining diacritics

### ISSUE THREAD

**Issue by gjvnq** [Julow/Unexpected-Keyboard#391]
Hi, I think it would be nice for the default querty layout to also have the following combining characters:

- Macron (U+0304), which is used in pinyin and modern Latin transcriptions as well as maths.
- Breve (U+0306), used in Vietnamese, Romanian, and trascriptions of Arabic and Hebrew.
- Caron (U+030C), used in Estonian, Finnish and pinyin.
- Overdot (U+0307), used in Polish, Arabic romanizations, traditional Irish typography, and maths (for the first derivative).
- Underdot (U+0323), used in Vietnamese, Yoruba, and some academic Latin transcriptions.

Also, it would be cool (but not really necessary) to have the fn key toggle between the combining diacritics in their normal positions versus their “reversed” positions. e.g. combining macron above vs combining macron below, dot above vs dot below.

**Comment by Julow** [comment]
These are already in the app in the form of dead keys. You can enable them in the "Add keys to the keyboard" option.

**Comment by Mispille** [comment]
@gjvnq did you find them ? 
is there everything you've been looking for?

**Comment by gjvnq** [comment]
I found them. Thank you all so much!
