### ISSUE TITLE
[Feature Request] Please add option to edit keys (in Add keys to the keyboard)

### ISSUE THREAD

**Issue by Nicholes444** [Julow/Unexpected-Keyboard#393]
Hi,
Please add option to edit keys for user so that we can make most usable content in just a swipe, 
for example there are some words which are very long and used frequently, so we can add/edit those words in "Add Keys To The Keyboard" manually and make use of it. Thanks

**Comment by Julow** [comment]
This is a good idea and has other use cases than words: Using letters from other languages that the keyboard don't support yet, rare symbols that are used frequently by some people, preferred emoji.

An other ideas for frequent words is https://github.com/Julow/Unexpected-Keyboard/issues/89 which would work best on top of word suggestion.

**Comment by Nicholes444** [comment]
> This is a good idea and has other use cases than words: Using letters from other languages that the keyboard don't support yet, rare symbols that are used frequently by some people, preferred emoji.
> 
> An other ideas for frequent words is #89 which would work best on top of word suggestion.

#89 That's even better i think.

**Comment by Spike-from-NH** [comment]
This is possible now either by editing your Qwerty.xml file or by using the new web tool to produce a custom Qwerty.xml file. My Qwerty.xml has a swipe to generate "the " and the only problem is training myself to use it! Putting a full keycap editor into Preferences is a less optimal way to do the same thing.

Regarding rare letters from other languages, I'd like a way to insert a character by typing its Unicode. If I needed it often, I'd define a new swipe in Qwerty.xml. If this were added, I could uninstall Hacker's Keyboard, which I keep around only for its Compose key.

**Comment by Julow** [comment]
This is an important feature for users of languages that the app doesn't support yet. implemented in 458e17b with the caveat that labels don't look great when they're longer than 4 letters.
