### ISSUE TITLE
0 is very difficult to type

### ISSUE THREAD

**Issue by Mrifk** [Julow/Unexpected-Keyboard#394]
In previous versions, all the numbers could be typed by swiping to the top right, except for 0, which could also be typed by swiping toward the top left. The most recent update seems to have removed this, which makes 0 very difficult to type, especially with small margins and a phone case that sticks up around the sides.

**Comment by Mrifk** [comment]
oh, I assumed it would be the same for all layouts that have the numbers on the top row – I'm using US English QWERTY

**Comment by Julow** [comment]
Ok, this was changed in 646ff48, which is quite a few releases in the past. The reason was that it's possible to reach `0` by going in a slightly different direction, for example up. (added in a27c644 and improved over time)

Does that work for you?

**Comment by Julow** [comment]
I believe this issue to be fixed.
