### ISSUE TITLE
[Feature Request] Allow 2 slots for custom layout.

### ISSUE THREAD

**Issue by YeaminSarder** [Julow/Unexpected-Keyboard#396]
If 2 slots for custom layout is allowed then we can set both primary and secondary layout as custom layout.

I have two custom layouts, one for English and the other for my native language. I would like to use both layouts together.

**Comment by Julow** [comment]
This would be a much welcome addition. 

Related to https://github.com/Julow/Unexpected-Keyboard/issues/321
An unbounded list of layouts would be even better to allow experimenting more freely. Also, switching between more than two layouts have been requested: https://github.com/Julow/Unexpected-Keyboard/issues/318

**Comment by Shareef101** [comment]
please make this happen

**Comment by Julow** [comment]
Implemented in 500f4e4
