### ISSUE TITLE
Proposal for very busy but very useful layout

### ISSUE THREAD

**Issue by marsmathis** [Julow/Unexpected-Keyboard#398]
![Screenshot_20230715-044514__01__01](https://github.com/Julow/Unexpected-Keyboard/assets/73719445/6a85598e-07b6-4795-b60e-05eb6f7e0369)
![Screenshot_20230715-044558__01](https://github.com/Julow/Unexpected-Keyboard/assets/73719445/0bab8aa3-b2c4-4620-9f20-05e0c9bdf346)

I made this layout a while ago. It features a full Greek alphabet along with lots of other symbols in a Dvorak layout. Maybe this could be considered? I'd obviously be glad to make the keymap available.

**Comment by Spike-from-NH** [comment]
Dvorak is already one of the layouts that can be selected in the long menu in the Preferences. Your layout is "very ideal" for you; promote it by disclosing your edited Qwerty.xml file. I don't think it ought to be added to the menu. (Nor should mine.)

**Comment by Julow** [comment]
It's nice to see people exploring new layouts but I do not want to add such layouts to the app at the moment. The layout option is getting crowded and this layout is likely to have only 1 user.

But sharing and taking inspiration from other people's layouts could be interesting. I've created a repository to contain these layouts: https://github.com/Julow/Unexpected-Keyboard-layouts
Would you be interested to share yours there ?

I plan to make some improvements to the custom layout option and to remove the scary warning on it during this year.
