### ISSUE TITLE
Done key behavior 1.11.x

### ISSUE THREAD

**Issue by rudolfmu** [Julow/Unexpected-Keyboard#40]
With 1.11.x the Done key is default when in editor(s) and closes the text instead of a new line. Please have Enter as default.
Tested on OI Editor and
https://f-droid.org/packages/bander.notepad/
With Total Commander Editor there is only Done, no Enter at all.

**Comment by Julow** [comment]
This is annoying indeed. Are you sure the Enter key isn't there in Total Commander's editor ? It is for me (on the corner of the Done key, annoyingly).
Related issue: https://github.com/Julow/Unexpected-Keyboard/issues/45

**Comment by Julow** [comment]
Both problems will be fixed in the next release: 348c278, 2f47d24.
