### ISSUE TITLE
the ability to press "Fn" for a long time to write many characters hidden in normal mode.

### ISSUE THREAD

**Issue by Wjxfi** [Julow/Unexpected-Keyboard#403]
the ability to press "Fn" for a long time to write many characters hidden in normal mode.

----------------------------------

I'm asking for the same button, but with a different icon and action for the Fn button only.
![c709bfd0-28de-4154-afd2-583e4eb330dd.jpg](https://github.com/Julow/Unexpected-Keyboard/assets/113500363/69bc156f-3735-4619-865d-d0b53d168c6f)

**Comment by Julow** [comment]
There's already two ways:
- Hold on Fn until it's locked. It will vibrate when it becomes locked. Tap again to unlock.
- Hold on Fn with one hand and type with the other.

For curiosity, for what use case do you need the symbols in the Fn layer so much ?
