### ISSUE TITLE
banking app doesn't work

### ISSUE THREAD

**Issue by islam2hamy** [Julow/Unexpected-Keyboard#405]
Hello,
This banking app doesn't work if "Unexpected Keyboard" is the default input

Banking app :
https://play.google.com/store/apps/details?id=com.NBEProdToken

Error :
https://www.google.com/untrustedkeyboard

**Comment by Julow** [comment]
It seems that the banking app explicitly wants you not to use this keyboard. It's possible that they found malicious keyboards in the wild.

Perhaps you can report this problem to them ? Mention that this app is open source and that they can review the code.
