### ISSUE TITLE
Adding Extra Layout

### ISSUE THREAD

**Issue by RockAriful** [Julow/Unexpected-Keyboard#408]
![Screenshot_2023-07-23-17-38-30-54_da9e875a8d9185d226f0619efbaab124](https://github.com/Julow/Unexpected-Keyboard/assets/69248471/24f32915-9821-414f-9844-ed33d68a1107)

How to add Extra layout like this, at the top of keyboard?  Please help me

**Comment by Julow** [comment]
Most of these don't have an equivalent on this app. Which one do you need ?

**Comment by RockAriful** [comment]
![IMG_20230724_063730](https://github.com/Julow/Unexpected-Keyboard/assets/69248471/a8f333c4-9d92-40cf-a5ff-629224cc0a66)
![Screenshot_2023-07-24-06-38-04-71_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Julow/Unexpected-Keyboard/assets/69248471/eacc812f-60b8-4ab0-8687-b9af88835ae1)

**Comment by RetrogisusDEV** [comment]
@Julow The idea is not bad, even I did this that it is quite useful...
(i no speak english good) 

(own modification)

![IMG_20230724_172222.jpg](https://github.com/Julow/Unexpected-Keyboard/assets/99091223/699f07ce-df68-4956-88fd-211897cae13e)

**Comment by RockAriful** [comment]
> @Julow The idea is not bad, even I did this that it is quite useful... (i no speak english good)
> 
> (own modification)
> 
> ![IMG_20230724_172222.jpg](https://user-images.githubusercontent.com/99091223/255724719-699f07ce-df68-4956-88fd-211897cae13e.jpg)

How to do? Please share with me

**Comment by RetrogisusDEV** [comment]
To app or the code?

**Comment by RetrogisusDEV** [comment]
@RockAriful Ok

It's still the same app, but with our own modifications, just to look better the code is the same

 There are some things I want to upload to the unexpert, but I haven't had time...

 https://www.mediafire.com/file/afnc6sc1jjcnrw9/RM_Keyboard_1.4.0Stable.apk/file

**Comment by RockAriful** [comment]
> @RockAriful Ok
> 
> It's still the same app, but with our own modifications, just to look better the code is the same
> 
> There are some things I want to upload to the unexperted, but I haven't had time...
> 
> https://www.mediafire.com/file/afnc6sc1jjcnrw9/RM_Keyboard_1.4.0Stable.apk/file

I want to know how to modify it? And how you added buttons here at top.pls share sourceCode

**Comment by RockAriful** [comment]
> @RockAriful Ok
> 
> It's still the same app, but with our own modifications, just to look better the code is the same
> 
> There are some things I want to upload to the unexperted, but I haven't had time...
> 
> https://www.mediafire.com/file/afnc6sc1jjcnrw9/RM_Keyboard_1.4.0Stable.apk/file

can you please give me your modified codes to me!

**Comment by RockAriful** [comment]
![Screenshot_2023-07-22-15-46-41-32_7352322957d4404136654ef4adb64504](https://github.com/Julow/Unexpected-Keyboard/assets/69248471/9aaf308b-2f73-424d-932d-128848717667)
I modified this but i want to add some extra layout at the top of keyboard. And i want to add text suggestion also 
![Screenshot_2023-07-24-06-38-04-71_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Julow/Unexpected-Keyboard/assets/69248471/d16c50c8-92f4-4843-8db8-7788ffd9aa59)
![IMG_20230724_063730](https://github.com/Julow/Unexpected-Keyboard/assets/69248471/450bc3ec-300d-40ed-aacc-3a221dfd160c)
![Screenshot_2023-07-22-18-58-13-41_da9e875a8d9185d226f0619efbaab124](https://github.com/Julow/Unexpected-Keyboard/assets/69248471/12719c22-de99-4325-b0dd-9796a4f53e74)

but i cant do it properly .please help me

**Comment by Julow** [comment]
This app does not have text suggestion/correction and there's an other issue to track the feature request.

The cut, copy, paste and voice button do exist in the app. Try making you own layout [with the layout editor](https://unexpected-keyboard-layout-editor.lixquid.com/). See [KeyValue.java](https://github.com/Julow/Unexpected-Keyboard/blob/master/srcs/juloo.keyboard2/KeyValue.java#L436) for the list of all the special keys.
You then paste your layout into the "Custom Layout" option at the bottom of the settings page.

Please don't share APKs, share layouts or git branches instead.

**Comment by Julow** [comment]
I'll close this as this can be expressed as a custom layout and text suggestion is tracked by other issues.
