### ISSUE TITLE
How do I type numbers?

### ISSUE THREAD

**Issue by THE-BLUE-FRIEND** [Julow/Unexpected-Keyboard#411]
I'm sorry this might be very silly but I can't figure out how to type numbers on this app. I've tried using the shift button, the function button and both of them together as well but it do doesn't work. Can you please help?

**Comment by Hadi-M0** [comment]
just swipe the letter to the direction of the number or swipe the ctrl "buttun?" to the directon of (123+) and it will show the numpad

**Comment by Julow** [comment]
Does this work for you ?

**Comment by THE-BLUE-FRIEND** [comment]
Thank you for answering. It works!
