### ISSUE TITLE
[Feature-request] Add Gboard long press popup

### ISSUE THREAD

**Issue by Coderx7** [Julow/Unexpected-Keyboard#415]
Google Gboard has this nice feature where you can long press on a symbol like `.` and a new pane pops up allowing you to select many symbols on the spot without going anywhere or taking much space.
here is how it looks :    

![04-gboard-shortcuts-punctuation-100896252-orig](https://github.com/termux/termux-app/assets/5382892/7ab76768-4b94-41d9-85ed-f754fb90a960)

it'd be great to have this imho and being able to edit the keys/symbols shown in the popup as well.

**Comment by Julow** [comment]
That doesn't seem more powerful than what the app already propose. All the symbols shown in your gif are present on the main board in this app.
It's true that the longpress is under utilized but I do not believe in this idea.

**Comment by Coderx7** [comment]
this is not about what you see here, Gboard doesn't have any functional keys, it's lacking a lot in thus respect. but overall it's very easy to use due to these enhancements. 
don't get me wrong this keyboard is really good but 
it currently is very cluttered and imho hard to use compared to if it adds this functionality. 
like 8f it adds this I don't need to go two levels deep to access some keys, I can easily get it in the same pane. 
this could also allow for better rearrangement of keys giving some more space to work with.

**Comment by Julow** [comment]
What symbols that you use often require you to go two levels deep ?

**Comment by Coderx7** [comment]
keys that you often use depend on the specific chore you are doing that moment. Thats an important aspect to take into account. 
for me currently the functional keys I want is not even there, and to have a faster typing and less errors, I use second level for tab,/ and the like. its hard working with keyboard at this current form and I mostly use Gboard or dcoders keyboard but mostly Gboard

**Comment by Julow** [comment]
The function keys are `Fn+digit`, that's not two levels deep. `tab` and `/` are on the main board on almost all layouts.

**Comment by Julow** [comment]
Perhaps you are using the Persian layout ? It's the only layout without `esc` and `tab`, the `Fn` modifier doesn't turn persian numbers into function keys and it also lacks `/`.
You can improve it: https://github.com/Julow/Unexpected-Keyboard/blob/master/res/xml/arab_pc_ir.xml
There's also this issue talking about the function keys: https://github.com/Julow/Unexpected-Keyboard/issues/176

**Comment by Coderx7** [comment]
thanks I had a look and if I can create my own layout I think it'd be good. but in any case I still say the long press or even better being able to assign different keys to different spots on the keyboard dynamically would be great, until then imho long press can somewhat does this.

for me to click on a single dedicated key is much faster and less error prune compared to multi directional keys. don't get me wrong this form is really nice but I think it's overly done in a very compact space and when someone like me with big fingers tries to type things it gets frustrating.

also is there a way to add home, end, pageup, pagedown, break and the likes to current keys?
I don't care much about F keys, but tab, Ctrl, alt, and the others I mentioned just now are very important to me. 
if I could do that and also reassign directional keys like 
     ↑ 
 ←↓→  ‌‌‌‌‌‌‌‌‌‌to some adjacent keys that'd be great. is this possible from editing layouts ? 

thanks a lot in advance.

**Comment by Julow** [comment]
You can home, end, the arrows, etc.. into your layouts. You can find the list of all these keys here: https://github.com/Julow/Unexpected-Keyboard/blob/master/srcs/juloo.keyboard2/KeyValue.java#L305

I've implemented the function keys and added `esc` and `tab` in dcbb4c4 and c46e5ec

**Comment by Julow** [comment]
I'll close this issue. Note that you can take the source for the Farsi layout, modify it and paste it in the custom layout option. See https://github.com/Julow/Unexpected-Keyboard/blob/master/res/xml/arab_pc_ir.xml
