### ISSUE TITLE
Correction of Farsi (Persian) translation on the keyboard activation page

### ISSUE THREAD

**Issue by ghost** [Julow/Unexpected-Keyboard#416]
Hello, the "این یک برنامه ازاد و منبع باز است. شما میتوانید پیدا کنید کد منبع را و گزارش کنید باگ ها را در گیتهاب" text on the keyboard activation page (in Farsi(Persian)) is wrong. And it should be:
"این یک برنامه متن باز و آزاد است. شما می‌توانید کد منبع را در گیتهاب پیدا کرده و نیز باگ‌ها را گزارش کنید."

**Comment by diawih** [comment]
I also click on the word "گیت هاب" but there is no reaction.
I don't know if it is like this only in Farsi (Persian) or other languages ​​too

**Comment by diawih** [comment]
![Uploading IMG_۲۰۲۳۰۸۰۳_۱۲۳۷۴۹.jpg…]()

**Comment by diawih** [comment]
![IMG_۲۰۲۳۰۸۰۳_۱۲۳۷۴۹](https://github.com/Julow/Unexpected-Keyboard/assets/133924958/3492016e-1110-4e4b-b7cd-7cfa9c2892db)
