### ISSUE TITLE
Mention similar input app Calculator++

### ISSUE THREAD

**Issue by lrq3000** [Julow/Unexpected-Keyboard#417]
There is a calculator implementing the same idea of sliding to the keys corners to input more complex characters, and it is hands down the best calculator I have ever used. I actually first discovered this UX concept first with Calculator++, and only recently found about UnexpectedKeyboard and loved it instantly!

Likewise, I guess some UK users may also find CPP a very nice companion app, so I suggest to mention it in the readme.

Here is the repo: https://github.com/Bubu/android-calculatorpp

And it's on f-droid: https://f-droid.org/en/packages/org.solovyev.android.calculator/

**Comment by Julow** [comment]
That seems like a good idea, would you be willing to write it ?

The repository you point to is marked as archived and the original repository last commit is 5 years old. How to mention that the app is potentially unmaintained ?

**Comment by lrq3000** [comment]
I made a PR, please let me know if it’s ok for you.

I mentioned it is maybe unmaintained, but in reality I will maintain the app if necessary (I maintain a lot of app, and I consider Calculator++ to be an essential now ;-) ). I tested it on several Android versions up to 13 (the latest stable) and it’s working perfectly fine, so maintenance is imho not necessary for now.

**Comment by Julow** [comment]
Good to know!

**Comment by Julow** [comment]
Thanks!

**Comment by lrq3000** [comment]
Thanks a lot to you! Love to see a fellow developer as open-minded and dedicated to their project as you are :D

**Comment by sdrapha** [comment]
@lrq3000, do you happen to know why fdroid says that calculator++ tracks users behaviors while at same time it points to a fork of tge original project, and that fork in oarticular says it removed the google analytics portion of it...

**Comment by lrq3000** [comment]
@sdrapha I unfortunately never uploaded to f-droid before so I don't know the arcanes of their publication system but iirc there is an approval process (unlike izzyondroid their open side track) so maybe there is a github issue or another issue tracker where more infos can be found.

**Comment by lrq3000** [comment]
@sdrapha so the current maintainer Bubu recently updated calculator++ on f-droid (he doesn't have access to the original version on google play) including [one commit](https://git.bubu1.eu/Bubu/android-calculatorpp/-/commit/f3cb964d3de8544e7875962ce68f52378d57f14d) to "remove the non-functional billing implementation" so maybe that's why? Also Bubu is involved in the F-Droid project [since 2016](https://bubu1.eu/) so I'm pretty confident that his package is free from any serious threat, but I will try to reach him about this issue.

**Comment by lrq3000** [comment]
@sdrapha Bubu replied, it was indeed a non-functional leftover of Google Analytics that he now removed 5 days ago in [this commit](https://gitlab.com/fdroid/fdroiddata/-/commit/ee370bc2e40c55656608bf13f0049cb5d579db77), now the anti-feature flag is removed on f-droid (I checked), so now this app has 0 antifeatures :-)

**Comment by sdrapha** [comment]
Awesome! Thank you for the follow up! I had the previous version installed and just updated to the new one since you mentioned. 

Only thing to add is, once we get spoiled on how good unexpected keyboard picks up the diagonal slide for the extra keys. I wish that calculator was that good too, it only works up and down. So I wonder if there is a way to use this keyboard as inspiration, and upgrade that gesture algorithm on the Calculator with a PR. But anyways..a bit off topic.

Thank you again for the updates.

**Comment by Julow** [comment]
@lrq3000 Thanks for the update. Could you update the text and the link in the README ?

**Comment by Julow** [comment]
The readme currently mentions this, do you think it's still accurate ?

> Works up to Android 13 but maybe unmaintained.
