### ISSUE TITLE
how to write § 

### ISSUE THREAD

**Issue by cannnAvar** [Julow/Unexpected-Keyboard#423]
hi i was playing minecraft and i need to type § charecter but i can't see on the keyboard is there any way to write.

**Comment by Julow** [comment]
It's not on the released app yet but it has been added recently in https://github.com/Julow/Unexpected-Keyboard/pull/410
It's an optional key that need to be enabled in the "Add keys to the keyboard" option.

You can download a recent debug build here: https://github.com/Julow/Unexpected-Keyboard/actions/runs/5787682182

**Comment by cannnAvar** [comment]
thx
