### ISSUE TITLE
Full Clipboard Support

### ISSUE THREAD

**Issue by knoxydev** [Julow/Unexpected-Keyboard#428]
it would be cool to have clipboard history support with the ability to insert the necessary information or delete it.

**Comment by kingkhan71** [comment]
Agreed

**Comment by kcryptonian** [comment]
if this feature is implemented, then this light keyboard just might completely replace gBoard on my phone.

**Comment by Julow** [comment]
There are other issues about this: https://github.com/Julow/Unexpected-Keyboard/issues/275 https://github.com/Julow/Unexpected-Keyboard/issues/239 https://github.com/Julow/Unexpected-Keyboard/issues/195
