### ISSUE TITLE
New setting activity style  for newer versions 

### ISSUE THREAD

**Issue by RetrogisusDEV** [Julow/Unexpected-Keyboard#429]
Well, I propose to update the configuration section for new devices so that it matches the device better, I have all the code almost ready.
 of course this will be for android 7+ devices (api 26+)

 If you want I can pass you the code and tell you more or less how to do it (I can't do forks or anything like that xd)

**Comment by Julow** [comment]
You can send the code in any way you want.

**Comment by RetrogisusDEV** [comment]
ok, it's not finished, I need to add some icons and descriptions, but it looks very good

**Comment by RetrogisusDEV** [comment]
Link : https://www.mediafire.com/file/70x4gk5n5ouz5cr/NewSettings.zip/file

decompile and add the files in `res/`

the folder `xml-v21` replace the folder xml (just settings.xml) in android 5.0+

drawable folder have `SVG` Resource (icon)

**Comment by RetrogisusDEV** [comment]
You can create new branch called `NewSettingDesing` ?

**Comment by RetrogisusDEV** [comment]
You can create new branch called `NewSettingsDesing` ?

**Comment by Julow** [comment]
I've taken your changes into this branch: https://github.com/Julow/Unexpected-Keyboard/tree/settings-icons
The debug build is here: https://github.com/Julow/Unexpected-Keyboard/actions/runs/5870520240/job/15917693147

The settings have changed a bit since last release, which you took as a base. I couldn't take some changes.

I see some problems with this change:
- Some options don't have an icon. I don't want to make adding new option harder due to icons so there will always be some options with no icon.
- Several options have the same icon (eg. the Typing section, transparency options) and some icons are not clearly related to the option (eg. number row, vertical spacing).
- This increases the app size by 40kbs, which is 4 times more than storing the 49 symbols of the embedded font. This is not a problem in itself but maybe the icons could be optimized.

**Comment by RetrogisusDEV** [comment]
Of course, I understand, but the question is that something is missing from the changes, the letters, and to change these, a font called `google_sans_medium.tts` is used, so using a font to optimize the icons does not allow us to use this one. 40KB is not much either (do not say that some phone will not be able to with 40kb more because I have a nokia C2-01 and that 40kb dinosaur is nah)

**Comment by RetrogisusDEV** [comment]
Although we can suppress the xml to be used only for the main options (that is, the initial ones), this way the increased weight is maintained at 5kb or less

**Comment by RetrogisusDEV** [comment]
I was reading the proposals and I saw that they made an online tool to make a layout visually, if you agree, I'll put an intent that sends to said page (below the option to code the custom layout)

**Comment by Julow** [comment]
You have not commented on the first two problems. What about options with no icons ?

Before you make more changes, please start from the debug build I linked above and not from the last release.

> I'll put an intent that sends to said page

Not a bad idea but beware that this option changed a lot recently.

**Comment by RetrogisusDEV** [comment]
> You have not commented on the first two problems. What about options with no icons ?
> 
> Before you make more changes, please start from the debug build I linked above and not from the last release.
> 

Actually, if I answered them using only one answer: in order not to make changes every new option, add icons only to the main screen and not to the sub-screens `PreferenceScreen`

>
> Not a bad idea but beware that this option changed a lot recently.
>

You can direct a page from a `Preference` using `intent` tags and specifying the option, without having to code in the main code but directly in the sm`settings.xml`

**Comment by Julow** [comment]
The custom layout option at the bottom is removed in the debug version (the layouts option takes its role). Have a look.

**Comment by RetrogisusDEV** [comment]
I intent compile but...

![IMG_20230817_152440.jpg](https://github.com/Julow/Unexpected-Keyboard/assets/99091223/a2336138-60ac-4065-b19d-e428a429d4c5)

i never compile in `Termux` (using Make)

**Comment by Julow** [comment]
You need OpenJDK 8 and the Android SDK (build tools 28.0.1 or more, platform 30). The `ANDROID_HOME` variable must be set to the installation directory of the Android SDK.
I've never installed this in Termux so I can't help much.

**Comment by Julow** [comment]
You've implemented this in https://github.com/Julow/Unexpected-Keyboard/pull/487 but then removed it with a force-push.
Many of your improvements are merged except this one. Could you open a new PR?

**Comment by RetrogisusDEV** [comment]
I've been trying to add so that the `border radius` of *Keyboard* can be customized, but I never understood `shared preference`, well I never dedicate myself to anything

**Comment by RetrogisusDEV** [comment]
I will try to open a new pr, and delete the previous one (I didn't manage it well anyway xD)

**Comment by RetrogisusDEV** [comment]
> Here's an example of a slider option: https://github.com/Julow/Unexpected-Keyboard/blob/master/res/xml/settings.xml#L30
> The internal name of the option is defined by `android:key="label_brightness"`. Here's where it's looked up: https://github.com/Julow/Unexpected-Keyboard/blob/master/srcs/juloo.keyboard2/Config.java#L145
> Then it can be used in the rendering code: https://github.com/Julow/Unexpected-Keyboard/blob/master/srcs/juloo.keyboard2/Keyboard2View.java#L392

oh, thanks for telling me what files to see and modify, I already made the custom border radius, I'm going to make the custom border line size, and then if you like it I'll send it to you in the pr

**Comment by RetrogisusDEV** [comment]
![Screenshot_20240116-003325.jpg](https://github.com/Julow/Unexpected-Keyboard/assets/99091223/3048d54e-3b9b-41bf-9691-b7d47e81f299)

**Comment by Spike-from-NH** [comment]
@RetrogisusDEV, this makes the keyboard look much better than a boxy style. The extreme would be a radius that turns the narrowest key into a circle; maybe you can compute this and use it as the maximum setting. I presume that area that now looks like it's not part of the key will still register if tapped.

**Comment by RetrogisusDEV** [comment]
Of course, for more specific tastes, I tried the 30dp radius, and there are certain flaws, the safest thing is 15dp, so I'll see which maximum setting is better

**Comment by RetrogisusDEV** [comment]
Spanish : 0
memeglish : 1

![IMG_20240116_120615.jpg](https://github.com/Julow/Unexpected-Keyboard/assets/99091223/6838da54-ef0c-428d-ac6e-c00810c00996)

**Comment by RetrogisusDEV** [comment]
the buttons: *become round*
the symbols in the corners: I can float :D.jpg

**Comment by Spike-from-NH** [comment]
In your illustration: ① Top line doesn't specify WHICH is selected by check-mark. Suggest "Custom keycap edges". ② Other fields are only enabled if custom is checked, so don't have to repeat "custom". Options might be "Border width" and "Corner radius". ③ If line 1 says Disable, lines 2 and 3 should be grayed out.

**Comment by RetrogisusDEV** [comment]
5:24:59 am

Mission : Completed

Now : Create pr :,d

![Screenshot_20240117-052225.jpg](https://github.com/Julow/Unexpected-Keyboard/assets/99091223/2c9432e9-e030-4f8a-8d50-5e95350a9083)

**Comment by Spike-from-NH** [comment]
Thanks! But it's not quite English. Modifiers come before nouns and don't take the plural. I still prefer the phrasings I suggested. Also: ① The style of the Settings page is not to capitalize each word (just the first, like Wikipedia, unlike many newspapers), and ② There's no need for that comma. Suggested subtitle: "Customize the keys' border width and corner radius". ("keys'" is plural. But the plural "radii" would be confusing.) Sorry to be so picky; technical editing is my job!

**Comment by RetrogisusDEV** [comment]
> Thanks! But it's not quite English. Modifiers come before nouns and don't take the plural. I still prefer the phrasings I suggested. Also: ① The style of the Settings page is not to capitalize each word (just the first, like Wikipedia, unlike many newspapers), and ② There's no need for that comma. Suggested subtitle: "Customize the keys' border width and corner radius". ("keys'" is plural. But the plural "radii" would be confusing.) Sorry to be so picky; technical editing is my job!

Ok, my english is basic 😅, but ok...

And now the new style (light/night) for Android 5+, using just `style.xml` and a custom button

![Screenshot_20240117-090017.png](https://github.com/Julow/Unexpected-Keyboard/assets/99091223/86ad8661-0804-415d-9776-854c3db9a189)

**Comment by RetrogisusDEV** [comment]
Now, to create a new pr **cry**

**Comment by Julow** [comment]
https://github.com/Julow/Unexpected-Keyboard/pull/524 is merged. Thanks!
