### ISSUE TITLE
[Feature] More currency symbols

### ISSUE THREAD

**Issue by ItsOnlyBinary** [Julow/Unexpected-Keyboard#44]
Being from the UK it would be really nice if you could add the pound `£` and euro `€` symbols to the keyboard

**Comment by Quantenzitrone** [comment]
maybe a selection menu in the settings where one can select up to 2 or 3 currency symbols.

**Comment by Julow** [comment]
Currently, `£` is `Fn+#` and `€` is `Fn+$`. This might be hard to guess. I'll consider adding the currency symbols directly on the keyboard depending on the locale.

**Comment by ItsOnlyBinary** [comment]
It would appear I looked everywhere but fn thanks for tip, Directly on the main keyboard depending on locale would make things much easier.

**Comment by Quantenzitrone** [comment]
why is € on Fn+$ if it is already on ↘️e
or has that something to do with my locale?
idk it looks kinda weird to have two € next to each other when in Fn mode.

**Comment by Julow** [comment]
Some layouts show the `€` directly but it's not on all of them. Ideally, I'd want every characters supported by the keyboard (except non-latin script languages) be present on QWERTY. It is reasonable to remove the `Fn` combination after that.

**Comment by Julow** [comment]
Should be fixed. 632a9ac
