### ISSUE TITLE
Custom Layout <keyboard bottomRow="false"> is not working

### ISSUE THREAD

**Issue by the-loan-wolf** [Julow/Unexpected-Keyboard#440]
adding `<keyboard bottomRow="false">` in custom layout should disable default bottom row but it's not hidding
![keyboard](https://github.com/Julow/Unexpected-Keyboard/assets/37395721/1ed930c3-0598-45c8-82d0-8070613ed626)

**Comment by Julow** [comment]
Try `bottom_row="false"`. Here's a layout that redefines the bottom row: https://github.com/Julow/Unexpected-Keyboard/blob/master/res/xml/latn_neo2.xml

**Comment by the-loan-wolf** [comment]
now i am closing this issue
