### ISSUE TITLE
(Reset shift on) Autocapitalization preventing common modifier key combinations (QoL)

### ISSUE THREAD

**Issue by Validbit** [Julow/Unexpected-Keyboard#441]
When using ctrl for copy/cut/paste (with auto-capitalization enabled) shift is (intuitively) preventing common hotkeys to funtion as expected (Ctrl[+Shift]+A; Ctrl[+Shift]+C;...)

This is disrupting, as expected for autocompletion; e.g. when:
- selecting all text (ctrl+a) (since autocapitalization triggers with start of line)
- copying between applications
- copying text after end of sentence (. )

I suggest resetting shift key when any other modifier key is pressed (after/while autocapitalization was triggered), or at least for ctrl

This is related to partial fixes in #181

**Comment by Spike-from-NH** [comment]
Better: Simply accept Ctrl-A as well as Ctrl-a for Select All, etc. Implicitly resetting a mode in order to more faithfully "do what I meant" may baffle the user.

(Also needs adaptation for non-Roman keyboards, as noted in the recent issue; Cyrillic keyboards can't make Ctrl-V.)

**Comment by Julow** [comment]
The keyboard does not accept keyboard shortcuts, the application in which you type does. @Validbit's suggestion is the right fix.

**Comment by Julow** [comment]
Fixed in f4c11d9.
