### ISSUE TITLE
Feature Request: Numpad for secondary language

### ISSUE THREAD

**Issue by imruf** [Julow/Unexpected-Keyboard#443]
While typing in secondary language, বাংলা (bangla) জাতীয় (jatiyao) layout in my case, it will be helpful if numpad input numbers also respect that layout. i,e tapping 1 should enter bengali digit ১ instead of 1. Much appreciate your work. Thanks.

**Comment by Julow** [comment]
Thanks for the request. This is implemented in 687d88f.
