### ISSUE TITLE
Czech QWERTY variant

### ISSUE THREAD

**Issue by pharook** [Julow/Unexpected-Keyboard#444]
Czech QWERTY variant is also quite widespread in Czech Republic (especially among programmers and people who regularly work in bilingual environments), wouldn't it be possible to add that also? (Or just having possibility to switch Z/Y in relevant group of layouts.)
Attached is my attempt in both Czech variants, basic and multifunctional (with .txt extension added, as GitHub does not allow XML upload). In multifunctional I've left ^ (caret) at 'y' (now at top row) to stay close to usual position at full numeric layouts, but moved ÷ (division sign) to 'z' (now at bottom row) to make place for number 6 at upper 'y' key.
[latn_qwerty_cz.xml.txt](https://github.com/Julow/Unexpected-Keyboard/files/12438847/latn_qwerty_cz.xml.txt)
[latn_qwerty_cz_multifunctional.xml.txt](https://github.com/Julow/Unexpected-Keyboard/files/12438848/latn_qwerty_cz_multifunctional.xml.txt)

_And of course my thanks for the cool keyboard which actually doesn't slow typing down._

**Comment by Julow** [comment]
Do you use the multifunctional layout ? I would hope to get rid of it in favor of new features that would work on every layouts.

Could you open a PR for `latn_qwerty_cz` ?

**Comment by pharook** [comment]
I don't use multifunctional, but not sure about other czech layouts contributors. I think the possibility to add own keys could substitute for it, however if I'm correct, one cannot (from config dialog) add own keys to specific places. At least I've tried to add spanish tilde modifier, and it ended up at 'A' key, and I don't see the possibility to change the place.
Anyway, I've tried to put together the pull request (#455) for latn_qwerty_cz with just necessary changes to QWERTZ.

**Comment by Julow** [comment]
> I don't use multifunctional, but not sure about other czech layouts contributors.

I would prefer to add only layouts that are used. I'm also not in favor of the multifunctional layout that I would want to remove once its usecases are covered by other features.

I've designated a place for layouts that are unlikely to have more than one user: https://github.com/Julow/Unexpected-Keyboard-layouts
You could add it here so it's not lost and might be added to the app later.

> however if I'm correct, one cannot (from config dialog) add own keys to specific places.

You are correct. This is something I'm aware but don't have a clear solution yet.

**Comment by pharook** [comment]
> > I don't use multifunctional, but not sure about other czech layouts contributors.
> 
> I would prefer to add only layouts that are used. I'm also not in favor of the multifunctional layout that I would want to remove once its usecases are covered by other features.

Fully understood. "Perfection is finally attained not when there is no longer anything to add, but when there is no longer anything to take away." – Antoine de Saint Exupéry :smile:

> I've designated a place for layouts that are unlikely to have more than one user: https://github.com/Julow/Unexpected-Keyboard-layouts You could add it here so it's not lost and might be added to the app later.

Cool. However I don't think my one added key warrants publishing the layout, as I definitely can live with modifier tilde on 'A' key for my occasional Duolingo lessons. :smile:

> > however if I'm correct, one cannot (from config dialog) add own keys to specific places.
> 
> You are correct. This is something I'm aware but don't have a clear solution yet.

Well, thing is whether there is simple solution. Either possibility to add key to specific position and keep those user changes atop of selected layout (but even if it looks simple, it brings its own can of worms and corner cases, for example what to do if selected layout changes with new version), or keep modified layout separate as new one (which is quite consistent, but precludes user of updates of original internal layout). And we are not talking about UI yet. :smile:
I may be wrong but I guess for you this is probably out of scope of Unexpected (to stay small, simple and discoverable). And that's fine, possibility of simple modifications and ability for power users to create their own layout externally and insert into app (as it effectively is today) seems as a good tradeoff.
However, we are drifting off topic here :smile:, so I guess this issue can be closed already (I'll leave it on you, for case you have some policies, like closing on new version, tagging and such).

Anyway, thanks for accepting the PR, as Czech QWERTY really is quite widespread here (and even supported by desktop OSes).

**Comment by Julow** [comment]
Thanks for your contribution! I'll close this issue.

> but even if it looks simple, it brings its own can of worms and corner cases

Indeed! My current idea is to place keys close to a second specified key but not to specify a particular position. The list of potential positions would be deterministic. This would make the placement more stable than currently but keys could still move if the layout changes.
Simpler layouts have more free spots than complex ones and don't change often.
