### ISSUE TITLE
Add CLIPBOARD HISTORY  delete, edit & pin

### ISSUE THREAD

**Issue by kingkhan71** [Julow/Unexpected-Keyboard#445]

**Comment by kcryptonian** [comment]
+1

**Comment by Julow** [comment]
There are other issues about this: https://github.com/Julow/Unexpected-Keyboard/issues/275 https://github.com/Julow/Unexpected-Keyboard/issues/234 https://github.com/Julow/Unexpected-Keyboard/issues/195

**Comment by kingkhan71** [comment]
> There are other issues about this: https://github.com/Julow/Unexpected-Keyboard/issues/275 https://github.com/Julow/Unexpected-Keyboard/issues/234 https://github.com/Julow/Unexpected-Keyboard/issues/195
> 

I checked those tags still found that everyone is asking about clipboard, because all we users felt that this expectation should be fulfilled by you..vvery useful & needy feature.
