### ISSUE TITLE
UNABLE TO CHANGE CASE OF ALREADY TYPED WORDS/LETTERS

### ISSUE THREAD

**Issue by kcryptonian** [Julow/Unexpected-Keyboard#447]
As the issue title says, I've tried the ussual key combinations of ctrl/shift/f3/alt. Nothing happens.

**Comment by Julow** [comment]
This has been suggested in https://github.com/Julow/Unexpected-Keyboard/issues/305#issuecomment-1483883049
I'll close as a duplicate.
