### ISSUE TITLE
Development Environment

### ISSUE THREAD

**Issue by deftkHD** [Julow/Unexpected-Keyboard#448]
Hi, I really appriciate your project and your efford. I would like to use this keyboard as my daily-driver, but there are some aspects, that I would really miss and since I have some time, I would like to contribute. What are your reasons not to use Gradle and Android Studio? I did some testing locally and apart from some localization issues, Gradle and Android Studio seem to work just fine. Or let me ask the other way around: Which development enrionment do you recommend to work on this project?

Also I am interested in hearing your oppion about integrating more modern features such as Kotlin code or AndroidX libraries. Is the goal to keep the minimum API level as low as possible or do you think this would be a good idea? As an example I would like to promote the AndroidX Emoji2 library, but you already mentioned it in #384.

Maybe as a background: I already did some work locally and made a new Emoji picker, which uses a combination of the AndroidX library for displaying the emojis and the Keyboard2View to display a custom keyboard layout at the bottom so the wheel gets not reinvented and haptic feedback and everything works automatically. But the changes I made to run the project in Android Studio are too large to contribute these changes, so I was wondering what you recommend.

**Comment by Julow** [comment]
Thanks for experimenting with the code :)

I needed a reproducible build system that works offline and is quick to set up on my machine and found that Gradle didn't allow any of that.
I recognize that the current build system is not ideal and I'm open to Gradle, though I insist that using visual studio shouldn't be a requirement.
I personally develop with `nix-shell ./shell.nix` and `make` and use no LSP.

The API level is kept as low as possible on purpose, as many users are stuck on very old versions in other parts of the world.
By how much would you need to increase it ?

An other goal is to keep the size of the APK at a minimum. It's currently ridiculously low and could be increased for new features but I didn't feel like libraries would be useful in an app that is mostly one custom view.

**Comment by deftkHD** [comment]
Thanks for the feedback :)

I never had any significant issues when setting up Gradle since the GradleWrapper is nearly always shipped together with the source code, but I don't know how this works on NixOS with their package manager. I forked the repo and set up a basic, but (I think) fully functional build system with Gradle. Maybe you could try if it works by invoking `./gradlew assembleDebug`, which will build the debug APK without the need of any LSP at all. The catch however is you need to run Gradle with Java 17, but from what I can see this should be adjustable in the shell.nix file.

I thought about that and like the idea of keeping the API level as low as possible, but the linter in the Android Gradle Plugin found several cases where unaccessible API calls to e.g. level 21 were made. If Gradle works, you can see those errors by using `./gradlew lint`. Besides that the API level does not have to change. AndroidX on the other hand requires at least API level 14 (a broad overview here: https://apilevels.com/).

I did some testing and astonishingly the APK size is even smaller when using Gradle. Anyways, here are the results:
![image](https://github.com/Julow/Unexpected-Keyboard/assets/32391033/b4e11619-5972-4bb5-9372-667bacb79a4e)
I have to note however that optimizations such as code shrinking remove unused code and for these tests I just added the dependencies, not implemented it, so the actual sizes would probably be a bit larger. I agree that this project does not require a large overhead of libraries. On the other hand I can see a chance of #384, #378, #298 and maybe even #239 getting fixed by using the AndroidX emoji library, but I guess this requires AndroidX to be enabled and as you can see, this has quite a huge impact on the APK size.

I think I can do the following things: Since I already have my fork using Gradle ready, I create a new branch which uses the AndroidX emoji library and you can have a look if its worth it. If not, maybe using Gradle could still be an option to allow more possible contributors to easily jump in, but thats up to you. I'll give an update when the branch is ready.

**Comment by deftkHD** [comment]
The branch https://github.com/deftkHD/Unexpected-Keyboard/tree/androidx-emoji now uses the AndroidX emoji picker and the release APK size increased to 541,5 KiB. I included a screenshot:
![image](https://github.com/Julow/Unexpected-Keyboard/assets/32391033/665e7015-09a4-4886-89d4-41d175065998)
While this seems to work pretty good, the AndroidX emoji library requires a minimum API level of 21 and the APK is now about twice the size.
What do you think?

**Comment by Julow** [comment]
Thanks a lot! The results look nice, let's use Gradle !

> I thought about that and like the idea of keeping the API level as low as possible, but the linter in the Android Gradle Plugin found several cases where unaccessible API calls to e.g. level 21 were made.

Hopefully beind an `if` or in rarely used code. The linter is something I want to have !

> The branch https://github.com/deftkHD/Unexpected-Keyboard/tree/androidx-emoji now uses the AndroidX emoji picker and the release APK size increased to 541,5 KiB

That looks nice! The size increase isn't too bad for a wanted feature.
The app currently contains a 100Kb list of emoji in `res/raw/emojis.txt` that would go away with the library.

The API level increase however isn't so nice. Do you think an older version or a different library could have a lower API level ?

> Besides that, the emoji library also seems to require hardware acceleration which is right now disabled in the AndroidManifest

I don't remember why that was the case. We can try enabling it.

**Comment by deftkHD** [comment]
That sounds fantastic! I will prepare a pull request, but I discovered one missing aspect: In order to call it fully functional, I have to fix the GitHub workflows. When I'm done, I will create the PR.

> Hopefully beind an `if` or in rarely used code. The linter is something I want to have !

I didn't investigate that much and just recall seeing it in code arround the AlertDialog in the custom preferences, but the linter will tell you ;)

> The app currently contains a 100Kb list of emoji in res/raw/emojis.txt that would go away with the library.

I totally forgot about that, but it might already have been optimized away by resource shrinking. I will investigate after the transfer to Gradle is done. The same goes for the API level.

> We can try enabling it.

I didn't notice any differences, but maybe it could have an impact on older devices. If any problems appear, it should also be possible to enable or disable it per view (https://developer.android.com/topic/performance/hardware-accel#view-level).

**Comment by deftkHD** [comment]
After a while I have the time again to catch up with my stuff here. The AndroidX emoji library is a different topic and has nothing to do with the development environment. With #452 being merged, I think this issue can be closed.
