### ISSUE TITLE
#feature #request Need modifiable adding keys to the keyboard

### ISSUE THREAD

**Issue by kingkhan71** [Julow/Unexpected-Keyboard#449]
Actually when we select/tick 'add keys' then they take place wherever the keyboards alphabates space is empty.. so its not handy.. if i untick other 'add keys' then they move and change the place, So the ones I want to use go away from the reach of my thumb then .. That's why I have to tick those which are not even in use.. ( important keys need to be handy- copy, paste, select all, share keys! RIGHT HAND USER)

**Comment by Julow** [comment]
This is an important issue that I intent to fix on the medium term.
