### ISSUE TITLE
always accessible enter key

### ISSUE THREAD

**Issue by Quantenzitrone** [Julow/Unexpected-Keyboard#45]
In a lot of input fields the enter key gets replaced by the action key, making the enter key only accessible via the 123+ menu.

It would be nice here to have the Enter key as a corner key of the Done key.

**Comment by Julow** [comment]
The enter key is supposed to be on a corner of the action key (top right). On what applications is it inaccessible ?

**Comment by Quantenzitrone** [comment]
In all applications where there is an action key. OctoDroid, Signal, Nekogram X etc.
I currently have Version 1.11.1 from F-Droid installed.
However the enter key is on the top right of the action key inside the 123+ menu.

**Comment by Julow** [comment]
Should be fixed for the next release. I found two problems: 348c278, 2f47d24. The Enter key will be back but also the Action key will be less annoying.

**Comment by Quantenzitrone** [comment]
thanks
