### ISSUE TITLE
congratulations and a suggestion

### ISSUE THREAD

**Issue by MateElPepitoQuerido** [Julow/Unexpected-Keyboard#450]
Hi bro, your application is the best I've seen of its kind and I have a suggestion to make it even better, that it be synchronized with the clipboard to use another keyboard for that purpose or that it have a synchronized clipboard as well. If I'm honest, the longer I remember the clips, the better!!.
greetings to you and those who contributed to unexpected keyboard 😸

**Comment by Julow** [comment]
Thanks for the encouragements!
We have some issues about clipboard already (one is https://github.com/Julow/Unexpected-Keyboard/issues/195).
Could you open a different issue for the background image idea ?

**Comment by BuenGenio** [comment]
I double the kudos - I love the swiping and soft vibration on taps - feels like im typing on a nice soft physical ke rboard 

Inportant to link up dicctionnaries and add aito-corrwct. Essential. Shoild i create a sepaeate issie for thjs?

**Comment by Julow** [comment]
Thanks :) There's already an issue for dictionaries and auto-correct: https://github.com/Julow/Unexpected-Keyboard/issues/343
