### ISSUE TITLE
Wrong Farsi translation

### ISSUE THREAD

**Issue by ghost** [Julow/Unexpected-Keyboard#451]
Almost 70% of your translation is not correct How can I help you in Persian (Farsi) translation?
- Of course, I am Persian (Farsi).

**Comment by Julow** [comment]
Thanks for your help!
Farsi translations are written in this file: https://github.com/Julow/Unexpected-Keyboard/blob/master/res/values-fa/strings.xml
The lines with `<!-- ... -->` indicate missing translations, remove `<!--` and `-->` and change the text.

**Comment by Julow** [comment]
I tried to make the translation guidelines a bit clearer: https://github.com/Julow/Unexpected-Keyboard/blob/master/CONTRIBUTING.md#updating-translations
Feedback welcome :)

**Comment by Julow** [comment]
The author of this issue turned into a ghost so I'll close. I leave a link to https://github.com/Julow/Unexpected-Keyboard/issues/373 so it could be found later.
