### ISSUE TITLE
[Feature Request] ability to jump cursor between words

### ISSUE THREAD

**Issue by mattiasboholm** [Julow/Unexpected-Keyboard#460]
If this is already a feature, I apologize, I must be blind. The left right arrow keys seem to a large extent function like the cursor movement available through the space bar, an option to make them jump between words instead I think would be a nice addition.

**Comment by Julow** [comment]
Holding Ctrl while moving the cursor should jump between words. This was broken in the last release but has been fixed recently (9b917e79).
In the meantime you can use the debug build: https://github.com/Julow/Unexpected-Keyboard/actions/runs/6021927695

**Comment by mattiasboholm** [comment]
Ahh ok, thank you!
