### ISSUE TITLE
Multi Custom Keyboards!

### ISSUE THREAD

**Issue by cachewram** [Julow/Unexpected-Keyboard#465]
Hello @Julow 

I just reinstalled the keyboard and saw the multi custom release is already out! This was totally - unexpected.
Can we access our own custom keyboards with a key like the numerical and greek buttons do?
Here is a compact keyboard I am working on. Any comments/help very welcome. 

<?xml version="1.0" encoding="UTF-8" standalone="yes"?> <keyboard bottom_row ="false"> <row height="1.6"> 

<key key0="|" key1="\\" key2="loc accent_cedille" key3="&lt;>" key4="."  
key5="" key6="," key7="\?" key8="/"/> 

<key key0="esc" key1="~" key2="\@" key3="!" key4="\#" key5="loc €" key6="loc ₪" key7="45" key8="$"/>

<key key0="%" key1="^" key2="&amp;" key3="()" key4="*" key5="loc accent_macron" key6="f11_placeholder" key7="f12_placeholder" key8="tab"/>

<key key0="`" key1="loc accent_ring" key2="\@" key3="loc accent_ogonek" key4="loc accent_grave" key5="loc £" key6="loc accent_aigu" key7="loc accent_dot_above" key8="loc accent_caron"/>

<key key0="-" key1="_" key2="=" key3="+" key4="loc accent_trema" key5="loc accent_circonflexe" key6="{}" key7="loc accent_double_aigu" key8="[]"/>

<key key0="5" key1="1" key2="3" key3="7" key4="9" key5="4"  key6="6" key7="2" key8="8"/>

<key key0="loc accent_tilde" key1=":" key2="0" key3=";" key4="&quot;" key5="'" key6="."/>

<key key2="ctrl" key1="loc alt" key0="loc meta" key3="loc switch_greekmath" key4="switch_numeric"key5="switch_emoji" key6="config"/>

<key key0="s" key1="q" key2="e" key3="z" key4="c" key5="a"  key6="d" key7="w" key8="x"  />

<key key0="g" key1="r" key2="y" key3="v" key4="n" key5="f" key6="h" key7="t" key8="b"/>

<key key0="k" key1="u" key2="o" key3="m" key4="delete" key5="j"  key6="l" key7="i" key8="backspace"/>

<key key0="space" key1="p" key2="enter"  key3="loc capslock" key4="ctrl" key5="left" key6="shift" key7="up" key8="down"/>

 </row> 
</keyboard>

**Comment by Julow** [comment]
There's no way to switch to a custom layout directly. That would be a good idea but there's two problems with placement:

- For custom placement of the switching key, custom layouts would need to have a name.
- For automatic placement, there's no way to specify where to place automatically added keys.

The only switching keys are up and down (key 7 and 8) on the space bar:

```xml
  <key width="4.4" key0="space" key7="switch_forward" key8="switch_backward" key5="cursor_left" key6="cursor_right" slider="true"/>
```

Your layout don't render in your issue. You must enclose it between two `` ``` `` lines. For what I saw in the email notification, is here only one very large row ?

**Comment by cachewram** [comment]
Yes its one row. Its designed for landscape mode. Although I can use it in profile mode as well. 
And I didnt suss that out about the  down key as well as the up space key calling layouts. Thanks.

**Comment by cachewram** [comment]
Is this what you mean? BTW spacebar is a tap on the far right directionals key.
...
<?xml version="1.0" encoding="UTF-8" standalone="yes"?> <keyboard bottom_row ="false"> <row height="1.6"> 


<key key0="|" key1="\\" key2="loc accent_cedille" key3="&lt;>" key4="."  
key5="" key6="," key7="\?" key8="/"/> 


<key key0="esc" key1="~" key2="\@" key3="!" key4="\#" key5="loc €" key6="loc ₪" key7="45" key8="$"/>


<key key0="%" key1="^" key2="&amp;" key3="()" key4="*" key5="loc accent_macron" key6="f11_placeholder" key7="f12_placeholder" key8="tab"/>



<key key0="`" key1="loc accent_ring" key2="\@" key3="loc accent_ogonek" key4="loc accent_grave" key5="loc £" key6="loc accent_aigu" key7="loc accent_dot_above" key8="loc accent_caron"/>



<key key0="-" key1="_" key2="=" key3="+" key4="loc accent_trema" key5="loc accent_circonflexe" key6="{}" key7="loc accent_double_aigu" key8="[]"/>

<key key0="5" key1="1" key2="3" key3="7" key4="9" key5="4"  key6="6" key7="2" key8="8"/>


<key key0="loc accent_tilde" key1=":" key2="0" key3=";" key4="&quot;" key5="'" key6="."/>



<key key2="ctrl" key1="loc alt" key0="loc meta" key3="loc switch_greekmath" key4="switch_numeric"key5="switch_emoji" key6="config"/>


<key key0="s" key1="q" key2="e" key3="z" key4="c" key5="a"  key6="d" key7="w" key8="x"  />

<key key0="g" key1="r" key2="y" key3="v" key4="n" key5="f" key6="h" key7="t" key8="b"/>


<key key0="k" key1="u" key2="o" key3="m" key4="delete" key5="j"  key6="l" key7="i" key8="backspace"/>

<key key0="space" key1="p" key2="enter"  key3="loc capslock" key4="ctrl" key5="left" key6="shift" key7="up" key8="down"/>





 </row> </keyboard>

...

**Comment by Julow** [comment]
I'm talking about the default space bar. You need to add `switch_forward` and `switch_backward` somewhere in your layout to be able to change layout.

Your layout is not visible on Github, you need to enclose it in a code block.

**Comment by cachewram** [comment]
Do you press this button (<>) in the toolbar above and then paste the code where the flashing cursor appears?

**Comment by cachewram** [comment]
`<?xml version="1.0" encoding="UTF-8" standalone="yes"?> <keyboard bottom_row ="false"> <row height="1.6"> 


<key key0="|" key1="\\" key2="loc accent_cedille" key3="&lt;>" key4="."  
key5="" key6="," key7="\?" key8="/"/> 


<key key0="esc" key1="~" key2="\@" key3="!" key4="\#" key5="loc €" key6="loc ₪" key7="45" key8="$"/>


<key key0="%" key1="^" key2="&amp;" key3="()" key4="*" key5="loc accent_macron" key6="f11_placeholder" key7="f12_placeholder" key8="tab"/>



<key key0="`" key1="loc accent_ring" key2="\@" key3="loc accent_ogonek" key4="loc accent_grave" key5="loc £" key6="loc accent_aigu" key7="loc accent_dot_above" key8="loc accent_caron"/>



<key key0="-" key1="_" key2="=" key3="+" key4="loc accent_trema" key5="loc accent_circonflexe" key6="{}" key7="loc accent_double_aigu" key8="[]"/>

<key key0="5" key1="1" key2="3" key3="7" key4="9" key5="4"  key6="6" key7="2" key8="8"/>


<key key0="loc accent_tilde" key1=":" key2="0" key3=";" key4="&quot;" key5="'" key6="."/>



<key key2="ctrl" key1="loc alt" key0="loc meta" key3="loc switch_greekmath" key4="switch_numeric"key5="switch_emoji" key6="config"/>


<key key0="s" key1="q" key2="e" key3="z" key4="c" key5="a"  key6="d" key7="w" key8="x"  />

<key key0="g" key1="r" key2="y" key3="v" key4="n" key5="f" key6="h" key7="t" key8="b"/>


<key key0="k" key1="u" key2="o" key3="m" key4="delete" key5="j"  key6="l" key7="i" key8="backspace"/>

<key key0="space" key1="p" key2="enter"  key3="loc capslock" key4="ctrl" key5="left" key6="shift" key7="up" key8="down"/>





 </row> </keyboard>



`

**Comment by cachewram** [comment]
{<?xml version="1.0" encoding="UTF-8" standalone="yes"?> <keyboard bottom_row ="false"> <row height="1.6"> 


<key key0="|" key1="\\" key2="loc accent_cedille" key3="&lt;>" key4="."  
key5="" key6="," key7="\?" key8="/"/> 


<key key0="esc" key1="~" key2="\@" key3="!" key4="\#" key5="loc €" key6="loc ₪" key7="45" key8="$"/>


<key key0="%" key1="^" key2="&amp;" key3="()" key4="*" key5="loc accent_macron" key6="f11_placeholder" key7="f12_placeholder" key8="tab"/>



<key key0="`" key1="loc accent_ring" key2="\@" key3="loc accent_ogonek" key4="loc accent_grave" key5="loc £" key6="loc accent_aigu" key7="loc accent_dot_above" key8="loc accent_caron"/>



<key key0="-" key1="_" key2="=" key3="+" key4="loc accent_trema" key5="loc accent_circonflexe" key6="{}" key7="loc accent_double_aigu" key8="[]"/>

<key key0="5" key1="1" key2="3" key3="7" key4="9" key5="4"  key6="6" key7="2" key8="8"/>


<key key0="loc accent_tilde" key1=":" key2="0" key3=";" key4="&quot;" key5="'" key6="."/>



<key key2="ctrl" key1="loc alt" key0="loc meta" key3="loc switch_greekmath" key4="switch_numeric"key5="switch_emoji" key6="config"/>


<key key0="s" key1="q" key2="e" key3="z" key4="c" key5="a"  key6="d" key7="w" key8="x"  />

<key key0="g" key1="r" key2="y" key3="v" key4="n" key5="f" key6="h" key7="t" key8="b"/>


<key key0="k" key1="u" key2="o" key3="m" key4="delete" key5="j"  key6="l" key7="i" key8="backspace"/>

<key key0="space" key1="p" key2="enter"  key3="loc capslock" key4="ctrl" key5="left" key6="shift" key7="up" key8="down"/>





 </row> </keyboard>



}

**Comment by cachewram** [comment]
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?> <keyboard bottom_row ="false"> <row height="1.6"> 


<key key0="|" key1="\\" key2="loc accent_cedille" key3="&lt;>" key4="."  
key5="" key6="," key7="\?" key8="/"/> 


<key key0="esc" key1="~" key2="\@" key3="!" key4="\#" key5="loc €" key6="loc ₪" key7="45" key8="$"/>


<key key0="%" key1="^" key2="&amp;" key3="()" key4="*" key5="loc accent_macron" key6="f11_placeholder" key7="f12_placeholder" key8="tab"/>



<key key0="`" key1="loc accent_ring" key2="\@" key3="loc accent_ogonek" key4="loc accent_grave" key5="loc £" key6="loc accent_aigu" key7="loc accent_dot_above" key8="loc accent_caron"/>



<key key0="-" key1="_" key2="=" key3="+" key4="loc accent_trema" key5="loc accent_circonflexe" key6="{}" key7="loc accent_double_aigu" key8="[]"/>

<key key0="5" key1="1" key2="3" key3="7" key4="9" key5="4"  key6="6" key7="2" key8="8"/>


<key key0="loc accent_tilde" key1=":" key2="0" key3=";" key4="&quot;" key5="'" key6="."/>



<key key2="ctrl" key1="loc alt" key0="loc meta" key3="loc switch_greekmath" key4="switch_numeric"key5="switch_emoji" key6="config"/>


<key key0="s" key1="q" key2="e" key3="z" key4="c" key5="a"  key6="d" key7="w" key8="x"  />

<key key0="g" key1="r" key2="y" key3="v" key4="n" key5="f" key6="h" key7="t" key8="b"/>


<key key0="k" key1="u" key2="o" key3="m" key4="delete" key5="j"  key6="l" key7="i" key8="backspace"/>

<key key0="space" key1="p" key2="enter"  key3="loc capslock" key4="ctrl" key5="left" key6="shift" key7="up" key8="down"/>





 </row> </keyboard>
```

**Comment by Julow** [comment]
That's quite an original layout! 
To gain some readability, perhaps you can move digits and less used punctuation to a different layout ?

**Comment by cachewram** [comment]
Cheers for posting the switchers up. I replaced the 45 key with one. Going to tidy it all up now. I might be some time...

**Comment by Julow** [comment]
I'll close this issue. The layout option should be sufficient for your needs. Please open more issues if needed.
