### ISSUE TITLE
Ability to show custom Layout names

### ISSUE THREAD

**Issue by sdrapha** [Julow/Unexpected-Keyboard#466]
Feature request to show the keyboard names of Custom Layouts.
I already have the names defined on the xml, but they don't show up in the list.

![Screenshot_20230909_101207_Unexpected Keyboard (debug)_1](https://github.com/Julow/Unexpected-Keyboard/assets/25059996/a8239bc7-75ff-4d53-8103-0910adb1d2cd)

I'm currently using two different custom layouts, and it's hard to tell them apart in the list.

**Comment by Julow** [comment]
Custom layouts are not parsed when they are shown in the settings but that would be a good thing to do. Parsing the layouts will allow to show errors.

**Comment by Julow** [comment]
This is implemented in 148f3df and was suggested in https://github.com/Julow/Unexpected-Keyboard/issues/522
