### ISSUE TITLE
Cursor (left & right) in emoji layout

### ISSUE THREAD

**Issue by BtAbdul** [Julow/Unexpected-Keyboard#467]
Hello,

it would be great and useful to add cursor left or right (arrows key) in emoji layout

Default layout: 
![IMG_20230913_000548](https://github.com/Julow/Unexpected-Keyboard/assets/46757797/8d9d8697-a28c-474d-9309-daec8bb6518c)

What I'm expecting to add arrows ⬅️➡️ :
![IMG_20230913_000747](https://github.com/Julow/Unexpected-Keyboard/assets/46757797/625b1d04-e230-4fc8-afb5-6ac255b5edfc)

**Comment by BtAbdul** [comment]
It would be useful, if you add it

**Comment by Julow** [comment]
Implemented in 148bed7
