### ISSUE TITLE
modification and development of keyboards in the application (xml)

### ISSUE THREAD

**Issue by MateElPepitoQuerido** [Julow/Unexpected-Keyboard#469]
I saw the page https://unexpected-keyboard-layout-editor.lixquid.com/ and I thought it would be a good idea, since sometimes the default shortcuts are inconvenient for me

**Comment by Julow** [comment]
Sorry for the slow reply. The layout generated by this web app can be pasted in the app settings, in "Custom layout", at the bottom of the dropdown menu for choosing a layout.

**Comment by Julow** [comment]
Was the suggestion to add a similar interface for defining custom layouts within the app settings ?
