### ISSUE TITLE
Option to specify custom vibration length/intensity (independent of system – limited)

### ISSUE THREAD

**Issue by Validbit** [Julow/Unexpected-Keyboard#470]
Hello again, apologies for no technical details, however another practical issue arisen, helped but unresolved for most cases in #118, #119, (#168)

The low vibration option in settings (or system setting on lowest) is too intensive on some devices - even though there are apps that allow much lower values)

Could intensity/length be **typed/slid in ms** (Custom option) or have other setting(s)/methods

Apps where it vibrations can be set to feel comfortable (device: Realme GT2, RMX3311):
- mint keyboard (1-2ms ideal)
- dcoder (different feel)

**Comment by Julow** [comment]
The vibration slider is added back in 73267d6
