### ISSUE TITLE
Alt + S combination is mapped to ß

### ISSUE THREAD

**Issue by playbyan1453** [Julow/Unexpected-Keyboard#472]
While activating `alt + s` key on every app translates to `ß` wich what I expect is raw key, like in blender `alt + s` is shortcut to reset scale. On this [forum](https://androidforums.com/threads/how-to-remove-alt-s-%C3%9F-mapping.1338780/) mentioned their workaround is to change left alt to right alt, that I think is it's not available in this keyboard.

**Comment by Julow** [comment]
Thanks for the report! This is indeed not wanted as it's possible to type ß with the keyboard in other ways.

The forum post you link to does not suggest changing left alt to right alt. Instead, they changes their emacs config to not have to use alt anymore.
By changing the keyboard to use the right alt, the problem persists.

**Comment by playbyan1453** [comment]
Interesting problem indeed but is there any solution to this?
