### ISSUE TITLE
Add Home and End key to additional keys

### ISSUE THREAD

**Issue by Dacid99** [Julow/Unexpected-Keyboard#478]
Would it be possible to add an Home and End key to the additional keys i can add to the keyboard? 
It would be very useful when navigating text.

Thank you for the amazing project, it's exactly the keyboard i always wanted (i absolutely love the math symbols section!) !

**Comment by Julow** [comment]
Home and end are on Fn+left and right. Do you need them directly on the keyboard ?

**Comment by Dacid99** [comment]
Yeah that would be very helpful. I have exactly the space for those two on the qwertz keyboard on the d and f key, and right on the keyboard with a swipe is much quicker than fn and swiping. Thank you for the quick reply!

**Comment by Spike-from-NH** [comment]
I want this too—often use Shift-Home and Shift-End too. One can specify "home" and "end" in the .XML custom layout:
  <key key0="right" key7="end"/>

**Comment by Julow** [comment]
I've added home, end, page up and page down to the extra keys in 33653a9 and placed them on the same key as the arrows:
![2023-10-20-12-21](https://github.com/Julow/Unexpected-Keyboard/assets/2310568/961d4d02-0c0b-4935-855c-73efb80a07a0)

It looks a bit messy when they are all enabled but it's ok when only two are enabled. Could you try it and check whether it's usable ?
Debug build can be found here: https://github.com/Julow/Unexpected-Keyboard/actions/runs/6586462297

**Comment by Dacid99** [comment]
Yeah that works very nicely!

Did i understand Spike-from-NHs comment correctly, is there the option of adding a custom layout by myself?
If yes, how would I do that?

**Comment by Julow** [comment]
When selecting a layout in the settings, at the bottom of the list is "Custom layout". Here's an example of a layout: https://github.com/Julow/Unexpected-Keyboard/blob/master/res/xml/latn_qwerty_us.xml

**Comment by Dacid99** [comment]
Ok that was unexpected-ly simple, thanks a lot!
I will be using this version now, if i get annoyed because of frequent mistyping ill report on it.
Keep up the great work!

**Comment by Spike-from-NH** [comment]
> Did i understand Spike-from-NHs comment correctly, is there the option of adding a custom layout by myself? If yes, how would I do that?

Yes, @Dacid99. @Julow taught me how to do so in my closed #345. The Preferences have changed since then, but the essence is to prepare your custom XML file, copy it into your phone's clipboard, activate Preferences (gear icon), select the custom layout, then paste it in. (Select All then Paste if updating.)

**Comment by Dacid99** [comment]
> > Did i understand Spike-from-NHs comment correctly, is there the option of adding a custom layout by myself? If yes, how would I do that?
> 
> Yes, @Dacid99. @Julow taught me how to do so in my closed #345. The Preferences have changed since then, but the essence is to prepare your custom XML file,* copy it into your phone's clipboard, activate Preferences (gear icon), select the custom layout, then paste it in. (Select All then Paste if updating.)
> 
>  .* #365 describes a web-based tool that accepts your gestures and writes the XML for you.

Super, thank you very much.
Maybe it would be a good idea to add these informtions to the description so everyone is aware of this option.
