### ISSUE TITLE
Add Russian Rouble sign

### ISSUE THREAD

**Issue by Twilightssuperb** [Julow/Unexpected-Keyboard#481]
₽

(It's annoying to use clipboard manager for copy/pasting it.)

Meanwhile you could also implement other [currency Unicode symbols](https://www.unicode.org/charts/nameslist/n_20A0.html).

**Comment by Julow** [comment]
Added in 2d164ca to the Russian layout and to the Latin FN layer. Other currency symbols will be added via the compose key later.
