### ISSUE TITLE
Question, Delete bottom row.

### ISSUE THREAD

**Issue by MartinMilesi** [Julow/Unexpected-Keyboard#482]
Hello, i am trying to make a custom layout,  is there any way to avoid getting the last row added automatically ? the one that have ctrl fn space and arrows keys.

**Comment by Julow** [comment]
This is done with `<keyboard bottom_row="false">`, here's an example: https://github.com/Julow/Unexpected-Keyboard/blob/master/res/xml/latn_neo2.xml

**Comment by MartinMilesi** [comment]
Thanks !
