### ISSUE TITLE
Add GBoard Like Alternate Layout

### ISSUE THREAD

**Issue by V6lhost** [Julow/Unexpected-Keyboard#488]
I think it might be nice to add an alternative layout similar to Gboard for new users. I tried to do it and for now it looks like this as a custom layout
![Screenshot_20231104-143527_Dosyalar.png](https://github.com/Julow/Unexpected-Keyboard/assets/147528068/b4e25116-ce7a-4caf-b268-ab9149fcd991)

**Comment by Diegoteclados** [comment]
Concordo

**Comment by Julow** [comment]
The layout looks nice, could you send a PR to this repository ? https://github.com/Julow/Unexpected-Keyboard-layouts

**Comment by Julow** [comment]
I'll close this issue as it's not actionable.
