### ISSUE TITLE
Enter key behaviour

### ISSUE THREAD

**Issue by KloolK** [Julow/Unexpected-Keyboard#49]
I just installed the most recent release (1.12.0) to test the fix from #45.
Unfortunately, this does not seem to have solved my issue. I recorded a video to demonstrate:

https://user-images.githubusercontent.com/3864672/151773212-10788eba-2e9f-44e0-a89f-3847cf37cb19.mp4

In the beginning, I press the _Enter_ key once which makes the focus change to the "Sorted by:" view below the search field. Only then, the _Enter_ button becomes the _Done_ button. Ideally, it should have been like this from the first time the keyboard pops up.
Then I perform various actions on the UI (clear search text, change focus) hoping to illustrate the issue.

Please let me know if you need any further details.

Many thanks for your great work! :+1:

**Comment by Julow** [comment]
The Action key is hard to get right! Every apps do crazy things and Android's APIs related to input methods are wide and badly documented.
Do you encounter this bug in other apps ? (preferably apps that don't require an account)

**Comment by KloolK** [comment]
Currently, I don't have any other app where this occurs.

I had it in https://tasks.org/ when adding subtasks before, but that was fixed by #45 :)

**Comment by Julow** [comment]
I'm closing this due to lack of feedback. I suspect this is fixed, please re-open with more informations if it's not/
