### ISSUE TITLE
Separate layouts for Landscape vs Portrait

### ISSUE THREAD

**Issue by Spike-from-NH** [Julow/Unexpected-Keyboard#491]
#224 last year proposed a new layout for Unexpected Keyboard. @moya2162 asked for an option that would depend on Landscape vs Portrait. The issue was settled by suggesting the use of custom layouts.

Extending moya's idea, I'd like the user to have the option of different layouts for Landscape and Portrait. I wrote a custom layout suitable for Portrait. However, in Landscape, the width of the keys wastes space, while my preferred 5-row format invades too much of the file being edited. I'd gladly write a second custom layout (perhaps moving the entire numeric row over to the side) if there were a way to specify they were each invoked according to orientation.

**Comment by Spike-from-NH** [comment]
I did write a custom layout for landscape and was able to test it. Now, Unexpected will let me add two custom layouts; but it seems there is only one buffer for the XML. Both use the last XML you pasted in; two custom layouts cannot coexist.

**Comment by Julow** [comment]
> Unexpected will let me add two custom layouts; but it seems there is only one buffer for the XML. Both use the last XML you pasted in; two custom layouts cannot coexist.

This is a bug that I cannot reproduce. How do you observe that ?

**Comment by Julow** [comment]
I have a suggestion to improve the situation.
The value `_currentTextLayout` in [https://github.com/Julow/Unexpected-Keyboard/blob/master/srcs/juloo.keyboard2/Keyboard2.java#L35](Keyboard2.java) represents which layout is currently visible (custom or not). This value is not persisted when the app restarts.

I suggest the following:
- Persist `_currentTextLayout` in the `SharedPreferences`. `Config.java` is the right place to do that. It would perhaps be moved to `_config.current_text_layout`.
- Add a `_config.current_text_layout_landscape` that is also persisted and is used in `current_layout_unmodified` and `setTextLayout` when in landscape mode. (this can be checked with `_config.orientation_landscape`)

This seems simpler and more intuitive than adding more settings and I think this would fix your problem.

**Comment by Spike-from-NH** [comment]
> This is a bug that I cannot reproduce. How do you observe that ?

① Have Layout 1: Custom layout" for my Portrait XML
② Select "Add an alternate layout", specify Custom, paste in my Landscape XML
③ Return to editing; it's still using the first XML

With a single custom layout, I can see that my 2nd XML file is error-free. Am I missing a step, such as restart? If this worked, it would resolve my problem; having to select Layout 2 is a small burden for the few times I want to edit in Landscape.

**Comment by Spike-from-NH** [comment]
> This value is not persisted when the app restarts.

Hasn't been a problem for me as I've only had one layout. But I agree, it's peculiar if JUK lapses back to a layout other that the last one the user selected.

> (this can be checked with `_config.orientation_landscape`)

I've been customizing solely by writing XML, not by editing the program code or doing custom builds. It makes sense not to burden users with an orientation question each time they select a layout. Perhaps a new XML attribute to specify that a given layout is Only-P or Only-L?

**Comment by sdrapha** [comment]
> I have a suggestion to improve the situation. The value `_currentTextLayout` in [https://github.com/Julow/Unexpected-Keyboard/blob/master/srcs/juloo.keyboard2/Keyboard2.java#L35](Keyboard2.java) represents which layout is currently visible (custom or not). This value is not persisted when the app restarts.
> 
> I suggest the following:
> 
> * Persist `_currentTextLayout` in the `SharedPreferences`. `Config.java` is the right place to do that. It would perhaps be moved to `_config.current_text_layout`.
> * Add a `_config.current_text_layout_landscape` that is also persisted and is used in `current_layout_unmodified` and `setTextLayout` when in landscape mode. (this can be checked with `_config.orientation_landscape`)
> 
> This seems simpler and more intuitive than adding more settings and I think this would fix your problem.

This !!! Getting a bit off topic but, I had plans to put an issue for that. I use two different custom layouts, one full screen and one shifted right for one hand operation, and no default layouts, only the custom ones. I always had the feeling that they kept switching on me randomly. but no true confirmation. That is it. Those mentioned upgrades would be really welcome.

**Comment by Spike-from-NH** [comment]
> Getting a bit off topic but,

Not off-topic to say that the proposed solution solves another problem too!

When I use the gear icon to select Custom layout 2 (this seems the only way to switch between layouts), it displays my 2nd XML file and may display the soft keyboard. I wonder if this sequence is a "restart" that lost the context.

**Comment by Julow** [comment]
> Perhaps a new XML attribute to specify that a given layout is Only-P or Only-L?

The implementation might contain edge cases and that's one more thing to explain. Since @sdrapha message I am confident that the persisted value idea is better.

**Comment by Spike-from-NH** [comment]
OK. By the way, my assertion in post №2 that there is only one custom XML buffer is untrue; I do see that JUK has remembered both my custom formats, it just never uses the second one.

**Comment by Julow** [comment]
> OK. By the way, my assertion in post №2 that there is only one custom XML buffer is untrue; I do see that JUK has remembered both my custom formats, it just never uses the second one.

That seems like a syntax error then. I plan to show these errors soon.

**Comment by Spike-from-NH** [comment]
> That seems like a syntax error then. I plan to show these errors soon.

I would appreciate that diagnostic help! But there's no syntax error; again, I can see my newer XML in operation—provided it's the only one.

**Comment by Julow** [comment]
Can you share your layouts ?

**Comment by Julow** [comment]
Implemented in 15de829 and 44adb55. Could you open a different issue for the custom layout issue ? With your layouts if possible.

**Comment by Spike-from-NH** [comment]
Here are my layouts—had to append ".txt" to upload.

Will wait and see before opening another issue—This fix might solve it.

[Julow custom qwerty, Landscape.xml.txt](https://github.com/Julow/Unexpected-Keyboard/files/13404440/Julow.custom.qwerty.Landscape.xml.txt)
[Julow custom qwerty, Portrait.xml.txt](https://github.com/Julow/Unexpected-Keyboard/files/13404441/Julow.custom.qwerty.Portrait.xml.txt)

**Comment by Spike-from-NH** [comment]
The second commit seems to meet my needs exactly, switching layouts implicitly on rotation of the device. But will it baffle other users who change the layout and then do not see their change in the other orientation?

**Comment by Julow** [comment]
> Here are my layouts—had to append ".txt" to upload.

Your layouts do not include the `switch_forward` and `switch_backward` keys, which allow switching between the selected layouts. Not having these keys feel the same as having only one layout.

I recommend not redefining the bottom row to avoid such surprises. The bottom row is defined separately by default on purpose to allow it to change often.

> But will it baffle other users who change the layout and then do not see their change in the other orientation?

I don't think so. First, I don't think many users have several layouts. Second, until now, layouts could change at any time when the app restarts. That could have been when rotating.

**Comment by Spike-from-NH** [comment]
Thanks; I added `key7=switch_forward` to both layouts at space bar. The layout doesn't automatically switch when I rotate the device (in fact, it disappears), but it's now trivial to toggle to the desired layout.

**Comment by Spike-from-NH** [comment]
![Screenshot_20231125-221439_Fennec](https://github.com/Julow/Unexpected-Keyboard/assets/126838489/9ad5cbab-e182-4fd6-a94a-6c34cd0e0323)

**Comment by Julow** [comment]
I improved the custom layout box, would you mind having a try ? (7af6adc, dd327cc, 478d808)

**Comment by Spike-from-NH** [comment]
@Julow - Am trying to try it. Am stuck for now with QWERTY.
1. I need a link to the APK, not just hex digits. This time, I found a link in the nearby thread. Installed in a Samsung Tab A 8 with Android 10.
2. Chronic annoyance - Samsungs have a notion of "Default keyboard" and every time you install a new Unexpected and disable the old one, Default lapses to Samsung keyboard. Can you do anything, even just inform the user?
3. On adding layout and specifying Custom, I was taken back to the initial screen (with "Enable Keyboard" button). Afterward I was told the app keeps crashing.

Will continue to test - if I can get beyond this stage!

**Comment by Julow** [comment]
@Spike-from-NH I'll send a link next time. I plan to add a "Select keyboard" button on the launcher activity that would help selecting the keyboard after it's enabled.

It seems that the app crashes. Do you have experience with getting the logs ? Thanks for testing !

**Comment by Spike-from-NH** [comment]
@Julow, thanks for that. I do have experience getting debug logs—but never from Unexpected. I don't see a Scoped Storage area for it in `/Android/data` where I'd look for crash logs.

**Comment by Spike-from-NH** [comment]
@Julow, I installed 1.25.0; this feature works fine; prior settings carried over and the only required tweaking was to ensure, once-only, that the desired layout was selected in Landscape and in Portrait.

The only oddity: Merely rotating the device dismisses the soft keyboard—SOMETIMES. Varies by Samsung model; sometimes, rotating doesn't but rotating back does. Observed even with the dummy text entry form in Unexpected's installation screen.
