### ISSUE TITLE
Compass-point synonyms in layout XML

### ISSUE THREAD

**Issue by Spike-from-NH** [Julow/Unexpected-Keyboard#495]
In #305, I proposed that it would save a mental step to use compass-point tags in the layout XML rather than `key1` through `key8`. For example, `nw="ñ"` for a swipe to "northwest". You replied positively and said both styles could be supported, or the current style could be phased out but slowly. I'm opening this issue as a reminder or placeholder for this enhancement. There is no urgency, as what we have now works fine.

**Comment by Spike-from-NH** [comment]
If this is trivial to implement and doesn't bog down users who don't want it, can you add this soon as an alternative? I don't advocate deprecating/removing the key_n_ alternative.

**Comment by Spike-from-NH** [comment]
@Julow, I tried coding in Java, modifying KeyboardData.java to define the compass-point synonyms to populate KeyValue.

Had to use a tiny phone as it wasn't working on my tablet; Iseem to have committed twice in a branch of the master, but only requested merge once. As before, you are welcome to massage this.

**Comment by Julow** [comment]
Implemented in https://github.com/Julow/Unexpected-Keyboard/pull/628, thanks!

**Comment by Spike-from-NH** [comment]
@Julow, may we have a 1.28? Or are you waiting until the Korean keyboard is perfected?

**Comment by Julow** [comment]
I'm waiting until I have enough free time. I'm planning to do it this weekend, if all goes well.

**Comment by Spike-from-NH** [comment]
Thanks; looking forward to it.
