### ISSUE TITLE
How to import custom keyboard?

### ISSUE THREAD

**Issue by MrWhipple** [Julow/Unexpected-Keyboard#499]
I’m sorry to ask such a basic question, but I can’t find any documentation for Unexpected Keyboard or posts about how to do this. :-(

I want to build my own keyboard. I’ve started working on the XML file. 

**Where do I import it?**

Is there a way to import it in the settings? Or is there a directory on my phone where I put the file? If the latter, where is that directory?

Thanks!

**Comment by Spike-from-NH** [comment]
You prepare XML on your device with any editor you prefer (or generate XML with the online tool) and import it by copypaste. In the settings, change a layout to, or add a layout with, "Custom layout". In the single input field in the resulting pop-up, paste in your XML from the clipboard. (If there is already XML there, replace using Sel.all+Paste.) Develop gradually as there is not yet any error-checking; on any error, it reverts to the default layout. More in #354.

**Comment by MrWhipple** [comment]
> You prepare XML on your device with any editor you prefer (or generate XML with the online tool) and import it by copypaste. In the settings, change a layout to, or add a layout with, "Custom layout". In the single input field in the resulting pop-up, paste in your XML from the clipboard. (If there is already XML there, replace using Sel.all+Paste.) Develop gradually as there is not yet any error-checking; on any error, it reverts to the default layout. More in #354.

Thank you very much. Your explanation makes sense, and I’ll give it a try. It was not obvious to me as a new user.

**Comment by Julow** [comment]
The custom layout option will now initially show the QWERTY US layout, which is a good starting point and contain some documentation (d7c230e). It also now show errors in layouts, you can try it here: https://github.com/Julow/Unexpected-Keyboard/actions/runs/7238250601
