### ISSUE TITLE
NumPad is empty when i enable number row

### ISSUE THREAD

**Issue by V6lhost** [Julow/Unexpected-Keyboard#504]
![Screenshot_20231218-003425_Musicolet](https://github.com/Julow/Unexpected-Keyboard/assets/147528068/12dedac4-8219-4854-a748-b6a58d43c263)
![Screenshot_20231218-175837_Papara](https://github.com/Julow/Unexpected-Keyboard/assets/147528068/9d0a2b69-d0ac-44d7-9105-9575eaf89622)

**Comment by V6lhost** [comment]
I use debug version, not stable.

**Comment by Julow** [comment]
Thanks for the report, this is fixed in 2db4ae3.
