### ISSUE TITLE
cant access clipboard

### ISSUE THREAD

**Issue by Hadi-M0** [Julow/Unexpected-Keyboard#508]
how do i do that?

**Comment by Spike-from-NH** [comment]
Swipe the "gear" logo on Fn to go to Settings. Tap "Add keys to the keyboard". The usual ones (Cut/Copy/Paste) are near the bottom of this list. Switch them on and they will now appear as swipes. Otherwise, you can still use the clipboard with Windows-style sequences, such as Ctrl,V for Paste.

**Comment by Julow** [comment]
I think this issue is about the clipboard history feature found in other keyboards. This is a commonly requested feature and I'll close as a duplicate of https://github.com/Julow/Unexpected-Keyboard/issues/195
