### ISSUE TITLE
change the type of numbers

### ISSUE THREAD

**Issue by Hadi-M0** [Julow/Unexpected-Keyboard#509]
hey can you add a setting that allows the use of arabic numbers(1, 2, 3...) insteed of the hindu ones (١ , ٢, ٣...) in the arabic layout?

**Comment by Julow** [comment]
The layout was added in https://github.com/Julow/Unexpected-Keyboard/pull/314. It was initially containing 0..9 but an other user asked for ٠..٩ and the compromise was to have hindu digits on the layout and arabic digits on the number row. This compromise was broken by 687d88f4f.

The arabic layouts are defined to be used with any arabic languages but it seems that we need mre specific layouts specific.
What's your language/country ?

**Comment by Hadi-M0** [comment]
i speak arabic and am from north africa
wo dont use the hindu numbers, i think they are only used in the gulf states (Saudi, qatar etc..)

**Comment by Julow** [comment]
I need a precise language/country code to make a change.

**Comment by Hadi-M0** [comment]
its arabic/tunisia

**Comment by Julow** [comment]
I added a layout for Tunisian (1af4e45), could you try it at https://github.com/Julow/Unexpected-Keyboard/actions/runs/7293035868 ? The APK is found in the "Artifact" section.

It would be nice to fix this for other languages. Do you know the full list of languages that use the hindu numbers ?

Also, feel free to propose change to the layout, it's defined here: https://github.com/Julow/Unexpected-Keyboard/blob/master/res/xml/arab_pc_tn.xml

**Comment by Hadi-M0** [comment]
thanks its working! 
i think the languages that use the hindu numbers are arabic, persian(farsi), peshto, urdu and kurdish 
there might be others though

**Comment by Julow** [comment]
I changed the Tunisian layout for a "Arabic PC" layout with arabic numerals instead, so this fix can apply to other arabic locales. 9ff8179, 7e7a5e4.
I couldn't find a exhaustive enough list to change the default so "Arabic PC (Hindu numerals)" is still the default for arabic locales that are not specified in [method.xml](https://github.com/Julow/Unexpected-Keyboard/blob/master/res/xml/method.xml).
