### ISSUE TITLE
[Feature Request] Delete/backspace key swipe selection

### ISSUE THREAD

**Issue by fAIseh00d** [Julow/Unexpected-Keyboard#516]
In OpenBoard when you hold and drag left the delete key, it acts somewhat like space key, it selects text (you can control selection by dragging left and right) and then deletes selected text once you release the finger.

GBoard has similar functionality but it selects per-word instead of per-symbol in openboard.

Is it possible to implement that as an option?
That behavior is super convenient, once you get used to it it's hard to go back to simple click or hold delete key.

**Comment by fAIseh00d** [comment]
duplicate of #46

**Comment by Julow** [comment]
Thanks for triaging :)
