### ISSUE TITLE
Ability to specify key height in custom layout

### ISSUE THREAD

**Issue by ego-lay-atman-bay** [Julow/Unexpected-Keyboard#518]
Simple, I'd like the ability to specify the height of specific keys in a custom layout. Some uses are for creating a custom utility row that has function keys that don't need to be as big as every other key.

**Comment by Julow** [comment]
You can specify the height of a row with `<row height="1">`, for example the bottom row height is 95% of a normal row: https://github.com/Julow/Unexpected-Keyboard/blob/master/res/xml/bottom_row.xml

Specifying the size of just one key is not possible but could be interesting and I'd approve a contribution. For example to make the Shift and Enter keys slightly different from the rest.

**Comment by Spike-from-NH** [comment]
Another useful secret disclosed! It's clear how to implement a fat row; less so how to implement a single key with height different from the rest in its row. What do you do with the unused space?

**Comment by ego-lay-atman-bay** [comment]
> You can specify the height of a row with `<row height="1">`,

I did not know that, thanks.

**Comment by Indranil012** [comment]
Is there any documentation for custom layout?

**Comment by ego-lay-atman-bay** [comment]
The only documentation that I know of is the comment in the default custom layout.

**Comment by Julow** [comment]
I'll close this. Feel free to re-open if you have more questions or if someone is motivated by the per-key height.

> It's clear how to implement a fat row; less so how to implement a single key with height different from the rest in its row. What do you do with the unused space?

That would create empty space around the key (preferably on top) that might make some layouts more readable. For example, a slightly shorter (90%) shift and backspace keys on most layouts would help differentiate the second and third rows.
