### ISSUE TITLE
Long press <space> key as <tab>

### ISSUE THREAD

**Issue by amsitlab** [Julow/Unexpected-Keyboard#520]
`I` very love this keyboard, but...
I have one question
Can we use long press key [space] as [tab] ?
For me, who use the Autocomplete feature on the editor (neovim + lsp) swipe from key [a] to top-left (as [tab]) is require many time than long press [space] as [tab]

- Using unexpected Keyboard (swipe from [a] to top-left as [tab])
https://github.com/Julow/Unexpected-Keyboard/assets/10000281/c455837b-08d1-4e63-9421-8cf8cf091a22

- Using android next keyboard ( long press [space] as [tab] )
https://github.com/Julow/Unexpected-Keyboard/assets/10000281/a3411088-0deb-4cad-9b0c-c6861cbfb4f6

I really want to contribute, but I have no experince on android dev
Thank for you and all contributor of this project.

**Comment by Julow** [comment]
The swipe gesture is intended to be very efficient. Could you try setting a shorter swipe distance in the settings ?

**Comment by Spike-from-NH** [comment]
I migrated from Hacker's Keyboard and agree that a swipe is much quicker than a long-press. @amsitlab, if the location of the swipe is inconvenient to you, the solution may be to create a custom layout. You can give TAB a dedicated key.

**Comment by amsitlab** [comment]
> The swipe gesture is intended to be very efficient. Could you try setting a shorter swipe distance in the settings ?

Yes.. I tried
Still too difficult for me
Sometimes even typo when swipe from [a] to the left-up



> I migrated from Hacker's Keyboard and agree that a swipe is much quicker than a long-press. @amsitlab, if the location of the swipe is inconvenient to you, the solution may be to create a custom layout. You can give TAB a dedicated key.

For me.. type [space] then [long press space as tab] is more faster rather than type [space] then pressing [other key]
If we can use [long press space as a tab] our thumb don't need to move to any key
Because autocomplete works after [space]

for Example:
`ls [tab]` <- for shell autocomplete directories
will be faster if you use
`ls [space] [longpress space as tab]`
rather than
`ls [space] [other key]`

**Comment by Spike-from-NH** [comment]
@amsitlab, I strongly disagree that the default layout should change to facilitate the sequences **you** happen to generate! Again, the way to customize Unexpected to be perfect for you is through a custom layout.

My custom layout is here: 
[Julow custom qwerty, Portrait.txt](https://github.com/Julow/Unexpected-Keyboard/files/13867411/Julow.custom.qwerty.Portrait.txt)
The line with `key0="space"` defines the space bar. You should change `switch—forward` to `tab`. Then you can execute your sequence by tapping space once, then again and swipe upward.

**Comment by Anarchtism** [comment]
I have a use case for long press actions;
For number input using a MessagEase layout. Since most of the keys already have swipe actions and switching to numbers mode chages the layout of the keyboard.

ANIHORTES(space) -> 7894561230

**Comment by Julow** [comment]
You can use a custom layout with a [modmap](https://github.com/Julow/Unexpected-Keyboard/blob/master/doc/Custom-layouts.md#modmap) that maps `Fn+space` into `tab`. Then you can do a clockwise circle on the space bar, which will type the equivalent of `Fn+space`.

```xml
<modmap>
  <fn a="space" b="tab"/>
</modmap>
```

You can now configure the anti-clockwise circle for each key in custom layouts with the [`anticircle` attribute](https://github.com/Julow/Unexpected-Keyboard/blob/master/doc/Custom-layouts.md#swipes).

I have no plans for long presses in the future.
