### ISSUE TITLE
[Bug] Shift not working (crashing) for custom layouts after 1.25.0 with more rows (important)

### ISSUE THREAD

**Issue by Validbit** [Julow/Unexpected-Keyboard#521]
When clicking on shift (any/general case), the keyboard crashes.

I verified this on VMs (clean install .23, .24 and put the layout through several linters but the issue seems to be elsewhere. (It happens to me **when having/adding additional row on top**)

I also tried pasting it into the new custom template but no luck there either.

Let me know if I can help in any way.

**Comment by Julow** [comment]
Thanks for the report ! This should be fixed by b319356 and 329a35e. You can find a debug build here: https://github.com/Julow/Unexpected-Keyboard/actions/runs/7468208373
