### ISSUE TITLE
Settings screen should identify custom layouts by name

### ISSUE THREAD

**Issue by Spike-from-NH** [Julow/Unexpected-Keyboard#522]
Currently in the Settings page, you may see:
 `Layout 1: Custom layout`

Recently, Unexpected has added support for multiple layouts, including multiple custom layouts, though all these are described as "Custom layout". @Validbit notes in the unrelated #519 that Unexpected lets the XML `keyboard` tag have a `name` attribute. It would be helpful if the list of layouts would identify each custom layout by name, if it contains one.

Also recommend to @Lixquid that the online tool to create custom layouts (see #365) add an optional field to specify the layout's name.

**Comment by Julow** [comment]
This is implemented in 148f3df. Adding it to the online tool would be a good idea.
