### ISSUE TITLE
Compose key, again

### ISSUE THREAD

**Issue by Spike-from-NH** [Julow/Unexpected-Keyboard#523]
Here is the Compose key translation table from Hacker's Keyboard. @Julow, you've said this is something you want to add to Unexpected. To the contrary, I haven't used it all year. All the niche characters that amuse me (①➋③) are now in my custom layout, and I'm about to ditch Hacker's entirely.

Rather than learning Compose sequences, all Unexpected needs is a way to invoke a pop-up that gets a number (toggle for hex vs decimal?) then inserts that UNICODE into the text. If needing it often, user would insert the UNICODE into the custom layout.

You've explained why we're not going to get Hacker's long-press menu of rare characters; indeed swipe is faster; and no one needs Hacker's particular menus but a personalized set—again, via custom layout.

So, for me, this is the last word on Hacker's. Dispose of this issue as you see fit.
[Hacker's Keyboard compose codes.xml.txt](https://github.com/Julow/Unexpected-Keyboard/files/13942055/Hacker.s.Keyboard.compose.codes.xml.txt)

**Comment by Julow** [comment]
Thanks for looking at this!

The compose key feature request is tracked by https://github.com/Julow/Unexpected-Keyboard/issues/204
I planned on using [xkb's sequences](https://cgit.freedesktop.org/xorg/lib/libX11/plain/nls/en_US.UTF-8/Compose.pre) but adding Hacker's Keyboard's ones is a good idea.

The unicode entry feature request is tracked by https://github.com/Julow/Unexpected-Keyboard/issues/191

I'll close this issue as duplicate but I'll make sure to keep your nice ideas.

**Comment by Julow** [comment]
I've found out that Hacker's Keyboard's compose sequences are very close to X11's ones that I included so I did not include both. Feedback appreciated.

**Comment by Spike-from-NH** [comment]
My feedback is as above: The characters I use often, I add to my custom layouts. The ones I use rarely, I don't mind if they take several keystrokes, provided the keystrokes are defined somewhere. In fact, if a rare character of interest is defined in a file, I'd just as soon copypaste it from the file into the document I'm composing.

And yes, X11 is a lot better-known than Hacker's Keyboard. But you ought not have a policy of limiting Unexpected Compose to only the characters X11 supports. And you ought to have a way to let me insert any character for which I have looked up the UNICODE.

**Comment by Julow** [comment]
> And yes, X11 is a lot better-known than Hacker's Keyboard. But you ought not have a policy of limiting Unexpected Compose to only the characters X11 supports.

As I said, Hacker's Keyboard's sequences are almost identical. Is here any sequence you miss ?

> And you ought to have a way to let me insert any character for which I have looked up the UNICODE. (PS—I can't read Python, but it looks like your Compose will accommodate this.)

The unicode entry feature is tracked by this issue: https://github.com/Julow/Unexpected-Keyboard/issues/191
The compose key is not idea for this as the state machine would become too large if all the unicode characters are added.
Though it could be a good idea to add support for some common names (for example, all the HTML entities).

**Comment by Spike-from-NH** [comment]
> the state machine would become too large if all the unicode characters are added.

I don't propose that the state machine enumerate every UNICODE character (nor did OP in #191), certainly not by name; only allow `Compose` plus four hex digits and emit that character.

(The most recent character I added to my own layout was EIGHTH NOTE, which I use maybe once a year to identify something as a song lyric; you cover it and Hacker's didn't.)
