### ISSUE TITLE
Different inter-key margins in Landscape vs Portrait

### ISSUE THREAD

**Issue by Spike-from-NH** [Julow/Unexpected-Keyboard#530]
Specifying "Vertical spacing between the keys" and "Horizontal"... both as 2dp gives satisfactory results in Portrait but a wider horizontal spacing in Landscape. (These are using separate custom layouts.)

Portrait:
![Interkey P](https://github.com/Julow/Unexpected-Keyboard/assets/126838489/80b18123-9ecd-4fcd-af25-8c4f6fd418ab)
Landscape:
![Interkey L](https://github.com/Julow/Unexpected-Keyboard/assets/126838489/e08de711-715b-4260-841e-0c8bfc3b3005)

Running 1.25.0 on a Samsung J7 with Android 8.
Problem mentioned in #507.

**Comment by Julow** [comment]
This is intended, the space between the keys is doubled in landscape mode: https://github.com/Julow/Unexpected-Keyboard/blob/master/srcs/juloo.keyboard2/Config.java#L118

In landscape mode, it's harder to precisely type near the middle of the screen. This changes slightly move parts of the keyboards away from the middle and slightly reduce errors.

**Comment by Spike-from-NH** [comment]
Is this technology (sensing is less precise there) or ergonomics (humans are less precise there)? The extra spacing pushes a few keys closer to the middle as well. I would rather have it look better, but thanks for the reply. Is this doubling worth mentioning near the slider for horizontal dp? Is there merit for a user override or even a separate setting?

**Comment by Julow** [comment]
This is an ergonomics problem and nothing gets pushed toward the middle as the keyboard is centered.

The width of the keyboard really depends on the width of the screen and the margin. The margin is different in landscape.
For more clarity, the space between the keys could be defined in term of the width of the keyboard.

**Comment by Spike-from-NH** [comment]
> nothing gets pushed toward the middle

I stand corrected; the keys are slightly narrower as the spacing gets wider.

> defined in term of the width of the keyboard.

It strikes me as clearer to specify a number of dp (if you actually got what you specified!).

**Comment by Julow** [comment]
I would like to address this. My current idea is to change the key margin option to be expressed in percent of a key width.

**Comment by Spike-from-NH** [comment]
> change the key margin option to be expressed in percent of a key width.

Presumably this is the nominal width for keys we don't re-size using `key width="0.8"` or whatever. It lets Unintended adapt dynamically to layouts that contain more/fewer keys. My choice, the old way, might have been 2dp but a new choice is called for as I add more keys (and they get narrower—the margins should get narrower too). A decent idea, but unrelated to my reason for opening this issue: I'd like the same look in Portrait and Landscape—to opt out of your margin tweaking even at the possible expense of mistyping more.

**Comment by Julow** [comment]
The width of a key is different in landscape and in portrait ? If yes, the margin should be different too.

**Comment by Julow** [comment]
I'm not suggesting a heuristics or an unspecified algorithm. The increased margin is intended. The two changes I intent to make are:
- make the margin dependent on the size of the key and remove the doubling
- change the option to be defined in `%` instead of `dp`.

You need to come up with a change that do not change the general case.

**Comment by Spike-from-NH** [comment]
Removing the doubling solves the "bug" I reported. Going to `%` is fine with me.

**Comment by Spike-from-NH** [comment]
Could the slider for `%` be accompanied by a dynamic graphic that shows the resulting appearance? I don't know what % I'll prefer, but will know it when I see it! A graphic would avoid trial-and-error cycles.

**Comment by Julow** [comment]
You are asking for a large effort that I plan for an eventual theming system but I clearly not have the time to implement it this year.

**Comment by Spike-from-NH** [comment]
Not a problem! I'll be satisfied if I can eventually get a desired appearance. But one other thing: It looks best to me if horizontal inter-key margin is identical to vertical; and it will not look good if horizontal (%) adapts automagically to change in layout but vertical is stuck at the number of dp I specified.

**Comment by Julow** [comment]
The change to `%` will not allow you to have the desired appearance. Ideas are needed.

**Comment by Spike-from-NH** [comment]
I think it will; I'll merely have to tweak vertical after editing/changing layout (which happens rarely). But, ideas:
① Set vertical, too, as % of (horizontal!) size of 1.0 key?
② Automatically use horiz. margin as vertical?
③ Change vertical margin slider to add checkbox, "Same as horizontal"?

**Comment by Julow** [comment]
The change to `%` is implemented in bbc6226. Debug APK: https://github.com/Julow/Unexpected-Keyboard/actions/runs/7687707013
Vertical and horizontal margins must stay separate, as they are different by default. The third ideas seems best as it doesn't change the default appearance. Would you be willing to implement it?

**Comment by Spike-from-NH** [comment]
Sorry! the last language I wrote a lot of code in was Pascal/Delphi! Could probably code by imitation but I have no confidence it would be the best solution. But I'll take your debug API and report.

**Comment by Spike-from-NH** [comment]
Debug APK suits me. Not identical appearance in P vs L but much less pronounced than in "bug report" above. I went with 3%,3%.

**Comment by Spike-from-NH** [comment]
PS—It might be better if it had a subtitle line (as "Label size" does) that answered the question, Percent of what?

**Comment by Spike-from-NH** [comment]
Closing this issue again! The new margins setting in 1.26 lets me get the effect I want and solves the original bug, a different look in Portrait vs Landscape.

**Comment by Julow** [comment]
Thanks for checking!
