### ISSUE TITLE
getSettingsTouchEffectStrength light spam (low priority)

### ISSUE THREAD

**Issue by Validbit** [Julow/Unexpected-Keyboard#533]
For a different reason I opened logcat and noticed there was a burst  (~30x, ~3/s) of

9458 9458 juloo.keyboard2.debug D LinearmotorVibrator : call linearmotor vibrator service getSettingsTouchEffectStrength

without me using the keyboard. I think it may be no longer necessary altogether (since setting of vibration is in ms) but I lack context.

**Comment by Julow** [comment]
I do not experience this on my device. This logs do not originate from the app, though the 3rd column make it seems like. 3 burst a second is a lot.

Do you see similar logs with an other keyboard selected ?

For reference, here's the code that calls the vibrator: https://github.com/Julow/Unexpected-Keyboard/blob/master/srcs/juloo.keyboard2/VibratorCompat.java

**Comment by Validbit** [comment]
(with the passage of time) I haven't seen this coming back (logcat) on my device. Not sure what could've caused it (only system update comes to mind).

Since it did only burst once I think we can close it now, since it'll be for reference anyway (if updates would be made in haptic feedback)
