### ISSUE TITLE
[Feature Request] Multiple custom layouts

### ISSUE THREAD

**Issue by stanislav-tsaplev** [Julow/Unexpected-Keyboard#543]
You can only add one custom layout to the list of alternate layouts at the moment. When you try to add another one, it will replace the previous. Is it possible to allow multiple addition?

Such a feature is crucial for the non-native users that have to use more than one language at the same time

**Comment by Julow** [comment]
Yes, it's possible to add several custom layouts. In the next version, you will also be able to name them.

Don't hesitate to contribute your layouts to the app :)
