### ISSUE TITLE
Cannot install 1.25

### ISSUE THREAD

**Issue by mfortini** [Julow/Unexpected-Keyboard#544]
1.24 works fine.
1.25 crashes installer on android 14

**Comment by Julow** [comment]
What's your version of Android ? Would you be able to get the debug logs ?

**Comment by geofrey** [comment]
Second that F-Droid can't install 1.25 on a Pixel 7.

**Comment by Julow** [comment]
I fail to reproduce the problem on the emulator. Could you try a complete uninstall and re-install ? (Don't if you have custom layouts)

Getting the logs might be a bit technical, F-Droid has some documentation about it: https://f-droid.org/docs/Getting_logcat_messages_after_crash/

**Comment by Julow** [comment]
Sorry, I misread the issue. Version 1.25 contained a known bug that has since been fixed (b319356). The latest version is 1.26 and is available on F-Droid.

**Comment by mfortini** [comment]
Same thing for 1.26 unfortunately. Tried both upgrading and uninstalling/reinstalling.

**Comment by mfortini** [comment]
An error that seems related in the logs is:

`1707724037.343  1000   766   773 W gralloc4: Unable to set buffer name VRI[InstallStaging]#0(BLAST Consumer)0: File name too long
1707724037.345  1000   766   773 W gralloc4: Unable to set buffer name VRI[InstallStaging]#0(BLAST Consumer)0: File name too long
1707724037.346  1000   766   773 W gralloc4: Unable to set buffer name VRI[InstallStaging]#0(BLAST Consumer)0: File name too long
1707724037.346  1000   766   773 W gralloc4: Unable to set buffer name VRI[InstallStaging]#0(BLAST Consumer)0: File name too long
1707724037.347  1000   766   773 W gralloc4: Unable to set buffer name VRI[InstallStaging]#0(BLAST Consumer)0: File name too long
`

**Comment by Julow** [comment]
Do you see any log with occurrences of `juloo.keyboard2` ?

**Comment by mfortini** [comment]
```
grep -i -A2 juloo

1707724037.121 10423 10209 10310 W PackageParser: Unknown element under <manifest>: queries at /data/user/0/org.fdroid.fdroid/cache/apks/f-droid.org--1/juloo.keyboard2_38.apk Binary XML file line #16
1707724037.129  1000  1720  5070 W ActivityTaskManager: startActivity called from non-Activity context; forcing Intent.FLAG_ACTIVITY_NEW_TASK for: Intent { act=org.fdroid.fdroid.installer.DefaultInstaller.action.INSTALL_PACKAGE dat=content://org.fdroid.fdroid.installer.ApkFileProvider/... cmp=org.fdroid.fdroid/.installer.DefaultInstallerActivity (has extras) }
1707724037.134  1000  1720  5070 E Transition: Trying to add a ready-group twice: Display{#0 state=ON size=1440x3120 ROTATION_0}
--
1707724037.282  1000  1720  1720 I NotificationService: Cannot find enqueued record for key: 0|org.fdroid.fdroid|1|https://f-droid.org/repo/juloo.keyboard2_38.apk|10423
1707724037.286  1000  1720  1720 I NotificationService: Cannot find enqueued record for key: 0|org.fdroid.fdroid|1|https://f-droid.org/repo/juloo.keyboard2_38.apk|10423
1707724037.287  1000  1720  1720 I NotificationService: Cannot find enqueued record for key: 0|org.fdroid.fdroid|1|updates|10423
1707724037.291 10072 17493 17493 D CompatibilityChangeReporter: Compat change id reported: 210923482; UID 10072; state: ENABLED

```

**Comment by Julow** [comment]
Thanks for the logs. This might be a bug in F-Droid: https://gitlab.com/fdroid/fdroidclient/-/issues/2728, https://gitlab.com/fdroid/fdroidclient/-/issues/2741, https://gitlab.com/fdroid/fdroidclient/-/issues/2752

Could you try F-Droid version 1.19 linked to in the last issue ?

**Comment by KevinGoodsell** [comment]
> Could you try F-Droid version 1.19 linked to in the last issue ?

I had this issue as well. I installed F-Droid 1.19 and retried the Unexpected Keyboard update. This time it worked fine.

Thank you.

**Comment by mfortini** [comment]
Confirmed, installation was successful with new f-droid release.
Thank you

**Comment by Julow** [comment]
Thanks for confirming!
