### ISSUE TITLE
Add option/xml/key to disable hold to type (or other slider keys)

### ISSUE THREAD

**Issue by Validbit** [Julow/Unexpected-Keyboard#548]
When using space to slide cursor, many times it's either just a few characters or multiple rows. One of the more important QoL improvements I see is to make it possible to "lock" slider key(s) to prevent repetetive input (default for holding a key) as I think I'm not the only one who uses it for quick and precise seeking that can take time when developing or thinking more about what is being written. 

_I can see people using repetetive spacebar not just for quick/dirty aligning so globally disabling/removing it might not be the best option._

e.g.
`<key key0="space" ... slider="true" block-hold="true"/>`
in combination with keyboard setting
'Block key repeat for slider keys'
that skips the check (e.g. `block-hold || global-block-hold`)

**Comment by Spike-from-NH** [comment]
That is, you pause while using the slider and Unexpected delivers multiple spaces rather than be more patient? Inventing XML ensures your modification wouldn't break anything for other users. However, I think that disabling auto-repeat once the slider is engaged is a good general rule.

(On rare occasions, I have paused at the end of a swipe and gotten multiple characters, but I don't claim this problem needs a solution, and other users might want this behavior.)

**Comment by Validbit** [comment]
> That is, you pause while using the slider and Unexpected delivers multiple spaces rather than be more patient? Inventing XML ensures your modification wouldn't break anything for other users. However, I think that disabling auto-repeat once the slider is engaged is a good general rule.
> 
> (On rare occasions, I have paused at the end of a swipe and gotten multiple characters, but I don't claim this problem needs a solution, and other users might want this behavior.)

I may not fully understand this reply (may be thought process) but the keyboard already has repeat "disabled" while you're sliding ("inputing" slide). since there are already attributes like slider="", there could be either a new/existing one that would say/bool if the key in the layout is supposed to be repeating or not.

Additionally there could be an settings option that skips the check (if key is repeating) for slider keys (existing slider="true") - since forcing it in code might not be good for people using it in specific environments (terminal,etc.)

**Comment by Julow** [comment]
Repeating is not very useful in general but I think repeating the space character is the second most useful key to repeat.
Perhaps you'd wish for a way to disable key repeat ?

As you noticed, the repeat is stopped as soon as sliding starts. That's the indented way to use the slider: The first slide is not precise but gives you a sense of the sensibility, then you can slow down and go in the other direction.

I can see that the slider is not very easy to use when the "swipe distance" option is set to "very large", is it your case ?

**Comment by Validbit** [comment]
> Perhaps you'd wish for a way to disable key repeat ?
Yes, but only for space (or certain keys for custom layouts)
> I can see that the slider is not very easy to use when the "swipe distance" option is set to "very large", is it your case ?
No, it's comforable (although vertical sliding it too fast but that might be different topic)

From what I can think of I can't see uses of (auto-)repeating space (except improperly aligning word documents) and in my environment (chat, school, web/app development, translation) it's considered bad practice or thing you want to unify (2+ whitespace into one) if a text is misformatted/grabbed

The solution/idea above would preserve both functionaloties but made typing less "cautious" by allowing you to rest your thumb on (large) space (and provides stability by holding phone (e.g. in transit)), as an option (that disables key repeat on hold)

**Comment by Julow** [comment]
I think the bad experience you had with the spacebar slider is due to the bug fixed by this PR: https://github.com/Julow/Unexpected-Keyboard/pull/593
Could you try it ?

**Comment by Validbit** [comment]
This (at least in the build in issue) made sliding experience better but the problem I'm trying point out here is that there's a natural tendency (mostly because the phones are much bigger than they used to be) to rest/hold the finger on display to ensure stability (physical) of phone and makes it more natural/frictionless to think about what's being written.

It's notable especially winter when generally (e.g.) holding phone outside keyboard may click instead, causing unwanted navigation. There are more practical examples but as said before, If it's not too heavy to implement, it'd be a nice improvement (at least i.e. hold space to type nothing (when not swiping))

**Comment by Julow** [comment]
Thanks for the feedback! This is the kind of option that I don't like adding as it has a big maintenance cost compared to its usefulness. A more general options would be better as it can be used by more people and work as the basis for future features.
For example it has been requested in the past to be able to disable key-repeat, on all keys. Do you sometimes use key-repeat on keys other than space ?

**Comment by Spike-from-NH** [comment]
I might auto-repeat "-" and "x". On the other hand, a couple times I've left my finger on "t" too long before deciding to swipe to my "the " instead—and got a dozen of them. I'd prefer auto-repeat only when the XML opts-in—but it's not a deal-breaker.

**Comment by Validbit** [comment]
I personally don't use key repeat so an option to disable key repeat could be a solution (compromise)

**Comment by Spike-from-NH** [comment]
Yes, I prefer auto-repeating rubout key to shift+slider+rubout. My custom layout has a swipe for capital I; not the other letters. Could long-press be faster than the Shift key? Very possibly.

**Comment by Julow** [comment]
I've added an option to disable key repeat in bdb0806. I do not see a reasonable use of long presses since the addition of gestures in https://github.com/Julow/Unexpected-Keyboard/pull/640 so this is just a checkbox.
