### ISSUE TITLE
How to hide the keyboard?

### ISSUE THREAD

**Issue by horada** [Julow/Unexpected-Keyboard#552]
Hello,
I'm exploring the options of this keyboard and it looks like very nice, adjustable and powerful app, but I'm missing and option to hide the keyboard. Is there such option (key) which I could add to custom layout, which will hide the keyboard? Or is there any other way to hide the keyboard?

Sometime the keyboard cover some part of application and the easiest way to handle this situation is to hide the keyboard (and it should show up again, when I click into some editable text field).

**Comment by Spike-from-NH** [comment]
When any soft keyboard is open, it goes to the top of the stack of dismissable elements, and pressing the BACK button generally makes it disappear. To make it come back, tap on a field that requires keyboard input.

**Comment by horada** [comment]
Thanks for the answer and explanation, my impression was, that the Back button sometimes closes also the original window (e.g. some pop-up where I was editing the text), but when I tried it now, it seems to be working as you described.
