### ISSUE TITLE
NumPad / PinPad sorting inconsistent

### ISSUE THREAD

**Issue by alotbsol555** [Julow/Unexpected-Keyboard#554]
the pin pad starts with 7 8 9 instead of 1 2 3:
![Screenshot_20240212-101329_1](https://github.com/Julow/Unexpected-Keyboard/assets/159767443/da8f1b8b-d050-4e14-8619-9bb8e8dc9f44)

the T9 indication is wrong in this case. the pin pad should shart with 1 2 3.

the numeric keyboard is set to start with 1 2 3. i'm using version 1.26 with german localiztion (de) and a custom layout.

the file res/xml/pin.xml looks correct. where does it go wrong?

**Comment by Spike-from-NH** [comment]
The 789 style is like traditional calculators. The 123 style is like telephones. Fortunately, you can have it either way with the "NumPad layout" setting.

However, the letters are wrong, "ABC" should join "2", and so on, in either setting.  (This association with 2 through 9 was created as a memory aid for U.S. telephone exchanges.  482-xxxx could be remembered as "HUnter-2".  0 and 1 were not used in exchanges.)

**Comment by Spike-from-NH** [comment]
I agree; both NumPad and pinpad should go the same way. The NumPad setting should affect both. Which is "right" depends on whether the user is more comfortable with calculators or phones. I can't imagine why a user would want the two layouts to be opposite.

**Comment by Julow** [comment]
Thanks for the report! The pin layout shouldn't be changed by the option. This is fixed in 17b8f1f
