### ISSUE TITLE
[Feature Request] Customisable Slider Trigger Distance

### ISSUE THREAD

**Issue by Lixquid** [Julow/Unexpected-Keyboard#566]
At the moment, the distance you need to move to trigger the slider is fixed at 25% of the distance you swipe to trigger a swipe key.

I have the swipe distance set very short, but that makes the slider very sensitive and hard to control. I would like to be able to set the slider trigger distance to a separate value, so I can have a short swipe distance and a more precise slider.

Thanks for the great app!

**Comment by Julow** [comment]
Thanks for the issue. I believe this is related to https://github.com/Julow/Unexpected-Keyboard/issues/548 where the long swipe distance makes the slider harder to use.

Before adding yet an other option, I planned to experiment with a slider speed that do not depend on an option but changes depending on the speed of the motion, making short slides more precise and large slides move further.

**Comment by Lixquid** [comment]
Interesting you mention that; after comments about this, I was going to bring up the idea of introducing an extra exponential factor which would increase the movement distance on fast slides but still allow for quite slow slide dragging. If that was implemented, it may be possible to avoid having to implement a sliding configuration option. I can respect wanting to avoid overloading the configuration page with having a control for every little part of the application.

However, I think sliding is deep in that category of features that is kind of different from person to person and really hurts ergonomics when it's "not quite right", like swipe distance or repeat speed. Since everyone's thumbs and phone screens are different sizes, the amount of movement that's comfortable will be quite different from user to user, so I think it'll be difficult to find a "one size fits all" scaling factor.

**Comment by Julow** [comment]
You are right, the new option is justified and fixes two issues while the experimentation I suggest might take some time.
Would you be willing to implement it?

**Comment by Spike-from-NH** [comment]
I like the exponential idea—I often run out of screen before I can select the 2-3 lines of text I want to cut. Small slides want precision; large slides want range, and can be perfected by a small follow-on slide.

I like detailed user preferences too, provided you avoid clutter by using submenus or otherwise hiding detailed options from users who don't care.

**Comment by Lixquid** [comment]
> You are right, the new option is justified and fixes two issues while the experimentation I suggest might take some time. Would you be willing to implement it?

I'll certainly make an attempt; Android development is not my strong suit and a very quick demo I made last night seemed to not really work, so I'll need a bit more time to try and debug it.

**Comment by Julow** [comment]
I've made an experiment in this PR: https://github.com/Julow/Unexpected-Keyboard/pull/593
Could you try it ?

**Comment by Julow** [comment]
https://github.com/Julow/Unexpected-Keyboard/pull/593 is merged. Feedback still welcome.
