### ISSUE TITLE
[Feature Request] Hide app from Android launcher

### ISSUE THREAD

**Issue by AndhikaWB** [Julow/Unexpected-Keyboard#567]
It would be nice to be able to hide the app icon from Android launcher, since the settings can be directly accessed via the keyboard itself.

Most keyboard apps have this option and usually can be toggled after the first run.

**Comment by AndhikaWB** [comment]
Whoops, turns out there's already similar request. Closing it.

**Comment by Spike-from-NH** [comment]
Not only that, @AndhikaWB, but most Android versions make it easy to remove an icon from the home screen, and in some versions, you can even "hide" an app from the list of all apps.

**Comment by Julow** [comment]
For reference, here's the issue: https://github.com/Julow/Unexpected-Keyboard/issues/350

It's indeed possible to hide icons on many launcher apps, making this not urgent at all. Though, if someone comes up with an implementation, I'd gladly accept it!

**Comment by AndhikaWB** [comment]
> Not only that, @AndhikaWB, but most Android versions make it easy to remove an icon from the home screen, and in some versions, you can even "hide" an app from the list of all apps.

Yes but I'm kinda perfectionist, sometimes it annoys me that there's a cleaner way to do it, but we haven't been able to do it yet.

But now that I see it often enough, I think I no longer care about it :sweat_smile:.
