### ISSUE TITLE
Custom Slovak QWERTY

### ISSUE THREAD

**Issue by sejkm** [Julow/Unexpected-Keyboard#573]
I made this custom SK keyboard with logical placement of keys. Some might enjoy! :) Thanks for a cool app.

```
<?xml version="1.0" encoding="utf-8"?>
<keyboard name="QWERTY (Slovak)" script="latin">
  <row>
    <key shift="0.33" key0="q" key1="1" key4="esc"/>
    <key key0="w" key1="2"/>
    <key key0="e" key1="3" key2="€" key3="é" key4="ě"/>
    <key key0="r" key1="4" key3="ŕ" key4="ř"/>
    <key key0="t" key1="5" key4="ť"/>
    <key key0="y" key1="6" key3="ý"/>
    <key key0="u" key1="7" key2="ü" key3="ú" key4="ů"/>
    <key key0="i" key1="8" key3="í"/>
    <key key0="o" key1="9" key2="ö" key3="ó" key4="ô"/>
    <key key0="p" key1="0" key2="=" key3="\\" key4="/"/>
  </row>
  <row>
    <key shift="0.75" key0="a" key1="tab" key3="á" key4="ä"/>
    <key key0="s" key1="loc §" key2="$" key3="ś" key4="š"/>
    <key key0="d" key4="ď"/>
    <key key0="f" key1="%" />
    <key key0="g" key1="~" key2="^"/>
    <key key0="h" key1="+" key2="-" key3="*" key4="÷"/>
    <key key0="j" key1="{" key2="}" key3="|" />
    <key key0="k" key1="[" key2="]" key3="'" key4="&quot;"/>
    <key key0="l" key1="(" key2=")" key3="ĺ" key4="ľ"/>
  </row>
  <row>
    <key width="1.5" key0="shift" key2="loc capslock"/>
    <key key0="z" key4="ž"/>
    <key key0="x" key1="loc †"/>
    <key key0="c" key4="č"/>
    <key key0="v" key4="\@"/>
    <key key0="b" key1="\#" key2="&amp;" key3=";" key4="_"/>
    <key key0="n" key1="«" key2="»" key4="ň"/>
    <key key0="m" key1="&lt;" key2="&gt;"/>
    <key key0="." key1="!" key2="\?" key3 ="," key4=":"/>
    <key key0="backspace" key3="delete"/>
  </row>    
</keyboard>
```

**Comment by sejkm** [comment]
Or like this

`<?xml version="1.0" encoding="utf-8"?>
<keyboard name="QWERTY (Slovak)" script="latin">
  <row>
    <key shift="0.33" key0="q" key1="1" key4="esc"/>
    <key key0="w" key1="2"/>
    <key key0="e" key1="3" key2="€" key3="é" key4="ě"/>
    <key key0="r" key1="4" key3="ŕ" key4="ř"/>
    <key key0="t" key1="5" key4="ť"/>
    <key key0="y" key1="6" key3="ý"/>
    <key key0="u" key1="7" key2="ü" key3="ú" key4="ů"/>
    <key key0="i" key1="8" key3="í"/>
    <key key0="o" key1="9" key2="ö" key3="ó" key4="ô"/>
    <key key0="p" key1="0" key2="=" key3="\\" key4="/"/>
  </row>
  <row>
    <key shift="0.75" key0="a" key1="tab" key2="&amp;" key3="á" key4="ä"/>
    <key key0="s" key1="loc §" key2="$" key3="ś" key4="š"/>
    <key key0="d" key4="ď"/>
    <key key0="f" key1="%" />
    <key key0="g" key1="~" key2="^"/>
    <key key0="h" key1="+" key2="-" key3="*" key4="÷"/>
    <key key0="j" key1="{" key2="}" key3="|" />
    <key key0="k" key1="[" key2="]" key3="'" key4="&quot;"/>
    <key key0="l" key1="(" key2=")" key3="ĺ" key4="ľ"/>
  </row>
  <row>
    <key width="1.5" key0="shift" key2="loc capslock"/>
    <key key0="z" key4="ž"/>
    <key key0="x" key1="loc †" key2="\#"/>
    <key key0="c" key4="č"/>
    <key key0="v" key4="\@"/>
    <key key0="b" />
    <key key0="n" key4="ň"/>
    <key key0="m" key1="&lt;" key2="&gt;" key3="_" key4=";" />
    <key key0="." key1="!" key2="\?" key3 ="," key4=":"/>
    <key key0="backspace" key3="delete"/>
  </row>    
</keyboard>`

**Comment by Julow** [comment]
Hi, could you open a PR?

I have a few remarks:
- The `shift="0.33"` looks weird when switching between different layouts.
- The symbols on the top and bottom right of the `p` key are hard to hit due to the edge of the screen.
- The backspace key is smaller than shift. The third row doesn't look centered. Is backspace easy to hit ?
- All ASCII special characters are present except `` ` ``.

To remove the 0.33 shift and make backspace bigger, I suggest to move the `.` key to the end of the second row.

**Comment by sejkm** [comment]
I'm sorry, I don't even know how it works here, I signed up yesterday just to be able to contact you.

Thank you for the suggestions, I actually made this from a layout which had slightly bigger keys and in a grid. Closer to what you suggest. I moved the backspace lower to shift the keys to something closer to what I was used to. Otherwise I tend to hit the neighboring key. And... I don't switch layouts. This is a one for all for me. :)

**Comment by Julow** [comment]
No problem, I can add the layout to the app for you.

Do you think the layout is ready for inclusion ? Can you share it ?

> I don't switch layouts. This is a one for all for me.

Well, it's intended to be used by other people that might switch layouts.

**Comment by sejkm** [comment]
Yes, prefer the 2nd version. It is a bit cleaned up version and will be enough for someone who wants to write Slovak, Czech and English in the same layout. (What is likely a situation of many people here.)

**Comment by Julow** [comment]
The second layout also contains the flaws I mentioned above (the weirdest being the small delete key). Is it really ready for inclusion ?

**Comment by sejkm** [comment]
It is up to you. I use it happily ever since.

**Comment by Julow** [comment]
I can anticipate people complaining. What do you think of this version ?

![shot](https://github.com/Julow/Unexpected-Keyboard/assets/2310568/618a01b7-a5b3-4350-80cf-8f463adf7616)

Changed:
- `.` is moved to the second row, making the layout a grid. This is the bad part.
- Shift and delete are of the same size.
- No margin on the first row. Which was unequal on both side.
- Symbols on the edge of the screen are moved (notably `` <>_;/\ ``).

Don't mind some extra symbols added by my own configuration.

**Comment by sejkm** [comment]
Looks ok

**Comment by Julow** [comment]
I added it to the app in 0e0c761. You can find a debug APK here: https://github.com/Julow/Unexpected-Keyboard/actions/runs/8125011772
I'd appreciate your feedback on whether my modifications work for you or not.

**Comment by Julow** [comment]
This has been released. Could you have a look at it?

**Comment by sejkm** [comment]
Well, for me personally the grid just doesn't work.

**Comment by Julow** [comment]
Sorry about that! What do you think of this version with the `.` key removed ?

![shot](https://github.com/Julow/Unexpected-Keyboard/assets/2310568/12a406e4-7875-41e3-a9a7-b83c07962fa4)

**Comment by sejkm** [comment]
Ok, this makes sense, I might even use it myself. However, I would rearrange the most used interpunction to be in the corner to somehow mirror a computer keyboard. So I would put !?,. on letter M. The rest (;:<>_) are not used that often so it doesn't matter where exactly they will land. But since they are two related couplets and we have ň with n, I would put <>;: on letter B. What remains is _ which I would put on 3rd position on N or 4th on J.

**Comment by Julow** [comment]
With your modifications:
![shot](https://github.com/Julow/Unexpected-Keyboard/assets/2310568/e81a3a70-cec7-4e5f-835d-1e73003402b8)

**Comment by sejkm** [comment]
Perfect!

**Comment by Julow** [comment]
It's in the app: fe0f824
