### ISSUE TITLE
important bug

### ISSUE THREAD

**Issue by eliasoft** [Julow/Unexpected-Keyboard#575]
Hello dev. I just started using this app and I love it. But I would like you to fix the following behavior.
The keyboard layout for numeric fields should respect the established setting (shown in the first image).

In the second image you can see that when entering the numeric keyboard from the alphabetic keyboard, the desired setting is respected. But it is in the third image (field to enter only numbers), where the desired setting is not respected.

A temporary solution was to disable the "PIN entry layout" option, but I would prefer the keyboard layout that is displayed when that setting is enabled.

![Screenshot_2024-02-26-16-44-02-784_juloo keyboard2](https://github.com/Julow/Unexpected-Keyboard/assets/40068066/7c6e4a3e-b163-4bf3-beb4-de5840e6b743)
![Screenshot_2024-02-26-16-44-16-064_com rhmsoft edit pro](https://github.com/Julow/Unexpected-Keyboard/assets/40068066/97e11b83-0227-4dc3-b28a-6db99f5ca024)
![Screenshot_2024-02-26-16-44-28-676_net dinglisch android taskerm](https://github.com/Julow/Unexpected-Keyboard/assets/40068066/0c313b6c-a79c-4a98-b1eb-3d652a6a13b6)

**Comment by Julow** [comment]
Thanks for the report, yes this is already fixed and will be released in a few days. Thanks @alotbsol555 for looking at the issues.
