### ISSUE TITLE
[Feature Request] Add a button to open Settings from inside the app.

### ISSUE THREAD

**Issue by leukoshta** [Julow/Unexpected-Keyboard#581]
While writing a custom layout for myself, matching the layout I use normally, while rearranging symbol positions after some trial and error, I absent-mindedly replaced both the Settings key, as well as the Switch Layout key and forgot to add them back.

Without realising the mistake I went to test the new configuration, saving the layout over the previous version, and closed out of the Settings. I went to adjust the layout again only to find that I was unable to open the Settings from my custom layout, and to make matters worse I could no longer switch to the default QWERTY layout to open the Settings from there either. Opening the app from the launcher also had no way to help, as the only elements are the Enable/Select Keyboard, the Input Field, and a link to this repository.

While I doubt anyone else is going to run into the same issue, it would be a simple safeguard to add a button that opens the Settings within the app itself and would protect against a lot more than just my intelligence, e.g. corruption, future conflicts, data loss, wizards, damaged screens, permission shenanigans, and so on and so forth. I know I can reinstall, but still.

Edit: Apologies, accidentally hit the close button as soon as it had posted.

**Comment by Spike-from-NH** [comment]
As this is a rare case of "locking yourself out of the house," it should suffice to have a "Settings menu" button on the initial screen, alongside "Enable keyboard" and "Select keyboard". I wouldn't force it onto the keyboard itself if the layout-writer has deleted it.

**Comment by leukoshta** [comment]
> the mentioned commit should be in 1.27. did you lock yourself out using the latest version?

Of course that's the issue, the FDroid/etcpositories are still in 1.26 and that is where I happened to find and install from, the most embarassing solution ;o)

> btw: you should always be able to reach the settings via the android settings, where you can tap the name of the keyboard to open each keyboard's settings. this might depend on your android version.

Ironically enough it actually seems to depend on the individual keyboards themselves, I was fairly certain that wouldn't do anything but out of the 9 keyboards currently installed only half do so, Unexpected is one of them, which is to be expected. Counting just the uninstalled Play Store keyboards brings it to 24 total, with more from elsewhere (I'm picky), I can't recall that being common or intuitive enough to ever have happened honestly.

Thanks for the help and the handy new tip for my buckets of keyboards.
<sup>~Also for the restraint it must have taken to respond sincerely in the face of my great achievment x)</sup>~
