### ISSUE TITLE
Translation updates process discussion

### ISSUE THREAD

**Issue by Julow** [Julow/Unexpected-Keyboard#584]
@Spike-from-NH This issue is for continuing the discussion in https://github.com/Julow/Unexpected-Keyboard/issues/373.

Sending a message in https://github.com/Julow/Unexpected-Keyboard/issues/373 sends notifications to potentially many people, please don't do that.

> I can't figure it out. I got to "Open a new pull request" and tapped it;
that planted me in the Compare dialog with no way to go further.

The "Open a new pull request" button expects you to have committed your change to a branch in your fork.
Have you tried to use the "Edit in place" feature ?

> Again, if I'm supposed to clone a complete copy of the project to change 9 lines in one file, that's absurd.

That's how Git works. Unfortunately, there's no way around it.
A complete copy of the code is a few Mb, which is nothing at all compare to other usages of the Internet.

When using the "Edit in place" button, you don't need a copy on your computer and you can trust Github to store the copy in an efficient manner.

**Comment by Spike-from-NH** [comment]
Thanks for the explanation. So I need to fork the whole project just to correct one file of prompts???

Edit in place continues to report, "Something went wrong"

**Comment by Julow** [comment]
> Thanks for the explanation. So I need to fork the whole project just to correct one file of prompts???

Yes, that's how Git works. It has many advantages instead. Also the repository is not that large, about 8Mb, that's 4 times the median web page size.

Thanks for the PR, it's merged!

**Comment by Spike-from-NH** [comment]
I see I also created remedial work for you! The Github editor resisted selecting entire lines, and several times after I pasted in the changes I specified in 373, I saw that line endings and indentations were disturbed. Looks like I missed one case, sorry.

**Comment by Spike-from-NH** [comment]
Can I delete the fork, as we are done with it? Can I rename it? as any future use will be about something else.

**Comment by Julow** [comment]
You can remove the fork or keep it for future contributions. You can also make different branches on it. The translation change would have been best in a different branch.
If you only use the "Edit in place" button be sure to use this button on the main repository.
