### ISSUE TITLE
Unable to add multiple cursors in editor

### ISSUE THREAD

**Issue by michaelsboost** [Julow/Unexpected-Keyboard#590]
The Ctrl key is nice (ctrl+c, ctrl+v, ctrl+z all worked fine, but ctrl+shift+z failed), but my attempt to use the ctrl key to add multiple cursors in my IDE failed. I tried another that required the Alt key and it also failed. In addition, another issue I have is when the shift key is enabled/active. When I tap on another area in the IDE or even a Notepad, it doesn't create a selection from the cursors' starting position. Lastly, have arrow keys instead of space bar or the other slide option.

**Comment by michaelsboost** [comment]
After reading the documentation of the editor it makes sense why taps don't work to add another cursor because it requires a mouse event which won't work for phones - https://codemirror.net/docs/ref/#view.EditorView%5EclickAddsSelectionRange

**Comment by Julow** [comment]
Thanks for the issue. It's possible that a tap is turned into a mouse event. Can you log the keyboard and mouse events and see ? We'd see whether the editor receives the ctrl event or not.

**Comment by starchyunderscore** [comment]
try ctrl+y instead of ctrl+shift+z

it seems most more modern applications use that keybinding for redo instead

**Comment by Julow** [comment]
I'll close this issue as there's nothing the keyboard can do.
