### ISSUE TITLE
Custom numeric keyboard layout

### ISSUE THREAD

**Issue by horada** [Julow/Unexpected-Keyboard#601]
Hello,

is it possible to create also custom numeric keyboard layout? (the one showed when clicking to the _123+_ button)

**Comment by Julow** [comment]
Hi, this is not possible at the moment. Related issue: https://github.com/Julow/Unexpected-Keyboard/issues/459

**Comment by horada** [comment]
Thanks for the link, I somehow missed the original issue.

Closing this one as duplicate of the #459.
