### ISSUE TITLE
Feature Request: Add space to numpad

### ISSUE THREAD

**Issue by innerspacepilot** [Julow/Unexpected-Keyboard#609]
Hello, thanks for nice keyboard.
It would be nice to have "space" on numpad e.g. swiping down "0". Needed for entering numbers with spaces like "telnet 192.168.198.198 80"

Thanks.

**Comment by Julow** [comment]
The numpad contains space: it is the key between `.` and enter.

Do you mean the "pin entry" layout that shows up 4 columns ? I agree it would be nice to have a space key here.

**Comment by innerspacepilot** [comment]
Oh, I've missed it. Was looking for it many times :)
 maybe it should have "|__|" symbol?

**Comment by Julow** [comment]
I noticed that too and fixed it in 78f85e5. Thanks for reporting issues!
