### ISSUE TITLE
any language

### ISSUE THREAD

**Issue by lu5her-s** [Julow/Unexpected-Keyboard#610]
How to add any language to keybord (Thai or other)

**Comment by Spike-from-NH** [comment]
① Go into Settings (swipe gear logo on Fn key)
② Tap "Add an alternate layout"
③ Pick from one of the layouts that have been written
④ If your preferred language isn't in the list, you can write your own custom layout in XML and install it into Unexpected by copypaste.

**Comment by Julow** [comment]
I think this issue is resolved, so I'll close.
Thai lacks a layout but this could be improved with your help.
