### ISSUE TITLE
Length of keycap legend

### ISSUE THREAD

**Issue by Spike-from-NH** [Julow/Unexpected-Keyboard#613]
I experimented with labeling my custom layout at the bottom of the space bar with `key8="Spike Apr'24"`. Only `Spi` appeared on the keycap. (Performing the swipe produced the whole string, but I'll never do that in real operation.) A three-character limit would be right for a normal key, but there's plenty of room on the space bar.

Very low priority, but you should either evaluate the width of the key in question, or remove the limit entirely even if it risks the user making a mess, or define XML to let the user specify the legend.

**Comment by Julow** [comment]
If you want a purely decorative text, you can use the `indication` attribute like in the pin entry layout: https://github.com/Julow/Unexpected-Keyboard/blob/master/res/xml/pin.xml#L5

**Comment by Spike-from-NH** [comment]
Problem solved, thank you!

**Comment by Spike-from-NH** [comment]
@Julow, here's a nitpick. In Portrait, the descenders ("p", "y") are in the textured bottom of the space bar. (I use the Dark theme.) In Landscape, descenders are clipped unless I set the bottom margin to 3dp.

**Comment by Spike-from-NH** [comment]
In 1.28, the original problem is back even though I'm using `indication`!

**Comment by Julow** [comment]
Thanks for reporting! This was broken when the anti-clockwise circle gesture was added, which internally use the same rendering logic. Fixed in 6ac973c.

**Comment by Spike-from-NH** [comment]
The APK to resolve #653 also includes this fix and it works correctly. If there were a 1.28.1 without waiting for the more ambitious tasks, I'd install it everywhere.
