### ISSUE TITLE
missing key?

### ISSUE THREAD

**Issue by nathgit** [Julow/Unexpected-Keyboard#616]
I keep getting an "expected" error. Originally I noticed when changing the layout a little (I replaced 'w' with 'ꝡ', and 'i' with 'ı'), I realized I'd left out a / at the end & added it, thinking that was the problem, but I still have the error. What's wrong? I added a link to Google drive containing the screenshot & the layout file.

**Comment by nathgit** [comment]
https://drive.google.com/drive/folders/1AdyuZC5ntcKxFOfgyLr4kHLIuzFWsrDB

**Comment by nathgit** [comment]
https://drive.google.com/drive/folders/1AdyuZC5ntcKxFOfgyLr4kHLIuzFWsrDB

**Comment by Julow** [comment]
The error is not located on the right line for some reason. It's actually on line 26:

```
    <key key0="ꝡ" key1="~" key2="2" key3="\@"/ key4="w"/>
```
The `/` after `key3="\@"` should be removed.

**Comment by nathgit** [comment]
Thank you. Kuaq kıe ka.
