### ISSUE TITLE
Windows/Super key

### ISSUE THREAD

**Issue by avently** [Julow/Unexpected-Keyboard#62]
There is no way to press Win key which is often located in left bottom part of keyboard. Without it there is no way to change active workspace in i3-wm (Linux) and to do other things bound to Win key. I would prefer it instead of Fn key

**Comment by 07416** [comment]
I created [a duplicate request](https://github.com/Julow/Unexpected-Keyboard/issues/65) by accident. Can you add "Super" to the title for search-optimization reasons?

---

>Is [the Super key ](https://en.wikipedia.org/wiki/Super_key_(keyboard_button)) part of the current key layout?

**Comment by Julow** [comment]
I just added the meta key (95c8acc).
I've choosen the diamond symbol for now (`◆`), which refers to the [Meta key](https://en.wikipedia.org/wiki/Meta_key). On Linux, the meta key is more related to Alt than Super but on Android it's really called [Meta](https://developer.android.com/reference/android/view/KeyEvent#META_META_ON).
Happy to change the symbol if one of you have a better idea, I'm not a fan of "Win" or "Sup", though. I placed it on the top-right of the Ctrl but I'm not too happy with this, I'll consider disabling the key with an option.

As you might want to use this key in unconventional applications, someone reported a problem with [the Ctrl key and Anydesk](https://github.com/Julow/Unexpected-Keyboard/issues/30#issuecomment-1029272691) that I have yet to investigate. Keeping this issue open until you confirm it works.

**Comment by avently** [comment]
@Julow thank you. Just updated to the new version. Every button I tested (Alt, Shift, Win, Ctrl) and combination of them work perfectly via Anydesk on Linux! So, yeah, you're great. The only thing I found not working is a done button which I expected should work as an Enter key. Button at the top right corner of the done button works as an enter key. So issue can be closed

**Comment by Julow** [comment]
The Done key is very annoying ! This is mostly due to the application not using Android's API correctly (but who does understand them ?) but can be fixed from the keyboard.

**Comment by doak** [comment]
Mh, yesterday I connected through MultiVNC to a _i3_ session and I was unable to send the super/Windows key with _Unexpected Keyboard_. What is the easiest way to test it? If this is really the case, I will create a new issue of course, but want to be sure beforehand.

**Comment by Julow** [comment]
@doak This might already be fixed (issue: https://github.com/Julow/Unexpected-Keyboard/issues/439)
You can download the latest debug build here: https://github.com/Julow/Unexpected-Keyboard/actions/runs/7719102743 (in the Artifacts section)

**Comment by doak** [comment]
@Julow, no, Meta is still not received. Tested with _MultiVNC_ and `xev` on the desktop.

**Comment by doak** [comment]
I am sorry, I double checked. Meta/Super does not work.  `Ctrl_L` is sent instead. Nothing is sent if I assign a dedicated key for Meta.

**Comment by vvirtues** [comment]
how do I press meta by itself without closing the keyboard? the application I'm using does not show the done key so I can't use it by itself. application is moonlight

**Comment by Julow** [comment]
You can enable the Meta key in the option "Add keys to the keyboard". What do you mean by "without closing the keyboard" ?
