### ISSUE TITLE
missing ctrl+ins copy / shift+ins paste

### ISSUE THREAD

**Issue by cantarini** [Julow/Unexpected-Keyboard#623]
in a linux CLI, the ctrl+c keystroke is used to send a SIGINT signal, hence it is useful to use the old ctrl+ins and shift+ins keystrokes to copy/paste text from/to the CLI.
Unfortunately such keystrokes currently don't trigger copy/paste functions
Oh, and there is a shift+del function to trigger the "cut" function too.
It would be very useful if such key combinations will be implemented in the future

**Comment by Julow** [comment]
What terminal application are you using ? It seems to be that the keyboard does sent the right keys for `ctrl+ins`, `shift+ins`, etc.. 
If you use Termux, it does not have keybindings with the insert key: https://wiki.termux.com/wiki/Touch_Keyboard

**Comment by cantarini** [comment]
I use Termux

**Comment by Julow** [comment]
Sorry for the slow reply. Termux doesn't do anything special for these keys by default. It also seems that it doesn't have any copy and paste shortcuts. I suggest to search through Termux issues if someone had the same problem.

**Comment by Binocularbath** [comment]
Hi there

if i can just tag onto this. Im also looking for an insert key for working on linux shell, is it possible with this keyboard?

**Comment by Julow** [comment]
You can add the insert key in the settings (it's named `insert`).
