### ISSUE TITLE
how to make a newline key

### ISSUE THREAD

**Issue by TaokyleYT** [Julow/Unexpected-Keyboard#624]
I tried \n, doesn't work (ofc, this is xml)
I looked through KeyValue and didnt find newline keyword
&#xA or &#10 doesn't work too

how to newline

**Comment by Spike-from-NH** [comment]
@JapanYoshi's emerging documentation (https://github.com/JapanYoshi/DocumentXML/wiki/Custom-layouts) suggests that `key="enter"` may be the keyword you need.

I'm surprised your two guesses didn't work, but try following them with `;`.

**Comment by TaokyleYT** [comment]
not the enter key because some platform just end/submit your prompt instead of newline when you press enter, but pasting newline char did work. I dont wanna waste my paste key for that as there is no clipboard feature and can only copy 1 string at a time.
Will try the semicolon

**Comment by Spike-from-NH** [comment]
@JapanYoshi, please note newline in your section on characters that need to be escaped.  `key="&#10;"`
