### ISSUE TITLE
Russian language

### ISSUE THREAD

**Issue by avently** [Julow/Unexpected-Keyboard#63]
In my life i use two languages often: russian and english. how to switch between them quickly? i don't even see the russian language support at all, but it can be added by different people. we still need the quick switch key between layouts

**Comment by Julow** [comment]
Unfortunately the keyboard doesn't support Russian at the moment. I would gladly accept any contributions for new languages!

There's a button to switch between the languages on the top-right of the Alt key. Since the last version it opens a popup to choose between the keyboards, this keyboard will appear several times, once for each language.

**Comment by avently** [comment]
@Julow am I understand correctly that if I want to use two or more languages I need to enable them in phone's settings inside system language section?
If so, why not to make an ability to select different languages inside app's settings? All keyboards I use work this way, pretty convenient.

**Comment by Julow** [comment]
That's right, you'll need to enable the languages in the system settings. There's a "Layout" option in the keyboard's settings but it overrides the language mechanism entirely and doesn't allow to switch between two languages easily.

Are you expecting something like the "globe" key on Android's default keyboard but that only switch between the languages inside the same keyboard app ? 

Someone just contributed a Russian layout: https://github.com/Julow/Unexpected-Keyboard/pull/66 Feel free to comment.

**Comment by avently** [comment]
@Julow 
>Are you expecting something like the "globe" key on Android's default keyboard but that only switch between the languages inside the same keyboard app ?

Yes, except additional key for that action. I mean it's better to bind swipe from right to left on space button that would cycle the languages.

>Someone just contributed a Russian layout:

That's cool, i'll look. I'm pretty sure that there is no idea layout for all Russian users and i'll need to do the layout myself, it's not a problem.

Did you think about adding your great idea with swipe to another open source keyboard like AnySoftKeyboard? Because in my opinion it is the best keyboard and your feature in it would be cooler than to start your own keyboard from scratch.

**Comment by Julow** [comment]
https://github.com/Julow/Unexpected-Keyboard/pull/66 is merged.

> Did you think about adding your great idea with swipe to another open source keyboard like AnySoftKeyboard?

Never thought about that. There's still things I want to try with this keyboard so I'm not going to start thinking about that soon. Of course, if AnySoftKeyboard works better for you, you can try to add the swipe concept to it.
