### ISSUE TITLE
Fast Switching Between Keyboards Apology-Explanation

### ISSUE THREAD

**Issue by JackDSRS** [Julow/Unexpected-Keyboard#631]
A while back, I explained an alternate way of switching between keyboards. Yes, Unexpected Keyboard has a very easy way to do so on the Fn key.

However, many other keyboards don't, which is frustrating. So I wanted to apologize to Julow for my poor explanation as to why I use that other way to change keyboards. Unexpected Keyboard easily allows you to switch keyboards, but other keyboards don't make it easy to switch back. 

One has a spellcheck, punctuation and other grammar checks when I'm doing writing and messaging, but there's no way to toggle back without slugging all the way through the Android Language and Input Setting. Another has nice, giant buttons, but it's ancient.

So there you have it.

**Comment by Julow** [comment]
When a keyboard is visible on the screen, there should be a silent notification. You can click on it to open the keyboard switcher. If you have the on-screen navigation bar, then the switching key should be there instead.

**Comment by JackDSRS** [comment]
Whoah. Remember, this was an apology, but I must not have thoroughly explained the rationale for the switcher I use.

This is a screenshot of another keyboard. As you can see, no switch. I've also added a screen grab of the settings, which also has no switch settings.

One more reason the alternative keyboard switcher is more helpful just in my case: as I mentioned, crap eyesight.

Most things are okay to see, but regardless of keyboard, switches are usually 3 tiny dots and those 3 tiny dots aren't in the same place, there can be multiple sets, and they're hard to see. They can be tiny, tiny symbolsc

The NextApp keyboard, as an example, has 4 keys with those 3 tiny dots across the bottom row. You hold them down to activate them. One is for keyboard switching.

Samsung has 3 dots at the top right that does whatever it wants, seemingly at random, activated with a tap. The actual keyboard icon only switches modes.

Big Button has nothing.

And of course UK at the bottom left, swiping ↗  on the Fn key. On my phone, the symbol looks like a blob.

Even though switching keyboards on the nav bar is set in the global settings, and each keyboard setting, I've never seen it.

The switching method I use just pops it up in large radio button choices in my systems default language. It can't be any simpler for an idiot like me. Hold the Home button, tap, tap. Regardless of the funky keyboard.

This is no reflection or bad thing about UK in anyway. Still the best for my tablet. Augmented with Grammarly for now for spell and grammar check.

May 5, 2024 3:09:37 PM Jules Aguillon ***@***.***>:


*DuckDuckGo* removed one tracker. _More[https://duckduckgo.com/-Uf7AHxbbMhzKBHEGyupd65fqkNQttoMeDRVnIwrNTMZFYbYV1kIooI5g6TmDAcNOACh4CPtDiBBgugI9SLAGCCLHZ3CrQUJ7PXfR_4Pk0-1T9Nk5_dHNg-pr1iDie0Zq-h0Y2MphamszB9-yWzBE1QPes8YwzwnJVQy9eDND2gxGm0meYpQKsI5wkGSnfHGzy1Jnzdmd41XhfBqBsGPBpiTTIAzzL3MYSQEWYoOM8IxTKM56HUcR_gRxXphkkoecijFwqadExmbTL_yfJo9DpQFGZm0FLWptJQVfECRFt1iikh_wUWlBnWH1HkFDbfHjaz8GT2vmPDM3Ddy2a3wLoPzIftTMY_BpYlbH3X5lb_HZ3A8dqOYokNTIvMg6gf-BpdGgRqeZeXa41Be0tuy-guCwTs74JFTP_-FSRpXKrvMN_jwg7V0OKrEldhDmGTOugA]_
Report Spam[https://duckduckgo.com/-Uf7AHxbbMhzKBHEGyupd65fqkNQttoMeDRVnIwrNTMZFYbYV1kIooI5g6TmDAcNOACh4CPtDiBBgugI9SLAGCCLHZ3CrQUJ7PXfR_4Pk0-1T9Nk5_dHNg-pr1iDie0Zq-h0Y2MphamszB9-yWzBE1QPes8YwzwnJVQy9eDND2gxGm0meYpQKsI5wkGSnfHGzy1Jnzdmd41XhfBqBsGPBpiTTIAzzL3MYSQEWYoOM8IxTKM56HUcR_gRxXphkkoecijFwqadExmbTL_yfJo9DpQFGZm0FLWptJQVfECRFt1iikh_wUWlBnWH1HkFDbfHjaz8GT2vmPDM3Ddy2a3wLoPzIftTMY_BpYlbH3X5lb_HZ3A8dqOYokNTIvMg6gf-BpdGgRqeZeXa41Be0tuy-guCwTs74JFTP_-FSRpXKrvMN_jwg7V0OKrEldhDmGTOugA]



When a keyboard is visible on the screen, there should be a silent notification. You can click on it to open the keyboard switcher. If you have the on-screen navigation bar, then the switching key should be there instead.

**Comment by Julow** [comment]
Happy that it works for you. With a custom layout you could place that key in an other place. 
Note that your email client inserts unwanted text in the messages you quote, you can view this on Github.

**Comment by JackDSRS** [comment]
Oops, sorry for the additional text.

Well, that's what Home Screen Assistant is for in the Android Settings. Just pick a super lightweight launcher and add the minimum you need.

**Comment by Julow** [comment]
I'll close this as I don't think the keyboard can be improved here. Thanks!
