### ISSUE TITLE
Termux Paste? Termux anything?

### ISSUE THREAD

**Issue by JackDSRS** [Julow/Unexpected-Keyboard#632]
I figured out how to add Meta to my keyboard. Is there an a way to add a way to add paste to it?

I know it says this was originally built for Termux, but I can't figure out how or what works. I'm tying it to Shizuku.

**Comment by Julow** [comment]
In the "Add keys to keyboard" option, you should find the paste key, close to the end with the other editing keys. Ctrl+V should also work in many apps.

**Comment by JackDSRS** [comment]
Ctrl+V works great in everything except terminal apps. I've tried the Paste with Plain Text so far. I'll try the Paste and Meta keys next.

I haven't seen anything that works in any references, but Android's hold down and Copy/Paste does.

If I find something that does work on the keyboard, I'll post it.

Meta works as its supposed to in ranger and text editing within the terminal apps though, so I'm really glad its available.

May 5, 2024 3:06:59 PM Jules Aguillon ***@***.***>:


*DuckDuckGo* removed one tracker. _More[https://duckduckgo.com/-AJEwuSAXg-2CYJ4T38sFBxRlfSw5QfMh33AT9R8WaShJJHnrgIaOrRmYXJ_CfLo9HrICgMxNBS1qbSUFWpBCT2_JRyxv4LXIjIcP9E8VPefHuETCKR3ntnfbC6pXvuxZ5rjmI7bJhgy7Pe98M2h-jG_472cFy2o1hig2mUaZD2A1-jU4Omdj_JObsn-nmdcVnLsm4IvdwUC5v-_hUkqV2G70R-yIUVqqTFVyWuQh9iImPQAQ]_
Report Spam[https://duckduckgo.com/-AJEwuSAXg-2CYJ4T38sFBxRlfSw5QfMh33AT9R8WaShJJHnrgIaOrRmYXJ_CfLo9HrICgMxNBS1qbSUFWpBCT2_JRyxv4LXIjIcP9E8VPefHuETCKR3ntnfbC6pXvuxZ5rjmI7bJhgy7Pe98M2h-jG_472cFy2o1hig2mUaZD2A1-jU4Omdj_JObsn-nmdcVnLsm4IvdwUC5v-_hUkqV2G70R-yIUVqqTFVyWuQh9iImPQAQ]



In the "Add keys to keyboard" option, you should find the paste key, close to the end with the other editing keys. Ctrl+V should also work in many apps.

**Comment by Julow** [comment]
I'm not aware of copy and paste shortcuts in Termux. If the dedicated copy and paste keys don't work, then the keyboard cannot do anything else at the moment. If clipboard is ever implemented, it should be able to paste into Termux (https://github.com/Julow/Unexpected-Keyboard/issues/195)

Similar recent issue: https://github.com/Julow/Unexpected-Keyboard/issues/623

**Comment by JackDSRS** [comment]
Did some deep digging. No keyboard of any kind supports copy-paste in
terminal apps. It was just never implemented on Android, iOS, Window, etc.
Great-grandaddy UNIX never had anything like it, and thats what I started
with back in the Jurassic period.

Worth a shot. Thanks!

**Comment by ChiefMikeK** [comment]
:neckbeard: Since other processes were assigned to Ctrl+C and Ctrl+V in UNIX|POSIX → Linux
Copy paste in a terminal = Ctrl+Shift+C  Ctrl+Shift+V.
- https://www.howtogeek.com/440558/how-to-copy-and-paste-text-at-linuxs-bash-shell/

**Comment by JackDSRS** [comment]
> :neckbeard: Since other processes were assigned to Ctrl+C and Ctrl+V in UNIX|POSIX → Linux Copy paste in a terminal = Ctrl+Shift+C Ctrl+Shift+V.
> 
> * https://www.howtogeek.com/440558/how-to-copy-and-paste-text-at-linuxs-bash-shell/

Thanks! 

And if you can't trust the Navy, who can you...

Wait, I was pinned down in an airport airport for 3 days because SEALS's were blown off course in one of the silliest ops, Urgent Fury, if their being met infil by hordes of reporters at the beach wasn't enou...

Er... Ah, well, that was 40 years ago. Good times. Reminded me of south side Detroit mixed with leeches.

Yes, someone stupid enough to be a 75th 11 bang bang...well...you know, and other stuff. Then another two years lurping further in and south, in places that are now spring break Girls Gone Wild hot spots. God bless Ronnie and Ollie.

Wait. Keyboards. Got distracted there. Many serious thanks!

Jack

**Comment by Julow** [comment]
I'll close this issue as terminal apps do not generally handle `Ctrl+C` and `Ctrl+V` as copy and paste and that's not something the keyboard can change.
Termux in particular doesn't have any copy and paste shortcuts (not even Ctrl+Shift+C). The special `copy` key can't work either.

**Comment by Julow** [comment]
The future clipboard feature will be able to paste into Termux: https://github.com/Julow/Unexpected-Keyboard/pull/681
