### ISSUE TITLE
Feature request: Swipe for CapsLock

### ISSUE THREAD

**Issue by MaxGyver83** [Julow/Unexpected-Keyboard#64]
Currently, you press the shift key once for activation and then twice for deactivation because this key has three states: Off, Shift, CapsLock.

Pressing this key twice for deactivation is not comfortable.

What do you think about this solution?

The shift key toggles only between on and off. And for CapsLock you could swipe to a corner of the shift key.

**Comment by sdrapha** [comment]
Just curious, why the need to press the shift key, and then deactivate it without being used? what is the use case? 

If you press shift once, and then actually use it by pressing any other char key, the shift deactivates itself automatically.
So I just can't see the real issue happening here in.

**Comment by MaxGyver83** [comment]
Oh, yes, after thinking again about it, I see that you are absolutely right! Pressing the shift key and undoing it should happen very seldom. I guess I did it more often than usual while playing around.

**Comment by Julow** [comment]
I had this experience too but I'm not sure why I would unintentionally press shift so often. I'm open to suggestions on this but adding an other key for capslock doesn't attract me. Please re-open if you have more thought.

This issue is what's keeping me from enabling shift automatically at the beginning of sentences so thanks for spelling it out loud.
(btw, my plan for auto-capitalization is to implement it through suggestion/completion when we have that, not soon)

**Comment by jenslody** [comment]
A possible solution would be to enable capslock with a double-tap, so that either shift or capslock can be released by one tap on the shiftkey.
That would probably also make it possible to enable shift automatically at the beginning of sentences.

**Comment by Julow** [comment]
@jenslody In the next release, modifiers will be locked by holding them for a time. (53b9afa) Double-tap would also be a good solution but I prefer holding on other modifiers than shift. 

You can find a debug build here, if you are interested to try before the release: https://github.com/Julow/Unexpected-Keyboard/actions/runs/2728751475

**Comment by jenslody** [comment]
Both works fine, just one (very) minor issue:
in settings it says: 

> **Double tap on shift for caps lock**
> Instead of holding modifiers for a time

But both works, if it is checked, so the _Instead_ is wrong here.
And instead of _modifiers_ it should be singular (or just _it_), because it only works for caps lock (as stated in the option).

**Comment by Julow** [comment]
I added a caps lock key in 36e10a7. 

@jenslody Sorry, I missed your comment. What I meant with this message is to inform people that modifiers can be held for locking, so I used plural. I improved the message in 6aa4740
