### ISSUE TITLE
Feature request: Monet theme support

### ISSUE THREAD

**Issue by TadaCZE** [Julow/Unexpected-Keyboard#642]
On Android 12 and above an app is more cohesive with the system when it uses the system theme colors (Monet).

By giving us the option to theme it as such you could make the app look more modern.

**Comment by TadaCZE** [comment]
Pull request: https://github.com/Julow/Unexpected-Keyboard/pull/647

**Comment by Julow** [comment]
https://github.com/Julow/Unexpected-Keyboard/pull/647 is merged, thanks!
Before I close this, what do you think of the modification I've made ?

**Comment by Julow** [comment]
This is released.
