### ISSUE TITLE
"Unexpectedly Quit" with Single Row Custom Keyboard Layout

### ISSUE THREAD

**Issue by bitboxx** [Julow/Unexpected-Keyboard#645]
When configuring a custom keyboard layout for the Unihertz Titan Slim phone with a physical keyboard, setting the keyboard to have only one row and bottom_row set to false causes the keyboard to "unexpectedly quit" when used.

Steps to Reproduce:

1. Create a custom keyboard layout XML file with the following configuration:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<keyboard bottom_row="false" name="Titan" script="latin">
  <row>
    <key key5="left" key6="right" key7="up" key8="down"/>
    <key key0="fn"/>
  </row>
</keyboard>

```

2. Attempt to use this custom keyboard by tapping on a text field.

Device: Unihertz Titan Slim
Operating System: Android 11
Unexpected Keyboard Version: 1.27.0

**Comment by Julow** [comment]
Thanks a lot for reporting! This should be fixed in 9d89297.

Note that Fn, Compose, and most features of the keyboard won't affect what you type on a physical keyboard. Only Ctrl, Shift, Alt might have an effect in some apps.
Any work toward this would be more than welcome!
