### ISSUE TITLE
Polish QWERTY

### ISSUE THREAD

**Issue by ZX-Commodore-ST** [Julow/Unexpected-Keyboard#649]
All Polish letters are assigned to bottom+right gesture but one single letter "ó" is assigned to top+left "o" key which makes it hard to use. From my point of view it would make sense to either:

- move "(" and ")" from "o" to "p" to make space for bottom+right gesture under "o" key
- keep "(" and ")" under "o" but change their default gesture for "(" and ")" from bottom to top

Is there an easy way to change it?

**Comment by Julow** [comment]
The polish qwerty is defined here: https://github.com/Julow/Unexpected-Keyboard/blob/master/srcs/layouts/latn_qwerty_pl.xml
Feel free to propose modifications by making a PR.

**Comment by ZX-Commodore-ST** [comment]
I don't use git tools so I have no knowledge how to do it. Anyway, this is a changed file I added as a custom layout. 
[latn_qwerty_pl.xml.txt](https://github.com/user-attachments/files/15521953/latn_qwerty_pl.xml.txt)

**Comment by Julow** [comment]
Thanks! I applied your change in c5e9e3f, except for the placeholders that I removed for convenience as they were clashing (I plan improvements for these soon). Here's how it looks:
![shot](https://github.com/Julow/Unexpected-Keyboard/assets/2310568/6fa43bab-f07f-4ac4-ae64-b014fac734f9)

**Comment by Julow** [comment]
I don't think the placement for the parentheses is ergonomic but I didn't want to suggest placing the opening parenthesis on the same key as `o`, as that was the previous position of `ó` and could cause many mistypes.

**Comment by ZX-Commodore-ST** [comment]
That's why I wanted to be able to change it just for myself as I didn't use Unexpected Keyboard long enough to understand it's work flow. Also I don't really use terminal from Android devices. Still with just few days of use I can say it's the best keyboard available.  Word prediction is a leftover from keypad phones era.
