### ISSUE TITLE
/doc/*.md typos

### ISSUE THREAD

**Issue by ChiefMikeK** [Julow/Unexpected-Keyboard#650]
https://github.com/Julow/Unexpected-Keyboard/blob/cf1aaa3bdfcb25388dd0ced888d2ad024fe4a029/doc/Possible-key-values.md?plain=1#L38  
do > `does` not perform editing in response to these keys.

https://github.com/Julow/Unexpected-Keyboard/blob/cf1aaa3bdfcb25388dd0ced888d2ad024fe4a029/doc/Possible-key-values.md?plain=1#L86  
`ᵢ` not displaying/showing any difference here?

**Comment by Spike-from-NH** [comment]
I'll fix these.

**Comment by Julow** [comment]
Fixed in https://github.com/Julow/Unexpected-Keyboard/pull/651
