### ISSUE TITLE
Turn off MessagEase style gestures

### ISSUE THREAD

**Issue by JapanYoshi** [Julow/Unexpected-Keyboard#653]
Ever since the latest update that introduced “MessagEase style gestures”, my typing has become less consistent, where I keep seeing uppercase versions of letters instead of an up or right swipe, and the left swipe gets dropped disruptively often, because my swipes are too fast and imprecise that the app is detecting them as curved.

Is there a way to turn off curved gestures, either in the settings or in the keyboard XML?

**Comment by Julow** [comment]
The sensitivity could be technically controlled so this doesn't need to be a on/off switch but a scale like the swipe distance.

**Comment by JapanYoshi** [comment]
![Screenshot_20240606-123927](https://github.com/Julow/Unexpected-Keyboard/assets/8707990/3b3520cd-ad55-4f55-a303-f78eed89c043)

Now why in the world would this type T instead of w?

**Comment by JapanYoshi** [comment]
![IMG_20240606_124539](https://github.com/Julow/Unexpected-Keyboard/assets/8707990/3bd06f1d-fc65-4dc0-ad1a-1622caee9bef)
This is an atrocity

**Comment by Julow** [comment]
It seems that the gesture algorithm is too sensitive on your device, that explains all of these. It's possible that some calculations are wrong.

**Comment by Spike-from-NH** [comment]
It works fine for me on several devices. @JapanYoshi, you must learn its ways. Shorter, more linear strokes. Your final example may have triggered auto-repeat; this is already adjustable in Settings. But you're right, it should be possible to train or disable it.

If a swipe starts in one octant (from the initial touch location, I guess) and ends up in another, it is a circle gesture.

**Comment by JapanYoshi** [comment]
> It works fine for me on several devices. @JapanYoshi, you must learn its ways. Shorter, more linear strokes. Your final example may have triggered auto-repeat; this is already adjustable in Settings. But you're right, it should be possible to train or disable it.
> 
> If a swipe starts in one octant (from the initial touch location, I guess) and ends up in another, it is a circle gesture.

"Skill issue" is not how you respond to a workflow-breaking usability regression.

I use the keyboard one-handed often, and therefore the strokes can get curved even when they're as short and linear as naturally possible at speed, whether because the finger pressed down unevenly at the start, causing the center of the tap to move in the wrong direction, or because the direction of the swipe was radial from the base of the thumb, causing it to arch.

Either way, I have no use for a gesture for capitalization, or a circle gesture in general, and would like a way to disable them altogether without raising my minimum swipe distance.

**Comment by Julow** [comment]
Let's not start an argument.

@Spike-from-NH No one has ruled out the possibility that this is really not usable on some screen size or density. No need to invoke skills yet.

@JapanYoshi I acknowledged your issue and added it to the next milestone when I first answered. Sorry if that was not clear but I intent to fix this issue without you changing your swipe distance.

Until that's fixed, you can downgrade the app by downloading the previous version from the "Assets" section on this page: https://github.com/Julow/Unexpected-Keyboard/releases/tag/1.27.0

**Comment by Spike-from-NH** [comment]
Sorry, @JapanYoshi, I didn't mean to impugn your dexterity.

**Comment by Julow** [comment]
I added an option in b5a96dc that should allow you to make the gesture less sensible or to entirely disable it.
You can find a debug build here: https://github.com/Julow/Unexpected-Keyboard/actions/runs/9436524723

**Comment by JapanYoshi** [comment]
Counterclockwise circle-around gesture still works when disabled. They’re not sensitive enough to *accidentally* activate, but they’re unable to be fully turned off.

**Comment by Julow** [comment]
@JapanYoshi The counterclockwise circle gesture do nothing unless you explicitly added them into your custom layout.
Are you accidentally making the round-trip gesture ? This is done by swiping towards a symbol, then reversing direction back to where you started.
This cannot be disabled.
