### ISSUE TITLE
[question] custom layouts and layouts included in app

### ISSUE THREAD

**Issue by mcrosson** [Julow/Unexpected-Keyboard#654]
Are there any standards for getting new layouts included in the main app? Also, is there any kind of repository or site where community members can post, share and remix their custom layouts?

**Comment by Julow** [comment]
Hi, thanks for your interest :)

Layouts can be added into the [srcs/layouts](https://github.com/Julow/Unexpected-Keyboard/tree/master/srcs/layouts) folder, some guidelines are written in [CONTRIBUTING.md](https://github.com/Julow/Unexpected-Keyboard/blob/master/CONTRIBUTING.md#adding-a-layout).
Only "standard" layouts are accepted, though that's not written down anywhere. I tend to accept layouts that have a name and a proof that they have users (eg. a wikipedia page).

This repository is intended for sharing user layouts: https://github.com/Julow/Unexpected-Keyboard-layouts

**Comment by mcrosson** [comment]
Thank you for the information, this is exactly what I was hoping to learn.

**Comment by Spike-from-NH** [comment]
> I tend to accept layouts that have a name and a proof that they have users (eg. a wikipedia page).

@Julow: Not Wikipedia; it has a notorious rule that all articles must be notable to the actual press, as in having newspaper articles about it. I can't just write a layout, or start a club, and document it on Wikipedia—they'd delete it.

**Comment by Julow** [comment]
@Spike-from-NH If you start a layout, it'll certainly not have more than one user until you make it popular enough for Wikipedia.
Anyway, that's not a rigid rule. The intention is that in the current state of the app, I only accept layout that are likely to have many users.

**Comment by Spike-from-NH** [comment]
Got it. See if my new final section of the .md file sums this up correctly.
