### ISSUE TITLE
modmap in custom keyboard layout

### ISSUE THREAD

**Issue by Joppla** [Julow/Unexpected-Keyboard#655]
Hello,

Realy nice keyboard. Compliments.

I was experimenting a bit with the custom keyboard. I try to use modmap to use the fn key in other way. But till now it doesn't what I suspect.

Questions
Can I use the modmap tag within the custom keybord?
Where to place the modmap tag?

Thanks for reaction.

**Comment by JapanYoshi** [comment]
Currently, I think `<modmap />` only works with Shift. I wish I could define custom Fn states, or even custom Compose sequences, too.

**Comment by Julow** [comment]
Hi,

The modmap is placed at the same levels as the rows, for example starting from the qwerty US layout:
```
<keyboard name="QWERTY (US)" script="latin">
  <modmap>
    <fn a="~" b="≈"/>
    <fn a="=" b="≠"/>
  </modmap>
  <row>
    <key key0="q" key2="1" key4="loc esc"/>
    <key key0="w" key1="~" key2="2" key3="\@"/>
    <key key0="e" key1="!" key2="3" key3="\#" key4="loc €"/>
    <key key0="r" key2="4" key3="$" key1="loc ₪"/>
    <key key0="t" key2="5" key3="%"/>
    <key key0="y" key2="6" key3="^"/>
    <key key0="u" key2="7" key3="&amp;"/>
    <key key0="i" key2="8" key3="*"/>
    <key key0="o" key1="loc accent_macron" key2="9" key3="(" key4=")"/>
    <key key0="p" key2="0"/>
  </row>
  ... The rest
</keyboard>
```

@JapanYoshi It's possible to map Fn since last release.

**Comment by Joppla** [comment]
Hi,
Thank for reaction.
I thought it should be something like that, but only the original replacement with æ en ₱ for a and b is shown.

This is my code:
[code]
<?xml version="1.0" encoding="utf-8"?>
<keyboard name="QWERTY (US)" script="latin">
  <modmap>
    <fn a="~" b="≈"/>
    <shift a="=" b="≠"/>
  </modmap>
  <row>
    <key key0="q" key2="1" key3="!" key4="esc"/>
    <key key0="w" key1="~" key2="2" key3="\@"/>
    <key key0="e" key1="!" key2="3" key3="\#" key4="loc €"/>
    <key key0="r" key2="4" key3="$" key1="loc ₪"/>
    <key key0="t" key2="5" key3="%"/>
    <key key0="y" key2="6" key3="^"/>
    <key key0="u" key2="7" key3="&amp;"/>
    <key key0="i" key2="8" key3="*"/>
    <key key0="o" key1="loc accent_macron" key2="9" key3="(" key4=")"/>
    <key key0="p" key2="0" key3="f11_placeholder" key4="f12_placeholder"/>
  </row>
  <row>
    <key shift="0.5" key0="a" key1="tab" key2="`"/>
    <key key0="s" key1="loc accent_ring" key2="loc §" key3="loc ß" key4="loc accent_ogonek"/>
    <key key0="d" key1="loc accent_grave" key2="loc £" key3="loc accent_aigu"/>
    <key key0="f" key1="loc accent_dot_above"/>
    <key key0="g" key1="loc accent_caron" key2="-" key3="_"/>
    <key key0="h" key2="=" key3="+"/>
    <key key0="j" key1="loc accent_trema" key2="loc accent_circonflexe" key4="}" key3="{"/>
    <key key0="k" key1="loc accent_double_aigu" key3="[" key4="]"/>
    <key key0="l" key2="|" key3="\\"/>
  </row>
  <row>
    <key width="1.5" key0="shift" key2="loc capslock"/>
    <key key0="z"/>
    <key key0="x" key2="loc †"/>
    <key key0="c" key1="loc accent_cedille" key2="&lt;" key3="."/>
    <key key0="v" key2="&gt;" key3=","/>
    <key key0="b" key2="\?" key3="/"/>
    <key key0="n" key1="loc accent_tilde" key2=":" key3=";"/>
    <key key0="m" key2="&quot;" key3="'"/>
    <key width="1.5" key0="backspace" key2="delete"/>
  </row>
</keyboard>
[/code]

**Comment by Julow** [comment]
This means that "~" should be changed into "≈" when Fn is pressed:

    <fn a="~" b="≈"/>

It's not related to the "a" and "b" keys, "a" and "b" are the XML attributes for "from" and "to".

Le 9 juin 2024 17:29:20 GMT+02:00, Joppla ***@***.***> a écrit :

**Comment by Joppla** [comment]
Thanks! Now I understand it! 😀

**Comment by Joppla** [comment]
Hi,
Just another question for the same subject. 

If in the default layout for example is written:
`<fn a="e" b="€" />`
but I don't want to change it in my layout, is than the only way to undo it to make the rule:
`<fn a="e" b="e" />`?
Or is there another way?

**Comment by Spike-from-NH** [comment]
If you have a custom layout file, it should be sufficient to remove the existing rule, rather than write a new rule to countermand it.

**Comment by Julow** [comment]
Fn+e gives € and the only way to disable that is to explicitly revert it as you did.

**Comment by Joppla** [comment]
Thanks!

**Comment by Spike-from-NH** [comment]
Now mentioned in the draft [documentation](https://github.com/Spike-from-NH/Unexpected-Keyboard-documentation/blob/master/doc/Custom-layouts.md).
