### ISSUE TITLE
unexpected behaviour for sup and sub

### ISSUE THREAD

**Issue by Joppla** [Julow/Unexpected-Keyboard#663]
Hello,

Another question, I see some unexpected behaviour by using the "sub" and "sup" keys.

With "sub" the following letters are not in sub position: q, w, y, d, f, g, z, c, b.
With "sup" the following letters not: q.

Further the the letters with accents are not possible to place in sub or sup position. But that is not so important for me.

Is there a reason for this choice or is it a bug?

**Comment by Yugicchi** [comment]
Hi @Julow ,

I noticed that some characters seem to be missing from srcs/compose/accent_subscript.json and accent_superscript.json, which might be causing them to not function properly.
 
Could you take a look at this and address the issue?

This is my first time commenting on GitHub as I am trying to improve my English. I'm interested in this app and hope this will contribute. Thank you for your understanding.

**Comment by Julow** [comment]
The unicode standard do not contain a sub or sup "combining" character that could make any other character a subscript or a superscript and not every letters exist in subscript or superscript variant. Though these tables show some characters that are not present in `accent_subscript.json` and `accent_superscript.json`: https://en.wikipedia.org/wiki/Unicode_subscripts_and_superscripts#Latin,_Greek,_Cyrillic,_and_IPA_tables
Contribution welcome :)

**Comment by Joppla** [comment]
Oke, thanks for explanation!
