### ISSUE TITLE
 [BRUH] Copy , paste , select all commands not working on termux

### ISSUE THREAD

**Issue by HafizBeyy** [Julow/Unexpected-Keyboard#665]
The app has these commands as swipe gesture as you know. i use them in my daily use , they are great.  but i tried them on termux, and none of them worked.

**Comment by Spike-from-NH** [comment]
Please ignore that last entry; it should have cited 655.

**Comment by Julow** [comment]
These keys are sent to the apps, that are free to ignore them. Termux is not an usual app and it's reasonable for it to ignore these. There's nothing we can do as the keyboard cannot access the text on the terminal.
