### ISSUE TITLE
Fuction keys

### ISSUE THREAD

**Issue by Alex423243** [Julow/Unexpected-Keyboard#671]
I am trying to install Windows XP using Limbo PC emulator and it wants me to press F8 to accept the license agreement. But when I press "FN" and "8" It keeps thinking I'm typing "i". Is this a bug cause if it is can you please fix it?

Thanks!

**Comment by Julow** [comment]
Hi, make sure to swipe your finger starting from the "i" key toward the "8" symbol.

**Comment by Julow** [comment]
Have you been able to make this work?

**Comment by Julow** [comment]
I'll close this. Feel free to re-open if needed.
