### ISSUE TITLE
Additional keys

### ISSUE THREAD

**Issue by mariush444** [Julow/Unexpected-Keyboard#674]
It seems that additional keys like copy, paste, past as a text doesn't work.
Nighter copy nor paste.
Is there any trick to use it?

**Comment by mariush444** [comment]
Sometimes work and sometimes not, I guess it depends on  aps

**Comment by Julow** [comment]
Hi, indeed, the copy, paste, etc.. keys are sent to the apps, which are free to ignore them or misbehave.
