### ISSUE TITLE
Superscript & Subscript issue

### ISSUE THREAD

**Issue by namalsemage** [Julow/Unexpected-Keyboard#680]
Hey, Anyone can tell me why its not superscript and subscript option not working for all letters?

I have attached some screenshots. Kindly check thanks?
![Screenshot_20240629_102733_Unexpected Keyboard](https://github.com/Julow/Unexpected-Keyboard/assets/57058335/23efb9e6-baf6-4025-9aca-17807b2d7f3a)
![Screenshot_20240629_102743_Unexpected Keyboard](https://github.com/Julow/Unexpected-Keyboard/assets/57058335/4bd2b71f-6286-4d7f-87a9-072fbb4ebd08)

**Comment by Julow** [comment]
Unicode do not define a "combining superscript" character that could make any other character a subscript and do not define a super/subscript version for every latin letters.
These tables show what is possible: https://en.wikipedia.org/wiki/Unicode_subscripts_and_superscripts#Latin,_Greek,_Cyrillic,_and_IPA_tables

These two files show what the keyboard currently supports: [accent_superscript.json](https://github.com/Julow/Unexpected-Keyboard/blob/master/srcs/compose/accent_superscript.json), [accent_subscript.json](https://github.com/Julow/Unexpected-Keyboard/blob/master/srcs/compose/accent_subscript.json)
Notably, all the uppercase super and subscripts are missing. Help welcome!

Related issue: https://github.com/Julow/Unexpected-Keyboard/issues/663

**Comment by notational** [comment]
It's true that Unicode does not officially support these characters. The committee rejected a past attempt to add them.

As a matter of interest, [Rupert Shepherd has discovered](https://rupertshepherd.info/resource_pages/superscript-letters-in-unicode) superscript characters that either are or resemble all of the lowercase latin characters, and most of the uppercase latin characters. Only superscript Z is missing. Superscript a and o (ª and º) are ordinal indicators that may be underlined in some fonts. The characters ᔆ and ᕽ are Canadian Aboriginal Syllabics, thus aren't guaranteed to align with latin superscript characters. Consider ᔆᵁᕽ.

Subscripts are a different matter. There are far fewer Unicode analogues to the Latin subscript letters.

**Comment by Julow** [comment]
Thanks for the source. The superscript table is quite complete currently (last improvement was https://github.com/Julow/Unexpected-Keyboard/pull/770) so I'll close this issue.
