### ISSUE TITLE
move cursor by holding the space key

### ISSUE THREAD

**Issue by rambip** [Julow/Unexpected-Keyboard#7]
Your keyboard is reallu great for symbols, but it could be even beyyer for gestures.

I tried [typewise](https://www.typewise.app/) for a few days, and the way you move your cursor ans delete characters with this keyboard is incredible.

If this keyboard had gestures for the cursor (and uppercase letters), this would probably be the best I have seen so far !

**Comment by Julow** [comment]
Hi! Thanks for the suggestion.

There's already a gesture on the keyboard that you might find useful. The key-repeat speed can be modulated by moving the finger farther or closer to the initial press, for the arrows, backspace and delete keys.
Could this work for you ?

**Comment by 532910** [comment]
I'd prefer to merge arrows button with the space button. Like on AnySoftKeyboard.

**Comment by moya2162** [comment]
I too agree that having this feature would be very useful. It's easier to precisely control in my opinion. 

Please check out simple keyboard by rkkr which has this feature. Code is on github as well so might be easy to add to your keyboard. 

[https://github.com/rkkr/simple-keyboard](url)

**Comment by Julow** [comment]
Implemented in 854eff2. A debug version of the app can be found here (it needs to be enabled again in the settings): https://github.com/Julow/Unexpected-Keyboard/actions/runs/3981827849

**Comment by moya2162** [comment]
@Julow 

Installed debug version to test this out. So far works well but there is 1 minor issue. After swiping to scroll to specific location, upon release of space bar the cursor moves by 1 space to left or right depending on where you are on the space bar when you remove your finger.

**Comment by sdrapha** [comment]
I can attest the issue that moya described is reproducible for me as well, same behavior, the cursor jumps one char.

Another issue I found on top of that, is that the SHIFT LOCK (by sliding the finger to the extra key) unlatches itself with any arrow movement. unlike the SHIFT LOCK by holding SHIFT for a time, which persists locked as expected.

**Comment by Julow** [comment]
Thanks both for trying. This should be fixed in 7bc93c4, debug apk is at https://github.com/Julow/Unexpected-Keyboard/actions/runs/4037961439
