### ISSUE TITLE
Keyboard switch does not work on 1.29

### ISSUE THREAD

**Issue by nikolasdmtr** [Julow/Unexpected-Keyboard#704]
- Switching languages with the keyboard switch button fails on 1.29. Tried both system languages option and adding the languages manually to the keyboard.
- I am on android 13, moto g13 device, stock rom.
- Uninstalled and installed 1.28 where keyboard switch works normally.

**Comment by Julow** [comment]
I fail to reproduce the problem. What are your languages ?

You are talking of the switching key that is on the top-right corner of the Fn key, not the one on the top of the space bar ? Also, no custom layouts ?

**Comment by nikolasdmtr** [comment]
English and Greek (Layout 1: System settings). I tried adding them as separate layouts too. 

I am referring to the Fn key, yes, and no custom layouts.

Also 1.38 works normally.

**Comment by Polux49** [comment]
Same thing here. 

Unexpected keyboard used to be in french (azerty), like all the virtual keyboards of my smartphone, but is now in english (qwerty), and I can't find any way to fix this. 

Great keyboard, by the way! :+1:

**Comment by nikolasdmtr** [comment]
> Same thing here.
> 
> Unexpected keyboard used to be in french (azerty), like are still all the virtual keyboards of my smartphone, but is now in english (qwerty), and I can't find any way to fix this.
> 
> Great keyboard, by the way! 👍

You can uninstall 1.39 and install 1.38 till there is a fix.

**Comment by Julow** [comment]
You can download 1.38 here: https://github.com/Julow/Unexpected-Keyboard/releases/tag/1.28.0

**Comment by Julow** [comment]
Thanks for reporting, this is fixed in 65f4ffd. You can find a debug version of the app at the bottom of this page: https://github.com/Julow/Unexpected-Keyboard/actions/runs/10019495077 (that's not an update to the released app).

I'll try to release this soon-ish.

**Comment by Polux49** [comment]
@nikolasdmtr: Thank you for the work-around. I have used it. 
@Julow: Thank you for the fix.
