### ISSUE TITLE
keystroke

### ISSUE THREAD

**Issue by LVMuftu** [Julow/Unexpected-Keyboard#705]
"Hello, I have a question. How can I write two parentheses characters and move the cursor between them with a single keystroke? Thank you."

**Comment by Julow** [comment]
Hi, that's currently not possible but would be a great addition to the app. Related issues: https://github.com/Julow/Unexpected-Keyboard/issues/568 https://github.com/Julow/Unexpected-Keyboard/issues/576

**Comment by LVMuftu** [comment]
Thanks a lot

**Comment by Y-T-G** [comment]
I wanted to do the same thing
