### ISSUE TITLE
New update created large empty space in preexisting layout

### ISSUE THREAD

**Issue by Mojken** [Julow/Unexpected-Keyboard#708]
Not sure if you just changed the format, but I mean, I haven't been told about that in any way. Removing the number row (which is the checkbox one, not a custom one) removes most of the space, but the last column is still not in line with the enter. Also, the diacritics moved, as usual.
![image](https://github.com/user-attachments/assets/2cf7be5a-966c-4dfe-9f30-a9dcf572033f)

**Comment by Julow** [comment]
Thanks for reporting. Can you share your layout ?

**Comment by Julow** [comment]
Should be fixed in 50a3c0f, thanks!
