### ISSUE TITLE
loc £ problem

### ISSUE THREAD

**Issue by mariush444** [Julow/Unexpected-Keyboard#710]
I defined
`<key key0="d" key1="loc accent_grave" key2="loc £" key3="loc accent_aigu"/>`
but I can't hide £ on the keyboard. It ss always shown  regardless to checkbox in the settings. What I do in wrong way?

**Comment by Julow** [comment]
The keyboard will try to add some keys to your layout depending on your languages. To avoid this in a custom layout set this attribute: `<keyboard ... locale_extra_keys="false">`.
Related issue: https://github.com/Julow/Unexpected-Keyboard/issues/683

**Comment by mariush444** [comment]
`<keyboard name="QWERTY (PL MyOwn)" bottom_row="false"  script="latin" locale_extra_keys="false">`
unfortunatly, it still does't work

**Comment by Julow** [comment]
What version of the keyboard do you use ? This was added in 1.29.0.

**Comment by mariush444** [comment]
I used 1.28 but I just install 1.29 and it works OK. Thank you.
