### ISSUE TITLE
Parenthesis moved from 'o' key over to 'p' in polish layout

### ISSUE THREAD

**Issue by asivery** [Julow/Unexpected-Keyboard#712]
Hello there,
It seems the new version has moved the parenthesis in the polish layout from the 'o' key over to 'p'.
No other layout I use has made this switch - this makes the polish layout inconsistent with the other layouts.
In addition to that, it is worth pointing out that on a lot of phones, the 'p' key (being on the edge of the display) is hard to swipe diagonally on. In my case, this makes it impossible to select the ')' key at all.
I propose to rollback c5e9e3f, or to make the new layout separate from the old one.

**Comment by Julow** [comment]
Thanks for pointing this out. The goal of c5e9e3f was to make a consistent placement for the letters with an accent. 
I agree the new placement of the parentheses is not right. Where would you put `ó` ?

Ping @ZX-Commodore-ST who suggested this in https://github.com/Julow/Unexpected-Keyboard/issues/649

**Comment by asivery** [comment]
Thanks for such a quick response @Julow !
I personally see three ways in which this problem could be resolved:
1. Roll back the change completely (I imagine a lot of people didn't notice the inconsistency with 'ó' being at the top instead of the bottom - I know I didn't)  - This will annoy the users who see this as a positive change
2. Go with @ZX-Commodore-ST's second approach (keep "(" and ")" under "o" but change their default gesture for "(" and ")" from bottom to top) - This will still not solve the issue of breaking muscle memory, but will make it less jarring.
3. Make it so we can define custom layouts based on these original "presets". Then make it so any key could be moved to any position. That way, both the people who find the change annoying, and those who welcome it would be happy. (Unfortunately I imagine this is the most complicated fix to implement)

**Comment by Julow** [comment]
I'm fine with reverting the parentheses back to where they were. PR welcome.

**Comment by ZX-Commodore-ST** [comment]
I have nothing against any of the changes proposed here as long as I can use a custom layout. I'm happy with help that I received to make a custom layout for myself that suits my workflow. Still from my point of view it makes sense to have all polish (and other language) letters follow consistent way of using them. At the same time @asivery is right that keyboard has to be consistent with different languages when using special signs. Is it possible to have it all together? I'm sure it is. But when you move a key you will get that kind of response from unhappy users who already got used to last version.

BTW I have no experience with Google keyboard or Apple keyboard etc so I don't event know what is default place for parenthesis.

**Comment by Julow** [comment]
I've merged https://github.com/Julow/Unexpected-Keyboard/pull/714 but if you have ideas on how to solve the issue of consistency between the layouts, please re-open.
