### ISSUE TITLE
Make swipeup default for a-z be A-Z.

### ISSUE THREAD

**Issue by bacionejs** [Julow/Unexpected-Keyboard#715]
This would save one click.
Current solution is setting key7 for a-z to A-Z but it is not visually appealing.
Pseudocode: if(swipeup && key7==undefined) return shift key0.

**Comment by Spike-from-NH** [comment]
The clockwise gesture already achieves this, and without any keycap legend.

**Comment by Julow** [comment]
I'll close this issue as the clockwise gesture is basically this. Do a swipe up gesture followed by a slight turn to the right.
