### ISSUE TITLE
Can I send keyevents?

### ISSUE THREAD

**Issue by dingodoppelt** [Julow/Unexpected-Keyboard#717]
Hi there,
sorry for posting a question rather than an issue.
I need to send a custom keyevent to an app, which I currently achieve by  ```adb shell input keyevent 82```.
Is it possible to assign a keyevent to a key in a custom layout?
cheers, nils

**Comment by ChiefMikeK** [comment]
Javascript Char Codes (Key Codes) - Cambia Research https://www.cambiaresearch.com/articles/15/javascript-char-codes-key-codes  
doesn't `r` work?

**Comment by Julow** [comment]
That's not possible at the moment but would be a great addition to the app. Would you be willing to implement it ?

The [KeyValue](https://github.com/Julow/Unexpected-Keyboard/blob/master/srcs/juloo.keyboard2/KeyValue.java#L317) class can already represent the new key and we just need a way to construct it. [KeyValue.getKeyByName](https://github.com/Julow/Unexpected-Keyboard/blob/master/srcs/juloo.keyboard2/KeyValue.java#L416) would be the best place to implement the new key syntax. The syntax should also allow specifying a label for the key.
The [custom key option](https://github.com/Julow/Unexpected-Keyboard/blob/master/srcs/juloo.keyboard2/prefs/CustomExtraKeysPreference.java#L43) do not use this `getKeyByName` function and instead makes raw string keys. It should be able to recognize the syntax too.

**Comment by dingodoppelt** [comment]
> That's not possible at the moment but would be a great addition to the app. Would you be willing to implement it ?

I'm not a programmer, but I got #726 to do what I need :) Is this something you can make use of?
cheers, nils

**Comment by Julow** [comment]
Thanks for the PR! That's the perfect way to solve your problem. I'd like to keep this issue open for discussing the other key events.

**Comment by dingodoppelt** [comment]
> Thanks for the PR! That's the perfect way to solve your problem. I'd like to keep this issue open for discussing the other key events.

Thanks! Very much appreciated :)

**Comment by ChiefMikeK** [comment]
> Thanks for the PR! That's the perfect way to solve your problem. I'd like to keep this issue open for discussing the other key events.

remember to update the docs.md 👌

**Comment by Julow** [comment]
Keyevent keys implemented in 2060e6a
