### ISSUE TITLE
v1.29.0 crashing immediately on Android 6.0. v1.28.0 Works.

### ISSUE THREAD

**Issue by barkoder** [Julow/Unexpected-Keyboard#722]
Steps to reproduce:

0. Have an Android 6.0 device.
1. Install/Update Unexpected Keyboard to v1.29.0 from https://f-droid.org
2. Set Unexpected Keyboard as the default(if it isn't already).
3. Try to type something.
4. Crash.

https://github.com/user-attachments/assets/3ca42aa2-4bcb-4c93-8470-79ff702dd41a

---------------------

Thank you @Julow for the app! The app is amazing! At least until v1.28.0 :)

**Comment by Julow** [comment]
Thanks for the issue! Fixed in d8fc4e8. I plan to release soon but in the meantime, you can download 1.28.0 here: https://github.com/Julow/Unexpected-Keyboard/releases/tag/1.28.0
