### ISSUE TITLE
en-US is used on a pl-PL phone

### ISSUE THREAD

**Issue by gszy** [Julow/Unexpected-Keyboard#724]
Since 1.29.0 (F-Droid), the keyboard changed its language and layout from Polish to English. The system language is still Polish, the Unexpected Keyboard layout is "System". I can manually change the layout to QWERTY (Polish), but the spell checking language is still en-US and I cannot find a way to change it (AOSP keyboard is still in Polish).

**Comment by Julow** [comment]
Thanks for reporting. This was fixed recently (https://github.com/Julow/Unexpected-Keyboard/issues/704) and I hope to release it this weekend.
