### ISSUE TITLE
clipboard and autocomplete feature

### ISSUE THREAD

**Issue by holymark** [Julow/Unexpected-Keyboard#729]
I  could not find a clipboard feature on the app, if there's already a function for that, then it's not concisely stated, and also the app doesn't seem to support au complete function, which would make it much better for the user to use. 

This is my observation, if this features are already implemented in the app, then it's not concisely stated as some users will find it a bit uncooperative.

**Comment by Spike-from-NH** [comment]
① Clipboard was added recently. It isn't well-documented but I found it self-explanatory. On my layout and v1.29.0, it automatically appears as the south-east swipe of the w key.
② A Complete function seems to be at odds with the goal of being a "lightweight" keyboard, as it would require inclusion of a dictionary and/or personal usage history.

**Comment by holymark** [comment]
Okay then. anyways the auto complete feature, i think will be worth implementing in the future, I propose.

**Comment by Julow** [comment]
It's true that clipboard should get documented. The word correction/completion feature is definitely wanted but I lack the time to implement it.
I'll close this issue as a duplicated of: https://github.com/Julow/Unexpected-Keyboard/issues/343, https://github.com/Julow/Unexpected-Keyboard/issues/716
