### ISSUE TITLE
Settings button does not appear on home screen

### ISSUE THREAD

**Issue by zachpoblete** [Julow/Unexpected-Keyboard#731]
On my tablet, the settings button appears on the top right of the home screen, but on my phone, there is no settings button at all.

<img src="https://github.com/user-attachments/assets/38e63bdd-6429-4748-bee3-cccf9fee89b9" width="250">

Device: Samsung Galaxy A03
Android version: 13

**Comment by Spike-from-NH** [comment]
That sounds like a bug. (Or, you haven't updated Unexpected on your phone? Access to Settings from the initial page was only added a couple versions ago.) A workaround is to tap the input field to raise the keyboard, then swipe the gear logo.

**Comment by zachpoblete** [comment]
Yup, I at least found out about that workaround.

I can't find the version the button was added, but I'm using v1.27.0 on both my tablet and phone.

**Comment by Spike-from-NH** [comment]
Baffling. V1.29.1 is here; upgrade to that and see if it fixes anything.

[https://github.com/Julow/Unexpected-Keyboard/releases/download/1.29.1/juloo.keyboard2.apk]

**Comment by zachpoblete** [comment]
Yay, that fixed it. Thanks guys.

The version in the Play Store on my tablet is wrong then as it's at least v1.28.
