### ISSUE TITLE
`switch_forward`: make it work for switching between `numeric.xml` layouts

### ISSUE THREAD

**Issue by lrvideckis** [Julow/Unexpected-Keyboard#732]
So I use 2 layouts: english, and Hindi, and they both have their own symbols for numbers:

![WhatsApp Image 2024-08-12 at 11 58 55(1)](https://github.com/user-attachments/assets/d230d068-8b82-4f2e-988a-a0531de3f023)
![WhatsApp Image 2024-08-12 at 11 58 55](https://github.com/user-attachments/assets/099c9192-c03a-4bd2-8424-0516ab76f2db)

I want to add `switch_forward` key to this layout which switches between these 2. I tried this, but it switches from english-num pad to hindi-regular layout and vice versa:

https://github.com/user-attachments/assets/795f9285-f9de-4de0-be59-5744ff12bf09

**Comment by lrvideckis** [comment]
basically I want a way to toggle between both numpad layouts

**Comment by lrvideckis** [comment]
I do plan to attempt to make this change myself sometime in the next week or so

**Comment by Spike-from-NH** [comment]
You might need to define a new key such as `switch_numpad_forward` to affect the numpad rather than the main keyboard. The active main keyboard is stored persistently—in fact, two; one for Portrait and one for Landscape—and I assume this too must be replicated.

**Comment by lrvideckis** [comment]
actually I no longer want this feature

**Comment by Julow** [comment]
A similar ideas that could help you is to add a way to switch to a custom layout by its name. It has been mentioned in [this issue](https://github.com/Julow/Unexpected-Keyboard/issues/678) (among other things) and is on my TODO list as a plan to allow custom numpads.
