### ISSUE TITLE
[bug] "Switch keyboard" key is broken

### ISSUE THREAD

**Issue by hyyrdbzm** [Julow/Unexpected-Keyboard#738]
How to reproduce:
1. install 1.29.1 version of the app from F-Droid;
2. add following layouts: QWERTY (US), ЙЦУКЕН (Русский), Armenian;
3. enable "Switch keyboard" key;
4. press the "Switch keyboard" key.

What you will get:
1. language switch widget contains only two first languages;
2. switching between languages isn't working.

How to bypass: leave only one layout and change it each time - switching first layout works correctly.

**Comment by Julow** [comment]
Hi,

The "Switch keyboard" key is meant to switch between different keyboard apps. It's enabled by default on the top-right of the Fn key.

The key for switching between layouts configured in the settings in upward on the space bar. I think that's what you want.

**Comment by Julow** [comment]
Happy to help. Don't hesitate to ask any questions
