### ISSUE TITLE
Change the place of چ in Persian Keyboard Layout

### ISSUE THREAD

**Issue by Danger-Mkh** [Julow/Unexpected-Keyboard#749]
Replace the 'چ' character to place it was.

Now :
https://github.com/Julow/Unexpected-Keyboard/blob/a8e331c3222dc7f84b823e1a53e3e6fe22839210/srcs/layouts/arab_pc_ir.xml#L14

Bbefore:
https://github.com/Julow/Unexpected-Keyboard/blob/deb611a0d2c7e75a1c276238064219fc54b4417d/srcs/layouts/arab_pc_ir.xml#L39

The change is annoying and it doesn't add anything more

**Comment by Spike-from-NH** [comment]
In other words, چ used to be on its own key but has been moved to a swipe of the ج key. Are these letters related? Is the first one relatively rare, that would justify this move? Is there a bigger problem than an annoying change? Is it a solution to copy-paste the old XML as a custom layout on your device?

**Comment by Danger-Mkh** [comment]
It's **separate letter** like others, so it should be on it's own key.

Yes, copy-paste old XML would solve the problem but the general problem will exists.

Both 'ج' and 'چ' used as normal letter and it's not other format of a letter like 'ا' and 'آ'.
'ا' and 'آ' is the same letter but used in different places.

For example 'آ' used as first letter of word and in middle of word letter 'ا' will be used.

**Comment by Danger-Mkh** [comment]
@Spike-from-NH  any suggestions?!

**Comment by Julow** [comment]
This was changed in https://github.com/Julow/unexpected-Keyboard/pull/711 by @RZHSSNZDH
@RZHSSNZDH What was the idea being removing this key ?

**Comment by Spike-from-NH** [comment]
@Danger-Mkh, you convinced me. @Julow asks the important question. There is an edit entitled "Change the place of چ in persian" but it doesn't say why.

**Comment by RZHSSNZDH** [comment]
> This was changed in #711 by @RZHSSNZDH @RZHSSNZDH What was the idea being removing this key ?

The backspace key had a small size so I removed چ from the button row, and I could not find a place for it in other rows.

**Comment by RZHSSNZDH** [comment]
> > This was changed in #711 by @RZHSSNZDH @RZHSSNZDH What was the idea being removing this key ?
> 
> The backspace key had a small size so I removed چ from the button row, and I could not find a place for it in other rows.

I do it on my own because I didn't think if there is a person who uses this keyboard in persian layout 😅
In this case I have an idea; We can replace ژ with چ which is a normal method in keyboards and add ژ to ر as a sub-key.

**Comment by Danger-Mkh** [comment]
> In this case I have an idea; We can replace ژ with چ which is a normal method in keyboards and add ژ to ر as a sub-key.

I think this is a good idea, I'm agreed.

For the record, the place of چ should be right side of و. the place it was before.

**Comment by RZHSSNZDH** [comment]
> > In this case I have an idea; We can replace ژ with چ which is a normal method in keyboards and add ژ to ر as a sub-key.
> 
> I think this is a good idea, I'm agreed.
> 
> For the record, the place of چ should be right side of و. the place it was before.

Will you do it or I should do?

**Comment by Danger-Mkh** [comment]
> Will you do it or I should do?

I will do it.

**Comment by Julow** [comment]
Thanks you both for resolving this issue :) I'm very happy that the layout is maintained.

**Comment by Julow** [comment]
Fixed in https://github.com/Julow/Unexpected-Keyboard/pull/757 by @Danger-Mkh
