### ISSUE TITLE
How to open the clipboard pane ? (help needed)

### ISSUE THREAD

**Issue by mahshy123** [Julow/Unexpected-Keyboard#750]
Hello ,
I saw that the clipboard menu has been added in version 1.29.0 but I can't open it because I can't find any source that explains how to open it, can anyone explain how to open it?

**Comment by Spike-from-NH** [comment]
Go into Settings (swipe the gear logo) and tap Add keys to the keyboard. Clipboard manager is near the top of this menu.

**Comment by Julow** [comment]
The clipboard button is on the bottom-left of the Ctrl key, in the bottom row, when it's enabled in the settings.

@Spike-from-NH I updated the doc in 13ad05c
