### ISSUE TITLE
Ability to modify key height

### ISSUE THREAD

**Issue by Juhan280** [Julow/Unexpected-Keyboard#755]
The keys are a bit taller then i am used to resulting in wrong being pressed. If there was an option to adjust key height, it would be great

**Comment by Spike-from-NH** [comment]
There is! Go to the Settings menu (by swiping on the gear icon), then go down the menu to find "Keyboard height". The percentages are of the total screen height. It has separate settings for Portrait and Landscape.

If you write a custom layout, you can specify the height of individual rows of keys.

**Comment by Juhan280** [comment]
Ohh, i didn't realize there was a custom layout which allows me to change key height per row

**Comment by Juhan280** [comment]
How do i modify number row? Do i need to just disable number row and roll my own?

**Comment by Spike-from-NH** [comment]
If you use the built-in number row or bottom row, you can't modify them. Tag properties to disable them are in the [documentation](https://github.com/Julow/Unexpected-Keyboard/blob/master/doc/Custom-layouts.md).

**Comment by sdrapha** [comment]
> How do i modify number row? Do i need to just disable number row and roll my own?

That is exactly what I do. I have my number row built-in into my own layout, with a custom height which is different than the other rows. And then I disable the programatically implemented number row from the settings so it doesn't interfere with mine.

**Comment by Spike-from-NH** [comment]
@sdrapha, if you want to guide people to your fork, please include a URL in your post.

I do the same thing on the number row. I briefly played with making it a different height; but for me, there is a best trade-off between type-ability vs. taking up screen space, and it's the same for every row.

**Comment by Juhan280** [comment]
Thanks for your kind answers
