### ISSUE TITLE
Media controles from keyboard 

### ISSUE THREAD

**Issue by shrimansoft** [Julow/Unexpected-Keyboard#759]
What if we can play plus media from the keyboard only. I use a kiss launcher with an unexpected keyboard. 

So the keyboard is easier to access than the drawer.

**Comment by Julow** [comment]
A "play pause" key event exists in Android but I think it's unlikely that it can affect the music player. It's best to try, you can add the `playpause` into your layout if you use [this branch](https://github.com/Julow/Unexpected-Keyboard/compare/play-pause-key), debug build is at the end of [this page](https://github.com/Julow/Unexpected-Keyboard/actions/runs/10975248372).

**Comment by Julow** [comment]
Due to lack of feedback, I'll close this.

**Comment by Julow** [comment]
With 2060e6a, it's now possible to add the play pause button like this:

```
:keyevent symbol='⏯' flags='small':85
```
