### ISSUE TITLE
Add F11 and F12 keys

### ISSUE THREAD

**Issue by juniorxcruz** [Julow/Unexpected-Keyboard#76]
Fantastic keyboard. There's only one thing I miss: it would be great to have access to the last two function keys (F11 and F12).

**Comment by ChiefMikeK** [comment]
suggest map to f11=j & f12=k top right swipe

**Comment by Julow** [comment]
The keys are now on the keyboard (ba6d62d). The position of the key is not as you suggested and not always the same on every layouts. Feedback welcome.
