### ISSUE TITLE
Compose and FN Combo Requests for Cyrillic

### ISSUE THREAD

**Issue by anaskaejdar** [Julow/Unexpected-Keyboard#768]
There aren't many compose combos set up in the cyrillic block yet, so I was
thinking about it, and I thought it'd be nice just to provide combinations for
some of the most commonly used cyrillic character sets --- russian, ukrainian,
serbian --- as well as early slavonic, since it's the root of them all. With
these combos implemented, somebody with the default russian keyboard (or the
default ukrainian one, or the default serbian one, etc.) would not only be able
to type any and every one of the old slavonic letters should they want to, but
they would be able to type all the letters of any of the other aforementioned modern
languages, without needing to set up additional keyboards to do it.

So first, here are some function-key (FN) alternates. Once the function key is
activated, the character on the left side of the arrow gets replaced with that
on the right side... but notice the first two entries are inverses of eachother... I assume this would work. I hope so, because there are others in this list that are similar in that way too:
ꙑ ⇒ ы
ы ⇒ ꙑ
ш ⇒ ѱ
з ⇒ ꙁ
и ⇒ і
і ⇒ и
я ⇒ ꙗ
е ⇒ ѥ
ѡ ⇒ ꙍ
о ⇒ ѻ
а ⇒ ѣ
э ⇒ є
ъ ⇒ ь
ь ⇒ ъ
й ⇒ ј
ꙉ  ⇒ ђ
ч ⇒ ћ
ҁ ⇒ қ
қ ⇒ ҁ
ҷ ⇒ џ
ј ⇒ й
у ⇒ ꙋ
м ⇒ ѫ
н ⇒ ѧ
с ⇒ ѕ

And then, here are some compose combos. Hit the compose key, then both of the
keys on the left of the arrow, and the keyboard would give you the key on the
right of the arrow.
ю+м ⇒ ѭ
ю+н ⇒ ѩ
г+х ⇒ ҁ
к+х ⇒ ҁ
о+у ⇒ ѹ
к+с ⇒ ѯ
к+ш ⇒ ѯ
а+у ⇒ ѡ
а+ꙋ ⇒ ꙍ
и+у ⇒ ѵ
і+у ⇒ ѵ
у+и ⇒ ѵ
у+і ⇒ ѵ
ю+е ⇒ ё
ј+а ⇒ ꙗ
я+ь ⇒ ꙝ
ј+ѣ ⇒ ꙝ
п+с ⇒ ѱ
ю+а ⇒ ꙓ
ш+т ⇒ щ
д+з ⇒ ꙃ
т+ф ⇒ ѳ
з+ф ⇒ ҙ
д+й ⇒ ꙉ
д+ј ⇒ ꙉ
д+е ⇒ ꙉ
д+ѥ ⇒ ђ
а+ь ⇒ ꙙ
о+т ⇒ ѿ
ѡ+т ⇒ ѿ
а+ы ⇒ ѣ
а+ꙑ ⇒ ѣ
а+е ⇒ ѣ
л+ь ⇒ љ
н+ь ⇒ њ
т+й ⇒ ћ
т+ј ⇒ ћ
д+ж ⇒ џ
і+. ⇒ ї
.+і ⇒ ї
"+і ⇒ ї
і+" ⇒ ї
к+г ⇒ ґ
г+к ⇒ ґ
г+й ⇒ ғ
г+ј ⇒ ғ
у+у ⇒ ӯ
и+и ⇒ ӣ
і+і ⇒ ӣ
у+й ⇒ ў
у+ј ⇒ ў
ч+ъ ⇒ combining_vertical_tilde
ч+а ⇒ combining_acute
ч+ю ⇒ combining_grave
ч+о ⇒ combining_inverted_breve
ч+у ⇒ combining_pokrytie
ч+б ⇒ combining_slavonic_psili
ч+х ⇒ combining_slavonic_dasia
ч+е ⇒ combining_trema
ч+й ⇒ combining_breve
ч+ј ⇒ combining_breve
ч+ч ⇒ combining_payerok
ч+н ⇒  combining_titlo
ч+ѧ ⇒  combining_vzmet
ъ+ч ⇒ combining_vertical_tilde
а+ч ⇒ combining_acute
ю+ч ⇒ combining_grave
о+ч ⇒ combining_inverted_breve
у+ч ⇒ combining_porkrytie
б+ч ⇒ combining_slavonic_psili
х+ч ⇒ combining_slavonic_dasia
е+ч ⇒ combining_trema
й+ч ⇒ combining_breve
ј+ч ⇒ combining_breve
ч+ч ⇒ combining_payerok
н+ч ⇒  combining_titlo
ѧ+ч ⇒  combining_vzmet
ч+. ⇒ ҷ
.+ч ⇒ ҷ
ж+. ⇒ җ
.+ж ⇒ җ
х+, ⇒ ӽ
,+х ⇒ ӽ
х+. ⇒ ҳ
.+х ⇒ ҳ
н+, ⇒ ӈ
,+н ⇒ ӈ
н+· ⇒ ԩ
,+ѧ ⇒ ӊ
.+н ⇒ ӊ
м+. ⇒ ӎ
.+м ⇒ ӎ
л+. ⇒ ԯ
.+л ⇒ ԯ
л+, ⇒ ԓ
,+л ⇒ ԓ
к+, ⇒ ӄ
,+к ⇒ ӄ
к+. ⇒ қ
.+к ⇒ қ
й+. ⇒ ҋ
.+й ⇒ ҋ
г+, ⇒ ӻ
,+г ⇒ ӻ
г+. ⇒ ӷ
.+г ⇒ ӷ

**Comment by Julow** [comment]
Thanks for providing the list. I implement the Fn combinations and Compose sequences in 9f0cf15
You can try the debug build at the bottom of this page: https://github.com/Julow/Unexpected-Keyboard/actions/runs/11095817526
I didn't include the combining diacritics as they didn't play well with my macros and renders badly on the keyboard. Wouldn't dead-keys like is used in latin layouts work better ? In any case, we need a dotted-circle glyph for these.

**Comment by anaskaejdar** [comment]
I didn't consider using deadkeys for that, because unlike in greek, there are no precomposed letters in unicode to deal with in this case. Everyone who types those slavonic diacritics just types the letter and then the combining diacritic. I thought the code would be simpler that way too. I'll make the dotted circle glyphs very shortly. What do you mean by “doesn't play well with my macros”?

**Comment by anaskaejdar** [comment]
Oh I have a question. Do you think it's generally ideal that combining-accents also have the dotted-circle glyph like the deadkey versions? If so, should they have may a different kind of dotted-line pattern to differentiate?

**Comment by Julow** [comment]
> Do you think it's generally ideal that combining-accents also have the dotted-circle glyph like the deadkey versions?

Dead keys can output combining diacritics (and it's done for some letters). I usually prefer to avoid adding different ways to do the same things but if people are used to typing the diacritics last, then I'm OK with adding combining diacritic keys.

These keys should not use the dotted circle to make things clearer. I like the dotted circle with a vertical line!
To make it a little less wide, what do you think of removing the right half of the circle and moving the line in its place ? Perhaps by making the line shorter.

> I thought that if you pressed Compose, and then pressed A, then you'd see B would be replaced with C, so then if you press Fn, C would become E. But now I'm seeing that Compose and FN don't stack in the same way I expected. Is there a way to get that same effect?

Modifiers are applied in a defined order on top of the original character that was on the keyboard and not in the order they are typed. Fn is applied before a pending compose sequence.
Applying the modifiers in the order they were pressed is a big change and might break layouts in way I don't anticipate at the moment.

In your scenario, `Compose+A+(Fn+B)` is different than `Compose+A+(the result of Fn+B)`. I think that Compose and Fn rules that work around this limitation will also be easier to type and remember.

I think making combinations that use both Compose and Fn is too much trouble. People will have to discover and then remember these.

**Comment by anaskaejdar** [comment]
Thank you for that! I'm in full agreement. I'll reworj some of these. It might not happen today or tomorrow because of work, but I'll ping you when it's ready. Some goes for #766 and #769

**Comment by anaskaejdar** [comment]
Okay, I went and made combining-accent versions of all the accent-modifier glyphs you already have in the special font. Maybe there aren't even combining-accent versions of some of these. I don't know, I just did all of them. Maybe some or many of them aren't useful, but let me know if the design is good. Then, I'll do the same for these special slavonic ones.

| Column A | Column B | Column C | Column D |
| --- | --- | --- | --- |
| ![5A combining](https://github.com/user-attachments/assets/d766269a-befe-46c3-950b-bf6889736ca7) | ![5B combining](https://github.com/user-attachments/assets/8d2b1dd5-5da1-4de3-ae6a-7e2b5239a9f3) | ![5C combining](https://github.com/user-attachments/assets/ee2b6f04-acfc-4e6a-9028-40a890c42dfc) | ![5D combining](https://github.com/user-attachments/assets/ffe075a3-3f94-4724-8742-200d8b17d1b7) |
| ![5E combining](https://github.com/user-attachments/assets/6dbdd41d-d24d-4918-b5e1-01b701d02ceb) | ![5F combining](https://github.com/user-attachments/assets/bec572ec-c485-4b6c-9d08-61c4e6ed7580) | ![50 combining](https://github.com/user-attachments/assets/211eb6b0-489e-48da-99bb-e2433e64001e) | ![51 combining](https://github.com/user-attachments/assets/b9a24b7a-8ac5-49e4-afd3-ce00fa344c10) |
| ![52 combining](https://github.com/user-attachments/assets/d58047f8-7115-4cec-a8f7-9a0ce14666e0) | ![53 combining](https://github.com/user-attachments/assets/5144b8a4-c259-499d-8bf2-bfb94d0dc08d) | ![54 combined](https://github.com/user-attachments/assets/3ae09e4e-0ac7-4f22-8471-7e2a150b78f9) | ![55 combining](https://github.com/user-attachments/assets/e9b05391-c533-446c-bcfb-377d5a682e22) |
| ![56 combining](https://github.com/user-attachments/assets/87e0a822-b1ab-469d-9878-0a3ab8c3b2dd) | ![57 combining](https://github.com/user-attachments/assets/e219add5-a838-4615-9a97-3bf1df8ccb78) | ![58 combining](https://github.com/user-attachments/assets/e66d0184-7c2a-46f5-b6e5-123bbf8c8ed2) | ![59 combining](https://github.com/user-attachments/assets/458a4040-ed13-4588-a86b-44819111bc60) |
| ![60 combining](https://github.com/user-attachments/assets/7d532792-132f-46ef-8702-5c28acaecf9f) | ![61 combining](https://github.com/user-attachments/assets/8074867c-00b9-46bd-ae38-b2dbbcbb6b7d) | ![62 combining](https://github.com/user-attachments/assets/f62afd83-a307-4c8e-8493-5d272b0136ca) | |

**Comment by anaskaejdar** [comment]
@Julow Boom! The Fn and Compose macros have all been updated! That goes for this ticket, and also for #766 and #769 : it's all been updated. They shouldn't conflict with anything anymore, and they should all be accessible now! Glyphs for the slavonic diacritics coming soon. I'll also similar glyphs for the arabic diacritics, because they display poorly on the keyboard the same way these slavonic ones do.

**Comment by Julow** [comment]
Sorry for the slow reply, I'm busy with life at the moment. I'm very grateful by the huge amount of work you're putting into the app :)

Thanks for the glyphs! I've added the combining diacritics to the app in 8a6dc34. I'll do the same for the arabic and slavic diacritics when you'll make them :)

There's a problem with compose sequences, backspace is not allowed in sequences. Also, most of sequences containing backspace results in a combining diacritic, in this case, I'd prefer an ASCII name rather than the combining character itself as this will be typed in layouts and in other places.

**Comment by Julow** [comment]
Thanks a lot for your help !

Added the diacritics in cd2932b and updated the compose sequences in c4a88e4. You can find a [debug build here](https://github.com/Julow/Unexpected-Keyboard/actions/runs/11192224311) to try it.

I'll close this issue to help see what's left to do.

**Comment by anaskaejdar** [comment]
@Julow I am so happy with this! I'm sorry to be that guy though... there's a couple typos, and I'll claim responsibility for at least one of them. I typed combining_porkrytie on one of the list items above, but it has an extra R... it should be combining_pokrytie

The other one is for combining_acute, which probably should have been combining_aigu, but in any case, something looks a bit off about it 😁:

![Screenshot_۲۰۲۴۱۰۰۵_۰۵۵۲۵۰_Unexpected Keyboard (Debug)_1](https://github.com/user-attachments/assets/4b46536c-79b4-48a2-ba30-53205be1d9d4)

and pokrytie:
![Screenshot_۲۰۲۴۱۰۰۵_۰۶۰۷۲۳_Unexpected Keyboard (Debug)_1](https://github.com/user-attachments/assets/5260a8a2-b3a8-40c5-896d-57ed96c38bd3)

**Comment by Julow** [comment]
Sorry for the slow response. This is fixed in 30fb50d
