### ISSUE TITLE
Compose and FN Combo Requests for Arabic-derived alphabets

### ISSUE THREAD

**Issue by anaskaejdar** [Julow/Unexpected-Keyboard#769]
There are hardly any compose combos or FN alternates yet set up for the
arabic-based letters, so I thought I'd put together some. I think this is a
strong start, but we'll probably want to add more to this list at some point.
But basically, I considered the alphabets for Arabic, Persian, Kurdish, and
Urdu, and the goal was to create combinations that would allow someone with just
one of those language's keyboards to type the letters which are present in the
other languages but absent in their own, and to type them without having to
enable an additional keyboard.

| Input (with Fn active) | Output |
| --- | --- |
| ل | ڵ |
| ُ | ۆ |
| ِ | ێ |
| ر | ڕ |
| ب | ٮ |
| ه | ھ |
| ث | پ |
| ز | ژ |
| غ | گ |
| ك | ک |
| ا | آ |
| ي | ی |
| ک | ك |
| ط | ظ |
| ص | ض |
| ی | ي |
| ق | غ |
| ع | ء |
| ح | ہ |
| ێ | ِ |
| ئ | ٔ |
| ؽ | ٛ |
| ۉ | ٛ |
| ڡ | ُ |
| ة | َ |
| إ | ٕ |
| ۆ | ٚ |
| ێ | ٚ |
| س | ـ |
| ف | ڤ |
| ن | ں  |
| [space] | zwnj (the letter called “halfspace” in UnexpectedKeyboard) |

| First Input (after pressing Compose) | Second Input | Output |
| --- | --- | --- |
| ل | ۷ | ڵ |
| ۷ | ل | ڵ |
| ۷ | ر | ڕ |
| ر | ۷ | ڕ |
| ف | و | ڡ |
| و | ف | ڡ |
| ه | و | ۆ |
| و | ۷ | ۆ |
| ۷ | و | ۆ |
| ه | ی | ێ |
| ه | ي | ێ |
| ۷ | ی | ێ |
| ی | ۷ | ێ |
| ۷ | ي | ێ |
| ي | ۷ | ێ |
| ق | و | ۊ |
| ا | ی | ؽ |
| ا | ي | ؽ |
| ی | ۸ | ؽ |
| ۸ | ی | ؽ |
| ي | ۸ | ؽ |
| ۸ | ي | ؽ |
| و | ۸ | ۉ |
| ۸ | و | ۉ |
| ا | و | ۉ |
| و | ۸ | ۉ |
| ۸ | و | ۉ |
| ه | [space] | ە |
| ه | ع | ۀ |
| ع | ه | ۀ |
| ج | ش | چ |
| غ | ک | گ |
| غ | ك | گ |
| ت | د | ط |
| س | ش | ص |
| د | ز | ذ |
| ی | ا | ى |
| ي | ا | ى |
| ه | ت | ة |
| ع | ی | ئ |
| ع | ي | ئ |
| ی | ع | ئ |
| ي | ع | ئ |
| ع | و | ؤ |
| و | ع | ؤ |
| ش | ت | ث |
| ت | ش | ث |
| ع | ا | إ |
| ا | ع | أ |
| ی | [space] | ے |
| ۷ | ۷ | arabic_combining_v |
| ۸ | ۸ | arabic_combining_inverted_v |
| ل | ل | arabic_combining_shaddah |
| ح | ح | arabic_combining_sukun |
| ه | ه | arabic_combining_fatha |
| و | و | arabic_combining_dammah |
| ی | ی | arabic_combining_kasra |
| ي | ي | arabic_combining_kasra |
| ع | ۸ | arabic_combining_hamza_above |
| ۸ | ع | arabic_combining_hamza_above |
| ع | ۷ | arabic_combining_hamza_below |
| ۷ | ع | arabic_combining_hamza_below |
| ا | ا | arabic_combining_alef_above |
| ا | ۷ | arabic_combining_alef_below |
| ۷ | ا | arabic_combining_alef_below |
| ه | ن | arabic_combining_fathatan |
| ی | ن | arabic_combining_kasratan |
| و | ن | arabic_combining_dammatan |
| ن | ه | arabic_combining_fathatan |
| ن | ی | arabic_combining_kasratan |
| ن | و | arabic_combining_dammatan |
| و | ث | ۋ |
| ن | ت | ٹ |
| ت | ن | ٹ |
| د | ت | ڈ |
| ت | ر | ڑ |
| ر | ت | ڑ |

| Diacritic names | combining character | graphemica link | glyph |
| --- | --- | --- | --- |
| arabic_combining_v | ٚ  | https://graphemica.com/065A | ![combining_v](https://github.com/user-attachments/assets/b378df10-2b3e-4c16-8fef-38837518f38c) |
| arabic_combining_inverted_v | ٛ  | https://graphemica.com/065B | ![combining_inverted_v](https://github.com/user-attachments/assets/a19271bb-b580-4091-85f6-9e70ed095358) |
| arabic_combining_shaddah |  ّ  | https://graphemica.com/0651 | ![combining_shaddah](https://github.com/user-attachments/assets/f073fa67-1723-41ee-8d99-ee551aea5328) |
| arabic_combining_sukun |  ْ  | https://graphemica.com/0652 | ![combining_sukun](https://github.com/user-attachments/assets/ed083c07-0613-4455-844d-f4be7814e5e2) |
| arabic_combining_fatha | َ  | https://graphemica.com/064E | ![combining_fatha](https://github.com/user-attachments/assets/6d3e4ab0-2e26-479b-95c9-9ccdb42447e9) |
| arabic_combining_dammah | ُ  | https://graphemica.com/064F | ![combining_dammah](https://github.com/user-attachments/assets/ea4f01fb-8f71-4b45-beef-9f62d4477019) |
| arabic_combining_kasra | ِ  | https://graphemica.com/0650 | ![combining_kasra](https://github.com/user-attachments/assets/8eedcc51-f17a-48f7-b9cb-d6149caaf834) |
| arabic_combining_hamza_above | ٔ | https://graphemica.com/0654 | ![combining_hamza_above](https://github.com/user-attachments/assets/17b849c8-1a89-4c4c-a821-e0636a1725dc) |
| arabic_combining_hamza_below | ٕ | https://graphemica.com/0655 | ![combining_hamza_below](https://github.com/user-attachments/assets/e6974a15-07c3-4cde-9c13-bb96bae55f0e) |
| arabic_combining_alef_above | ٰ  | https://graphemica.com/0670 | ![combining_alef_above](https://github.com/user-attachments/assets/21f5627f-719a-4e57-b1d4-099813cb2408) |
| arabic_combining_fathatan | ً  | https://graphemica.com/064B | ![combining_fathatan](https://github.com/user-attachments/assets/845761d8-bf09-46ec-a7e1-5354b89f910e) |
| arabic_combining_kasratan | ٍ  | https://graphemica.com/064D | ![combining_kasratan](https://github.com/user-attachments/assets/e6bc9d49-8029-471c-a56f-2a417959aebb) |
| arabic_combining_dammatan | ٌ  | https://graphemica.com/064C | ![combining_dammatan](https://github.com/user-attachments/assets/9b339e0f-906a-4b1c-b92b-f4044c35ab32) |

**Comment by anaskaejdar** [comment]
The glyphs have been made, @Julow ! Except there's a couple things to know about them: Firstly, I had to change the font for those, because Roboto had improper shapes and even missing shapes for some of them. We used Noto Arabic. Secondly, these glyphs feel cramped. How important is it that I keep the symbol within bounds? Would it be okay to scale down the half-circle to make more room for the diacritic?

**Comment by anaskaejdar** [comment]
Here's the same table with less cramped versions of the glyphs, assuming that it's okay for the shapes to poke through the ceiling like this. When I was working on combining forms of the existing glyphs, I noticed that some of them poked through the ceiling a bit, so I thought that might be fine. If it is fine, let's try these:

| Diacritic names | combining character | graphemica link | glyph |
| --- | --- | --- | --- |
| arabic_combining_v | ٚ  | https://graphemica.com/065A | ![combining_v](https://github.com/user-attachments/assets/72b4c4a1-b70f-4402-94f9-fe915d23b5f4) |
| arabic_combining_inverted_v | ٛ  | https://graphemica.com/065B | ![combining_inverted_v](https://github.com/user-attachments/assets/5934e559-4859-4c0f-bfac-74abccf1f22f) |
| arabic_combining_shaddah |  ّ  | https://graphemica.com/0651 | ![combining_shaddah](https://github.com/user-attachments/assets/adc652da-cf40-45eb-8bc3-308b7dff3026) |
| arabic_combining_sukun |  ْ  | https://graphemica.com/0652 | ![combining_sukun](https://github.com/user-attachments/assets/d1723f1e-830a-424e-9415-1b8004d23a88) |
| arabic_combining_fatha | َ  | https://graphemica.com/064E | ![combining_fatha](https://github.com/user-attachments/assets/4b34082f-d767-4fad-8a22-cc9a9216a4fd) |
| arabic_combining_dammah | ُ  | https://graphemica.com/064F | ![combining_dammah](https://github.com/user-attachments/assets/4082527f-cc74-49f6-ae71-c5709226b1a4) |
| arabic_combining_kasra | ِ  | https://graphemica.com/0650 | ![combining_kasra](https://github.com/user-attachments/assets/16658313-f62d-4be5-9d13-9a8f55dcac4b) |
| arabic_combining_hamza_above | ٔ | https://graphemica.com/0654 | ![combining_hamza_above](https://github.com/user-attachments/assets/f821c89e-ca2a-4131-a884-37e1b9748515) |
| arabic_combining_hamza_below | ٕ | https://graphemica.com/0655 | ![combining_hamza_below](https://github.com/user-attachments/assets/a4bf8f10-1a4e-4cc5-8b52-705592982a59) |
| arabic_combining_alef_above | ٰ  | https://graphemica.com/0670 | ![combining_alef_above](https://github.com/user-attachments/assets/e71d967a-dbce-4e14-a1c3-d65f12ecfc75) |
| arabic_combining_fathatan | ً  | https://graphemica.com/064B | ![combining_fathatan](https://github.com/user-attachments/assets/66bfb344-1d17-49b8-a7a3-f5b534d5cd67) |
| arabic_combining_kasratan | ٍ  | https://graphemica.com/064D | ![combining_kasratan](https://github.com/user-attachments/assets/ed08455b-819a-41e4-9c47-64b41643b786) |
| arabic_combining_dammatan | ٌ  | https://graphemica.com/064C | ![combining_dammatan](https://github.com/user-attachments/assets/6d2d103e-0516-4fe2-bd83-1b85b1649254) |

**Comment by anaskaejdar** [comment]
Here's the same table once again, but this time I shrank the half-circle thing to make more room.

| Diacritic names | combining character | graphemica link | glyph |
| --- | --- | --- | --- |
| arabic_combining_v | ٚ  | https://graphemica.com/065A | ![combining_v](https://github.com/user-attachments/assets/ce5d32e9-066b-4e33-9701-cbbb1a9ef6c0) |
| arabic_combining_inverted_v | ٛ  | https://graphemica.com/065B | ![combining_inverted_v](https://github.com/user-attachments/assets/c530da65-feff-4028-80be-b77c1281a1e1) |
| arabic_combining_shaddah |  ّ  | https://graphemica.com/0651 | ![combining_shaddah](https://github.com/user-attachments/assets/69a23b27-0d0e-468f-a1dc-278446e1ef63) |
| arabic_combining_sukun |  ْ  | https://graphemica.com/0652 | ![combining_sukun](https://github.com/user-attachments/assets/ded01e45-4863-4e01-9943-346831f761d7) |
| arabic_combining_fatha | َ  | https://graphemica.com/064E | ![combining_fatha](https://github.com/user-attachments/assets/26037ec0-a8bc-4c87-a657-c4fe2f18d0bf) |
| arabic_combining_dammah | ُ  | https://graphemica.com/064F | ![combining_dammah](https://github.com/user-attachments/assets/bb672b1e-6df2-4d5a-af78-91ce179666a3) |
| arabic_combining_kasra | ِ  | https://graphemica.com/0650 | ![combining_kasra](https://github.com/user-attachments/assets/f5e7340a-1008-48ff-a7d6-7d7910577cee) |
| arabic_combining_hamza_above | ٔ | https://graphemica.com/0654 | ![combining_hamza_above](https://github.com/user-attachments/assets/83942362-f8be-4aa7-939a-f5cba799dee4) |
| arabic_combining_hamza_below | ٕ | https://graphemica.com/0655 | ![combining_hamza_below](https://github.com/user-attachments/assets/65e375c5-cae3-4a89-a00d-3c3c3413712c) |
| arabic_combining_alef_above | ٰ  | https://graphemica.com/0670 | ![combining_alef_above](https://github.com/user-attachments/assets/d0388683-30d3-441c-8042-274340bba56d) |
| arabic_combining_fathatan | ً  | https://graphemica.com/064B | ![combining_fathatan](https://github.com/user-attachments/assets/6e886cdc-890b-4cc3-ac93-1e68852511af) |
| arabic_combining_kasratan | ٍ  | https://graphemica.com/064D | ![combining_kasratan](https://github.com/user-attachments/assets/05c94d6e-1ced-4bb3-ad9b-019e81cde4dd) |
| arabic_combining_dammatan | ٌ  | https://graphemica.com/064C | ![combining_dammatan](https://github.com/user-attachments/assets/60ac6af4-9114-4380-b80a-376115784c33) |

**Comment by anaskaejdar** [comment]
I added another symbol: the small-alef diacritic which goes below the letter rather than above.

| ---- | ---- | ----- | ----- |
| ---- | ---- | ----- | ----- |
| arabic_combining_alef_below | ٖ | https://graphemica.com/0656 | ![combining_alef_below](https://github.com/user-attachments/assets/2eb22cf7-5ed0-450a-92f7-40dd9169ff2b) |

**Comment by Julow** [comment]
Sorry for the slow reply. I've added all of that in https://github.com/Julow/Unexpected-Keyboard/pull/807.
Can you have a look at it and check whether everything works fine ? The debug build is at the end of [this page](https://github.com/Julow/Unexpected-Keyboard/actions/runs/11986915241?pr=807).

**Comment by Julow** [comment]
The only problem is `zwnj`, which cannot be bound to `Fn+space` as that's already taken for `nbsp`. Do you have an other place to put it ?

**Comment by anaskaejdar** [comment]
Wow, Jules! I'll keep toying with it, but my initial impression is just… Chef's kiss, my friend🤩! This is incredible. It's so powerful, without being cluttered

**Comment by anaskaejdar** [comment]
As for Fn+space, I apologize for that oversight. It could just go on Fn+: in that case. Or alternatively, Fn+، which is just the arabic version of the comma.

**Comment by anaskaejdar** [comment]
Ok I've toyed some and found a couple of things. So I didn't realize, but ۷۸

**Comment by anaskaejdar** [comment]
Ok I've toyed some and found a couple of things. So I didn't realize, but the persian numbers, ۷ and ۸, are different codepoints than the arabic counterparts, ٧ and ٨ even though they pretty much look identical. So for keyboard layouts that use the arabic versions of the numbers, let's add the following which are essentially duplicated from what we have already, but with the persian codepoint swapped for the arabic one:

| First Input (after pressing Compose) | Second Input | Output |
| --- | --- | --- |
| ل | ٧ | ڵ |
| ٧ | ل | ڵ |
| ٧ | ر | ڕ |
| ر | ٧ | ڕ |
| و | ٧ | ۆ |
| ٧ | و | ۆ |
| ٧ | ی | ێ |
| ی | ٧ | ێ |
| ٧ | ي | ێ |
| ي | ٧ | ێ |
| ی | ٨ | ؽ |
| ٨ | ی | ؽ |
| ي | ٨ | ؽ |
| ٨ | ي | ؽ |
| و | ٨ | ۉ |
| ٨ | و | ۉ |
| و | ٨ | ۉ |
| ٨ | و | ۉ |
| ٧ | ٧ | arabic_combining_v |
| ٨ | ٨ | arabic_combining_inverted_v |
| ع | ٨ | arabic_combining_hamza_above |
| ٨ | ع | arabic_combining_hamza_above |
| ع | ٧ | arabic_combining_hamza_below |
| ٧ | ع | arabic_combining_hamza_below |
| ا | ا | arabic_combining_alef_above |
| ا | ٧ | arabic_combining_alef_below |
| ٧ | ا | arabic_combining_alef_below |

Then, since arabic and persian have slightly different versions of the same letter— ي and ی, respectively — I tried to make sure each combination that used this letter was duplicated so that it would work with either version of the letter. With the following three, I didn't realize I neglected to do this, so let's also add:

| First Input (after pressing Compose) | Second Input | Output |
| --- | --- | --- |
| ي | ن | arabic_combining_kasratan |
| ن | ي | arabic_combining_kasratan |
| ي | [space] | ے |

---

And then, with the FN variants, I noticed this discrepancy in behaviour. Sorry, by the way, that I didn't replace the diacritical marks with their named versions up in the table in the OP. Anyway, the OP table had these:

| Input (with Fn active) | Output |
| --- | --- |
| arabic_combining_kasra | ێ |
| ێ | arabic_combining_kasra |

whereas in this build it behaves rather like this:

| Input (with Fn active) | Output |
| --- | --- |
| arabic_combining_kasra | *it just stays as kasra* |
| ێ | arabic_combining_v *(v instead of kasra)* |

**Comment by Julow** [comment]
Thanks for taking a look! I have done the fixes you listed, here's the new debug build: https://github.com/Julow/Unexpected-Keyboard/actions/runs/11990917674?pr=807

> As for Fn+space, I apologize for that oversight. It could just go on Fn+: in that case. Or alternatively, Fn+، which is just the arabic version of the comma.

I went for `Fn+:` because `:` is currently present on more arabic layouts than `،`. But I feel that the placement is not right.
It's also possible to set `Fn+space` for arabic layouts only, by adding a custom `<modmap>` into every arabic layouts.
