### ISSUE TITLE
Lable size of secondary symbols

### ISSUE THREAD

**Issue by ChiefMikeK** [Julow/Unexpected-Keyboard#78]
### Maybe increase the contrast and use standard or web safe colors ` ¯\_(ツ)_/¯ `   
     res/values/themes.xml

```
<style name="Dark">
30 ~ <item name="colorLabel">#FFFFFF</item>
33 ~ <item name="colorSubLabel">#A0A0A0</item>  
    #9e9e9e  

<style name="Light">
46 ~ <item name="colorLabel">#000000</item>
49 ~ <item name="colorSubLabel">#5e5e5e</item>  
    #616161  

<style name="Black">
62 ~ <item name="colorLabel">#eeeeee</item>
65 ~ <item name="colorSubLabel">#bbbbbb</item>  
    #eeeeee

```

**Comment by ChiefMikeK** [comment]
The lable size of the secondary symbols are too small, especially (){} ., and should be adjusted via a seperate settings
![Screenshot1](https://user-images.githubusercontent.com/20070053/155745556-35ab887e-9a86-4133-b448-e51f8a542b5f.png)
![Screenshot_2](https://user-images.githubusercontent.com/20070053/155745591-5537d52c-0d50-48c0-9d38-e3b7f174f9ca.png)

**Comment by Julow** [comment]
I definitely agree ! The label sizes need to be reworked a bit and I'll improve the color too. Thanks for the suggestions.

**Comment by Julow** [comment]
I've made improvements to the way the label size was computed and increased the contrast slightly (23685dd, 1451857, f6d4554). Here's how the keyboard looks now:

![screen](https://user-images.githubusercontent.com/2310568/155886556-81c9b442-67b5-413a-bace-47f4ef10b827.png)
