### ISSUE TITLE
Undo and Redo not working on termux and some other

### ISSUE THREAD

**Issue by zuwf** [Julow/Unexpected-Keyboard#786]
The undo and redo function does not work in some apps like termux and obsidian

**Comment by Julow** [comment]
That's correct, it is the application's fault. The keyboard just send the "undo" or "redo" code to the application, which is free to ignore it.

**Comment by zuwf** [comment]
I tried futo keybloard recently, there the undo works with the apps which are not supported by unexpected keyboard

**Comment by Spike-from-NH** [comment]
Do you have a way to find out what codes Futo is sending to the apps?
