### ISSUE TITLE
Problem with numeric row

### ISSUE THREAD

**Issue by mariush444** [Julow/Unexpected-Keyboard#787]
I have my own definition of keyboard but when I set option to show numbers row then the definition is autonaticaly changed for some keys.

How to solve it?
![IMG_20241020_204848](https://github.com/user-attachments/assets/d2d11eb6-0f33-4caf-b9d1-c1e57c2b866d)

**Comment by Julow** [comment]
Thanks for the issue, should be fixed by 3c30e82. You can find a debug build at the bottom of [this page](https://github.com/Julow/Unexpected-Keyboard/actions/runs/11539566578)
