### ISSUE TITLE
[Bug] consistently crashing on Firefox/Fennec/Mull

### ISSUE THREAD

**Issue by panty-sniffer** [Julow/Unexpected-Keyboard#789]
**Steps to reproduce:**
1. Open Firefox on your possibly shitty android phone (I am using Pixel 6a, running GrapheneOS).
2. Copy any **URL** (can't be any other text) so your clipboard isn't blank. Also make sure clipboard suggestion is enabled (settings > search > scroll down to "Address bar preferences" > toggle to enable "Show clipboard suggestions") on the Firefox settings (is default).
3. Click on address bar and press "Fill link from clipboard". It immediately unexpectedly crash unexpected keyboard.

| Screenshot1 | Screenshot2 |
| - | - |
| ![your](https://github.com/user-attachments/assets/4aaa6944-f50e-4b29-bf32-0b38997e80d6) | ![mom](https://github.com/user-attachments/assets/01ad7270-b722-4f60-9156-f433cf5be1bf) |

**Note**: while I am using [Mull](https://divestos.org/pages/our_apps#mull) here, this problem is reproducible with [Fennec](https://f-droid.org/packages/org.mozilla.fennec_fdroid/) and possibly Mozilla Firefox (installed from ~~google~~ E-corp's play store) as well.

**Comment by Julow** [comment]
Thanks for the issue! This is possibly fixed by 4d0598a, can you try with the latest debug build found at the bottom of [this page](https://github.com/Julow/Unexpected-Keyboard/actions/runs/11526493969) ?

**Comment by panty-sniffer** [comment]
@Julow yes the debug build doesn't crash from my end. thank you.
