### ISSUE TITLE
Inconsistent symbols across different devices

### ISSUE THREAD

**Issue by sdrapha** [Julow/Unexpected-Keyboard#79]
Different devices have different system fonts. So they don't always render the symbols as expected.
For example, in my Galaxy Tab S6:
![image](https://user-images.githubusercontent.com/25059996/155744868-53bd771a-a0fd-443d-948f-ea6dcfd947b2.png)

So what is supposed to be a Cog symbol for the settings, renders as a brightness? icon, the emoji key also doesnt't render as expected

I already made changes to that and I will follow up with a pull request

**Comment by Julow** [comment]
#80 is merged so I close this. The issue remains for some other symbols https://github.com/Julow/Unexpected-Keyboard/issues/82
