### ISSUE TITLE
Unable to select unexpected keyboard 

### ISSUE THREAD

**Issue by ArekkusuMagni** [Julow/Unexpected-Keyboard#790]
I am unable to to select unexpected keyboard as a option. I uninstalled and reinstalled to see if that would remedy the issue. The device is a factory unlocked galaxy S23 on Android 14, One UI version 6.1

![Screenshot_20241023_075846_Unexpected Keyboard](https://github.com/user-attachments/assets/c67bbb46-5836-4af2-b72e-49f3a468dc52)
![Screenshot_20241023_075900_Settings](https://github.com/user-attachments/assets/27c09379-0c5f-4ad0-874e-1369ad787d97)

**Comment by Julow** [comment]
Unexpected Keyboard is the 5th in the input method chooser.
