### ISSUE TITLE
 keys are lag while touching

### ISSUE THREAD

**Issue by OxRachid** [Julow/Unexpected-Keyboard#791]
hello unexpected-keyboard team ...
my issues is sometimes while touching keys they lag for certain seconds, its like no respond ...
i need to click many times on keys till can be responde..
this issue not always happen but just sometimes ..
i hope u to solve this problem to make it flexible and respond faster as possible as it can ...

**Comment by Julow** [comment]
With what application do you observe this lag ?

**Comment by OxRachid** [comment]
All I work on is chatgpt inside the browser, neovim editor inside termux and some social media apps...
I'm not sure where exactly this happened, but at the same time it might be because my finger lost its sense of touch due to too much keyboard pressing hhhh
