### ISSUE TITLE
Change display of (home, end) keys symbol

### ISSUE THREAD

**Issue by OxRachid** [Julow/Unexpected-Keyboard#792]
i costomize a row that include ( up, down, left, right, home, end) and all of them has similr look witch made me confused and not conftubale..
i hope u to change how the ( home , end ) display in layout , as long as there is an arrows for (up,down,left,right) , i think no need to make home and end to look similer to them  ..
instead make home and end to be displayed just with their names to be in diffrent look ...

**Comment by Julow** [comment]
`home` and `end` are also `Fn+left` and `Fn+right`, do you need them on your layout ?
These keys apparently have a standard symbol that we could use, that look different from the arrow keys https://en.wikipedia.org/wiki/Home_key https://en.wikipedia.org/wiki/End_key

**Comment by OxRachid** [comment]
after include them in my layout the symbols are looked like the arrows with '|' at the end. 
my desire is instead of displaying these symbols i want them to be displayed like how they look in laptop's keyboard or termux's extra keys ...

**Comment by OxRachid** [comment]
i want them like this
![IMG_20241028_102905](https://github.com/user-attachments/assets/14fa8f86-d7c5-49f3-828f-90f7d1aedd3d)

**Comment by Julow** [comment]
Using "HOME" and "END" doesn't work because the labels are too long and collide. I opted for the standard symbols in 4640857. You can find a debug APK to try it here: https://github.com/Julow/Unexpected-Keyboard/actions/runs/11869628264

**Comment by OxRachid** [comment]
I like this new standard symbols in the debug apk you mentioned , can u add it to the stable apk ?

**Comment by Julow** [comment]
I hope to release at the end of the month.

**Comment by OxRachid** [comment]
Ok and best of luck to you 😍
I want to talk about emoji too
When i try to click on some emoji at the first time it didn't work until i switch to another emoji in different  emoji categorie and returned to it then it work ...
Try to fix this as well..
And please try to give us the ability to customize the place where to put clipboard place ..
Thank you in advance
