### ISSUE TITLE
Outdated links

### ISSUE THREAD

**Issue by GitAlasGo** [Julow/Unexpected-Keyboard#793]
The calculator++ link you provided from your **README.md** is a outdated link.

The link should be https://git.bubu1.eu/Bubu/android-calculatorpp

Steps to find this new link

Step 1: Click the calculator++ link from your **README.md**

Step 2. From the outdated calculator++ github, click on **GET IT ON F-DROID**

Step 3: Click on the **Source code** button

Step 4: Now you are on [https://git.bubu1.eu/](https://git.bubu1.eu/Bubu/android-calculatorpp)

**Comment by Julow** [comment]
Thanks! It also appears to be maintained. Fixed in 70365b4
