### ISSUE TITLE
"key repeat on long press" not working for emojis

### ISSUE THREAD

**Issue by lrvideckis** [Julow/Unexpected-Keyboard#794]

**Comment by Julow** [comment]
For what purpose do you need this ? I'm planning to remove the "repeat on long press" feature in the future and I'd prefer not to have this if avoidable.

**Comment by Spike-from-NH** [comment]
Yes; as we discussed once, there are very few characters you want to auto-repeat. Spaces, hyphens, underlines, periods; not clown faces or national flags. Not that you can't get as many as you want by manual repetition or copypaste.

**Comment by lrvideckis** [comment]
well I was going to use it to send a bunch of smiley faces in a text, I don't need it tho. I'm okay with key repeat being removed
