### ISSUE TITLE
Scroll Lock?

### ISSUE THREAD

**Issue by DocJr90** [Julow/Unexpected-Keyboard#796]
I've searched the issues and scoured the app itself, so if I missed this, I may just be obtuse: is it possible - and if so - is there an easy way to send the "scroll lock" key?

My next stop will be to look at custom layouts and/or the code itself for any indication if it is possible, but I thought I'd ask first.

**Comment by Spike-from-NH** [comment]
Currently, [Possible-key-values.md](https://github.com/Julow/Unexpected-Keyboard/blob/master/doc/Possible-key-values.md) doesn't contain the word "scroll", suggesting there is not yet any way to specify this in a custom layout. It probably should be added.

**Comment by DocJr90** [comment]
Thank you. I did look there too.

**Comment by ChiefMikeK** [comment]
ref; 
- https://developer.android.com/reference/android/view/KeyEvent#KEYCODE_SCROLL_LOCK

**Comment by DocJr90** [comment]
Has anyone made a modification to the code and pushed it into an APK?

Just perusing the code it superficially appears that you could add a case in KeyValue.java.getKeyByName for KeyEvent.KEYCODE_SCROLL_LOCK

Not sure how it would be invoked afterwards though. Possibly through the Compose function?

**Comment by DocJr90** [comment]
Adding it to KeyValue.java.getKeyByName worked. It is then invoked by specifying the corresponding key text. I will make a pull request.

**Comment by DocJr90** [comment]
Made pull request.

**Comment by Julow** [comment]
PR is <https://github.com/Julow/Unexpected-Keyboard/pull/800>. Thanks!
