### ISSUE TITLE
Material You theme isn't properly colored?

### ISSUE THREAD

**Issue by MarGar12** [Julow/Unexpected-Keyboard#797]
Basically the Material You theme isn't properly colored unlike GBoard's Dynamic Color theme (Sorry I don't know how to explain this properly >.< The images might give you an idea on what I mean)

GBoard:
![Screenshot_20241105-115625_Material Files](https://github.com/user-attachments/assets/eb055f6e-fda5-4c9d-8d93-81b2b6016fa1)

Unexpected Keyboard:
![Screenshot_20241105-115619_Material Files](https://github.com/user-attachments/assets/8f511591-7f76-48bd-8696-efc6613644da)

**Comment by 0skar2** [comment]
Yeah, can confirm, the material themed keyboard is too vivid for me as well.

**Comment by GitAlasGo** [comment]
How did you get the keyboard to look purple?

**Comment by MarGar12** [comment]
> How did you get the keyboard to look purple?

using the Monet Theme (Dark) but the colors isn't really accurate

**Comment by Julow** [comment]
https://github.com/Julow/Unexpected-Keyboard/pull/803 looks reasonable on my device, can you try the debug build at the end of [this page](https://github.com/Julow/Unexpected-Keyboard/actions/runs/11874071920) ?

**Comment by 0skar2** [comment]
# Unexpected:
![Screenshot_20241117-005935](https://github.com/user-attachments/assets/2cf06224-92be-48aa-ae1f-85b44622c82b)
# Gboard:
![Screenshot_20241117-005920](https://github.com/user-attachments/assets/d6b2ef6c-f014-4e87-9a38-3870bae7a7eb)

(Monet System)

**Comment by MarGar12** [comment]
You nailed the background color! The key colors are still a little off though

GBoard:
![Screenshot_20241117-092727.png](https://github.com/user-attachments/assets/af9a2d57-e265-4f79-9931-80374b5afc7b)

Unexpected Keyboard:
![Screenshot_20241117-092721.png](https://github.com/user-attachments/assets/19e58825-69e5-48ea-bde5-c0bd9683833e)

Also sliding in some suggestions, maybe add keyboard sound and perhaps also inline support stuff like this for password managers? I think it'd be cool since its also meant for daily use :3

![Screenshot_20241117-093626.png](https://github.com/user-attachments/assets/48bf9fba-80ea-4c58-abf7-fce4aa007794)

**Comment by Julow** [comment]
Is the keyboard too vivid like this ? I'm afraid the keyboard will look very bland if all the keys are gray.

Coloring some keys differently looks very nice but that's not on my priority list. Anyone interested on improving the rendering of the keyboard ? It's done in [this method](https://github.com/Julow/Unexpected-Keyboard/blob/master/srcs/juloo.keyboard2/Keyboard2View.java#L309) and I'm happy to give pointers.
