### ISSUE TITLE
Transparency mode

### ISSUE THREAD

**Issue by ghost** [Julow/Unexpected-Keyboard#8]
Very excited to try this. Would be nice to see the source code moved to Codeberg,  F-Droid showcased front and center and a transparency mode added if not already available. Here's how to accomplish transparency: https://github.com/klausw/hackerskeyboard

**Comment by Julow** [comment]
Hi! I don't plan to moving the source code. I'll update the screenshots for the next release (in a few days).

A transparency mode could be interesting !

**Comment by Sidahmed-ben** [comment]
hello @Julow  , i want to contribute on this project, do you agree that i add this feature . Thank you 😉

**Comment by Julow** [comment]
@Sidahmed-ben That would be awesome, yes!

**Comment by Vaisakhkm2625** [comment]
> hello @Julow  , i want to contribute on this project, do you agree that i add this feature . Thank you 😉

are yoi workong on it?

**Comment by Sidahmed-ben** [comment]
> > hello @Julow  , i want to contribute on this project, do you agree that i add this feature . Thank you 😉
> 
> are you working on it? :)

No i'm not working for it 👍

**Comment by Julow** [comment]
Implemented in https://github.com/Julow/Unexpected-Keyboard/pull/252 by @ChasmSolacer
