### ISSUE TITLE
add keys to go to beginning/end of input box?

### ISSUE THREAD

**Issue by lrvideckis** [Julow/Unexpected-Keyboard#804]
the functionality i want is to be able to (after placing the cursor somewhere in the middle of a lot of text) to then delete all text (in the input box) after/before the cursor

example use case: my friend sends me a text containing an address (but with a ton of other stuff), on whatsapp. my goal is to copy just the address. but whatsapp only allows coping entire texts so i do that. then i paste somewhere else (like maybe google maps) but i only want to search for the address

so i tap to place the cursor right after the address. and now i want to delete all text afterwards

**Comment by lrvideckis** [comment]
I tried the home/end keys (like hit caps lock first, then end, then backspace), but they only go to the beginning/end of the current line, not the entire text box

**Comment by lrvideckis** [comment]
currently the way i do this is:

- tap to place cursor in the middle of some text
- caps lock
- hold the down arrow until it highlights everything up to the end
- backspace

**Comment by GitAlasGo** [comment]
> does ctrl+shift+end work for you?

Where is **Shift** i only see **Meta**

**Comment by lrvideckis** [comment]
> does ctrl+shift+end work for you?

oh it does, thanks!
