### ISSUE TITLE
Accent keys are poorly rendered

### ISSUE THREAD

**Issue by ChiefMikeK** [Julow/Unexpected-Keyboard#82]
several of the accent keys do not align properly with the dotted circle and overlap such as this;  
![COMBINING MACRON](https://user-images.githubusercontent.com/20070053/155773397-d89fcaa8-c69f-43e1-9fa8-79518c14d980.png)  

and these other ones:  

> "accent_caron", "◌̌"  
> "accent_cedille", "◌̧"  
> "accent_circonflexe", "◌̂"  
> "accent_trema", "◌̈"  
> "accent_ring", "◌̊"  
> "superscript", "◌͆" maybe change it to"sup"  
> "subscript", "◌̺" maybe change it to "sub"  
> like as per how "ordinal", "ºʳᵈ" is done?

discussed/mentioned in pr #80

**Comment by Julow** [comment]
Having better fonts for accents and other specific keys is planned. I'm searching for a better way to represent the glyphs, editing the font file with fontforge isn't ideal.
