### ISSUE TITLE
Pls help me with Kannada kb layout

### ISSUE THREAD

**Issue by srikanban** [Julow/Unexpected-Keyboard#820]
The devanagari (hindi) - 2 layout is very good. Is there a kannada layout available?

Thank you for this wonderful keyboard btw🙏🏼

**Comment by Julow** [comment]
There are two layouts for devanagari (देवनागरी (हिंदी)). Here's how they are defined: https://raw.githubusercontent.com/Julow/Unexpected-Keyboard/refs/heads/master/srcs/layouts/deva_inscript.xml and https://raw.githubusercontent.com/Julow/Unexpected-Keyboard/refs/heads/master/srcs/layouts/deva_alt.xml

Could you take one as a starting point and make a Kannada layout ? Paste it in a comment on this issue and I'll take care of adding it to the app.

**Comment by Julow** [comment]
You can paste your layout into the "Custom layout" option at the end of the layout list in the settings to see how it looks and edit it from there.

**Comment by srikanban** [comment]
Here is the one I tried, can be improved

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<keyboard name="ಕನ್ನಡ" script="kannada">
  <row>
    <key key0="ಕ" key1="ಖ" key2="ಘ" key3="ಙ" key4="ಗ"/>
    <key key0="ಚ" key1="ಛ" key2="ಝ" key3="ಞ" key4="ಜ"/>
    <key key0="ಟ" key1="ಠ" key2="ಢ" key3="ಣ" key4="ಡ"/>
    <key key0="ತ" key1="ಥ" key2="ಧ" key3="ನ" key4="ದ"/>
    <key key0="ಪ" key1="ಫ" key2="ಭ" key3="ಮ" key4="ಬ"/>
    <key key0="ಯ" key1="ರ" key2="ವ" key3="ಱ" key4="ಲ" key8="ೞ"/>
    <key key0="ಶ" key1="ಷ" key2="ಹ" key3="ಳ" key4="ಸ" key8="※"/>
  </row>
  <row>
    <key key0="ಾ" key1="ಅ" key2="ಆ"/>
    <key key0="◌ಿ" key1="ಇ" key2="ಈ" key4="ೀ"/>
    <key key0="ು" key1="ಉ" key2="ಊ" key4="ೂ"/>
    <key key0="ೃ" key1="ಋ" key2="ೠ" key3="ಌ" key4="ೄ" key5="ೡ" key6="ೣ" key8="ೢ"/>
    <key key0="ೆ" key1="ಎ" key2="ಏ" key4="ೇ" key6="ೕ"/>
    <key key0="ೈ" key1="ಐ" key2="ಒ" key4="ೊ" key5="ೖ"/>
    <key key0="ೋ" key1="ಓ" key2="ಔ" key4="ೌ"/>
  </row>
  <row>
    <key key0="್" key1="\@" key2="&amp;" key8="಼"/>
    <key key0="ಂ" key1="₹" key2="卐" key3="!" key4="\?" key7="ॐ"/>
    <key key0="ಃ" key5="ೲ" key6="ೱ" key7="ಽ"/>
    <key key0="।" key1="'" key2="&quot;" key3="." key4="," key5="∪" key6="॥" key8="॰"/>
    <key key0="೦" key3="-" key4="॒" key5=":" key6=";" key8="•"/>
    <key key0="೫" key1="೧" key2="೩" key3="೭" key4="೯" key5="೪" key6="೬" key7="೨" key8="೮"/>
    <key key0="backspace" key2="delete"/>
  </row>
</keyboard>
```

**Comment by srikanban** [comment]
Looks noisy, but working perfectly well

**Comment by Julow** [comment]
Looks nice :) I love the number key. I added it in baa16d7
Don't hesitate to make edits in the future, it's here: https://github.com/Julow/Unexpected-Keyboard/blob/master/srcs/layouts/kann_kannada.xml
You can find a debug build at the end of this page: https://github.com/Julow/Unexpected-Keyboard/actions/runs/12216267397

**Comment by srikanban** [comment]
> Looks nice :) I love the number key. I added it in https://github.com/Julow/Unexpected-Keyboard/commit/baa16d742baea0496b67ac6ab125a3ee163e15a4

Thank you

>Don't hesitate to make edits in the future, it's here: https://github.com/Julow/Unexpected-Keyboard/blob/master/srcs/layouts/kann_kannada.xml

Will do

>You can find a debug build at the end of this page: https://github.com/Julow/Unexpected-Keyboard/actions/runs/12216267397

Tested it, works good
