### ISSUE TITLE
Max allowed char label size still too small for big screens

### ISSUE THREAD

**Issue by sdrapha** [Julow/Unexpected-Keyboard#83]
In my tablets this keyboard doesn't scale up well for higher resolutions, this screenshot is taken already using the max allowed char label size of 1.2. It's still small.

<img src=https://user-images.githubusercontent.com/25059996/155810309-f482b2c9-dfe0-4129-9660-121440e763f7.png height=800px>

I already done some changes and will follow up with PR.

I noticed issue #78 that may ride along with this one, but the request there is not exactly the same from this issue here.

**Comment by Julow** [comment]
The label size is now relative to the height of the keyboard (23685dd) and should look right by default (when the label size setting is set to `1`).
