### ISSUE TITLE
[Feature Request] Config to disable the default mappings for modifiers

### ISSUE THREAD

**Issue by amihsekai** [Julow/Unexpected-Keyboard#831]
To facilitate on a granular overhaul.

**Comment by Julow** [comment]
You are talking of disabling the default mapping of Shift and Fn modifiers when using a custom layout that defines a `<modmap>` ? Can you describe your exact use case ?

**Comment by amihsekai** [comment]
It's because I'm having an unexpected behavior.
My config file has the following line in modmap:

<shift a="," b="&lt;"/>

It follows it's premise. Whenever I press shift, the , switches to <
However, when I press Ctrl together, the < goes back to , (I guess that's intended by design).
Even after setting the following line, it still behaves the same way:

<ctrl a="&lt;" b="&lt;"/>

**Comment by Julow** [comment]
That's unfortunate but the reason is that Ctrl is applied before Shift. Ctrl+, makes the "," key from a physical keyboard and the shift modmap doesn't affect this one. That cannot be fixed easily as Ctrl+Shift+, is a valid combination and is useful for Termux users.

**Comment by Julow** [comment]
Sorry but this request is technically too hard to do so I'll close. Thanks for opening the issue!
