### ISSUE TITLE
Shift modifier key not working in new layout

### ISSUE THREAD

**Issue by npnpatidar** [Julow/Unexpected-Keyboard#836]
I am trying to add a new Hindi phonetic layout.  When I click on shift key, characters are not changing. Could you please help me debug it ? 

deva_phonetic_in.xml

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<keyboard name="हिन्दी फोनेटिक - Hindi Phonetic" script="devanagari">
  <row>
    <key key0="ट" key1="`" key2="1" key3="!" key4="esc"/>
    <key key0="ड" key1="~" key2="2" key3="\@" key4="\#"/>
    <key key0="े" key1="ए" key2="3" key3="$" />
    <key key0="र" key1="ऋ" key2="4" key3="ृ" key4="₹"/>
    <key key0="त" key1="ट" key2="5" key3="%"/>
    <key key0="य" key2="6" key3="^"/>
    <key key0="ु" key1="उ" key2="7" key3="&amp;"/>
    <key key0="ि" key1="इ" key2="8" key3="*" key4="ँ"/>
    <key key0="ो" key1="ओ" key2="9" key3="(" key4=")"/>
    <key key0="प" key1="०" key2="0" key4="॒"/>
  </row>
  <row>
    <key shift="0.5" key0="ा" key1="tab" key3="अ"/>
    <key key0="स" key1="“" key4="”"/>
    <key key0="द" key1="ड"/>
    <key key0="्" key1="ं" key3="ं"/>
    <key key0="ग" key2="-" key3="_"/>
    <key key0="ह" key2="=" key3="+"/>
    <key key0="ज" key3="{" key4="}"/>
    <key key0="क" key1="ऌ" key2="ष" key3="[" key4="]"/>
    <key key0="ल" key1="।" key2="|" key3="\\" key4="॥"/>
  </row>
  <row>
    <key width="1.5" key0="shift" key2="loc capslock"/>
    <key key0="ञ" key1="ज्ञ" key2="ॅ" key3="ङ" key4="ऍ"/>
    <key key0="ष" key1="क्ष" key2="ॉ" key3="़" key4="ऑ"/>
    <key key0="च" key2="&lt;" key3="."/>
    <key key0="व" key2=">" key3=","/>
    <key key0="ब" key2="\?" key3="/"/>
    <key key0="न" key2=":" key3=";"/>
    <key key0="म" key1="ॐ" key2="&quot;" key3="'" key4="ँ" key6="ऽ"/>
    <key width="1.5" key0="backspace" key2="delete"/>
  </row>
</keyboard>

```

shift.json
```
"अ":"आ",
"इ":"ई",
"ि":"ी",
"उ":"ऊ",
"ु":"ू",
"ए":"ऐ",
"े":"ै",
"ओ":"औ",
"ो":"ौ",
"क":"ख",
"ग":"घ",
"च":"छ",
"ज":"झ",
"ट":"ठ",
"ड":"ढ",
"न":"ण",
"त":"थ",
"द":"ध",
"प":"फ",
"ब":"भ",
"म":"ं",
"ल":"ळ",
"स":"श",
"ह":"ः"
```

**Comment by Spike-from-NH** [comment]
I see nothing that would cause the characters to change when shifted. A shift.json file does not achieve it. I think you need to put these instructions into your custom layout, as a modmap.

**Comment by Julow** [comment]
Hi! Adding a `<modmap>` to your layout will allow you to implement your layout quickly but changing `shift.json` is the way to go.
For the changes in `shift.json` to take effect in the app, you need to run `gradle test`.

**Comment by npnpatidar** [comment]
If everything related to one layout is in one file. Wouldn't that be better ? If shift.json is modified and two layouts want to modify  same key  then there will be some conficts between layouts. I may be wrong.

**Comment by Julow** [comment]
Sorry I replied to https://github.com/Julow/Unexpected-Keyboard/pull/837 before seeing your comment here. If an other layout want to use different shift mappings, then it will have to use the `<modmap>` element. If the shift mappings I just added to `shift.json` don't make any sense to any future layout, then they should be removed.
Are [these](bd2170e) going to be useful to different Hindi layouts ?

**Comment by Julow** [comment]
This is solved in https://github.com/Julow/Unexpected-Keyboard/pull/837
