### ISSUE TITLE
Anticircle definition adds label to a key's `s` position

### ISSUE THREAD

**Issue by jonnyl2** [Julow/Unexpected-Keyboard#843]
When adding an `anticircle` action to a key, it adds a label to the key's `s` position (which covers up an already existing label for the s-swipe, if applicable). It is my understanding that there should be no label at all for the anticircle-gesture.

Btw, how do I custom-define a key's _clockwise_-half-circle action? Is that gesture not user-definable?

Thanks very much for this great and super-useful project!

**Comment by wwqwq2313** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the drawIndication method to not draw a label for anticircle gestures. This ensures that the s-swipe label remains visible if it exists. Also added a comment about clockwise half-circle actions not being user-definable.

You can review changes in this commit: https://github.com/wwqwq2313/Julow-Unexpected-Keyboard-843/commit/545e5d3a61145a7bc24a327faae81d5ab8f7eb71.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by jonnyl2** [comment]
@alotbsol555 It doesn't override it though; it just adds an additional label. So if you have a `s`, `anticircle` and `indication` tag on that key, you have 3 labels overlapping!

**Comment by jonnyl2** [comment]
You're right, sorry. I hadn't tried with an empty string. This works indeed.

**Comment by jonnyl2** [comment]
This seems like a workaround though, or is this how it's supposed to work? If so, that's fine. Then I will close this issue.

**Comment by Julow** [comment]
Fixed with 52af262
