### ISSUE TITLE
Complex key values not working?

### ISSUE THREAD

**Issue by amihsekai** [Julow/Unexpected-Keyboard#847]
I tried the following:

<key key0="w" key1="~" key2="2" key3="\@" key4=":keyevent symbol='⏯' flags='small':85"/>

There was no symbol, and it was definitely not working as I intended (it's typing out this string).
I'm not sure what I'm doing wrong.

**Comment by Julow** [comment]
`:keyevent` keys were added in 1.30.0.

**Comment by amihsekai** [comment]
That makes sense, I've been using the latest version in F-Droid (1.29.1).
I should've checked for new a new release in the repo.
Thank you for your great work.
