### ISSUE TITLE
How to switch or add layout on Android 15?

### ISSUE THREAD

**Issue by vavanade** [Julow/Unexpected-Keyboard#851]
Once downloaded the app and chosen layouts I can't find any option to change the layouts or add new ones. e.g. I have a QWERTZ layout and want the QWERTY version but I'm not able to find where to add the QWERTY layout.

On GBoard it is the first option in the settings but in Unexpected Keyboard there is no "add layouts" option in the settings menu.

**Comment by Julow** [comment]
This is the same bug as https://github.com/Julow/Unexpected-Keyboard/issues/842

The "add layouts" is the first option but it's obscured by the title bar. You might still click it, it's just above the "Add keys to the keyboard" option.

**Comment by Julow** [comment]
Should be fixed with https://github.com/Julow/Unexpected-Keyboard/pull/848
