### ISSUE TITLE
[Feature request] More set/element symbols

### ISSUE THREAD

**Issue by HaleyHalcyon** [Julow/Unexpected-Keyboard#852]
Unexpected Keyboard can currently input ⊂ ⊃ ∈, but not any of the following related ones.

* ⊄ = Shift ⊂
* ⊅ = Shift ⊃
* ⊈ = Shift Fn ⊂
* ⊉ = Shift Fn ⊃
* ∋ = New swipe target, maybe ↙γ
* ∌ = Shift + ∋

**Comment by Julow** [comment]
I've added your suggestion in 12d9e5e.
