### ISSUE TITLE
copy, paste, cut, undo, redo, select all, etc. (Ctrl + <a key>)

### ISSUE THREAD

**Issue by 07416** [Julow/Unexpected-Keyboard#9]
Are these functions currently functional? Many third-party keyboards I've used have had a Ctrl key, but the modifier key actions (see the title) have been borked in some way.

Currently the interactions seem to have no effect (LineageOS 17.1 on Oneplus 5T, v 1.9.2 from F-Droid).

**Comment by Julow** [comment]
Thanks for the report. It's true that the Ctrl key doesn't work as expected in most applications.

**Comment by Julow** [comment]
I've pushed a fix for this in 58e37b484c8d4cf8099372e6f307557d0ed2458e, I'll release some time in the next few days.

**Comment by Julow** [comment]
This is part of the new release. Feel free to re-open if it still doesn't work in some applications.
