### ISSUE TITLE
Done, Search, Go font size too big.

### ISSUE THREAD

**Issue by krystean** [Julow/Unexpected-Keyboard#93]
![UK](https://user-images.githubusercontent.com/66447871/156608329-94858fd1-5f39-401b-9ca4-941a7f417218.jpg)

Please make it consistent with other keys. UK's getting more awesome every update. Thanks!

PS: Settings key (? Alt key, bottom right) does not work. Android 9.

**Comment by Julow** [comment]
Have you tried the last version from last week ? The bottom row and some other keys should have a smaller font size. Perhaps still not enough?

**Comment by Julow** [comment]
The settings are working fine in my emulator for Android 9. Is it crashing ? Can you try re-installing the app ?

**Comment by krystean** [comment]
> Have you tried the last version from last week ? The bottom row and some other keys should have a smaller font size. Perhaps still not enough?

I have the latest F-droid release installed. On the keyboard screenshot, the font size of `Ctrl` and `Alt` key is ok and both are the same size but the `Done` key's is bigger. Maybe the `Done`, `Search` and `Go` font size is following the size for the `Enter` symbol?

**Comment by krystean** [comment]
> The settings are working fine in my emulator for Android 9. Is it crashing ? Can you try re-installing the app ?

I have reinstalled the app but the key is still not doing anything. No obvious crashes when I swipe to it. Thanks!

**Comment by Julow** [comment]
Indeed the font size for the action key wasn't right, fixed in 534e4cb. Your problem with settings key still puzzle me.

**Comment by krystean** [comment]
> Indeed the font size for the action key wasn't right, fixed in 534e4cb. Your problem with settings key still puzzle me.

I figured it out, it's a permission issue. "Display pop-up windows while running in the background" permission must be enabled manually in Settings for UK. My phone is a Xiaomi so it might be device-specific. The key is now working. Thanks!

**Comment by Julow** [comment]
Thanks! I'll keep this in mind if this is reported again.
