### ISSUE TITLE
Backspace does not work when ShiftLocked

### ISSUE THREAD

**Issue by skybldev** [Julow/Unexpected-Keyboard#99]
First of all I would like to thank you for developing this keyboard. It's truly incredible, pretty much the best mobile keyboard I have ever used, even surpassing Gboard and SwiftKey.

There is jusy one small problem though; I often find myself having to backspace even when typing in Caps or ShiftLock, but on this keyboard, that does not work for some reason.

**Comment by Julow** [comment]
This works fine in my testing. In what applications do you have that problem ? And what's your version of Android ?

**Comment by skybldev** [comment]
FluffyChat is the only app that I can see that behavior with. Now that I realize that I should probably raise this as an issue there too... Also I use Android 11.

**Comment by Julow** [comment]
After a bit of testing, I feel it's not the keyboard's fault. If this happens in every flutter apps, I'll have to add a workaround but I'll leave this unfixed for the next release.

**Comment by Julow** [comment]
Additionally, Ctrl+Backspace makes the app crash. I'll consider that FluffyChat is broken and I'll close this issue.
